define([], function() {
  return {
    "PropertyPaneDescription": "تكوين تصور البيانات",
    // Header
    "HeaderGroupName": "الرأس",
    "WebPartHeaderFieldLabel": "نص الرأس",
    "WebPartHeaderPlaceholder": "مثل لوحة معلومات المبيعات",
    "ShowWebPartHeaderFieldLabel": "إظهار الرأس",
    // Chart Settings group
    "ChartSettingsGroupName": "إعدادات المخطط",
    "ChartTitleFieldLabel": "عنوان المخطط",
    "ChartTypeFieldLabel": "نوع المخطط",
    "LegendPositionFieldLabel": "موضع وسيلة الإيضاح",
    "ChartHeightFieldLabel": "ارتفاع المخطط (بكسل)",
    "ShowLegendFieldLabel": "إظهار وسيلة الإيضاح",
    "StackedFieldLabel": "مكدس (أشرطة/خطوط)",
    "ShowDataTableFieldLabel": "إظهار جدول البيانات",
    "ShowExportBarFieldLabel": "إظهار شريط التصدير",
    "XAxisLabelFieldLabel": "تسمية المحور X (اختياري)",
    "XAxisPlaceholder": "افتراضيًا العمود المحدد",
    "YAxisLabelFieldLabel": "تسمية المحور Y (اختياري)",
    "YAxisPlaceholder": "افتراضيًا الأعمدة المحددة",
    // Chart type group headers
    "ChartGroupStandard": "المخططات القياسية",
    "ChartGroupSpecialized": "المخططات المتخصصة",
    // Chart type options
    "ChartTypeBarLabel": "مخطط شريطي (رأسي)",
    "ChartTypeHorizontalBarLabel": "مخطط شريطي (أفقي)",
    "ChartTypeLineLabel": "مخطط خطي",
    "ChartTypeAreaLabel": "مخطط مساحي",
    "ChartTypeScatterLabel": "مخطط مبعثر",
    "ChartTypePieLabel": "مخطط دائري",
    "ChartTypeDoughnutLabel": "مخطط حلقي",
    "ChartTypeBubbleLabel": "مخطط فقاعي",
    "ChartTypeRadarLabel": "مخطط راداري",
    "ChartTypeKpiLabel": "مربع KPI",
    "ChartTypeHistogramLabel": "مدرج تكراري",
    "ChartTypeWaterfallLabel": "مخطط انسيابي",
    "ChartTypeBoxplotLabel": "مخطط الصندوق",
    "ChartTypeViolinLabel": "مخطط الكمان",
    "ChartTypeBeforeAfterLabel": "مخطط قبل وبعد",
    "ChartTypeTreemapLabel": "خريطة شجرية",
    "ChartTypeHeatmapLabel": "خريطة حرارية",
    "HistogramBinsFieldLabel": "فئات المدرج التكراري",
    "AppearancePageDescription": "الألوان والتسميات والمحاور",
    "AdvancedPageDescription": "التحليلات وخطوط المرجع والتفاعل وتحديث البيانات",
    // Legend position options
    "LegendTopLabel": "أعلى",
    "LegendBottomLabel": "أسفل",
    "LegendLeftLabel": "يسار",
    "LegendRightLabel": "يمين",
    // Colors group
    "ColorsGroupName": "الألوان",
    "ColorPaletteFieldLabel": "لوحة الألوان",
    "PaletteOfficeLabel": "Office (افتراضي)",
    "PaletteVibrantLabel": "نابضة بالحياة",
    "PalettePastelLabel": "باستيل",
    "PaletteMonochromeLabel": "أحادية اللون",
    "PaletteTrafficLightLabel": "إشارة المرور",
    "PaletteWarmLabel": "دافئة",
    "PaletteCoolLabel": "باردة",
    // Data Labels group
    "DataLabelsGroupName": "تسميات البيانات والتنسيق",
    "ShowDataLabelsFieldLabel": "إظهار تسميات البيانات",
    "ValuePrefixFieldLabel": "بادئة القيمة",
    "ValuePrefixPlaceholder": "مثل $",
    "ValueSuffixFieldLabel": "لاحقة القيمة",
    "ValueSuffixPlaceholder": "مثل %",
    "ValueDecimalsFieldLabel": "المنازل العشرية",
    "AbbreviateNumbersFieldLabel": "اختصار الأرقام (K/M)",
    // Axes & Grid group
    "AxesGridGroupName": "المحاور والشبكة",
    "YAxisMinFieldLabel": "الحد الأدنى للمحور Y",
    "YAxisMaxFieldLabel": "الحد الأقصى للمحور Y",
    "AutoPlaceholder": "تلقائي",
    "NumericValidationError": "أدخل رقمًا، أو اتركه فارغًا للوضع التلقائي.",
    "ColorValidationError": "أدخل لونًا بصيغة سداسية عشرية (مثل #d13438)، أو اتركه فارغًا للقيمة الافتراضية.",
    "LogScaleFieldLabel": "مقياس لوغاريتمي (Y)",
    "LogScaleXFieldLabel": "مقياس لوغاريتمي (X)",
    "StepLineFieldLabel": "استيفاء متدرج",
    "ShowGridLinesFieldLabel": "إظهار خطوط الشبكة",
    "XLabelRotationFieldLabel": "تدوير تسمية X (بالدرجات)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "نوع المحور X",
    "XAxisTypeAuto": "اكتشاف تلقائي",
    "XAxisTypeCategory": "فئة",
    "XAxisTypeTime": "الوقت (تواريخ)",
    // Analytics group
    "AnalyticsGroupName": "التحليلات",
    "TrendlineFieldLabel": "خط الاتجاه",
    "TrendlineNone": "بلا",
    "TrendlineLinear": "خطي",
    "TrendlineMovingAverage": "المتوسط المتحرك",
    "TrendWindowFieldLabel": "نافذة المتوسط المتحرك",
    "TrendSuffix": " (الاتجاه)",
    "ForecastPeriodsFieldLabel": "فترات التنبؤ (خط الاتجاه الخطي)",
    // Reference line
    "ReferenceLineGroupName": "خط المرجع",
    "ReferenceLineTypeFieldLabel": "خط المرجع",
    "ReferenceLineValueFieldLabel": "قيمة ثابتة",
    "ReferenceLineColorFieldLabel": "لون الخط (سداسي عشري)",
    "RefLineFixed": "قيمة ثابتة",
    "RefLineMean": "المتوسط",
    "RefLineMedian": "الوسيط",
    // Dual Y axis group
    "DualAxisGroupName": "محور Y مزدوج",
    "Y2ColumnsFieldLabel": "سلاسل المحور الأيمن (أسماء الأعمدة مفصولة بفواصل)",
    "Y2ColumnsPlaceholder": "مثل الهامش,النمو",
    "Y2AxisLabelFieldLabel": "تسمية المحور الأيمن",
    "LogScaleY2FieldLabel": "مقياس لوغاريتمي (المحور الأيمن)",
    // Error bars group
    "ErrorBarsGroupName": "أشرطة الخطأ",
    "ErrorBarTypeFieldLabel": "نوع شريط الخطأ",
    "ErrorBarTypeNone": "بلا",
    "ErrorBarTypeCustom": "عمود مخصص (±)",
    "ErrorBarTypeSd": "الانحراف المعياري (محسوب)",
    "ErrorBarTypeSem": "الخطأ المعياري للمتوسط (محسوب)",
    "ErrorBarColumnFieldLabel": "عمود قيم الخطأ",
    // Significance annotations group
    "SignificanceGroupName": "أقواس الدلالة",
    "SignificancePairsFieldLabel": "أزواج الأقواس",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "قوس واحد في كل سطر: عمود1,عمود2,تسمية  — مثل GroupA,GroupB,*  أو  GroupA,GroupB,p<0.05  (يتم قبول مصفوفة JSON أيضًا)",
    "BeforeAfterColumnsError": "يتطلب مخطط قبل وبعد عمودين Y بالضبط — أحدهما لقيم قبل والآخر لقيم بعد.",
    // Interactivity
    "InteractivityGroupName": "التفاعل",
    "ShowViewerFiltersFieldLabel": "إظهار عوامل التصفية للمشاهدين",
    "DetailsOnDemandFieldLabel": "إظهار صفوف البيانات عند النقر",
    "ShowDataPointsFieldLabel": "تراكب نقاط البيانات على الأشرطة",
    "ShowBubbleSizeLegendFieldLabel": "إظهار وسيلة إيضاح حجم الفقاعة",
    "ViewerFilterLabel": "عامل التصفية:",
    "ViewerFilterColumnAria": "عمود التصفية",
    "ViewerFilterValueAria": "قيمة التصفية",
    "DrillAllLabel": "الكل",
    "DetailsChipLabel": "التفاصيل: {0} ({1} صفوف)",
    // KPI
    "KpiSubLabel": "{0} • {1} • {2} صفوف",
    // Conditional formatting group
    "ConditionalGroupName": "التنسيق الشرطي",
    "ThresholdValueFieldLabel": "قيمة الحد",
    "ThresholdValuePlaceholder": "إيقاف",
    "ThresholdDirectionFieldLabel": "تمييز القيم",
    "ThresholdBelow": "أقل من الحد",
    "ThresholdAbove": "أعلى من الحد",
    "ThresholdColorFieldLabel": "لون التمييز (سداسي عشري)",
    // Data & refresh group
    "DataRefreshGroupName": "البيانات والتحديث",
    "RefreshIntervalFieldLabel": "فاصل التحديث التلقائي (بالدقائق، 0 = إيقاف)",
    "CacheMinutesFieldLabel": "تخزين البيانات مؤقتًا (بالدقائق، 0 = إيقاف)",
    // Dynamic data
    "DynamicDataCategoryLabel": "الفئة المحددة",
    "DynamicDataValueLabel": "القيمة المحددة",
    "DynamicDataSeriesLabel": "السلسلة المحددة",
    // Legacy / unused
    "DataSourceGroupName": "مصدر البيانات",
    // Main component
    "HideDataSourceButton": "▲ إخفاء مصدر البيانات",
    "ConfigureDataSourceButton": "▼ تكوين مصدر البيانات",
    "RowsLoadedBadge": "✓ تم تحميل {0} صفوف",
    "ReadModeLoadError": "تعذر تحميل البيانات: {0}. قم بالتبديل إلى وضع التحرير لإعادة تكوين مصدر البيانات.",
    "RefreshDataButton": "↻ تحديث البيانات",
    "RefreshingLabel": "جارٍ التحديث…",
    "RefreshDataTitle": "إعادة تحميل البيانات من المصدر الذي تم تكوينه",
    // Chart renderer
    "NoDataMessage": "لم يتم تحميل أي بيانات بعد. قم بتكوين مصدر البيانات أعلاه ثم انقر فوق تحميل البيانات.",
    "SelectMappingsMessage": "تم تحميل البيانات ({0} صفوف). يُرجى تحديد تعيينات الأعمدة أعلاه لعرض المخطط.",
    "ChartRenderErrorLabel": "خطأ في عرض المخطط: {0}",
    "UnsupportedChartTypeLabel": "نوع مخطط غير مدعوم: {0}",
    "ChartAriaLabel": "مخطط تصور البيانات",
    "FilterOperatorLabel": "العامل",
    "FilterValueLabel": "القيمة",
    "FilterOpContains": "يحتوي على",
    "FilterOpEquals": "يساوي",
    "FilterOpNotEquals": "لا يساوي",
    "FilterOpGt": "أكبر من",
    "FilterOpLt": "أقل من",
    "FilterOpBetween": "بين (الأدنى..الأعلى)",
    "FilterOpIsEmpty": "فارغ",
    "FilterOpNotEmpty": "غير فارغ",
    "AddFilterButton": "+ إضافة عامل تصفية",
    "RemoveFilterButton": "إزالة",
    "SelectValuePlaceholder": "تحديد قيمة…",
    "ViewerFilterOperatorAria": "عامل التصفية",
    "PaletteColorblindLabel": "آمنة لعمى الألوان",
    "WaterfallGroupName": "المخطط الانسيابي",
    "WaterfallShowTotalFieldLabel": "إظهار شريط الإجمالي",
    "WaterfallPositiveColorFieldLabel": "لون الزيادة",
    "WaterfallNegativeColorFieldLabel": "لون النقصان",
    "WaterfallTotalColorFieldLabel": "لون الإجمالي",
    "WaterfallTotalLabel": "الإجمالي",
    "ExternalFilterGroupName": "التصفية من جزء ويب آخر",
    "ExternalFilterFieldLabel": "مصدر قيمة التصفية",
    "ExternalFilterColumnFieldLabel": "العمود المراد تصفيته",
    "ExternalFilterColumnPlaceholder": "افتراضيًا عمود المحور X",
    "ViewAsTableButton": "عرض كجدول",
    "HideTableButton": "إخفاء الجدول",
    "ChartKeyboardHint": "استخدم مفاتيح الأسهم للتنقل بين نقاط البيانات ومفتاح Enter لتحديد إحداها.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "بادئة قيمة Y2",
    "Y2ValueSuffixFieldLabel": "لاحقة قيمة Y2",
    "AnnotationsGroupName": "التعليقات التوضيحية",
    "AnnotationsFieldLabel": "التعليقات التوضيحية",
    "AnnotationsPlaceholder": "يناير, إطلاق المنتج",
    "AnnotationsHelp": "تعليق واحد في كل سطر: قيمة المحور X، ثم فاصلة، ثم نص الملاحظة. يتم رسم علامة رأسية عند قيمة X هذه.",
    "BeforeLabel": "قبل",
    "AfterLabel": "بعد",
    "RowLabel": "الصف {0}",
    "PointsSuffix": " (نقاط)",
    "ExportSheetName": "البيانات",
    "RefreshFailedNote": "فشل آخر تحديث: {0}. يتم عرض البيانات التي تم تحميلها سابقًا.",
    "TruncatedDataNote": "يتم عرض أول {0} صفوف فقط؛ يحتوي المصدر على مزيد من البيانات.",
    "ScatterNumericWarning": "تتطلب المخططات المبعثرة والفقاعية قيمًا رقمية. لا يحتوي العمود \"{0}\" على بيانات رقمية — اختر عمودًا مختلفًا في التعيين أعلاه.",
    "TimeAxisUnparseableWarning": "لا يحتوي عمود المحور X \"{0}\" على قيم يمكن تحليلها كتواريخ. غيّر نوع المحور X إلى \"فئة\"، أو قم بتعيين عمود تاريخ.",
    // Data source panel
    "DataSourceSectionHeader": "مصدر البيانات",
    "SourceUploadLabel": "تحميل ملف",
    "SourceSharePointListLabel": "قائمة SharePoint",
    "SourceSharePointFileLabel": "ملف SharePoint",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "مسار Graph API",
    "GraphPathHelp": "مسار Microsoft Graph نسبي، مثل /me/memberOf أو /reports/getTeamsUserActivityUserCounts(period='D7'). يتطلب هذا المصدر أذونات Graph معتمدة من قبل مسؤول — وتعمل جميع مصادر البيانات الأخرى بدونها.",
    "SheetNameLabel": "ورقة Excel",
    "DelimiterLabel": "المحدِّد",
    "DelimiterAutoDetect": "اكتشاف تلقائي",
    "DelimiterComma": "فاصلة (,)",
    "DelimiterTab": "علامة تبويب",
    "DelimiterSemicolon": "فاصلة منقوطة (;)",
    "DelimiterPipe": "خط عمودي (|)",
    "SiteUrlLabel": "عنوان URL للموقع (اختياري)",
    "SiteUrlHelp": "اتركه فارغًا لاستخدام الموقع الحالي.",
    "ListNameLabel": "اسم القائمة",
    "LoadingListsLabel": "— جارٍ تحميل القوائم…",
    "SelectListPlaceholder": "— حدد قائمة —",
    "EnterListNamePlaceholder": "أدخل اسم القائمة",
    "ListNameExamplePlaceholder": "مثل بيانات المبيعات",
    "ListDiscoveryError": "تعذر تحميل القوائم — أدخل الاسم يدويًا أدناه.",
    "FileUrlLabel": "عنوان URL للملف (CSV/TSV/Excel في SharePoint)",
    "FileUrlHelp": "عنوان URL كامل لملف في مكتبة مستندات.",
    "ApiUrlLabel": "عنوان URL لواجهة API",
    "DataPathLabel": "مسار البيانات (اختياري)",
    "DataPathHelp": "مسار مفصول بنقاط إلى المصفوفة في استجابة JSON. اتركه فارغًا إذا كان الجذر مصفوفة. استخدم \"value\" مع REST API في SharePoint.",
    "UploadHelp": "قم بتحميل ملف CSV أو TSV أو Excel (.xlsx أو .xls).",
    "LoadedFileRowsLabel": "— {0} صفوف",
    "ChangeFileButton": "تغيير الملف…",
    "ClearButton": "مسح",
    "ChooseFileButton": "اختيار ملف…",
    "LoadDataButton": "تحميل البيانات",
    "LoadingLabel": "جارٍ التحميل…",
    "ErrorSelectListName": "يُرجى تحديد اسم قائمة أو إدخاله.",
    "ErrorEnterFileUrl": "يُرجى إدخال عنوان URL للملف.",
    "ErrorEnterUrl": "يُرجى إدخال عنوان URL.",
    "ErrorLoadList": "فشل تحميل قائمة SharePoint: {0}",
    "ErrorLoadFile": "فشل تحميل الملف: {0}",
    "ErrorFetchData": "فشل جلب البيانات: {0}",
    "ErrorDataPathNotFound": "لم يتم العثور على مسار البيانات \"{0}\" في الاستجابة.",
    "ErrorUrlReturnedHtml": "أرجع عنوان URL هذا صفحة ويب وليس ملفًا. استخدم مسار تنزيل الملف المباشر، وليس عنوان URL للمشاركة من \"نسخ الارتباط\".",
    "ErrorRequestTimedOut": "انتهت مهلة الطلب. تحقق من عنوان URL واتصال الشبكة.",
    "ErrorNonJsonResponse": "تعذر تحليل الاستجابة كـ JSON.",
    "ErrorUnsupportedFileType": "نوع ملف غير مدعوم. يُرجى تحميل ملف .csv أو .tsv أو .xlsx أو .xls.",
    "ErrorReadFile": "فشلت قراءة الملف",
    "ErrorParseFile": "فشل تحليل الملف",
    "LoadedRowsColumns": "تم تحميل {0} صفوف بها {1} أعمدة.",
    "LoadedRowsColumnsPersist": "تم تحميل {0} صفوف بها {1} أعمدة. ستظل البيانات محفوظة عند مغادرة الصفحة.",
    "SizeWarning": "تتجاوز مجموعة البيانات ({0} كيلوبايت) حد الاستمرارية البالغ 200 كيلوبايت. سيعرض المخطط البيانات في هذه الجلسة ولكن سيتم مسحها عند إعادة تحميل الصفحة. بالنسبة للملفات الكبيرة، قم بتحميلها إلى مكتبة SharePoint واستخدم مصدر ملف SharePoint.",
    "ListTruncatedWarning": "تحتوي هذه القائمة على {0} عنصر أو أكثر؛ تم تحميل أول {0} فقط.",
    "GraphTruncatedWarning": "تحتوي نتيجة Microsoft Graph هذه على صفحات أكثر مما أمكن تحميله؛ تم استرداد أول {0} صفحات فقط.",
    "CsvParseWarning": "تعذر تحليل {0} من الصفوف وتم تخطيها.",
    // Column mapper
    "ColumnMappingSectionHeader": "تعيين الأعمدة",
    "CategoryColumnLabel": "عمود الفئة (X / التسميات)",
    "LabelColumnLabel": "عمود التسمية",
    "XAxisColumnLabel": "عمود المحور X",
    "ValueColumnLabel": "عمود القيمة",
    "YAxisColumnLabel": "عمود المحور Y",
    "YAxisColumnsLabel": "أعمدة المحور Y",
    "YAxisColumnsHelp": "(حدد عمودًا واحدًا أو أكثر؛ انقر فوق العينة لتعيين اللون)",
    "SelectColumnPlaceholder": "— حدد عمودًا —",
    "ScatterLabelColumnLabel": "تسمية النقطة",
    "SizeColumnLabel":"عمود الحجم / نصف القطر",
    "NoSizeColumnOption": "— بلا (حجم ثابت) —",
    "SeriesColorTitle": "لون {0}",
    "SeriesTypeTitle": "نوع المخطط لـ {0}",
    "SeriesTypeDefault": "افتراضي",
    "SeriesTypeBar": "شريط",
    "SeriesTypeLine": "خط",
    "HistogramColumnLabel": "العمود المراد تقسيمه إلى فئات (رقمي)",
    "TreemapGroupLabel": "عمود المجموعة / التسمية",
    "HeatmapColumnLabel": "فئة العمود (X)",
    "HeatmapRowLabel": "فئة الصف (Y)",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ خيارات متقدمة",
    "AdvancedOptionsOpen": "▲ خيارات متقدمة",
    "ColorByLabel": "التلوين حسب العمود",
    "ColorByHelp": "تلوين النقاط حسب الفئة بدلاً من السلسلة.",
    "TooltipColumnsLabel": "أعمدة تلميح الأدوات",
    "TooltipColumnsHelp": "(أعمدة إضافية تظهر عند التمرير فوق نقطة بيانات)",
    "DrillLevelLabel": "مستوى التعمق {0}",
    "DrillDownHelp": "حدد تسلسلاً هرميًا للأعمدة لتمكين التعمق بالنقر (مثل المنطقة ← البلد ← المدينة). يتم تجميع القيم في كل مستوى.",
    "BookmarksLabel": "الإشارات المرجعية",
    "BookmarkNameLabel": "اسم الإشارة المرجعية",
    "BookmarkNamePlaceholder": "مثل أفضل 10 حسب المنطقة",
    "SaveBookmarkButton": "حفظ العرض الحالي",
    "ApplyBookmarkButton": "تطبيق",
    "DeleteBookmarkButton": "حذف",
    "ApplyBookmarkPlaceholder": "— تطبيق إشارة مرجعية —",
    // Data controls
    "DataControlsSectionHeader": "عناصر التحكم في البيانات",
    "SortByColumnLabel": "الفرز حسب العمود",
    "NoneOption": "— بلا —",
    "SortDirectionLabel": "اتجاه الفرز",
    "AscendingOption": "تصاعدي",
    "DescendingOption": "تنازلي",
    "RowLimitLabel": "حد الصفوف (0 = الكل)",
    "FilterColumnLabel": "عمود التصفية",
    "FilterContainsLabel": "التصفية: يحتوي على",
    "FilterValuePlaceholder": "قيمة التصفية…",
    "GroupByLabel": "التجميع حسب العمود",
    "AggregationLabel": "التجميع الحسابي",
    "GroupByHelp": "يتم تجميع الأعمدة الرقمية لكل مجموعة. يضيف العدد عمود \"Count\".",
    "AggNone": "بلا",
    "AggSum": "المجموع",
    "AggAvg": "المتوسط",
    "AggCount": "العدد",
    "AggMin": "الحد الأدنى",
    "AggMax": "الحد الأقصى",
    // Data table
    "DataTableHeader": "جدول البيانات ({0} صفوف)",
    "PrevPageButton": "→ السابق",
    "NextPageButton": "التالي ←",
    "PageOfLabel": "صفحة {0} من {1}",
    // Export bar
    "ExportLabel": "تصدير:",
    "ExportPngTitle": "تنزيل المخطط كصورة PNG",
    "ExportJpegTitle": "تنزيل المخطط كصورة JPEG",
    "ExportCsvTitle": "تنزيل البيانات بتنسيق CSV",
    "ExportExcelTitle": "تنزيل البيانات كمصنف Excel"
  }
});
