define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurace vizualizace dat",
    // Header
    "HeaderGroupName": "Záhlaví",
    "WebPartHeaderFieldLabel": "Text záhlaví",
    "WebPartHeaderPlaceholder": "např. Prodejní řídicí panel",
    "ShowWebPartHeaderFieldLabel": "Zobrazit záhlaví",
    // Chart Settings group
    "ChartSettingsGroupName": "Nastavení grafu",
    "ChartTitleFieldLabel": "Název grafu",
    "ChartTypeFieldLabel": "Typ grafu",
    "LegendPositionFieldLabel": "Umístění legendy",
    "ChartHeightFieldLabel": "Výška grafu (px)",
    "ShowLegendFieldLabel": "Zobrazit legendu",
    "StackedFieldLabel": "Skládaný (sloupcový/spojnicový)",
    "ShowDataTableFieldLabel": "Zobrazit tabulku dat",
    "ShowExportBarFieldLabel": "Zobrazit panel exportu",
    "XAxisLabelFieldLabel": "Popisek osy X (volitelné)",
    "XAxisPlaceholder": "Ve výchozím nastavení vybraný sloupec",
    "YAxisLabelFieldLabel": "Popisek osy Y (volitelné)",
    "YAxisPlaceholder": "Ve výchozím nastavení vybrané sloupce",
    // Chart type group headers
    "ChartGroupStandard": "Standardní grafy",
    "ChartGroupSpecialized": "Specializované grafy",
    // Chart type options
    "ChartTypeBarLabel": "Sloupcový graf (svislý)",
    "ChartTypeHorizontalBarLabel": "Pruhový graf (vodorovný)",
    "ChartTypeLineLabel": "Spojnicový graf",
    "ChartTypeAreaLabel": "Plošný graf",
    "ChartTypeScatterLabel": "Bodový graf",
    "ChartTypePieLabel": "Výsečový graf",
    "ChartTypeDoughnutLabel": "Prstencový graf",
    "ChartTypeBubbleLabel": "Bublinový graf",
    "ChartTypeRadarLabel": "Paprskový graf",
    "ChartTypeKpiLabel": "Dlaždice KPI",
    "ChartTypeHistogramLabel": "Histogram",
    "ChartTypeWaterfallLabel": "Kaskádový graf",
    "ChartTypeBoxplotLabel": "Krabicový graf",
    "ChartTypeViolinLabel": "Houslový graf",
    "ChartTypeBeforeAfterLabel": "Graf před a po",
    "ChartTypeTreemapLabel": "Stromová mapa",
    "ChartTypeHeatmapLabel": "Teplotní mapa",
    "HistogramBinsFieldLabel": "Intervaly histogramu",
    "AppearancePageDescription": "Barvy, popisky a osy",
    "AdvancedPageDescription": "Analýzy, referenční čáry, interaktivita a aktualizace dat",
    // Legend position options
    "LegendTopLabel": "Nahoře",
    "LegendBottomLabel": "Dole",
    "LegendLeftLabel": "Vlevo",
    "LegendRightLabel": "Vpravo",
    // Colors group
    "ColorsGroupName": "Barvy",
    "ColorPaletteFieldLabel": "Paleta barev",
    "PaletteOfficeLabel": "Office (výchozí)",
    "PaletteVibrantLabel": "Živá",
    "PalettePastelLabel": "Pastelová",
    "PaletteMonochromeLabel": "Jednobarevná",
    "PaletteTrafficLightLabel": "Semafor",
    "PaletteWarmLabel": "Teplá",
    "PaletteCoolLabel": "Studená",
    // Data Labels group
    "DataLabelsGroupName": "Popisky dat a formátování",
    "ShowDataLabelsFieldLabel": "Zobrazit popisky dat",
    "ValuePrefixFieldLabel": "Předpona hodnoty",
    "ValuePrefixPlaceholder": "např. $",
    "ValueSuffixFieldLabel": "Přípona hodnoty",
    "ValueSuffixPlaceholder": "např. %",
    "ValueDecimalsFieldLabel": "Desetinná místa",
    "AbbreviateNumbersFieldLabel": "Zkracovat čísla (K/M)",
    // Axes & Grid group
    "AxesGridGroupName": "Osy a mřížka",
    "YAxisMinFieldLabel": "Minimum osy Y",
    "YAxisMaxFieldLabel": "Maximum osy Y",
    "AutoPlaceholder": "Automaticky",
    "NumericValidationError": "Zadejte číslo, nebo pole nechte prázdné pro automatickou hodnotu.",
    "ColorValidationError": "Zadejte hexadecimální barvu (např. #d13438), nebo pole nechte prázdné pro výchozí hodnotu.",
    "LogScaleFieldLabel": "Logaritmické měřítko (Y)",
    "LogScaleXFieldLabel": "Logaritmické měřítko (X)",
    "StepLineFieldLabel": "Schodovitá interpolace",
    "ShowGridLinesFieldLabel": "Zobrazit čáry mřížky",
    "XLabelRotationFieldLabel": "Otočení popisků osy X (stupně)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "Typ osy X",
    "XAxisTypeAuto": "Automatická detekce",
    "XAxisTypeCategory": "Kategorie",
    "XAxisTypeTime": "Čas (data)",
    // Analytics group
    "AnalyticsGroupName": "Analýzy",
    "TrendlineFieldLabel": "Spojnice trendu",
    "TrendlineNone": "Žádná",
    "TrendlineLinear": "Lineární",
    "TrendlineMovingAverage": "Klouzavý průměr",
    "TrendWindowFieldLabel": "Okno klouzavého průměru",
    "TrendSuffix": " (trend)",
    "ForecastPeriodsFieldLabel": "Období předpovědi (lineární spojnice trendu)",
    // Reference line
    "ReferenceLineGroupName": "Referenční čára",
    "ReferenceLineTypeFieldLabel": "Referenční čára",
    "ReferenceLineValueFieldLabel": "Pevná hodnota",
    "ReferenceLineColorFieldLabel": "Barva čáry (hex)",
    "RefLineFixed": "Pevná hodnota",
    "RefLineMean": "Průměr",
    "RefLineMedian": "Medián",
    // Dual Y axis group
    "DualAxisGroupName": "Dvojitá osa Y",
    "Y2ColumnsFieldLabel": "Řady pravé osy (názvy sloupců oddělené čárkami)",
    "Y2ColumnsPlaceholder": "např. Marže,Růst",
    "Y2AxisLabelFieldLabel": "Popisek pravé osy",
    "LogScaleY2FieldLabel": "Logaritmické měřítko (pravá osa)",
    // Error bars group
    "ErrorBarsGroupName": "Chybové úsečky",
    "ErrorBarTypeFieldLabel": "Typ chybové úsečky",
    "ErrorBarTypeNone": "Žádné",
    "ErrorBarTypeCustom": "Vlastní sloupec (±)",
    "ErrorBarTypeSd": "Směrodatná odchylka (vypočtená)",
    "ErrorBarTypeSem": "Směrodatná chyba průměru (vypočtená)",
    "ErrorBarColumnFieldLabel": "Sloupec s hodnotami chyb",
    // Significance annotations group
    "SignificanceGroupName": "Závorky významnosti",
    "SignificancePairsFieldLabel": "Páry závorek",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Jedna závorka na řádek: sloupec1,sloupec2,popisek  — např. SkupinaA,SkupinaB,*  nebo  SkupinaA,SkupinaB,p<0.05  (povoleno je i pole JSON)",
    "BeforeAfterColumnsError": "Graf před a po vyžaduje přesně 2 sloupce Y — jeden pro hodnoty před a jeden pro hodnoty po.",
    // Interactivity
    "InteractivityGroupName": "Interaktivita",
    "ShowViewerFiltersFieldLabel": "Zobrazit filtry čtenářům",
    "DetailsOnDemandFieldLabel": "Zobrazit datové řádky po kliknutí",
    "ShowDataPointsFieldLabel": "Překrýt sloupce datovými body",
    "ShowBubbleSizeLegendFieldLabel": "Zobrazit legendu velikosti bublin",
    "ViewerFilterLabel": "Filtr:",
    "ViewerFilterColumnAria": "Sloupec filtru",
    "ViewerFilterValueAria": "Hodnota filtru",
    "DrillAllLabel": "Vše",
    "DetailsChipLabel": "Podrobnosti: {0} (řádků: {1})",
    // KPI
    "KpiSubLabel": "{0} • {1} • řádků: {2}",
    // Conditional formatting group
    "ConditionalGroupName": "Podmíněné formátování",
    "ThresholdValueFieldLabel": "Prahová hodnota",
    "ThresholdValuePlaceholder": "Vypnuto",
    "ThresholdDirectionFieldLabel": "Zvýraznit hodnoty",
    "ThresholdBelow": "Pod prahovou hodnotou",
    "ThresholdAbove": "Nad prahovou hodnotou",
    "ThresholdColorFieldLabel": "Barva zvýraznění (hex)",
    // Data & refresh group
    "DataRefreshGroupName": "Data a aktualizace",
    "RefreshIntervalFieldLabel": "Interval automatické aktualizace (minuty, 0 = vypnuto)",
    "CacheMinutesFieldLabel": "Ukládat data do mezipaměti (minuty, 0 = vypnuto)",
    // Dynamic data
    "DynamicDataCategoryLabel": "Vybraná kategorie",
    "DynamicDataValueLabel": "Vybraná hodnota",
    "DynamicDataSeriesLabel": "Vybraná řada",
    // Legacy / unused
    "DataSourceGroupName": "Zdroj dat",
    // Main component
    "HideDataSourceButton": "▲ Skrýt zdroj dat",
    "ConfigureDataSourceButton": "▼ Konfigurovat zdroj dat",
    "RowsLoadedBadge": "✓ Načteno řádků: {0}",
    "ReadModeLoadError": "Data se nepodařilo načíst: {0}. Přepněte do režimu úprav a zdroj dat překonfigurujte.",
    "RefreshDataButton": "↻ Aktualizovat data",
    "RefreshingLabel": "Aktualizuje se…",
    "RefreshDataTitle": "Znovu načíst data z nakonfigurovaného zdroje",
    // Chart renderer
    "NoDataMessage": "Zatím nebyla načtena žádná data. Nakonfigurujte výše zdroj dat a klikněte na Načíst data.",
    "SelectMappingsMessage": "Data byla načtena (řádků: {0}). Chcete-li zobrazit graf, vyberte výše mapování sloupců.",
    "ChartRenderErrorLabel": "Chyba při vykreslování grafu: {0}",
    "UnsupportedChartTypeLabel": "Nepodporovaný typ grafu: {0}",
    "ChartAriaLabel": "Graf vizualizace dat",
    "FilterOperatorLabel": "Operátor",
    "FilterValueLabel": "Hodnota",
    "FilterOpContains": "obsahuje",
    "FilterOpEquals": "je rovno",
    "FilterOpNotEquals": "není rovno",
    "FilterOpGt": "větší než",
    "FilterOpLt": "menší než",
    "FilterOpBetween": "mezi (nízká..vysoká)",
    "FilterOpIsEmpty": "je prázdné",
    "FilterOpNotEmpty": "není prázdné",
    "AddFilterButton": "+ Přidat filtr",
    "RemoveFilterButton": "Odebrat",
    "SelectValuePlaceholder": "Vyberte hodnotu…",
    "ViewerFilterOperatorAria": "Operátor filtru",
    "PaletteColorblindLabel": "Vhodná pro barvoslepé",
    "WaterfallGroupName": "Kaskáda",
    "WaterfallShowTotalFieldLabel": "Zobrazit sloupec součtu",
    "WaterfallPositiveColorFieldLabel": "Barva nárůstu",
    "WaterfallNegativeColorFieldLabel": "Barva poklesu",
    "WaterfallTotalColorFieldLabel": "Barva součtu",
    "WaterfallTotalLabel": "Součet",
    "ExternalFilterGroupName": "Filtr z jiné webové části",
    "ExternalFilterFieldLabel": "Zdroj hodnoty filtru",
    "ExternalFilterColumnFieldLabel": "Sloupec k filtrování",
    "ExternalFilterColumnPlaceholder": "Ve výchozím nastavení sloupec osy X",
    "ViewAsTableButton": "Zobrazit jako tabulku",
    "HideTableButton": "Skrýt tabulku",
    "ChartKeyboardHint": "Mezi datovými body se pohybujte pomocí kláves se šipkami, klávesou Enter jeden z nich vyberete.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Předpona hodnoty Y2",
    "Y2ValueSuffixFieldLabel": "Přípona hodnoty Y2",
    "AnnotationsGroupName": "Poznámky",
    "AnnotationsFieldLabel": "Poznámky",
    "AnnotationsPlaceholder": "Led, Uvedení produktu",
    "AnnotationsHelp": "Jedna na řádek: hodnota osy X, čárka a text poznámky. Na této hodnotě X se vykreslí svislá značka.",
    "BeforeLabel": "Před",
    "AfterLabel": "Po",
    "RowLabel": "Řádek {0}",
    "PointsSuffix": " (body)",
    "ExportSheetName": "Data",
    "RefreshFailedNote": "Poslední aktualizace se nezdařila: {0}. Zobrazují se dříve načtená data.",
    "TruncatedDataNote": "Zobrazeno je pouze prvních {0} řádků; zdroj obsahuje více dat.",
    "ScatterNumericWarning": "Bodové a bublinové grafy vyžadují číselné hodnoty. Sloupec „{0}“ neobsahuje žádná číselná data — vyberte ve výše uvedeném mapování jiný sloupec.",
    "TimeAxisUnparseableWarning": "Sloupec osy X „{0}“ neobsahuje žádné hodnoty, které lze zpracovat jako data. Změňte typ osy X na „Kategorie“ nebo namapujte sloupec s daty.",
    // Data source panel
    "DataSourceSectionHeader": "Zdroj dat",
    "SourceUploadLabel": "Nahrát soubor",
    "SourceSharePointListLabel": "Seznam SharePoint",
    "SourceSharePointFileLabel": "Soubor SharePoint",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Cesta rozhraní Graph API",
    "GraphPathHelp": "Relativní cesta Microsoft Graph, např. /me/memberOf nebo /reports/getTeamsUserActivityUserCounts(period='D7'). Tento zdroj vyžaduje oprávnění Graph schválená správcem — všechny ostatní zdroje dat fungují bez nich.",
    "SheetNameLabel": "List Excelu",
    "DelimiterLabel": "Oddělovač",
    "DelimiterAutoDetect": "Automatická detekce",
    "DelimiterComma": "Čárka (,)",
    "DelimiterTab": "Tabulátor",
    "DelimiterSemicolon": "Středník (;)",
    "DelimiterPipe": "Svislá čára (|)",
    "SiteUrlLabel": "Adresa URL webu (volitelné)",
    "SiteUrlHelp": "Necháte-li pole prázdné, použije se aktuální web.",
    "ListNameLabel": "Název seznamu",
    "LoadingListsLabel": "— Načítání seznamů…",
    "SelectListPlaceholder": "— Vyberte seznam —",
    "EnterListNamePlaceholder": "Zadejte název seznamu",
    "ListNameExamplePlaceholder": "např. Prodejní data",
    "ListDiscoveryError": "Seznamy se nepodařilo načíst — zadejte název ručně níže.",
    "FileUrlLabel": "Adresa URL souboru (CSV/TSV/Excel v SharePointu)",
    "FileUrlHelp": "Úplná adresa URL souboru v knihovně dokumentů.",
    "ApiUrlLabel": "Adresa URL rozhraní API",
    "DataPathLabel": "Cesta k datům (volitelné)",
    "DataPathHelp": "Cesta k poli v odpovědi JSON oddělená tečkami. Pokud je kořenem pole, nechte prázdné. Pro REST API SharePointu použijte „value“.",
    "UploadHelp": "Nahrajte soubor CSV, TSV nebo Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— řádků: {0}",
    "ChangeFileButton": "Změnit soubor…",
    "ClearButton": "Vymazat",
    "ChooseFileButton": "Vybrat soubor…",
    "LoadDataButton": "Načíst data",
    "LoadingLabel": "Načítání…",
    "ErrorSelectListName": "Vyberte nebo zadejte název seznamu.",
    "ErrorEnterFileUrl": "Zadejte adresu URL souboru.",
    "ErrorEnterUrl": "Zadejte adresu URL.",
    "ErrorLoadList": "Seznam SharePoint se nepodařilo načíst: {0}",
    "ErrorLoadFile": "Soubor se nepodařilo načíst: {0}",
    "ErrorFetchData": "Data se nepodařilo získat: {0}",
    "ErrorDataPathNotFound": "Cesta k datům „{0}“ nebyla v odpovědi nalezena.",
    "ErrorUrlReturnedHtml": "Tato adresa URL vrátila webovou stránku, nikoli soubor. Použijte přímou cestu ke stažení souboru, nikoli sdílenou adresu URL „Kopírovat odkaz“.",
    "ErrorRequestTimedOut": "Vypršel časový limit požadavku. Zkontrolujte adresu URL a síťové připojení.",
    "ErrorNonJsonResponse": "Odpověď se nepodařilo zpracovat jako JSON.",
    "ErrorUnsupportedFileType": "Nepodporovaný typ souboru. Nahrajte soubor .csv, .tsv, .xlsx nebo .xls.",
    "ErrorReadFile": "Soubor se nepodařilo přečíst",
    "ErrorParseFile": "Soubor se nepodařilo zpracovat",
    "LoadedRowsColumns": "Načteno řádků: {0}, sloupců: {1}.",
    "LoadedRowsColumnsPersist": "Načteno řádků: {0}, sloupců: {1}. Data zůstanou zachována i po opuštění stránky.",
    "SizeWarning": "Sada dat ({0} kB) překračuje limit trvalého uložení 200 kB. Graf zobrazí data v této relaci, ale po opětovném načtení stránky se vymažou. U velkých souborů je nahrajte do knihovny SharePoint a použijte zdroj Soubor SharePoint.",
    "ListTruncatedWarning": "Tento seznam obsahuje {0} nebo více položek; načteno bylo pouze prvních {0}.",
    "GraphTruncatedWarning": "Tento výsledek Microsoft Graph obsahuje více stránek, než bylo možné načíst; bylo načteno pouze prvních {0} stránek.",
    "CsvParseWarning": "Počet řádků, které se nepodařilo zpracovat a byly přeskočeny: {0}.",
    // Column mapper
    "ColumnMappingSectionHeader": "Mapování sloupců",
    "CategoryColumnLabel": "Sloupec kategorie (X / popisky)",
    "LabelColumnLabel": "Sloupec popisku",
    "XAxisColumnLabel": "Sloupec osy X",
    "ValueColumnLabel": "Sloupec hodnot",
    "YAxisColumnLabel": "Sloupec osy Y",
    "YAxisColumnsLabel": "Sloupce osy Y",
    "YAxisColumnsHelp": "(vyberte jeden nebo více; kliknutím na vzorek nastavíte barvu)",
    "SelectColumnPlaceholder": "— Vyberte sloupec —",
    "ScatterLabelColumnLabel": "Popisek bodu",
    "SizeColumnLabel":"Sloupec velikosti / poloměru",
    "NoSizeColumnOption": "— Žádný (pevná velikost) —",
    "SeriesColorTitle": "Barva pro {0}",
    "SeriesTypeTitle": "Typ grafu pro {0}",
    "SeriesTypeDefault": "Výchozí",
    "SeriesTypeBar": "Sloupce",
    "SeriesTypeLine": "Spojnice",
    "HistogramColumnLabel": "Sloupec k rozdělení do intervalů (číselný)",
    "TreemapGroupLabel": "Sloupec skupiny / popisku",
    "HeatmapColumnLabel": "Kategorie sloupce (X)",
    "HeatmapRowLabel": "Kategorie řádku (Y)",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ Upřesnit možnosti",
    "AdvancedOptionsOpen": "▲ Upřesnit možnosti",
    "ColorByLabel": "Obarvit podle sloupce",
    "ColorByHelp": "Obarví body podle kategorie místo podle řady.",
    "TooltipColumnsLabel": "Sloupce popisku",
    "TooltipColumnsHelp": "(další sloupce zobrazené při najetí na datový bod)",
    "DrillLevelLabel": "Úroveň prozkoumání {0}",
    "DrillDownHelp": "Definujte hierarchii sloupců pro povolení prozkoumání kliknutím (např. Region → Země → Město). Hodnoty se agregují na každé úrovni.",
    "BookmarksLabel": "Záložky",
    "BookmarkNameLabel": "Název záložky",
    "BookmarkNamePlaceholder": "např. Top 10 podle regionu",
    "SaveBookmarkButton": "Uložit aktuální zobrazení",
    "ApplyBookmarkButton": "Použít",
    "DeleteBookmarkButton": "Odstranit",
    "ApplyBookmarkPlaceholder": "— Použít záložku —",
    // Data controls
    "DataControlsSectionHeader": "Ovládací prvky dat",
    "SortByColumnLabel": "Seřadit podle sloupce",
    "NoneOption": "— Žádné —",
    "SortDirectionLabel": "Směr řazení",
    "AscendingOption": "Vzestupně",
    "DescendingOption": "Sestupně",
    "RowLimitLabel": "Limit řádků (0 = všechny)",
    "FilterColumnLabel": "Sloupec filtru",
    "FilterContainsLabel": "Filtr: obsahuje",
    "FilterValuePlaceholder": "Hodnota filtru…",
    "GroupByLabel": "Seskupit podle sloupce",
    "AggregationLabel": "Agregace",
    "GroupByHelp": "Číselné sloupce se agregují pro každou skupinu. Počet přidá sloupec „Count“.",
    "AggNone": "Žádná",
    "AggSum": "Součet",
    "AggAvg": "Průměr",
    "AggCount": "Počet",
    "AggMin": "Min.",
    "AggMax": "Max.",
    // Data table
    "DataTableHeader": "Tabulka dat (řádků: {0})",
    "PrevPageButton": "← Předchozí",
    "NextPageButton": "Další →",
    "PageOfLabel": "Stránka {0} z {1}",
    // Export bar
    "ExportLabel": "Exportovat:",
    "ExportPngTitle": "Stáhnout graf jako obrázek PNG",
    "ExportJpegTitle": "Stáhnout graf jako obrázek JPEG",
    "ExportCsvTitle": "Stáhnout data jako CSV",
    "ExportExcelTitle": "Stáhnout data jako sešit Excelu"
  }
});
