define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurer din datavisualisering",
    // Header
    "HeaderGroupName": "Overskrift",
    "WebPartHeaderFieldLabel": "Overskriftstekst",
    "WebPartHeaderPlaceholder": "f.eks. Salgsdashboard",
    "ShowWebPartHeaderFieldLabel": "Vis overskrift",
    // Chart Settings group
    "ChartSettingsGroupName": "Diagramindstillinger",
    "ChartTitleFieldLabel": "Diagramtitel",
    "ChartTypeFieldLabel": "Diagramtype",
    "LegendPositionFieldLabel": "Placering af signaturforklaring",
    "ChartHeightFieldLabel": "Diagramhøjde (px)",
    "ShowLegendFieldLabel": "Vis signaturforklaring",
    "StackedFieldLabel": "Stablet (søjle/linje)",
    "ShowDataTableFieldLabel": "Vis datatabel",
    "ShowExportBarFieldLabel": "Vis eksportlinje",
    "XAxisLabelFieldLabel": "Etiket for x-akse (valgfri)",
    "XAxisPlaceholder": "Bruger som standard den valgte kolonne",
    "YAxisLabelFieldLabel": "Etiket for y-akse (valgfri)",
    "YAxisPlaceholder": "Bruger som standard de valgte kolonner",
    // Chart type group headers
    "ChartGroupStandard": "Standarddiagrammer",
    "ChartGroupSpecialized": "Specialdiagrammer",
    // Chart type options
    "ChartTypeBarLabel": "Søjlediagram (lodret)",
    "ChartTypeHorizontalBarLabel": "Liggende søjlediagram (vandret)",
    "ChartTypeLineLabel": "Kurvediagram",
    "ChartTypeAreaLabel": "Områdediagram",
    "ChartTypeScatterLabel": "Punktdiagram",
    "ChartTypePieLabel": "Cirkeldiagram",
    "ChartTypeDoughnutLabel": "Ringdiagram",
    "ChartTypeBubbleLabel": "Boblediagram",
    "ChartTypeRadarLabel": "Radardiagram",
    "ChartTypeKpiLabel": "KPI-felt",
    "ChartTypeHistogramLabel": "Histogram",
    "ChartTypeWaterfallLabel": "Vandfaldsdiagram",
    "ChartTypeBoxplotLabel": "Boksplot",
    "ChartTypeViolinLabel": "Violinplot",
    "ChartTypeBeforeAfterLabel": "Før-efter-diagram",
    "ChartTypeTreemapLabel": "Trædiagram",
    "ChartTypeHeatmapLabel": "Varmekort",
    "HistogramBinsFieldLabel": "Histogramintervaller",
    "AppearancePageDescription": "Farver, etiketter og akser",
    "AdvancedPageDescription": "Analyser, referencelinjer, interaktivitet og dataopdatering",
    // Legend position options
    "LegendTopLabel": "Øverst",
    "LegendBottomLabel": "Nederst",
    "LegendLeftLabel": "Venstre",
    "LegendRightLabel": "Højre",
    // Colors group
    "ColorsGroupName": "Farver",
    "ColorPaletteFieldLabel": "Farvepalet",
    "PaletteOfficeLabel": "Office (standard)",
    "PaletteVibrantLabel": "Livlig",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Ensfarvet",
    "PaletteTrafficLightLabel": "Trafiklys",
    "PaletteWarmLabel": "Varm",
    "PaletteCoolLabel": "Kølig",
    // Data Labels group
    "DataLabelsGroupName": "Dataetiketter og formatering",
    "ShowDataLabelsFieldLabel": "Vis dataetiketter",
    "ValuePrefixFieldLabel": "Værdipræfiks",
    "ValuePrefixPlaceholder": "f.eks. $",
    "ValueSuffixFieldLabel": "Værdisuffiks",
    "ValueSuffixPlaceholder": "f.eks. %",
    "ValueDecimalsFieldLabel": "Decimaler",
    "AbbreviateNumbersFieldLabel": "Forkort tal (K/M)",
    // Axes & Grid group
    "AxesGridGroupName": "Akser og gitter",
    "YAxisMinFieldLabel": "Minimum for y-akse",
    "YAxisMaxFieldLabel": "Maksimum for y-akse",
    "AutoPlaceholder": "Automatisk",
    "NumericValidationError": "Angiv et tal, eller lad feltet være tomt for automatisk.",
    "ColorValidationError": "Angiv en hex-farve (f.eks. #d13438), eller lad feltet være tomt for standard.",
    "LogScaleFieldLabel": "Logaritmisk skala (Y)",
    "LogScaleXFieldLabel": "Logaritmisk skala (X)",
    "StepLineFieldLabel": "Trinvis interpolation",
    "ShowGridLinesFieldLabel": "Vis gitterlinjer",
    "XLabelRotationFieldLabel": "Rotation af x-etiket (grader)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "Type for x-akse",
    "XAxisTypeAuto": "Registrer automatisk",
    "XAxisTypeCategory": "Kategori",
    "XAxisTypeTime": "Tid (datoer)",
    // Analytics group
    "AnalyticsGroupName": "Analyser",
    "TrendlineFieldLabel": "Tendenslinje",
    "TrendlineNone": "Ingen",
    "TrendlineLinear": "Lineær",
    "TrendlineMovingAverage": "Glidende gennemsnit",
    "TrendWindowFieldLabel": "Vindue for glidende gennemsnit",
    "TrendSuffix": " (tendens)",
    "ForecastPeriodsFieldLabel": "Prognoseperioder (lineær tendenslinje)",
    // Reference line
    "ReferenceLineGroupName": "Referencelinje",
    "ReferenceLineTypeFieldLabel": "Referencelinje",
    "ReferenceLineValueFieldLabel": "Fast værdi",
    "ReferenceLineColorFieldLabel": "Linjefarve (hex)",
    "RefLineFixed": "Fast værdi",
    "RefLineMean": "Middelværdi",
    "RefLineMedian": "Median",
    // Dual Y axis group
    "DualAxisGroupName": "Dobbelt y-akse",
    "Y2ColumnsFieldLabel": "Serier på højre akse (kolonnenavne adskilt af komma)",
    "Y2ColumnsPlaceholder": "f.eks. Margin,Vækst",
    "Y2AxisLabelFieldLabel": "Etiket for højre akse",
    "LogScaleY2FieldLabel": "Logaritmisk skala (højre akse)",
    // Error bars group
    "ErrorBarsGroupName": "Fejllinjer",
    "ErrorBarTypeFieldLabel": "Type af fejllinje",
    "ErrorBarTypeNone": "Ingen",
    "ErrorBarTypeCustom": "Brugerdefineret kolonne (±)",
    "ErrorBarTypeSd": "Standardafvigelse (beregnet)",
    "ErrorBarTypeSem": "Standardfejl på middelværdi (beregnet)",
    "ErrorBarColumnFieldLabel": "Kolonne med fejlværdier",
    // Significance annotations group
    "SignificanceGroupName": "Signifikanskonsoller",
    "SignificancePairsFieldLabel": "Konsolpar",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Én konsol pr. linje: kol1,kol2,etiket  — f.eks. GruppeA,GruppeB,*  eller  GruppeA,GruppeB,p<0.05  (JSON-array accepteres også)",
    "BeforeAfterColumnsError": "Et før-efter-diagram kræver præcis 2 Y-kolonner — én til førværdier og én til efterværdier.",
    // Interactivity
    "InteractivityGroupName": "Interaktivitet",
    "ShowViewerFiltersFieldLabel": "Vis filtre for seere",
    "DetailsOnDemandFieldLabel": "Vis datarækker ved klik",
    "ShowDataPointsFieldLabel": "Læg datapunkter oven på søjler",
    "ShowBubbleSizeLegendFieldLabel": "Vis signaturforklaring for boblestørrelse",
    "ViewerFilterLabel": "Filter:",
    "ViewerFilterColumnAria": "Filterkolonne",
    "ViewerFilterValueAria": "Filterværdi",
    "DrillAllLabel": "Alle",
    "DetailsChipLabel": "Detaljer: {0} ({1} rækker)",
    // KPI
    "KpiSubLabel": "{0} • {1} • {2} rækker",
    // Conditional formatting group
    "ConditionalGroupName": "Betinget formatering",
    "ThresholdValueFieldLabel": "Tærskelværdi",
    "ThresholdValuePlaceholder": "Fra",
    "ThresholdDirectionFieldLabel": "Fremhæv værdier",
    "ThresholdBelow": "Under tærskel",
    "ThresholdAbove": "Over tærskel",
    "ThresholdColorFieldLabel": "Fremhævningsfarve (hex)",
    // Data & refresh group
    "DataRefreshGroupName": "Data og opdatering",
    "RefreshIntervalFieldLabel": "Interval for automatisk opdatering (minutter, 0 = fra)",
    "CacheMinutesFieldLabel": "Cachelagr data (minutter, 0 = fra)",
    // Dynamic data
    "DynamicDataCategoryLabel": "Valgt kategori",
    "DynamicDataValueLabel": "Valgt værdi",
    "DynamicDataSeriesLabel": "Valgt serie",
    // Legacy / unused
    "DataSourceGroupName": "Datakilde",
    // Main component
    "HideDataSourceButton": "▲ Skjul datakilde",
    "ConfigureDataSourceButton": "▼ Konfigurer datakilde",
    "RowsLoadedBadge": "✓ {0} rækker indlæst",
    "ReadModeLoadError": "Dataene kunne ikke indlæses: {0}. Skift til redigeringstilstand for at konfigurere datakilden igen.",
    "RefreshDataButton": "↻ Opdater data",
    "RefreshingLabel": "Opdaterer…",
    "RefreshDataTitle": "Genindlæs data fra den konfigurerede kilde",
    // Chart renderer
    "NoDataMessage": "Der er ikke indlæst data endnu. Konfigurer din datakilde ovenfor, og klik på Indlæs data.",
    "SelectMappingsMessage": "Data indlæst ({0} rækker). Vælg kolonnetilknytninger ovenfor for at få vist diagrammet.",
    "ChartRenderErrorLabel": "Fejl ved gengivelse af diagram: {0}",
    "UnsupportedChartTypeLabel": "Diagramtypen understøttes ikke: {0}",
    "ChartAriaLabel": "Diagram til datavisualisering",
    "FilterOperatorLabel": "Operator",
    "FilterValueLabel": "Værdi",
    "FilterOpContains": "indeholder",
    "FilterOpEquals": "er lig med",
    "FilterOpNotEquals": "er ikke lig med",
    "FilterOpGt": "større end",
    "FilterOpLt": "mindre end",
    "FilterOpBetween": "mellem (lav..høj)",
    "FilterOpIsEmpty": "er tom",
    "FilterOpNotEmpty": "er ikke tom",
    "AddFilterButton": "+ Tilføj filter",
    "RemoveFilterButton": "Fjern",
    "SelectValuePlaceholder": "Vælg værdi…",
    "ViewerFilterOperatorAria": "Filteroperator",
    "PaletteColorblindLabel": "Farveblindvenlig",
    "WaterfallGroupName": "Vandfald",
    "WaterfallShowTotalFieldLabel": "Vis totalsøjle",
    "WaterfallPositiveColorFieldLabel": "Farve for stigning",
    "WaterfallNegativeColorFieldLabel": "Farve for fald",
    "WaterfallTotalColorFieldLabel": "Farve for total",
    "WaterfallTotalLabel": "Total",
    "ExternalFilterGroupName": "Filter fra en anden webdel",
    "ExternalFilterFieldLabel": "Kilde til filterværdi",
    "ExternalFilterColumnFieldLabel": "Kolonne der skal filtreres",
    "ExternalFilterColumnPlaceholder": "Bruger som standard kolonnen for x-aksen",
    "ViewAsTableButton": "Vis som tabel",
    "HideTableButton": "Skjul tabel",
    "ChartKeyboardHint": "Brug piletasterne til at flytte mellem datapunkter og Enter til at vælge et.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Y2-værdipræfiks",
    "Y2ValueSuffixFieldLabel": "Y2-værdisuffiks",
    "AnnotationsGroupName": "Anmærkninger",
    "AnnotationsFieldLabel": "Anmærkninger",
    "AnnotationsPlaceholder": "Jan, Produktlancering",
    "AnnotationsHelp": "Én pr. linje: værdien på x-aksen, et komma og derefter notatteksten. Der tegnes en lodret markør ved denne x-værdi.",
    "BeforeLabel": "Før",
    "AfterLabel": "Efter",
    "RowLabel": "Række {0}",
    "PointsSuffix": " (punkter)",
    "ExportSheetName": "Data",
    "RefreshFailedNote": "Seneste opdatering mislykkedes: {0}. Viser tidligere indlæste data.",
    "TruncatedDataNote": "Kun de første {0} rækker vises; kilden indeholder flere data.",
    "ScatterNumericWarning": "Punkt- og boblediagrammer kræver numeriske værdier. Kolonnen \"{0}\" indeholder ingen numeriske data — vælg en anden kolonne i tilknytningen ovenfor.",
    "TimeAxisUnparseableWarning": "Kolonnen for x-aksen \"{0}\" har ingen værdier, der kan fortolkes som datoer. Skift type for x-akse til \"Kategori\", eller tilknyt en datokolonne.",
    // Data source panel
    "DataSourceSectionHeader": "Datakilde",
    "SourceUploadLabel": "Upload fil",
    "SourceSharePointListLabel": "SharePoint-liste",
    "SourceSharePointFileLabel": "SharePoint-fil",
    "SourceRestApiLabel": "REST-API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API-sti",
    "GraphPathHelp": "Relativ Microsoft Graph-sti, f.eks. /me/memberOf eller /reports/getTeamsUserActivityUserCounts(period='D7'). Denne kilde kræver Graph-tilladelser, der er godkendt af en administrator — alle andre datakilder fungerer uden dem.",
    "SheetNameLabel": "Excel-ark",
    "DelimiterLabel": "Skilletegn",
    "DelimiterAutoDetect": "Registrer automatisk",
    "DelimiterComma": "Komma (,)",
    "DelimiterTab": "Tabulator",
    "DelimiterSemicolon": "Semikolon (;)",
    "DelimiterPipe": "Lodret streg (|)",
    "SiteUrlLabel": "Websteds-URL (valgfri)",
    "SiteUrlHelp": "Lad feltet være tomt for at bruge det aktuelle websted.",
    "ListNameLabel": "Listenavn",
    "LoadingListsLabel": "— Indlæser lister…",
    "SelectListPlaceholder": "— Vælg en liste —",
    "EnterListNamePlaceholder": "Angiv listenavn",
    "ListNameExamplePlaceholder": "f.eks. Salgsdata",
    "ListDiscoveryError": "Listerne kunne ikke indlæses — angiv navnet manuelt nedenfor.",
    "FileUrlLabel": "Fil-URL (CSV/TSV/Excel i SharePoint)",
    "FileUrlHelp": "Fuld URL til en fil i et dokumentbibliotek.",
    "ApiUrlLabel": "API-URL",
    "DataPathLabel": "Datasti (valgfri)",
    "DataPathHelp": "Sti med punktummer til arrayet i JSON-svaret. Lad feltet være tomt, hvis roden er et array. Brug \"value\" til SharePoint REST-API'en.",
    "UploadHelp": "Upload en CSV-, TSV- eller Excel-fil (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} rækker",
    "ChangeFileButton": "Skift fil…",
    "ClearButton": "Ryd",
    "ChooseFileButton": "Vælg fil…",
    "LoadDataButton": "Indlæs data",
    "LoadingLabel": "Indlæser…",
    "ErrorSelectListName": "Vælg eller angiv et listenavn.",
    "ErrorEnterFileUrl": "Angiv en fil-URL.",
    "ErrorEnterUrl": "Angiv en URL.",
    "ErrorLoadList": "SharePoint-listen kunne ikke indlæses: {0}",
    "ErrorLoadFile": "Filen kunne ikke indlæses: {0}",
    "ErrorFetchData": "Dataene kunne ikke hentes: {0}",
    "ErrorDataPathNotFound": "Datastien \"{0}\" blev ikke fundet i svaret.",
    "ErrorUrlReturnedHtml": "Denne URL returnerede en webside, ikke en fil. Brug den direkte sti til filoverførsel, ikke en delings-URL fra \"Kopier link\".",
    "ErrorRequestTimedOut": "Anmodningen fik timeout. Kontroller URL'en og din netværksforbindelse.",
    "ErrorNonJsonResponse": "Svaret kunne ikke fortolkes som JSON.",
    "ErrorUnsupportedFileType": "Filtypen understøttes ikke. Upload en .csv-, .tsv-, .xlsx- eller .xls-fil.",
    "ErrorReadFile": "Filen kunne ikke læses",
    "ErrorParseFile": "Filen kunne ikke fortolkes",
    "LoadedRowsColumns": "{0} rækker med {1} kolonner indlæst.",
    "LoadedRowsColumnsPersist": "{0} rækker med {1} kolonner indlæst. Dataene bevares, når du forlader siden.",
    "SizeWarning": "Datasættet ({0} KB) overskrider grænsen på 200 KB for vedvarende lagring. Diagrammet viser dataene i denne session, men de ryddes, når siden genindlæses. Til store filer skal du uploade dem til et SharePoint-bibliotek og bruge kilden SharePoint-fil.",
    "ListTruncatedWarning": "Denne liste har {0} eller flere elementer; kun de første {0} blev indlæst.",
    "GraphTruncatedWarning": "Dette Microsoft Graph-resultat har flere sider, end der kunne indlæses; kun de første {0} sider blev hentet.",
    "CsvParseWarning": "{0} række(r) kunne ikke fortolkes og blev sprunget over.",
    // Column mapper
    "ColumnMappingSectionHeader": "Kolonnetilknytning",
    "CategoryColumnLabel": "Kategorikolonne (X / etiketter)",
    "LabelColumnLabel": "Etiketkolonne",
    "XAxisColumnLabel": "Kolonne for x-akse",
    "ValueColumnLabel": "Værdikolonne",
    "YAxisColumnLabel": "Kolonne for y-akse",
    "YAxisColumnsLabel": "Kolonne(r) for y-akse",
    "YAxisColumnsHelp": "(vælg en eller flere; klik på farveprøven for at angive farve)",
    "SelectColumnPlaceholder": "— Vælg kolonne —",
    "ScatterLabelColumnLabel": "Punktetiket",
    "SizeColumnLabel":"Kolonne for størrelse/radius",
    "NoSizeColumnOption": "— Ingen (fast størrelse) —",
    "SeriesColorTitle": "Farve til {0}",
    "SeriesTypeTitle": "Diagramtype til {0}",
    "SeriesTypeDefault": "Standard",
    "SeriesTypeBar": "Søjle",
    "SeriesTypeLine": "Linje",
    "HistogramColumnLabel": "Kolonne der skal inddeles i intervaller (numerisk)",
    "TreemapGroupLabel": "Gruppe-/etiketkolonne",
    "HeatmapColumnLabel": "Kategori for kolonne (X)",
    "HeatmapRowLabel": "Kategori for række (Y)",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ Avancerede indstillinger",
    "AdvancedOptionsOpen": "▲ Avancerede indstillinger",
    "ColorByLabel": "Farv efter kolonne",
    "ColorByHelp": "Farv punkter efter kategori i stedet for efter serie.",
    "TooltipColumnsLabel": "Kolonner i værktøjstip",
    "TooltipColumnsHelp": "(ekstra kolonner, der vises, når du peger på et datapunkt)",
    "DrillLevelLabel": "Drilniveau {0}",
    "DrillDownHelp": "Definer et kolonnehierarki for at aktivere drill ned med et klik (f.eks. Region → Land → By). Værdier aggregeres på hvert niveau.",
    "BookmarksLabel": "Bogmærker",
    "BookmarkNameLabel": "Bogmærkenavn",
    "BookmarkNamePlaceholder": "f.eks. Top 10 pr. region",
    "SaveBookmarkButton": "Gem aktuel visning",
    "ApplyBookmarkButton": "Anvend",
    "DeleteBookmarkButton": "Slet",
    "ApplyBookmarkPlaceholder": "— Anvend et bogmærke —",
    // Data controls
    "DataControlsSectionHeader": "Datakontrolelementer",
    "SortByColumnLabel": "Sortér efter kolonne",
    "NoneOption": "— Ingen —",
    "SortDirectionLabel": "Sorteringsretning",
    "AscendingOption": "Stigende",
    "DescendingOption": "Faldende",
    "RowLimitLabel": "Rækkegrænse (0 = alle)",
    "FilterColumnLabel": "Filterkolonne",
    "FilterContainsLabel": "Filter: indeholder",
    "FilterValuePlaceholder": "Filterværdi…",
    "GroupByLabel": "Gruppér efter kolonne",
    "AggregationLabel": "Aggregering",
    "GroupByHelp": "Numeriske kolonner aggregeres pr. gruppe. Antal tilføjer en kolonne kaldet \"Count\".",
    "AggNone": "Ingen",
    "AggSum": "Sum",
    "AggAvg": "Gennemsnit",
    "AggCount": "Antal",
    "AggMin": "Min.",
    "AggMax": "Maks.",
    // Data table
    "DataTableHeader": "Datatabel ({0} rækker)",
    "PrevPageButton": "← Forrige",
    "NextPageButton": "Næste →",
    "PageOfLabel": "Side {0} af {1}",
    // Export bar
    "ExportLabel": "Eksportér:",
    "ExportPngTitle": "Download diagram som PNG-billede",
    "ExportJpegTitle": "Download diagram som JPEG-billede",
    "ExportCsvTitle": "Download data som CSV",
    "ExportExcelTitle": "Download data som Excel-projektmappe"
  }
});
