define([], function() {
  return {
    "PropertyPaneDescription": "Διαμόρφωση της απεικόνισης δεδομένων",
    // Header
    "HeaderGroupName": "Κεφαλίδα",
    "WebPartHeaderFieldLabel": "Κείμενο κεφαλίδας",
    "WebPartHeaderPlaceholder": "π.χ. Πίνακας ελέγχου πωλήσεων",
    "ShowWebPartHeaderFieldLabel": "Εμφάνιση κεφαλίδας",
    // Chart Settings group
    "ChartSettingsGroupName": "Ρυθμίσεις γραφήματος",
    "ChartTitleFieldLabel": "Τίτλος γραφήματος",
    "ChartTypeFieldLabel": "Τύπος γραφήματος",
    "LegendPositionFieldLabel": "Θέση υπομνήματος",
    "ChartHeightFieldLabel": "Ύψος γραφήματος (px)",
    "ShowLegendFieldLabel": "Εμφάνιση υπομνήματος",
    "StackedFieldLabel": "Στοιβαγμένο (ράβδοι/γραμμές)",
    "ShowDataTableFieldLabel": "Εμφάνιση πίνακα δεδομένων",
    "ShowExportBarFieldLabel": "Εμφάνιση γραμμής εξαγωγής",
    "XAxisLabelFieldLabel": "Ετικέτα άξονα X (προαιρετικό)",
    "XAxisPlaceholder": "Από προεπιλογή, η επιλεγμένη στήλη",
    "YAxisLabelFieldLabel": "Ετικέτα άξονα Y (προαιρετικό)",
    "YAxisPlaceholder": "Από προεπιλογή, οι επιλεγμένες στήλες",
    // Chart type group headers
    "ChartGroupStandard": "Τυπικά γραφήματα",
    "ChartGroupSpecialized": "Εξειδικευμένα γραφήματα",
    // Chart type options
    "ChartTypeBarLabel": "Γράφημα στηλών (κάθετο)",
    "ChartTypeHorizontalBarLabel": "Γράφημα ράβδων (οριζόντιο)",
    "ChartTypeLineLabel": "Γράφημα γραμμών",
    "ChartTypeAreaLabel": "Γράφημα περιοχών",
    "ChartTypeScatterLabel": "Γράφημα διασποράς",
    "ChartTypePieLabel": "Γράφημα πίτας",
    "ChartTypeDoughnutLabel": "Γράφημα δακτυλίου",
    "ChartTypeBubbleLabel": "Γράφημα φυσαλίδων",
    "ChartTypeRadarLabel": "Γράφημα radar",
    "ChartTypeKpiLabel": "Πλακίδιο KPI",
    "ChartTypeHistogramLabel": "Ιστόγραμμα",
    "ChartTypeWaterfallLabel": "Γράφημα καταρράκτη",
    "ChartTypeBoxplotLabel": "Θηκόγραμμα",
    "ChartTypeViolinLabel": "Γράφημα βιολιού",
    "ChartTypeBeforeAfterLabel": "Γράφημα πριν-μετά",
    "ChartTypeTreemapLabel": "Treemap",
    "ChartTypeHeatmapLabel": "Χάρτης θερμότητας",
    "HistogramBinsFieldLabel": "Κλάσεις ιστογράμματος",
    "AppearancePageDescription": "Χρώματα, ετικέτες και άξονες",
    "AdvancedPageDescription": "Αναλύσεις, γραμμές αναφοράς, διαδραστικότητα και ανανέωση δεδομένων",
    // Legend position options
    "LegendTopLabel": "Επάνω",
    "LegendBottomLabel": "Κάτω",
    "LegendLeftLabel": "Αριστερά",
    "LegendRightLabel": "Δεξιά",
    // Colors group
    "ColorsGroupName": "Χρώματα",
    "ColorPaletteFieldLabel": "Παλέτα χρωμάτων",
    "PaletteOfficeLabel": "Office (προεπιλογή)",
    "PaletteVibrantLabel": "Ζωηρή",
    "PalettePastelLabel": "Παστέλ",
    "PaletteMonochromeLabel": "Μονόχρωμη",
    "PaletteTrafficLightLabel": "Φανάρι",
    "PaletteWarmLabel": "Ζεστή",
    "PaletteCoolLabel": "Ψυχρή",
    // Data Labels group
    "DataLabelsGroupName": "Ετικέτες δεδομένων και μορφοποίηση",
    "ShowDataLabelsFieldLabel": "Εμφάνιση ετικετών δεδομένων",
    "ValuePrefixFieldLabel": "Πρόθεμα τιμής",
    "ValuePrefixPlaceholder": "π.χ. $",
    "ValueSuffixFieldLabel": "Επίθεμα τιμής",
    "ValueSuffixPlaceholder": "π.χ. %",
    "ValueDecimalsFieldLabel": "Δεκαδικά ψηφία",
    "AbbreviateNumbersFieldLabel": "Συντόμευση αριθμών (K/M)",
    // Axes & Grid group
    "AxesGridGroupName": "Άξονες και πλέγμα",
    "YAxisMinFieldLabel": "Ελάχιστο άξονα Y",
    "YAxisMaxFieldLabel": "Μέγιστο άξονα Y",
    "AutoPlaceholder": "Αυτόματο",
    "NumericValidationError": "Εισαγάγετε έναν αριθμό ή αφήστε κενό για αυτόματη τιμή.",
    "ColorValidationError": "Εισαγάγετε ένα δεκαεξαδικό χρώμα (π.χ. #d13438) ή αφήστε κενό για την προεπιλογή.",
    "LogScaleFieldLabel": "Λογαριθμική κλίμακα (Y)",
    "LogScaleXFieldLabel": "Λογαριθμική κλίμακα (X)",
    "StepLineFieldLabel": "Κλιμακωτή παρεμβολή",
    "ShowGridLinesFieldLabel": "Εμφάνιση γραμμών πλέγματος",
    "XLabelRotationFieldLabel": "Περιστροφή ετικέτας X (μοίρες)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "Τύπος άξονα X",
    "XAxisTypeAuto": "Αυτόματος εντοπισμός",
    "XAxisTypeCategory": "Κατηγορία",
    "XAxisTypeTime": "Χρόνος (ημερομηνίες)",
    // Analytics group
    "AnalyticsGroupName": "Αναλύσεις",
    "TrendlineFieldLabel": "Γραμμή τάσης",
    "TrendlineNone": "Καμία",
    "TrendlineLinear": "Γραμμική",
    "TrendlineMovingAverage": "Κινητός μέσος όρος",
    "TrendWindowFieldLabel": "Παράθυρο κινητού μέσου όρου",
    "TrendSuffix": " (τάση)",
    "ForecastPeriodsFieldLabel": "Περίοδοι πρόβλεψης (γραμμική γραμμή τάσης)",
    // Reference line
    "ReferenceLineGroupName": "Γραμμή αναφοράς",
    "ReferenceLineTypeFieldLabel": "Γραμμή αναφοράς",
    "ReferenceLineValueFieldLabel": "Σταθερή τιμή",
    "ReferenceLineColorFieldLabel": "Χρώμα γραμμής (hex)",
    "RefLineFixed": "Σταθερή τιμή",
    "RefLineMean": "Μέσος όρος",
    "RefLineMedian": "Διάμεσος",
    // Dual Y axis group
    "DualAxisGroupName": "Διπλός άξονας Y",
    "Y2ColumnsFieldLabel": "Σειρές δεξιού άξονα (ονόματα στηλών διαχωρισμένα με κόμμα)",
    "Y2ColumnsPlaceholder": "π.χ. Περιθώριο,Ανάπτυξη",
    "Y2AxisLabelFieldLabel": "Ετικέτα δεξιού άξονα",
    "LogScaleY2FieldLabel": "Λογαριθμική κλίμακα (δεξιός άξονας)",
    // Error bars group
    "ErrorBarsGroupName": "Ράβδοι σφάλματος",
    "ErrorBarTypeFieldLabel": "Τύπος ράβδου σφάλματος",
    "ErrorBarTypeNone": "Καμία",
    "ErrorBarTypeCustom": "Προσαρμοσμένη στήλη (±)",
    "ErrorBarTypeSd": "Τυπική απόκλιση (υπολογισμένη)",
    "ErrorBarTypeSem": "Τυπικό σφάλμα μέσου όρου (υπολογισμένο)",
    "ErrorBarColumnFieldLabel": "Στήλη τιμών σφάλματος",
    // Significance annotations group
    "SignificanceGroupName": "Αγκύλες σημαντικότητας",
    "SignificancePairsFieldLabel": "Ζεύγη αγκυλών",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Μία αγκύλη ανά γραμμή: στήλη1,στήλη2,ετικέτα  — π.χ. ΟμάδαΑ,ΟμάδαΒ,*  ή  ΟμάδαΑ,ΟμάδαΒ,p<0.05  (γίνεται δεκτός και πίνακας JSON)",
    "BeforeAfterColumnsError": "Το γράφημα πριν-μετά απαιτεί ακριβώς 2 στήλες Y — μία για τις τιμές πριν και μία για τις τιμές μετά.",
    // Interactivity
    "InteractivityGroupName": "Διαδραστικότητα",
    "ShowViewerFiltersFieldLabel": "Εμφάνιση φίλτρων στους αναγνώστες",
    "DetailsOnDemandFieldLabel": "Εμφάνιση γραμμών δεδομένων με κλικ",
    "ShowDataPointsFieldLabel": "Επικάλυψη σημείων δεδομένων στις ράβδους",
    "ShowBubbleSizeLegendFieldLabel": "Εμφάνιση υπομνήματος μεγέθους φυσαλίδων",
    "ViewerFilterLabel": "Φίλτρο:",
    "ViewerFilterColumnAria": "Στήλη φίλτρου",
    "ViewerFilterValueAria": "Τιμή φίλτρου",
    "DrillAllLabel": "Όλα",
    "DetailsChipLabel": "Λεπτομέρειες: {0} ({1} γραμμές)",
    // KPI
    "KpiSubLabel": "{0} • {1} • {2} γραμμές",
    // Conditional formatting group
    "ConditionalGroupName": "Μορφοποίηση υπό όρους",
    "ThresholdValueFieldLabel": "Τιμή κατωφλίου",
    "ThresholdValuePlaceholder": "Ανενεργό",
    "ThresholdDirectionFieldLabel": "Επισήμανση τιμών",
    "ThresholdBelow": "Κάτω από το κατώφλι",
    "ThresholdAbove": "Πάνω από το κατώφλι",
    "ThresholdColorFieldLabel": "Χρώμα επισήμανσης (hex)",
    // Data & refresh group
    "DataRefreshGroupName": "Δεδομένα και ανανέωση",
    "RefreshIntervalFieldLabel": "Διάστημα αυτόματης ανανέωσης (λεπτά, 0 = ανενεργό)",
    "CacheMinutesFieldLabel": "Προσωρινή αποθήκευση δεδομένων (λεπτά, 0 = ανενεργή)",
    // Dynamic data
    "DynamicDataCategoryLabel": "Επιλεγμένη κατηγορία",
    "DynamicDataValueLabel": "Επιλεγμένη τιμή",
    "DynamicDataSeriesLabel": "Επιλεγμένη σειρά",
    // Legacy / unused
    "DataSourceGroupName": "Προέλευση δεδομένων",
    // Main component
    "HideDataSourceButton": "▲ Απόκρυψη προέλευσης δεδομένων",
    "ConfigureDataSourceButton": "▼ Διαμόρφωση προέλευσης δεδομένων",
    "RowsLoadedBadge": "✓ Φορτώθηκαν {0} γραμμές",
    "ReadModeLoadError": "Δεν ήταν δυνατή η φόρτωση των δεδομένων: {0}. Μεταβείτε στη λειτουργία επεξεργασίας για να διαμορφώσετε ξανά την προέλευση δεδομένων.",
    "RefreshDataButton": "↻ Ανανέωση δεδομένων",
    "RefreshingLabel": "Ανανέωση…",
    "RefreshDataTitle": "Επαναφόρτωση δεδομένων από τη διαμορφωμένη προέλευση",
    // Chart renderer
    "NoDataMessage": "Δεν έχουν φορτωθεί ακόμη δεδομένα. Διαμορφώστε την προέλευση δεδομένων παραπάνω και κάντε κλικ στην επιλογή Φόρτωση δεδομένων.",
    "SelectMappingsMessage": "Τα δεδομένα φορτώθηκαν ({0} γραμμές). Επιλέξτε αντιστοιχίσεις στηλών παραπάνω για να εμφανιστεί το γράφημα.",
    "ChartRenderErrorLabel": "Σφάλμα απόδοσης γραφήματος: {0}",
    "UnsupportedChartTypeLabel": "Μη υποστηριζόμενος τύπος γραφήματος: {0}",
    "ChartAriaLabel": "Γράφημα απεικόνισης δεδομένων",
    "FilterOperatorLabel": "Τελεστής",
    "FilterValueLabel": "Τιμή",
    "FilterOpContains": "περιέχει",
    "FilterOpEquals": "ισούται με",
    "FilterOpNotEquals": "δεν ισούται με",
    "FilterOpGt": "μεγαλύτερο από",
    "FilterOpLt": "μικρότερο από",
    "FilterOpBetween": "μεταξύ (χαμηλό..υψηλό)",
    "FilterOpIsEmpty": "είναι κενό",
    "FilterOpNotEmpty": "δεν είναι κενό",
    "AddFilterButton": "+ Προσθήκη φίλτρου",
    "RemoveFilterButton": "Κατάργηση",
    "SelectValuePlaceholder": "Επιλογή τιμής…",
    "ViewerFilterOperatorAria": "Τελεστής φίλτρου",
    "PaletteColorblindLabel": "Κατάλληλη για αχρωματοψία",
    "WaterfallGroupName": "Καταρράκτης",
    "WaterfallShowTotalFieldLabel": "Εμφάνιση ράβδου συνόλου",
    "WaterfallPositiveColorFieldLabel": "Χρώμα αύξησης",
    "WaterfallNegativeColorFieldLabel": "Χρώμα μείωσης",
    "WaterfallTotalColorFieldLabel": "Χρώμα συνόλου",
    "WaterfallTotalLabel": "Σύνολο",
    "ExternalFilterGroupName": "Φίλτρο από άλλο web part",
    "ExternalFilterFieldLabel": "Προέλευση τιμής φίλτρου",
    "ExternalFilterColumnFieldLabel": "Στήλη προς φιλτράρισμα",
    "ExternalFilterColumnPlaceholder": "Από προεπιλογή, η στήλη του άξονα X",
    "ViewAsTableButton": "Προβολή ως πίνακα",
    "HideTableButton": "Απόκρυψη πίνακα",
    "ChartKeyboardHint": "Χρησιμοποιήστε τα πλήκτρα βέλους για να μετακινηθείτε μεταξύ των σημείων δεδομένων και το Enter για να επιλέξετε ένα.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Πρόθεμα τιμής Y2",
    "Y2ValueSuffixFieldLabel": "Επίθεμα τιμής Y2",
    "AnnotationsGroupName": "Σχολιασμοί",
    "AnnotationsFieldLabel": "Σχολιασμοί",
    "AnnotationsPlaceholder": "Ιαν, Κυκλοφορία προϊόντος",
    "AnnotationsHelp": "Ένας ανά γραμμή: η τιμή του άξονα X, ένα κόμμα και έπειτα το κείμενο της σημείωσης. Σχεδιάζεται ένας κάθετος δείκτης σε αυτήν την τιμή X.",
    "BeforeLabel": "Πριν",
    "AfterLabel": "Μετά",
    "RowLabel": "Γραμμή {0}",
    "PointsSuffix": " (σημεία)",
    "ExportSheetName": "Δεδομένα",
    "RefreshFailedNote": "Η τελευταία ανανέωση απέτυχε: {0}. Εμφανίζονται τα δεδομένα που είχαν φορτωθεί προηγουμένως.",
    "TruncatedDataNote": "Εμφανίζονται μόνο οι πρώτες {0} γραμμές· η προέλευση περιέχει περισσότερα δεδομένα.",
    "ScatterNumericWarning": "Τα γραφήματα διασποράς και φυσαλίδων απαιτούν αριθμητικές τιμές. Η στήλη \"{0}\" δεν περιέχει αριθμητικά δεδομένα — επιλέξτε διαφορετική στήλη στην αντιστοίχιση παραπάνω.",
    "TimeAxisUnparseableWarning": "Η στήλη του άξονα X \"{0}\" δεν έχει τιμές που να μπορούν να αναγνωριστούν ως ημερομηνίες. Αλλάξτε τον τύπο άξονα X σε \"Κατηγορία\" ή αντιστοιχίστε μια στήλη ημερομηνιών.",
    // Data source panel
    "DataSourceSectionHeader": "Προέλευση δεδομένων",
    "SourceUploadLabel": "Αποστολή αρχείου",
    "SourceSharePointListLabel": "Λίστα SharePoint",
    "SourceSharePointFileLabel": "Αρχείο SharePoint",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Διαδρομή Graph API",
    "GraphPathHelp": "Σχετική διαδρομή Microsoft Graph, π.χ. /me/memberOf ή /reports/getTeamsUserActivityUserCounts(period='D7'). Αυτή η προέλευση απαιτεί δικαιώματα Graph που έχουν εγκριθεί από διαχειριστή — όλες οι άλλες προελεύσεις δεδομένων λειτουργούν χωρίς αυτά.",
    "SheetNameLabel": "Φύλλο Excel",
    "DelimiterLabel": "Οριοθέτης",
    "DelimiterAutoDetect": "Αυτόματος εντοπισμός",
    "DelimiterComma": "Κόμμα (,)",
    "DelimiterTab": "Στηλοθέτης",
    "DelimiterSemicolon": "Ερωτηματικό (;)",
    "DelimiterPipe": "Κάθετη γραμμή (|)",
    "SiteUrlLabel": "URL τοποθεσίας (προαιρετικό)",
    "SiteUrlHelp": "Αφήστε κενό για να χρησιμοποιηθεί η τρέχουσα τοποθεσία.",
    "ListNameLabel": "Όνομα λίστας",
    "LoadingListsLabel": "— Φόρτωση λιστών…",
    "SelectListPlaceholder": "— Επιλέξτε μια λίστα —",
    "EnterListNamePlaceholder": "Εισαγάγετε όνομα λίστας",
    "ListNameExamplePlaceholder": "π.χ. Δεδομένα πωλήσεων",
    "ListDiscoveryError": "Δεν ήταν δυνατή η φόρτωση των λιστών — εισαγάγετε το όνομα με μη αυτόματο τρόπο παρακάτω.",
    "FileUrlLabel": "URL αρχείου (CSV/TSV/Excel στο SharePoint)",
    "FileUrlHelp": "Πλήρες URL προς ένα αρχείο σε μια βιβλιοθήκη εγγράφων.",
    "ApiUrlLabel": "URL API",
    "DataPathLabel": "Διαδρομή δεδομένων (προαιρετικό)",
    "DataPathHelp": "Διαδρομή με τελείες προς τον πίνακα στην απάντηση JSON. Αφήστε κενό αν η ρίζα είναι πίνακας. Για το REST API του SharePoint χρησιμοποιήστε \"value\".",
    "UploadHelp": "Αποστείλετε ένα αρχείο CSV, TSV ή Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} γραμμές",
    "ChangeFileButton": "Αλλαγή αρχείου…",
    "ClearButton": "Απαλοιφή",
    "ChooseFileButton": "Επιλογή αρχείου…",
    "LoadDataButton": "Φόρτωση δεδομένων",
    "LoadingLabel": "Φόρτωση…",
    "ErrorSelectListName": "Επιλέξτε ή εισαγάγετε ένα όνομα λίστας.",
    "ErrorEnterFileUrl": "Εισαγάγετε ένα URL αρχείου.",
    "ErrorEnterUrl": "Εισαγάγετε ένα URL.",
    "ErrorLoadList": "Αποτυχία φόρτωσης της λίστας SharePoint: {0}",
    "ErrorLoadFile": "Αποτυχία φόρτωσης του αρχείου: {0}",
    "ErrorFetchData": "Αποτυχία ανάκτησης δεδομένων: {0}",
    "ErrorDataPathNotFound": "Η διαδρομή δεδομένων \"{0}\" δεν βρέθηκε στην απάντηση.",
    "ErrorUrlReturnedHtml": "Αυτό το URL επέστρεψε μια ιστοσελίδα, όχι αρχείο. Χρησιμοποιήστε την απευθείας διαδρομή λήψης του αρχείου, όχι ένα URL κοινής χρήσης από το \"Αντιγραφή συνδέσμου\".",
    "ErrorRequestTimedOut": "Το αίτημα έληξε. Ελέγξτε το URL και τη σύνδεσή σας στο δίκτυο.",
    "ErrorNonJsonResponse": "Δεν ήταν δυνατή η ανάλυση της απάντησης ως JSON.",
    "ErrorUnsupportedFileType": "Μη υποστηριζόμενος τύπος αρχείου. Αποστείλετε ένα αρχείο .csv, .tsv, .xlsx ή .xls.",
    "ErrorReadFile": "Αποτυχία ανάγνωσης του αρχείου",
    "ErrorParseFile": "Αποτυχία ανάλυσης του αρχείου",
    "LoadedRowsColumns": "Φορτώθηκαν {0} γραμμές με {1} στήλες.",
    "LoadedRowsColumnsPersist": "Φορτώθηκαν {0} γραμμές με {1} στήλες. Τα δεδομένα θα διατηρηθούν όταν φύγετε από τη σελίδα.",
    "SizeWarning": "Το σύνολο δεδομένων ({0} KB) υπερβαίνει το όριο διατήρησης των 200 KB. Το γράφημα θα εμφανίσει τα δεδομένα σε αυτήν τη συνεδρία, αλλά θα διαγραφούν κατά την επαναφόρτωση της σελίδας. Για μεγάλα αρχεία, αποστείλτε τα σε μια βιβλιοθήκη του SharePoint και χρησιμοποιήστε την προέλευση Αρχείο SharePoint.",
    "ListTruncatedWarning": "Αυτή η λίστα έχει {0} ή περισσότερα στοιχεία· φορτώθηκαν μόνο τα πρώτα {0}.",
    "GraphTruncatedWarning": "Αυτό το αποτέλεσμα του Microsoft Graph έχει περισσότερες σελίδες από όσες ήταν δυνατό να φορτωθούν· ανακτήθηκαν μόνο οι πρώτες {0} σελίδες.",
    "CsvParseWarning": "Δεν ήταν δυνατή η ανάλυση {0} γραμμής(-ών) και παραλείφθηκαν.",
    // Column mapper
    "ColumnMappingSectionHeader": "Αντιστοίχιση στηλών",
    "CategoryColumnLabel": "Στήλη κατηγορίας (X / ετικέτες)",
    "LabelColumnLabel": "Στήλη ετικέτας",
    "XAxisColumnLabel": "Στήλη άξονα X",
    "ValueColumnLabel": "Στήλη τιμής",
    "YAxisColumnLabel": "Στήλη άξονα Y",
    "YAxisColumnsLabel": "Στήλες άξονα Y",
    "YAxisColumnsHelp": "(επιλέξτε μία ή περισσότερες· κάντε κλικ στο δείγμα για να ορίσετε χρώμα)",
    "SelectColumnPlaceholder": "— Επιλογή στήλης —",
    "ScatterLabelColumnLabel": "Ετικέτα σημείου",
    "SizeColumnLabel":"Στήλη μεγέθους / ακτίνας",
    "NoSizeColumnOption": "— Καμία (σταθερό μέγεθος) —",
    "SeriesColorTitle": "Χρώμα για {0}",
    "SeriesTypeTitle": "Τύπος γραφήματος για {0}",
    "SeriesTypeDefault": "Προεπιλογή",
    "SeriesTypeBar": "Ράβδοι",
    "SeriesTypeLine": "Γραμμή",
    "HistogramColumnLabel": "Στήλη προς ομαδοποίηση σε κλάσεις (αριθμητική)",
    "TreemapGroupLabel": "Στήλη ομάδας / ετικέτας",
    "HeatmapColumnLabel": "Κατηγορία στήλης (X)",
    "HeatmapRowLabel": "Κατηγορία γραμμής (Y)",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ Σύνθετες επιλογές",
    "AdvancedOptionsOpen": "▲ Σύνθετες επιλογές",
    "ColorByLabel": "Χρωματισμός ανά στήλη",
    "ColorByHelp": "Χρωματισμός σημείων ανά κατηγορία αντί για ανά σειρά.",
    "TooltipColumnsLabel": "Στήλες συμβουλής εργαλείου",
    "TooltipColumnsHelp": "(πρόσθετες στήλες που εμφανίζονται όταν τοποθετείτε το ποντίκι πάνω σε ένα σημείο δεδομένων)",
    "DrillLevelLabel": "Επίπεδο λεπτομέρειας {0}",
    "DrillDownHelp": "Ορίστε μια ιεραρχία στηλών για να ενεργοποιήσετε την ανάλυση με κλικ (π.χ. Περιοχή → Χώρα → Πόλη). Οι τιμές συγκεντρώνονται σε κάθε επίπεδο.",
    "BookmarksLabel": "Σελιδοδείκτες",
    "BookmarkNameLabel": "Όνομα σελιδοδείκτη",
    "BookmarkNamePlaceholder": "π.χ. Κορυφαία 10 ανά περιοχή",
    "SaveBookmarkButton": "Αποθήκευση τρέχουσας προβολής",
    "ApplyBookmarkButton": "Εφαρμογή",
    "DeleteBookmarkButton": "Διαγραφή",
    "ApplyBookmarkPlaceholder": "— Εφαρμογή σελιδοδείκτη —",
    // Data controls
    "DataControlsSectionHeader": "Στοιχεία ελέγχου δεδομένων",
    "SortByColumnLabel": "Ταξινόμηση κατά στήλη",
    "NoneOption": "— Καμία —",
    "SortDirectionLabel": "Κατεύθυνση ταξινόμησης",
    "AscendingOption": "Αύξουσα",
    "DescendingOption": "Φθίνουσα",
    "RowLimitLabel": "Όριο γραμμών (0 = όλες)",
    "FilterColumnLabel": "Στήλη φίλτρου",
    "FilterContainsLabel": "Φίλτρο: περιέχει",
    "FilterValuePlaceholder": "Τιμή φίλτρου…",
    "GroupByLabel": "Ομαδοποίηση κατά στήλη",
    "AggregationLabel": "Συνάθροιση",
    "GroupByHelp": "Οι αριθμητικές στήλες συγκεντρώνονται ανά ομάδα. Το Πλήθος προσθέτει μια στήλη \"Count\".",
    "AggNone": "Καμία",
    "AggSum": "Άθροισμα",
    "AggAvg": "Μέσος όρος",
    "AggCount": "Πλήθος",
    "AggMin": "Ελάχ.",
    "AggMax": "Μέγ.",
    // Data table
    "DataTableHeader": "Πίνακας δεδομένων ({0} γραμμές)",
    "PrevPageButton": "← Προηγούμενη",
    "NextPageButton": "Επόμενη →",
    "PageOfLabel": "Σελίδα {0} από {1}",
    // Export bar
    "ExportLabel": "Εξαγωγή:",
    "ExportPngTitle": "Λήψη γραφήματος ως εικόνα PNG",
    "ExportJpegTitle": "Λήψη γραφήματος ως εικόνα JPEG",
    "ExportCsvTitle": "Λήψη δεδομένων ως CSV",
    "ExportExcelTitle": "Λήψη δεδομένων ως βιβλίο εργασίας του Excel"
  }
});
