define([], function() {
  return {
    "PropertyPaneDescription": "Configure la visualización de datos",
    // Header
    "HeaderGroupName": "Encabezado",
    "WebPartHeaderFieldLabel": "Texto del encabezado",
    "WebPartHeaderPlaceholder": "p. ej., Panel de ventas",
    "ShowWebPartHeaderFieldLabel": "Mostrar encabezado",
    // Chart Settings group
    "ChartSettingsGroupName": "Configuración del gráfico",
    "ChartTitleFieldLabel": "Título del gráfico",
    "ChartTypeFieldLabel": "Tipo de gráfico",
    "LegendPositionFieldLabel": "Posición de la leyenda",
    "ChartHeightFieldLabel": "Alto del gráfico (px)",
    "ShowLegendFieldLabel": "Mostrar leyenda",
    "StackedFieldLabel": "Apilado (barras/líneas)",
    "ShowDataTableFieldLabel": "Mostrar tabla de datos",
    "ShowExportBarFieldLabel": "Mostrar barra de exportación",
    "XAxisLabelFieldLabel": "Etiqueta del eje X (opcional)",
    "XAxisPlaceholder": "De forma predeterminada, la columna seleccionada",
    "YAxisLabelFieldLabel": "Etiqueta del eje Y (opcional)",
    "YAxisPlaceholder": "De forma predeterminada, las columnas seleccionadas",
    // Chart type group headers
    "ChartGroupStandard": "Gráficos estándar",
    "ChartGroupSpecialized": "Gráficos especializados",
    // Chart type options
    "ChartTypeBarLabel": "Gráfico de columnas (vertical)",
    "ChartTypeHorizontalBarLabel": "Gráfico de barras (horizontal)",
    "ChartTypeLineLabel": "Gráfico de líneas",
    "ChartTypeAreaLabel": "Gráfico de áreas",
    "ChartTypeScatterLabel": "Gráfico de dispersión",
    "ChartTypePieLabel": "Gráfico circular",
    "ChartTypeDoughnutLabel": "Gráfico de anillos",
    "ChartTypeBubbleLabel": "Gráfico de burbujas",
    "ChartTypeRadarLabel": "Gráfico de radar",
    "ChartTypeKpiLabel": "Icono de KPI",
    "ChartTypeHistogramLabel": "Histograma",
    "ChartTypeWaterfallLabel": "Gráfico de cascada",
    "ChartTypeBoxplotLabel": "Diagrama de cajas",
    "ChartTypeViolinLabel": "Diagrama de violín",
    "ChartTypeBeforeAfterLabel": "Gráfico de antes y después",
    "ChartTypeTreemapLabel": "Mapa de árbol",
    "ChartTypeHeatmapLabel": "Mapa de calor",
    "HistogramBinsFieldLabel": "Intervalos del histograma",
    "AppearancePageDescription": "Colores, etiquetas y ejes",
    "AdvancedPageDescription": "Análisis, líneas de referencia, interactividad y actualización de datos",
    // Legend position options
    "LegendTopLabel": "Arriba",
    "LegendBottomLabel": "Abajo",
    "LegendLeftLabel": "Izquierda",
    "LegendRightLabel": "Derecha",
    // Colors group
    "ColorsGroupName": "Colores",
    "ColorPaletteFieldLabel": "Paleta de colores",
    "PaletteOfficeLabel": "Office (predeterminada)",
    "PaletteVibrantLabel": "Vibrante",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Monocromo",
    "PaletteTrafficLightLabel": "Semáforo",
    "PaletteWarmLabel": "Cálida",
    "PaletteCoolLabel": "Fría",
    // Data Labels group
    "DataLabelsGroupName": "Etiquetas de datos y formato",
    "ShowDataLabelsFieldLabel": "Mostrar etiquetas de datos",
    "ValuePrefixFieldLabel": "Prefijo del valor",
    "ValuePrefixPlaceholder": "p. ej., $",
    "ValueSuffixFieldLabel": "Sufijo del valor",
    "ValueSuffixPlaceholder": "p. ej., %",
    "ValueDecimalsFieldLabel": "Posiciones decimales",
    "AbbreviateNumbersFieldLabel": "Abreviar números (K/M)",
    // Axes & Grid group
    "AxesGridGroupName": "Ejes y cuadrícula",
    "YAxisMinFieldLabel": "Mínimo del eje Y",
    "YAxisMaxFieldLabel": "Máximo del eje Y",
    "AutoPlaceholder": "Automático",
    "NumericValidationError": "Escriba un número o déjelo en blanco para usar el valor automático.",
    "ColorValidationError": "Escriba un color hexadecimal (p. ej., #d13438) o déjelo en blanco para usar el valor predeterminado.",
    "LogScaleFieldLabel": "Escala logarítmica (Y)",
    "LogScaleXFieldLabel": "Escala logarítmica (X)",
    "StepLineFieldLabel": "Interpolación escalonada",
    "ShowGridLinesFieldLabel": "Mostrar líneas de cuadrícula",
    "XLabelRotationFieldLabel": "Rotación de la etiqueta X (grados)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "Tipo de eje X",
    "XAxisTypeAuto": "Detección automática",
    "XAxisTypeCategory": "Categoría",
    "XAxisTypeTime": "Tiempo (fechas)",
    // Analytics group
    "AnalyticsGroupName": "Análisis",
    "TrendlineFieldLabel": "Línea de tendencia",
    "TrendlineNone": "Ninguna",
    "TrendlineLinear": "Lineal",
    "TrendlineMovingAverage": "Media móvil",
    "TrendWindowFieldLabel": "Ventana de media móvil",
    "TrendSuffix": " (tendencia)",
    "ForecastPeriodsFieldLabel": "Períodos de previsión (línea de tendencia lineal)",
    // Reference line
    "ReferenceLineGroupName": "Línea de referencia",
    "ReferenceLineTypeFieldLabel": "Línea de referencia",
    "ReferenceLineValueFieldLabel": "Valor fijo",
    "ReferenceLineColorFieldLabel": "Color de línea (hex)",
    "RefLineFixed": "Valor fijo",
    "RefLineMean": "Media",
    "RefLineMedian": "Mediana",
    // Dual Y axis group
    "DualAxisGroupName": "Eje Y doble",
    "Y2ColumnsFieldLabel": "Series del eje derecho (nombres de columna separados por comas)",
    "Y2ColumnsPlaceholder": "p. ej., Margen,Crecimiento",
    "Y2AxisLabelFieldLabel": "Etiqueta del eje derecho",
    "LogScaleY2FieldLabel": "Escala logarítmica (eje derecho)",
    // Error bars group
    "ErrorBarsGroupName": "Barras de error",
    "ErrorBarTypeFieldLabel": "Tipo de barra de error",
    "ErrorBarTypeNone": "Ninguna",
    "ErrorBarTypeCustom": "Columna personalizada (±)",
    "ErrorBarTypeSd": "Desviación estándar (calculada)",
    "ErrorBarTypeSem": "Error estándar de la media (calculado)",
    "ErrorBarColumnFieldLabel": "Columna de valores de error",
    // Significance annotations group
    "SignificanceGroupName": "Corchetes de significación",
    "SignificancePairsFieldLabel": "Pares de corchetes",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Un corchete por línea: col1,col2,etiqueta  — p. ej., GrupoA,GrupoB,*  o  GrupoA,GrupoB,p<0.05  (también se acepta una matriz JSON)",
    "BeforeAfterColumnsError": "El gráfico de antes y después requiere exactamente 2 columnas Y: una para los valores de antes y otra para los valores de después.",
    // Interactivity
    "InteractivityGroupName": "Interactividad",
    "ShowViewerFiltersFieldLabel": "Mostrar filtros a los lectores",
    "DetailsOnDemandFieldLabel": "Mostrar filas de datos al hacer clic",
    "ShowDataPointsFieldLabel": "Superponer puntos de datos en las barras",
    "ShowBubbleSizeLegendFieldLabel": "Mostrar leyenda de tamaño de burbuja",
    "ViewerFilterLabel": "Filtro:",
    "ViewerFilterColumnAria": "Columna de filtro",
    "ViewerFilterValueAria": "Valor de filtro",
    "DrillAllLabel": "Todo",
    "DetailsChipLabel": "Detalles: {0} ({1} filas)",
    // KPI
    "KpiSubLabel": "{0} • {1} • {2} filas",
    // Conditional formatting group
    "ConditionalGroupName": "Formato condicional",
    "ThresholdValueFieldLabel": "Valor de umbral",
    "ThresholdValuePlaceholder": "Desactivado",
    "ThresholdDirectionFieldLabel": "Resaltar valores",
    "ThresholdBelow": "Por debajo del umbral",
    "ThresholdAbove": "Por encima del umbral",
    "ThresholdColorFieldLabel": "Color de resaltado (hex)",
    // Data & refresh group
    "DataRefreshGroupName": "Datos y actualización",
    "RefreshIntervalFieldLabel": "Intervalo de actualización automática (minutos, 0 = desactivada)",
    "CacheMinutesFieldLabel": "Almacenar datos en caché (minutos, 0 = desactivado)",
    // Dynamic data
    "DynamicDataCategoryLabel": "Categoría seleccionada",
    "DynamicDataValueLabel": "Valor seleccionado",
    "DynamicDataSeriesLabel": "Serie seleccionada",
    // Legacy / unused
    "DataSourceGroupName": "Origen de datos",
    // Main component
    "HideDataSourceButton": "▲ Ocultar origen de datos",
    "ConfigureDataSourceButton": "▼ Configurar origen de datos",
    "RowsLoadedBadge": "✓ {0} filas cargadas",
    "ReadModeLoadError": "No se pudieron cargar los datos: {0}. Cambie al modo de edición para volver a configurar el origen de datos.",
    "RefreshDataButton": "↻ Actualizar datos",
    "RefreshingLabel": "Actualizando…",
    "RefreshDataTitle": "Volver a cargar los datos desde el origen configurado",
    // Chart renderer
    "NoDataMessage": "Todavía no se han cargado datos. Configure el origen de datos anterior y haga clic en Cargar datos.",
    "SelectMappingsMessage": "Datos cargados ({0} filas). Seleccione las asignaciones de columnas anteriores para mostrar el gráfico.",
    "ChartRenderErrorLabel": "Error al representar el gráfico: {0}",
    "UnsupportedChartTypeLabel": "Tipo de gráfico no compatible: {0}",
    "ChartAriaLabel": "Gráfico de visualización de datos",
    "FilterOperatorLabel": "Operador",
    "FilterValueLabel": "Valor",
    "FilterOpContains": "contiene",
    "FilterOpEquals": "es igual a",
    "FilterOpNotEquals": "no es igual a",
    "FilterOpGt": "mayor que",
    "FilterOpLt": "menor que",
    "FilterOpBetween": "entre (bajo..alto)",
    "FilterOpIsEmpty": "está vacío",
    "FilterOpNotEmpty": "no está vacío",
    "AddFilterButton": "+ Agregar filtro",
    "RemoveFilterButton": "Quitar",
    "SelectValuePlaceholder": "Seleccionar valor…",
    "ViewerFilterOperatorAria": "Operador de filtro",
    "PaletteColorblindLabel": "Apta para daltonismo",
    "WaterfallGroupName": "Cascada",
    "WaterfallShowTotalFieldLabel": "Mostrar barra de total",
    "WaterfallPositiveColorFieldLabel": "Color de aumento",
    "WaterfallNegativeColorFieldLabel": "Color de disminución",
    "WaterfallTotalColorFieldLabel": "Color del total",
    "WaterfallTotalLabel": "Total",
    "ExternalFilterGroupName": "Filtrar desde otra parte web",
    "ExternalFilterFieldLabel": "Origen del valor de filtro",
    "ExternalFilterColumnFieldLabel": "Columna que se va a filtrar",
    "ExternalFilterColumnPlaceholder": "De forma predeterminada, la columna del eje X",
    "ViewAsTableButton": "Ver como tabla",
    "HideTableButton": "Ocultar tabla",
    "ChartKeyboardHint": "Use las teclas de flecha para moverse entre los puntos de datos y Entrar para seleccionar uno.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Prefijo del valor Y2",
    "Y2ValueSuffixFieldLabel": "Sufijo del valor Y2",
    "AnnotationsGroupName": "Anotaciones",
    "AnnotationsFieldLabel": "Anotaciones",
    "AnnotationsPlaceholder": "Ene, Lanzamiento del producto",
    "AnnotationsHelp": "Una por línea: el valor del eje X, una coma y después el texto de la nota. Se dibuja un marcador vertical en ese valor de X.",
    "BeforeLabel": "Antes",
    "AfterLabel": "Después",
    "RowLabel": "Fila {0}",
    "PointsSuffix": " (puntos)",
    "ExportSheetName": "Datos",
    "RefreshFailedNote": "Error en la última actualización: {0}. Se muestran los datos cargados anteriormente.",
    "TruncatedDataNote": "Solo se muestran las primeras {0} filas; el origen tiene más datos.",
    "ScatterNumericWarning": "Los gráficos de dispersión y de burbujas necesitan valores numéricos. La columna \"{0}\" no tiene datos numéricos; elija otra columna en la asignación anterior.",
    "TimeAxisUnparseableWarning": "La columna del eje X \"{0}\" no tiene valores que se puedan interpretar como fechas. Cambie el tipo de eje X a \"Categoría\" o asigne una columna de fecha.",
    // Data source panel
    "DataSourceSectionHeader": "Origen de datos",
    "SourceUploadLabel": "Cargar archivo",
    "SourceSharePointListLabel": "Lista de SharePoint",
    "SourceSharePointFileLabel": "Archivo de SharePoint",
    "SourceRestApiLabel": "API REST",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Ruta de la API de Graph",
    "GraphPathHelp": "Ruta relativa de Microsoft Graph, p. ej., /me/memberOf o /reports/getTeamsUserActivityUserCounts(period='D7'). Este origen requiere permisos de Graph aprobados por un administrador; el resto de los orígenes de datos funcionan sin ellos.",
    "SheetNameLabel": "Hoja de Excel",
    "DelimiterLabel": "Delimitador",
    "DelimiterAutoDetect": "Detección automática",
    "DelimiterComma": "Coma (,)",
    "DelimiterTab": "Tabulación",
    "DelimiterSemicolon": "Punto y coma (;)",
    "DelimiterPipe": "Barra vertical (|)",
    "SiteUrlLabel": "URL del sitio (opcional)",
    "SiteUrlHelp": "Déjela en blanco para usar el sitio actual.",
    "ListNameLabel": "Nombre de la lista",
    "LoadingListsLabel": "— Cargando listas…",
    "SelectListPlaceholder": "— Seleccione una lista —",
    "EnterListNamePlaceholder": "Escriba el nombre de la lista",
    "ListNameExamplePlaceholder": "p. ej., Datos de ventas",
    "ListDiscoveryError": "No se pudieron cargar las listas; escriba el nombre manualmente a continuación.",
    "FileUrlLabel": "URL del archivo (CSV/TSV/Excel en SharePoint)",
    "FileUrlHelp": "URL completa de un archivo de una biblioteca de documentos.",
    "ApiUrlLabel": "URL de la API",
    "DataPathLabel": "Ruta de datos (opcional)",
    "DataPathHelp": "Ruta separada por puntos a la matriz de la respuesta JSON. Déjela en blanco si la raíz es una matriz. Para la API REST de SharePoint, use \"value\".",
    "UploadHelp": "Cargue un archivo CSV, TSV o Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} filas",
    "ChangeFileButton": "Cambiar archivo…",
    "ClearButton": "Borrar",
    "ChooseFileButton": "Elegir archivo…",
    "LoadDataButton": "Cargar datos",
    "LoadingLabel": "Cargando…",
    "ErrorSelectListName": "Seleccione o escriba el nombre de una lista.",
    "ErrorEnterFileUrl": "Escriba la URL de un archivo.",
    "ErrorEnterUrl": "Escriba una URL.",
    "ErrorLoadList": "No se pudo cargar la lista de SharePoint: {0}",
    "ErrorLoadFile": "No se pudo cargar el archivo: {0}",
    "ErrorFetchData": "No se pudieron obtener los datos: {0}",
    "ErrorDataPathNotFound": "No se encontró la ruta de datos \"{0}\" en la respuesta.",
    "ErrorUrlReturnedHtml": "Esta URL devolvió una página web, no un archivo. Use la ruta de descarga directa del archivo, no una URL para compartir de \"Copiar vínculo\".",
    "ErrorRequestTimedOut": "Se agotó el tiempo de espera de la solicitud. Compruebe la URL y la conexión de red.",
    "ErrorNonJsonResponse": "No se pudo analizar la respuesta como JSON.",
    "ErrorUnsupportedFileType": "Tipo de archivo no compatible. Cargue un archivo .csv, .tsv, .xlsx o .xls.",
    "ErrorReadFile": "No se pudo leer el archivo",
    "ErrorParseFile": "No se pudo analizar el archivo",
    "LoadedRowsColumns": "Se cargaron {0} filas con {1} columnas.",
    "LoadedRowsColumnsPersist": "Se cargaron {0} filas con {1} columnas. Los datos se conservarán al salir de la página.",
    "SizeWarning": "El conjunto de datos ({0} KB) supera el límite de persistencia de 200 KB. El gráfico mostrará los datos durante esta sesión, pero se borrarán al volver a cargar la página. Para archivos grandes, cárguelos en una biblioteca de SharePoint y use el origen Archivo de SharePoint.",
    "ListTruncatedWarning": "Esta lista tiene {0} o más elementos; solo se cargaron los primeros {0}.",
    "GraphTruncatedWarning": "Este resultado de Microsoft Graph tiene más páginas de las que se pudieron cargar; solo se recuperaron las primeras {0} páginas.",
    "CsvParseWarning": "No se pudieron analizar {0} fila(s) y se omitieron.",
    // Column mapper
    "ColumnMappingSectionHeader": "Asignación de columnas",
    "CategoryColumnLabel": "Columna de categoría (X / etiquetas)",
    "LabelColumnLabel": "Columna de etiqueta",
    "XAxisColumnLabel": "Columna del eje X",
    "ValueColumnLabel": "Columna de valor",
    "YAxisColumnLabel": "Columna del eje Y",
    "YAxisColumnsLabel": "Columna(s) del eje Y",
    "YAxisColumnsHelp": "(seleccione una o varias; haga clic en la muestra para establecer el color)",
    "SelectColumnPlaceholder": "— Seleccione una columna —",
    "ScatterLabelColumnLabel": "Etiqueta de punto",
    "SizeColumnLabel":"Columna de tamaño/radio",
    "NoSizeColumnOption": "— Ninguna (tamaño fijo) —",
    "SeriesColorTitle": "Color de {0}",
    "SeriesTypeTitle": "Tipo de gráfico de {0}",
    "SeriesTypeDefault": "Predeterminado",
    "SeriesTypeBar": "Barras",
    "SeriesTypeLine": "Líneas",
    "HistogramColumnLabel": "Columna que se va a agrupar (numérica)",
    "TreemapGroupLabel": "Columna de grupo/etiqueta",
    "HeatmapColumnLabel": "Categoría de columna (X)",
    "HeatmapRowLabel": "Categoría de fila (Y)",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ Opciones avanzadas",
    "AdvancedOptionsOpen": "▲ Opciones avanzadas",
    "ColorByLabel": "Colorear por columna",
    "ColorByHelp": "Colorea los puntos por categoría en lugar de por serie.",
    "TooltipColumnsLabel": "Columnas de la información sobre herramientas",
    "TooltipColumnsHelp": "(columnas adicionales que se muestran al pasar el cursor sobre un punto de datos)",
    "DrillLevelLabel": "Nivel de desglose {0}",
    "DrillDownHelp": "Defina una jerarquía de columnas para habilitar el desglose con un clic (p. ej., Región → País → Ciudad). Los valores se agregan en cada nivel.",
    "BookmarksLabel": "Marcadores",
    "BookmarkNameLabel": "Nombre del marcador",
    "BookmarkNamePlaceholder": "p. ej., Los 10 primeros por región",
    "SaveBookmarkButton": "Guardar vista actual",
    "ApplyBookmarkButton": "Aplicar",
    "DeleteBookmarkButton": "Eliminar",
    "ApplyBookmarkPlaceholder": "— Aplicar un marcador —",
    // Data controls
    "DataControlsSectionHeader": "Controles de datos",
    "SortByColumnLabel": "Ordenar por columna",
    "NoneOption": "— Ninguna —",
    "SortDirectionLabel": "Dirección de ordenación",
    "AscendingOption": "Ascendente",
    "DescendingOption": "Descendente",
    "RowLimitLabel": "Límite de filas (0 = todas)",
    "FilterColumnLabel": "Columna de filtro",
    "FilterContainsLabel": "Filtro: contiene",
    "FilterValuePlaceholder": "Valor de filtro…",
    "GroupByLabel": "Agrupar por columna",
    "AggregationLabel": "Agregación",
    "GroupByHelp": "Las columnas numéricas se agregan por grupo. Recuento agrega una columna \"Count\".",
    "AggNone": "Ninguna",
    "AggSum": "Suma",
    "AggAvg": "Promedio",
    "AggCount": "Recuento",
    "AggMin": "Mín.",
    "AggMax": "Máx.",
    // Data table
    "DataTableHeader": "Tabla de datos ({0} filas)",
    "PrevPageButton": "← Anterior",
    "NextPageButton": "Siguiente →",
    "PageOfLabel": "Página {0} de {1}",
    // Export bar
    "ExportLabel": "Exportar:",
    "ExportPngTitle": "Descargar gráfico como imagen PNG",
    "ExportJpegTitle": "Descargar gráfico como imagen JPEG",
    "ExportCsvTitle": "Descargar datos como CSV",
    "ExportExcelTitle": "Descargar datos como libro de Excel"
  }
});
