define([], function() {
  return {
    "PropertyPaneDescription": "Määritä tietojen visualisointi",
    // Header
    "HeaderGroupName": "Otsikko",
    "WebPartHeaderFieldLabel": "Otsikkoteksti",
    "WebPartHeaderPlaceholder": "esim. Myyntiraportti",
    "ShowWebPartHeaderFieldLabel": "Näytä otsikko",
    // Chart Settings group
    "ChartSettingsGroupName": "Kaavion asetukset",
    "ChartTitleFieldLabel": "Kaavion otsikko",
    "ChartTypeFieldLabel": "Kaaviotyyppi",
    "LegendPositionFieldLabel": "Selitteen sijainti",
    "ChartHeightFieldLabel": "Kaavion korkeus (px)",
    "ShowLegendFieldLabel": "Näytä selite",
    "StackedFieldLabel": "Pinottu (pylväs/viiva)",
    "ShowDataTableFieldLabel": "Näytä taulukko",
    "ShowExportBarFieldLabel": "Näytä vientipalkki",
    "XAxisLabelFieldLabel": "X-akselin nimiö (valinnainen)",
    "XAxisPlaceholder": "Oletuksena valittu sarake",
    "YAxisLabelFieldLabel": "Y-akselin nimiö (valinnainen)",
    "YAxisPlaceholder": "Oletuksena valitut sarakkeet",
    // Chart type group headers
    "ChartGroupStandard": "Vakiokaaviot",
    "ChartGroupSpecialized": "Erikoiskaaviot",
    // Chart type options
    "ChartTypeBarLabel": "Pylväskaavio (pysty)",
    "ChartTypeHorizontalBarLabel": "Pylväskaavio (vaaka)",
    "ChartTypeLineLabel": "Viivakaavio",
    "ChartTypeAreaLabel": "Aluekaavio",
    "ChartTypeScatterLabel": "Hajontakaavio",
    "ChartTypePieLabel": "Ympyräkaavio",
    "ChartTypeDoughnutLabel": "Rengaskaavio",
    "ChartTypeBubbleLabel": "Kuplakaavio",
    "ChartTypeRadarLabel": "Tutkakaavio",
    "ChartTypeKpiLabel": "KPI-ruutu",
    "ChartTypeHistogramLabel": "Histogrammi",
    "ChartTypeWaterfallLabel": "Vesiputouskaavio",
    "ChartTypeBoxplotLabel": "Laatikkokaavio",
    "ChartTypeViolinLabel": "Viulukaavio",
    "ChartTypeBeforeAfterLabel": "Ennen–jälkeen-kaavio",
    "ChartTypeTreemapLabel": "Puukartta",
    "ChartTypeHeatmapLabel": "Lämpökartta",
    "HistogramBinsFieldLabel": "Histogrammin luokat",
    "AppearancePageDescription": "Värit, nimiöt ja akselit",
    "AdvancedPageDescription": "Analytiikka, viitaviivat, vuorovaikutteisuus ja tietojen päivitys",
    // Legend position options
    "LegendTopLabel": "Ylhäällä",
    "LegendBottomLabel": "Alhaalla",
    "LegendLeftLabel": "Vasemmalla",
    "LegendRightLabel": "Oikealla",
    // Colors group
    "ColorsGroupName": "Värit",
    "ColorPaletteFieldLabel": "Väripaletti",
    "PaletteOfficeLabel": "Office (oletus)",
    "PaletteVibrantLabel": "Eloisa",
    "PalettePastelLabel": "Pastelli",
    "PaletteMonochromeLabel": "Yksivärinen",
    "PaletteTrafficLightLabel": "Liikennevalo",
    "PaletteWarmLabel": "Lämmin",
    "PaletteCoolLabel": "Viileä",
    // Data Labels group
    "DataLabelsGroupName": "Tietotunnisteet ja muotoilu",
    "ShowDataLabelsFieldLabel": "Näytä tietotunnisteet",
    "ValuePrefixFieldLabel": "Arvon etuliite",
    "ValuePrefixPlaceholder": "esim. €",
    "ValueSuffixFieldLabel": "Arvon jälkiliite",
    "ValueSuffixPlaceholder": "esim. %",
    "ValueDecimalsFieldLabel": "Desimaalien määrä",
    "AbbreviateNumbersFieldLabel": "Lyhennä luvut (k/M)",
    // Axes & Grid group
    "AxesGridGroupName": "Akselit ja ruudukko",
    "YAxisMinFieldLabel": "Y-akselin vähimmäisarvo",
    "YAxisMaxFieldLabel": "Y-akselin enimmäisarvo",
    "AutoPlaceholder": "Automaattinen",
    "NumericValidationError": "Anna luku tai jätä tyhjäksi automaattista arvoa varten.",
    "ColorValidationError": "Anna heksadesimaaliväri (esim. #d13438) tai jätä tyhjäksi oletusta varten.",
    "LogScaleFieldLabel": "Logaritminen asteikko (Y)",
    "LogScaleXFieldLabel": "Logaritminen asteikko (X)",
    "StepLineFieldLabel": "Porrasinterpolointi",
    "ShowGridLinesFieldLabel": "Näytä ruudukkoviivat",
    "XLabelRotationFieldLabel": "X-nimiön kierto (astetta)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "X-akselin tyyppi",
    "XAxisTypeAuto": "Tunnista automaattisesti",
    "XAxisTypeCategory": "Luokka",
    "XAxisTypeTime": "Aika (päivämäärät)",
    // Analytics group
    "AnalyticsGroupName": "Analytiikka",
    "TrendlineFieldLabel": "Trendiviiva",
    "TrendlineNone": "Ei mitään",
    "TrendlineLinear": "Lineaarinen",
    "TrendlineMovingAverage": "Liukuva keskiarvo",
    "TrendWindowFieldLabel": "Liukuvan keskiarvon ikkuna",
    "TrendSuffix": " (trendi)",
    "ForecastPeriodsFieldLabel": "Ennustejaksot (lineaarinen trendiviiva)",
    // Reference line
    "ReferenceLineGroupName": "Viiteviiva",
    "ReferenceLineTypeFieldLabel": "Viiteviiva",
    "ReferenceLineValueFieldLabel": "Kiinteä arvo",
    "ReferenceLineColorFieldLabel": "Viivan väri (heksa)",
    "RefLineFixed": "Kiinteä arvo",
    "RefLineMean": "Keskiarvo",
    "RefLineMedian": "Mediaani",
    // Dual Y axis group
    "DualAxisGroupName": "Kaksois-Y-akseli",
    "Y2ColumnsFieldLabel": "Oikean akselin sarjat (pilkuilla erotetut sarakenimet)",
    "Y2ColumnsPlaceholder": "esim. Kate,Kasvu",
    "Y2AxisLabelFieldLabel": "Oikean akselin nimiö",
    "LogScaleY2FieldLabel": "Logaritminen asteikko (oikea akseli)",
    // Error bars group
    "ErrorBarsGroupName": "Virhepalkit",
    "ErrorBarTypeFieldLabel": "Virhepalkin tyyppi",
    "ErrorBarTypeNone": "Ei mitään",
    "ErrorBarTypeCustom": "Mukautettu sarake (±)",
    "ErrorBarTypeSd": "Keskihajonta (laskettu)",
    "ErrorBarTypeSem": "Keskiarvon keskivirhe (laskettu)",
    "ErrorBarColumnFieldLabel": "Virhearvon sarake",
    // Significance annotations group
    "SignificanceGroupName": "Merkitsevyyssulkeet",
    "SignificancePairsFieldLabel": "Sulkeiden parit",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Yksi sulje riviä kohti: sarake1,sarake2,tunniste  — esim. RyhmäA,RyhmäB,*  tai  RyhmäA,RyhmäB,p<0.05  (myös JSON-taulukko hyväksytään)",
    "BeforeAfterColumnsError": "Ennen–jälkeen-kaavio vaatii täsmälleen 2 Y-saraketta — yhden Ennen-arvoille ja yhden Jälkeen-arvoille.",
    // Interactivity
    "InteractivityGroupName": "Vuorovaikutteisuus",
    "ShowViewerFiltersFieldLabel": "Näytä suodattimet katselijoille",
    "DetailsOnDemandFieldLabel": "Näytä tietorivit napsautettaessa",
    "ShowDataPointsFieldLabel": "Näytä datapisteet pylväiden päällä",
    "ShowBubbleSizeLegendFieldLabel": "Näytä kuplakoon selite",
    "ViewerFilterLabel": "Suodatin:",
    "ViewerFilterColumnAria": "Suodatettava sarake",
    "ViewerFilterValueAria": "Suodattimen arvo",
    "DrillAllLabel": "Kaikki",
    "DetailsChipLabel": "Tiedot: {0} ({1} riviä)",
    // KPI
    "KpiSubLabel": "{0} • {1} • {2} riviä",
    // Conditional formatting group
    "ConditionalGroupName": "Ehdollinen muotoilu",
    "ThresholdValueFieldLabel": "Raja-arvo",
    "ThresholdValuePlaceholder": "Pois",
    "ThresholdDirectionFieldLabel": "Korosta arvot",
    "ThresholdBelow": "Raja-arvon alapuolella",
    "ThresholdAbove": "Raja-arvon yläpuolella",
    "ThresholdColorFieldLabel": "Korostusväri (heksa)",
    // Data & refresh group
    "DataRefreshGroupName": "Tiedot ja päivitys",
    "RefreshIntervalFieldLabel": "Automaattisen päivityksen väli (minuuttia, 0 = pois)",
    "CacheMinutesFieldLabel": "Tietojen välimuisti (minuuttia, 0 = pois)",
    // Dynamic data
    "DynamicDataCategoryLabel": "Valittu luokka",
    "DynamicDataValueLabel": "Valittu arvo",
    "DynamicDataSeriesLabel": "Valittu sarja",
    // Legacy / unused
    "DataSourceGroupName": "Tietolähde",
    // Main component
    "HideDataSourceButton": "▲ Piilota tietolähde",
    "ConfigureDataSourceButton": "▼ Määritä tietolähde",
    "RowsLoadedBadge": "✓ {0} riviä ladattu",
    "ReadModeLoadError": "Tietoja ei voitu ladata: {0}. Siirry muokkaustilaan määrittääksesi tietolähteen uudelleen.",
    "RefreshDataButton": "↻ Päivitä tiedot",
    "RefreshingLabel": "Päivitetään…",
    "RefreshDataTitle": "Lataa tiedot uudelleen määritetystä lähteestä",
    // Chart renderer
    "NoDataMessage": "Tietoja ei ole vielä ladattu. Määritä tietolähde yllä ja valitse Lataa tiedot.",
    "SelectMappingsMessage": "Tiedot ladattu ({0} riviä). Valitse sarakemääritykset yltä näyttääksesi kaavion.",
    "ChartRenderErrorLabel": "Kaavion hahmonnusvirhe: {0}",
    "UnsupportedChartTypeLabel": "Kaaviotyyppiä ei tueta: {0}",
    "ChartAriaLabel": "Tietojen visualisointikaavio",
    "FilterOperatorLabel": "Operaattori",
    "FilterValueLabel": "Arvo",
    "FilterOpContains": "sisältää",
    "FilterOpEquals": "on yhtä suuri kuin",
    "FilterOpNotEquals": "ei ole yhtä suuri kuin",
    "FilterOpGt": "suurempi kuin",
    "FilterOpLt": "pienempi kuin",
    "FilterOpBetween": "välillä (alin..ylin)",
    "FilterOpIsEmpty": "on tyhjä",
    "FilterOpNotEmpty": "ei ole tyhjä",
    "AddFilterButton": "+ Lisää suodatin",
    "RemoveFilterButton": "Poista",
    "SelectValuePlaceholder": "Valitse arvo…",
    "ViewerFilterOperatorAria": "Suodattimen operaattori",
    "PaletteColorblindLabel": "Värisokeusystävällinen",
    "WaterfallGroupName": "Vesiputous",
    "WaterfallShowTotalFieldLabel": "Näytä yhteispalkki",
    "WaterfallPositiveColorFieldLabel": "Kasvun väri",
    "WaterfallNegativeColorFieldLabel": "Laskun väri",
    "WaterfallTotalColorFieldLabel": "Yhteissumman väri",
    "WaterfallTotalLabel": "Yhteensä",
    "ExternalFilterGroupName": "Suodata toisesta verkko-osasta",
    "ExternalFilterFieldLabel": "Suodatusarvon lähde",
    "ExternalFilterColumnFieldLabel": "Suodatettava sarake",
    "ExternalFilterColumnPlaceholder": "Oletuksena X-akselin sarake",
    "ViewAsTableButton": "Näytä taulukkona",
    "HideTableButton": "Piilota taulukko",
    "ChartKeyboardHint": "Siirry datapisteestä toiseen nuolinäppäimillä ja valitse yksi Enter-näppäimellä.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Y2-arvon etuliite",
    "Y2ValueSuffixFieldLabel": "Y2-arvon jälkiliite",
    "AnnotationsGroupName": "Huomautukset",
    "AnnotationsFieldLabel": "Huomautukset",
    "AnnotationsPlaceholder": "Tammi, Tuotelanseeraus",
    "AnnotationsHelp": "Yksi riviä kohti: X-akselin arvo, pilkku ja huomautuksen teksti. Pystymerkki piirretään kyseiseen X-arvoon.",
    "BeforeLabel": "Ennen",
    "AfterLabel": "Jälkeen",
    "RowLabel": "Rivi {0}",
    "PointsSuffix": " (pisteet)",
    "ExportSheetName": "Tiedot",
    "RefreshFailedNote": "Viimeisin päivitys epäonnistui: {0}. Näytetään aiemmin ladatut tiedot.",
    "TruncatedDataNote": "Vain {0} ensimmäistä riviä näytetään; lähteessä on enemmän tietoja.",
    "ScatterNumericWarning": "Hajonta- ja kuplakaaviot tarvitsevat numeerisia arvoja. Sarakkeessa \"{0}\" ei ole numeerisia tietoja — valitse toinen sarake yllä olevassa määrityksessä.",
    "TimeAxisUnparseableWarning": "X-akselin sarakkeessa \"{0}\" ei ole arvoja, jotka voitaisiin tulkita päivämääriksi. Vaihda X-akselin tyypiksi \"Luokka\" tai yhdistä päivämääräsarake.",
    // Data source panel
    "DataSourceSectionHeader": "Tietolähde",
    "SourceUploadLabel": "Lataa tiedosto",
    "SourceSharePointListLabel": "SharePoint-luettelo",
    "SourceSharePointFileLabel": "SharePoint-tiedosto",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API -polku",
    "GraphPathHelp": "Suhteellinen Microsoft Graph -polku, esim. /me/memberOf tai /reports/getTeamsUserActivityUserCounts(period='D7'). Tämä lähde vaatii järjestelmänvalvojan hyväksymät Graph-oikeudet — kaikki muut tietolähteet toimivat ilman niitä.",
    "SheetNameLabel": "Excel-taulukko",
    "DelimiterLabel": "Erotin",
    "DelimiterAutoDetect": "Tunnista automaattisesti",
    "DelimiterComma": "Pilkku (,)",
    "DelimiterTab": "Sarkain",
    "DelimiterSemicolon": "Puolipiste (;)",
    "DelimiterPipe": "Pystyviiva (|)",
    "SiteUrlLabel": "Sivuston URL-osoite (valinnainen)",
    "SiteUrlHelp": "Jätä tyhjäksi käyttääksesi nykyistä sivustoa.",
    "ListNameLabel": "Luettelon nimi",
    "LoadingListsLabel": "— Ladataan luetteloita…",
    "SelectListPlaceholder": "— Valitse luettelo —",
    "EnterListNamePlaceholder": "Anna luettelon nimi",
    "ListNameExamplePlaceholder": "esim. Myyntitiedot",
    "ListDiscoveryError": "Luetteloita ei voitu ladata — anna nimi manuaalisesti alla.",
    "FileUrlLabel": "Tiedoston URL-osoite (CSV/TSV/Excel SharePointissa)",
    "FileUrlHelp": "Asiakirjakirjastossa olevan tiedoston täydellinen URL-osoite.",
    "ApiUrlLabel": "API-URL-osoite",
    "DataPathLabel": "Tietopolku (valinnainen)",
    "DataPathHelp": "Pisteillä erotettu polku JSON-vastauksen taulukkoon. Jätä tyhjäksi, jos juuri on taulukko. SharePoint REST API:ssa käytä arvoa \"value\".",
    "UploadHelp": "Lataa CSV-, TSV- tai Excel-tiedosto (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} riviä",
    "ChangeFileButton": "Vaihda tiedosto…",
    "ClearButton": "Tyhjennä",
    "ChooseFileButton": "Valitse tiedosto…",
    "LoadDataButton": "Lataa tiedot",
    "LoadingLabel": "Ladataan…",
    "ErrorSelectListName": "Valitse tai anna luettelon nimi.",
    "ErrorEnterFileUrl": "Anna tiedoston URL-osoite.",
    "ErrorEnterUrl": "Anna URL-osoite.",
    "ErrorLoadList": "SharePoint-luettelon lataaminen epäonnistui: {0}",
    "ErrorLoadFile": "Tiedoston lataaminen epäonnistui: {0}",
    "ErrorFetchData": "Tietojen nouto epäonnistui: {0}",
    "ErrorDataPathNotFound": "Tietopolkua \"{0}\" ei löytynyt vastauksesta.",
    "ErrorUrlReturnedHtml": "Tämä URL-osoite palautti verkkosivun, ei tiedostoa. Käytä suoraa tiedoston lataamispolkua äläkä \"Kopioi linkki\" -jakamis-URL-osoitetta.",
    "ErrorRequestTimedOut": "Pyyntö aikakatkaistiin. Tarkista URL-osoite ja verkkoyhteytesi.",
    "ErrorNonJsonResponse": "Vastausta ei voitu jäsentää JSON-muodossa.",
    "ErrorUnsupportedFileType": "Tiedostotyyppiä ei tueta. Lataa .csv-, .tsv-, .xlsx- tai .xls-tiedosto.",
    "ErrorReadFile": "Tiedoston lukeminen epäonnistui",
    "ErrorParseFile": "Tiedoston jäsentäminen epäonnistui",
    "LoadedRowsColumns": "Ladattu {0} riviä ja {1} saraketta.",
    "LoadedRowsColumnsPersist": "Ladattu {0} riviä ja {1} saraketta. Tiedot säilyvät, kun poistut sivulta.",
    "SizeWarning": "Tietojoukko ({0} kt) ylittää 200 kt:n tallennusrajan. Kaavio näyttää tiedot tämän istunnon ajan, mutta ne tyhjennetään sivun uudelleenlatauksessa. Suurille tiedostoille lataa tiedosto SharePoint-kirjastoon ja käytä SharePoint-tiedosto-lähdettä.",
    "ListTruncatedWarning": "Tässä luettelossa on vähintään {0} kohdetta; vain ensimmäiset {0} ladattiin.",
    "GraphTruncatedWarning": "Tässä Microsoft Graph -tuloksessa on enemmän sivuja kuin voitiin ladata; vain ensimmäiset {0} sivua haettiin.",
    "CsvParseWarning": "{0} riviä ei voitu jäsentää, ja ne ohitettiin.",
    // Column mapper
    "ColumnMappingSectionHeader": "Sarakemääritys",
    "CategoryColumnLabel": "Luokkasarake (X / nimiöt)",
    "LabelColumnLabel": "Nimiösarake",
    "XAxisColumnLabel": "X-akselin sarake",
    "ValueColumnLabel": "Arvosarake",
    "YAxisColumnLabel": "Y-akselin sarake",
    "YAxisColumnsLabel": "Y-akselin sarakkeet",
    "YAxisColumnsHelp": "(valitse yksi tai useampi; aseta väri napsauttamalla värimallia)",
    "SelectColumnPlaceholder": "— Valitse sarake —",
    "ScatterLabelColumnLabel": "Pisteen nimiö",
    "SizeColumnLabel":"Koko- / sädesarake",
    "NoSizeColumnOption": "— Ei mitään (kiinteä koko) —",
    "SeriesColorTitle": "Väri: {0}",
    "SeriesTypeTitle": "Kaaviotyyppi: {0}",
    "SeriesTypeDefault": "Oletus",
    "SeriesTypeBar": "Pylväs",
    "SeriesTypeLine": "Viiva",
    "HistogramColumnLabel": "Luokiteltava sarake (numeerinen)",
    "TreemapGroupLabel": "Ryhmä- / nimiösarake",
    "HeatmapColumnLabel": "Sarakkeen (X) luokka",
    "HeatmapRowLabel": "Rivin (Y) luokka",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ Lisäasetukset",
    "AdvancedOptionsOpen": "▲ Lisäasetukset",
    "ColorByLabel": "Väritä sarakkeen mukaan",
    "ColorByHelp": "Väritä pisteet luokan eikä sarjan mukaan.",
    "TooltipColumnsLabel": "Työkaluvihjeen sarakkeet",
    "TooltipColumnsHelp": "(lisäsarakkeet, jotka näytetään osoitettaessa datapistettä)",
    "DrillLevelLabel": "Porautumistaso {0}",
    "DrillDownHelp": "Määritä sarakehierarkia napsautuksella porautumista varten (esim. Alue → Maa → Kaupunki). Arvot yhdistetään kullakin tasolla.",
    "BookmarksLabel": "Kirjanmerkit",
    "BookmarkNameLabel": "Kirjanmerkin nimi",
    "BookmarkNamePlaceholder": "esim. 10 parasta alueittain",
    "SaveBookmarkButton": "Tallenna nykyinen näkymä",
    "ApplyBookmarkButton": "Käytä",
    "DeleteBookmarkButton": "Poista",
    "ApplyBookmarkPlaceholder": "— Käytä kirjanmerkkiä —",
    // Data controls
    "DataControlsSectionHeader": "Tietojen hallinta",
    "SortByColumnLabel": "Lajitteluperuste",
    "NoneOption": "— Ei mitään —",
    "SortDirectionLabel": "Lajittelusuunta",
    "AscendingOption": "Nouseva",
    "DescendingOption": "Laskeva",
    "RowLimitLabel": "Rivirajoitus (0 = kaikki)",
    "FilterColumnLabel": "Suodatettava sarake",
    "FilterContainsLabel": "Suodatin: sisältää",
    "FilterValuePlaceholder": "Suodattimen arvo…",
    "GroupByLabel": "Ryhmittele sarakkeen mukaan",
    "AggregationLabel": "Koostaminen",
    "GroupByHelp": "Numeeriset sarakkeet koostetaan ryhmittäin. Määrä lisää \"Määrä\"-sarakkeen.",
    "AggNone": "Ei mitään",
    "AggSum": "Summa",
    "AggAvg": "Keskiarvo",
    "AggCount": "Määrä",
    "AggMin": "Pienin",
    "AggMax": "Suurin",
    // Data table
    "DataTableHeader": "Taulukko ({0} riviä)",
    "PrevPageButton": "← Edellinen",
    "NextPageButton": "Seuraava →",
    "PageOfLabel": "Sivu {0}/{1}",
    // Export bar
    "ExportLabel": "Vie:",
    "ExportPngTitle": "Lataa kaavio PNG-kuvana",
    "ExportJpegTitle": "Lataa kaavio JPEG-kuvana",
    "ExportCsvTitle": "Lataa tiedot CSV-tiedostona",
    "ExportExcelTitle": "Lataa tiedot Excel-työkirjana"
  }
});
