define([], function() {
  return {
    "PropertyPaneDescription": "Configurez votre visualisation de données",
    // Header
    "HeaderGroupName": "En-tête",
    "WebPartHeaderFieldLabel": "Texte de l'en-tête",
    "WebPartHeaderPlaceholder": "p. ex. Tableau de bord des ventes",
    "ShowWebPartHeaderFieldLabel": "Afficher l'en-tête",
    // Chart Settings group
    "ChartSettingsGroupName": "Paramètres du graphique",
    "ChartTitleFieldLabel": "Titre du graphique",
    "ChartTypeFieldLabel": "Type de graphique",
    "LegendPositionFieldLabel": "Position de la légende",
    "ChartHeightFieldLabel": "Hauteur du graphique (px)",
    "ShowLegendFieldLabel": "Afficher la légende",
    "StackedFieldLabel": "Empilé (barres/courbes)",
    "ShowDataTableFieldLabel": "Afficher le tableau de données",
    "ShowExportBarFieldLabel": "Afficher la barre d'exportation",
    "XAxisLabelFieldLabel": "Étiquette de l'axe X (facultatif)",
    "XAxisPlaceholder": "Colonne sélectionnée par défaut",
    "YAxisLabelFieldLabel": "Étiquette de l'axe Y (facultatif)",
    "YAxisPlaceholder": "Colonne(s) sélectionnée(s) par défaut",
    // Chart type group headers
    "ChartGroupStandard": "Graphiques standard",
    "ChartGroupSpecialized": "Graphiques spécialisés",
    // Chart type options
    "ChartTypeBarLabel": "Histogramme (vertical)",
    "ChartTypeHorizontalBarLabel": "Graphique à barres (horizontal)",
    "ChartTypeLineLabel": "Graphique en courbes",
    "ChartTypeAreaLabel": "Graphique en aires",
    "ChartTypeScatterLabel": "Nuage de points",
    "ChartTypePieLabel": "Graphique en secteurs",
    "ChartTypeDoughnutLabel": "Graphique en anneau",
    "ChartTypeBubbleLabel": "Graphique à bulles",
    "ChartTypeRadarLabel": "Graphique radar",
    "ChartTypeKpiLabel": "Vignette KPI",
    "ChartTypeHistogramLabel": "Histogramme",
    "ChartTypeWaterfallLabel": "Graphique en cascade",
    "ChartTypeBoxplotLabel": "Boîte à moustaches",
    "ChartTypeViolinLabel": "Graphique en violon",
    "ChartTypeBeforeAfterLabel": "Graphique avant-après",
    "ChartTypeTreemapLabel": "Treemap",
    "ChartTypeHeatmapLabel": "Carte thermique",
    "HistogramBinsFieldLabel": "Classes de l'histogramme",
    "AppearancePageDescription": "Couleurs, étiquettes et axes",
    "AdvancedPageDescription": "Analyses, lignes de référence, interactivité et actualisation des données",
    // Legend position options
    "LegendTopLabel": "En haut",
    "LegendBottomLabel": "En bas",
    "LegendLeftLabel": "À gauche",
    "LegendRightLabel": "À droite",
    // Colors group
    "ColorsGroupName": "Couleurs",
    "ColorPaletteFieldLabel": "Palette de couleurs",
    "PaletteOfficeLabel": "Office (par défaut)",
    "PaletteVibrantLabel": "Vive",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Monochrome",
    "PaletteTrafficLightLabel": "Feu tricolore",
    "PaletteWarmLabel": "Chaude",
    "PaletteCoolLabel": "Froide",
    // Data Labels group
    "DataLabelsGroupName": "Étiquettes de données et mise en forme",
    "ShowDataLabelsFieldLabel": "Afficher les étiquettes de données",
    "ValuePrefixFieldLabel": "Préfixe de valeur",
    "ValuePrefixPlaceholder": "p. ex. €",
    "ValueSuffixFieldLabel": "Suffixe de valeur",
    "ValueSuffixPlaceholder": "p. ex. %",
    "ValueDecimalsFieldLabel": "Nombre de décimales",
    "AbbreviateNumbersFieldLabel": "Abréger les nombres (k/M)",
    // Axes & Grid group
    "AxesGridGroupName": "Axes et quadrillage",
    "YAxisMinFieldLabel": "Minimum de l'axe Y",
    "YAxisMaxFieldLabel": "Maximum de l'axe Y",
    "AutoPlaceholder": "Auto",
    "NumericValidationError": "Entrez un nombre, ou laissez vide pour un réglage automatique.",
    "ColorValidationError": "Entrez une couleur hexadécimale (p. ex. #d13438), ou laissez vide pour la valeur par défaut.",
    "LogScaleFieldLabel": "Échelle logarithmique (Y)",
    "LogScaleXFieldLabel": "Échelle logarithmique (X)",
    "StepLineFieldLabel": "Interpolation en escalier",
    "ShowGridLinesFieldLabel": "Afficher le quadrillage",
    "XLabelRotationFieldLabel": "Rotation des étiquettes X (degrés)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "Type d'axe X",
    "XAxisTypeAuto": "Détection automatique",
    "XAxisTypeCategory": "Catégorie",
    "XAxisTypeTime": "Temps (dates)",
    // Analytics group
    "AnalyticsGroupName": "Analyses",
    "TrendlineFieldLabel": "Courbe de tendance",
    "TrendlineNone": "Aucune",
    "TrendlineLinear": "Linéaire",
    "TrendlineMovingAverage": "Moyenne mobile",
    "TrendWindowFieldLabel": "Fenêtre de la moyenne mobile",
    "TrendSuffix": " (tendance)",
    "ForecastPeriodsFieldLabel": "Périodes de prévision (tendance linéaire)",
    // Reference line
    "ReferenceLineGroupName": "Ligne de référence",
    "ReferenceLineTypeFieldLabel": "Ligne de référence",
    "ReferenceLineValueFieldLabel": "Valeur fixe",
    "ReferenceLineColorFieldLabel": "Couleur de la ligne (hex)",
    "RefLineFixed": "Valeur fixe",
    "RefLineMean": "Moyenne",
    "RefLineMedian": "Médiane",
    // Dual Y axis group
    "DualAxisGroupName": "Double axe Y",
    "Y2ColumnsFieldLabel": "Séries de l'axe droit (noms de colonnes séparés par des virgules)",
    "Y2ColumnsPlaceholder": "p. ex. Marge,Croissance",
    "Y2AxisLabelFieldLabel": "Étiquette de l'axe droit",
    "LogScaleY2FieldLabel": "Échelle logarithmique (axe droit)",
    // Error bars group
    "ErrorBarsGroupName": "Barres d'erreur",
    "ErrorBarTypeFieldLabel": "Type de barre d'erreur",
    "ErrorBarTypeNone": "Aucune",
    "ErrorBarTypeCustom": "Colonne personnalisée (±)",
    "ErrorBarTypeSd": "Écart type (calculé)",
    "ErrorBarTypeSem": "Erreur standard de la moyenne (calculée)",
    "ErrorBarColumnFieldLabel": "Colonne de valeur d'erreur",
    // Significance annotations group
    "SignificanceGroupName": "Crochets de signification",
    "SignificancePairsFieldLabel": "Paires de crochets",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Un crochet par ligne : col1,col2,étiquette  — p. ex. GroupeA,GroupeB,*  ou  GroupeA,GroupeB,p<0.05  (un tableau JSON est également accepté)",
    "BeforeAfterColumnsError": "Le graphique avant-après nécessite exactement 2 colonnes Y — une pour les valeurs Avant et une pour les valeurs Après.",
    // Interactivity
    "InteractivityGroupName": "Interactivité",
    "ShowViewerFiltersFieldLabel": "Afficher les filtres aux lecteurs",
    "DetailsOnDemandFieldLabel": "Afficher les lignes de données au clic",
    "ShowDataPointsFieldLabel": "Superposer les points de données aux barres",
    "ShowBubbleSizeLegendFieldLabel": "Afficher la légende de taille des bulles",
    "ViewerFilterLabel": "Filtre :",
    "ViewerFilterColumnAria": "Colonne de filtre",
    "ViewerFilterValueAria": "Valeur de filtre",
    "DrillAllLabel": "Tout",
    "DetailsChipLabel": "Détails : {0} ({1} lignes)",
    // KPI
    "KpiSubLabel": "{0} • {1} • {2} lignes",
    // Conditional formatting group
    "ConditionalGroupName": "Mise en forme conditionnelle",
    "ThresholdValueFieldLabel": "Valeur seuil",
    "ThresholdValuePlaceholder": "Désactivé",
    "ThresholdDirectionFieldLabel": "Mettre en évidence les valeurs",
    "ThresholdBelow": "Inférieures au seuil",
    "ThresholdAbove": "Supérieures au seuil",
    "ThresholdColorFieldLabel": "Couleur de mise en évidence (hex)",
    // Data & refresh group
    "DataRefreshGroupName": "Données et actualisation",
    "RefreshIntervalFieldLabel": "Intervalle d'actualisation automatique (minutes, 0 = désactivé)",
    "CacheMinutesFieldLabel": "Mettre les données en cache (minutes, 0 = désactivé)",
    // Dynamic data
    "DynamicDataCategoryLabel": "Catégorie sélectionnée",
    "DynamicDataValueLabel": "Valeur sélectionnée",
    "DynamicDataSeriesLabel": "Série sélectionnée",
    // Legacy / unused
    "DataSourceGroupName": "Source de données",
    // Main component
    "HideDataSourceButton": "▲ Masquer la source de données",
    "ConfigureDataSourceButton": "▼ Configurer la source de données",
    "RowsLoadedBadge": "✓ {0} lignes chargées",
    "ReadModeLoadError": "Impossible de charger les données : {0}. Passez en mode Édition pour reconfigurer la source de données.",
    "RefreshDataButton": "↻ Actualiser les données",
    "RefreshingLabel": "Actualisation…",
    "RefreshDataTitle": "Recharger les données à partir de la source configurée",
    // Chart renderer
    "NoDataMessage": "Aucune donnée chargée pour le moment. Configurez votre source de données ci-dessus et cliquez sur Charger les données.",
    "SelectMappingsMessage": "Données chargées ({0} lignes). Sélectionnez les correspondances de colonnes ci-dessus pour afficher le graphique.",
    "ChartRenderErrorLabel": "Erreur de rendu du graphique : {0}",
    "UnsupportedChartTypeLabel": "Type de graphique non pris en charge : {0}",
    "ChartAriaLabel": "Graphique de visualisation de données",
    "FilterOperatorLabel": "Opérateur",
    "FilterValueLabel": "Valeur",
    "FilterOpContains": "contient",
    "FilterOpEquals": "est égal à",
    "FilterOpNotEquals": "n'est pas égal à",
    "FilterOpGt": "supérieur à",
    "FilterOpLt": "inférieur à",
    "FilterOpBetween": "entre (bas..haut)",
    "FilterOpIsEmpty": "est vide",
    "FilterOpNotEmpty": "n'est pas vide",
    "AddFilterButton": "+ Ajouter un filtre",
    "RemoveFilterButton": "Supprimer",
    "SelectValuePlaceholder": "Sélectionner une valeur…",
    "ViewerFilterOperatorAria": "Opérateur de filtre",
    "PaletteColorblindLabel": "Adaptée au daltonisme",
    "WaterfallGroupName": "Cascade",
    "WaterfallShowTotalFieldLabel": "Afficher la barre de total",
    "WaterfallPositiveColorFieldLabel": "Couleur d'augmentation",
    "WaterfallNegativeColorFieldLabel": "Couleur de diminution",
    "WaterfallTotalColorFieldLabel": "Couleur du total",
    "WaterfallTotalLabel": "Total",
    "ExternalFilterGroupName": "Filtrer à partir d'un autre composant WebPart",
    "ExternalFilterFieldLabel": "Source de la valeur de filtre",
    "ExternalFilterColumnFieldLabel": "Colonne à filtrer",
    "ExternalFilterColumnPlaceholder": "Colonne de l'axe X par défaut",
    "ViewAsTableButton": "Afficher sous forme de tableau",
    "HideTableButton": "Masquer le tableau",
    "ChartKeyboardHint": "Utilisez les touches fléchées pour passer d'un point de données à l'autre et Entrée pour en sélectionner un.",
    "ChartPointAnnouncement": "{0} : {1}",
    "Y2ValuePrefixFieldLabel": "Préfixe de valeur Y2",
    "Y2ValueSuffixFieldLabel": "Suffixe de valeur Y2",
    "AnnotationsGroupName": "Annotations",
    "AnnotationsFieldLabel": "Annotations",
    "AnnotationsPlaceholder": "Janv, Lancement du produit",
    "AnnotationsHelp": "Une par ligne : la valeur de l'axe X, une virgule, puis le texte de la note. Un repère vertical est tracé à cette valeur X.",
    "BeforeLabel": "Avant",
    "AfterLabel": "Après",
    "RowLabel": "Ligne {0}",
    "PointsSuffix": " (points)",
    "ExportSheetName": "Données",
    "RefreshFailedNote": "Échec de la dernière actualisation : {0}. Affichage des données chargées précédemment.",
    "TruncatedDataNote": "Seules les {0} premières lignes sont affichées ; la source contient davantage de données.",
    "ScatterNumericWarning": "Les nuages de points et les graphiques à bulles nécessitent des valeurs numériques. La colonne \"{0}\" ne contient aucune donnée numérique — choisissez une autre colonne dans la correspondance ci-dessus.",
    "TimeAxisUnparseableWarning": "La colonne de l'axe X \"{0}\" ne contient aucune valeur pouvant être interprétée comme une date. Définissez le type d'axe X sur \"Catégorie\", ou associez une colonne de dates.",
    // Data source panel
    "DataSourceSectionHeader": "Source de données",
    "SourceUploadLabel": "Charger un fichier",
    "SourceSharePointListLabel": "Liste SharePoint",
    "SourceSharePointFileLabel": "Fichier SharePoint",
    "SourceRestApiLabel": "API REST",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Chemin de l'API Graph",
    "GraphPathHelp": "Chemin Microsoft Graph relatif, p. ex. /me/memberOf ou /reports/getTeamsUserActivityUserCounts(period='D7'). Cette source nécessite des autorisations Graph approuvées par un administrateur — toutes les autres sources de données fonctionnent sans elles.",
    "SheetNameLabel": "Feuille Excel",
    "DelimiterLabel": "Délimiteur",
    "DelimiterAutoDetect": "Détection automatique",
    "DelimiterComma": "Virgule (,)",
    "DelimiterTab": "Tabulation",
    "DelimiterSemicolon": "Point-virgule (;)",
    "DelimiterPipe": "Barre verticale (|)",
    "SiteUrlLabel": "URL du site (facultatif)",
    "SiteUrlHelp": "Laissez vide pour utiliser le site actuel.",
    "ListNameLabel": "Nom de la liste",
    "LoadingListsLabel": "— Chargement des listes…",
    "SelectListPlaceholder": "— Sélectionner une liste —",
    "EnterListNamePlaceholder": "Entrez le nom de la liste",
    "ListNameExamplePlaceholder": "p. ex. Données de ventes",
    "ListDiscoveryError": "Impossible de charger les listes — entrez le nom manuellement ci-dessous.",
    "FileUrlLabel": "URL du fichier (CSV/TSV/Excel dans SharePoint)",
    "FileUrlHelp": "URL complète d'un fichier dans une bibliothèque de documents.",
    "ApiUrlLabel": "URL de l'API",
    "DataPathLabel": "Chemin des données (facultatif)",
    "DataPathHelp": "Chemin séparé par des points vers le tableau dans la réponse JSON. Laissez vide si la racine est un tableau. Pour l'API REST SharePoint, utilisez \"value\".",
    "UploadHelp": "Chargez un fichier CSV, TSV ou Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} lignes",
    "ChangeFileButton": "Changer de fichier…",
    "ClearButton": "Effacer",
    "ChooseFileButton": "Choisir un fichier…",
    "LoadDataButton": "Charger les données",
    "LoadingLabel": "Chargement…",
    "ErrorSelectListName": "Veuillez sélectionner ou entrer un nom de liste.",
    "ErrorEnterFileUrl": "Veuillez entrer l'URL d'un fichier.",
    "ErrorEnterUrl": "Veuillez entrer une URL.",
    "ErrorLoadList": "Échec du chargement de la liste SharePoint : {0}",
    "ErrorLoadFile": "Échec du chargement du fichier : {0}",
    "ErrorFetchData": "Échec de la récupération des données : {0}",
    "ErrorDataPathNotFound": "Le chemin de données \"{0}\" est introuvable dans la réponse.",
    "ErrorUrlReturnedHtml": "Cette URL a renvoyé une page web, et non un fichier. Utilisez le chemin de téléchargement direct du fichier, et non une URL de partage \"Copier le lien\".",
    "ErrorRequestTimedOut": "La requête a expiré. Vérifiez l'URL et votre connexion réseau.",
    "ErrorNonJsonResponse": "La réponse n'a pas pu être analysée en tant que JSON.",
    "ErrorUnsupportedFileType": "Type de fichier non pris en charge. Veuillez charger un fichier .csv, .tsv, .xlsx ou .xls.",
    "ErrorReadFile": "Échec de la lecture du fichier",
    "ErrorParseFile": "Échec de l'analyse du fichier",
    "LoadedRowsColumns": "{0} lignes chargées avec {1} colonnes.",
    "LoadedRowsColumnsPersist": "{0} lignes chargées avec {1} colonnes. Les données seront conservées lorsque vous quitterez la page.",
    "SizeWarning": "Le jeu de données ({0} Ko) dépasse la limite de persistance de 200 Ko. Le graphique affichera les données durant cette session, mais elles seront effacées au rechargement de la page. Pour les fichiers volumineux, chargez-les dans une bibliothèque SharePoint et utilisez la source Fichier SharePoint.",
    "ListTruncatedWarning": "Cette liste contient {0} éléments ou plus ; seuls les {0} premiers ont été chargés.",
    "GraphTruncatedWarning": "Ce résultat Microsoft Graph comporte plus de pages que ce qui a pu être chargé ; seules les {0} premières pages ont été récupérées.",
    "CsvParseWarning": "{0} ligne(s) n'ont pas pu être analysées et ont été ignorées.",
    // Column mapper
    "ColumnMappingSectionHeader": "Correspondance des colonnes",
    "CategoryColumnLabel": "Colonne de catégorie (X / étiquettes)",
    "LabelColumnLabel": "Colonne d'étiquette",
    "XAxisColumnLabel": "Colonne de l'axe X",
    "ValueColumnLabel": "Colonne de valeur",
    "YAxisColumnLabel": "Colonne de l'axe Y",
    "YAxisColumnsLabel": "Colonne(s) de l'axe Y",
    "YAxisColumnsHelp": "(sélectionnez-en une ou plusieurs ; cliquez sur l'échantillon pour définir la couleur)",
    "SelectColumnPlaceholder": "— Sélectionner une colonne —",
    "ScatterLabelColumnLabel": "Étiquette du point",
    "SizeColumnLabel":"Colonne de taille / rayon",
    "NoSizeColumnOption": "— Aucune (taille fixe) —",
    "SeriesColorTitle": "Couleur pour {0}",
    "SeriesTypeTitle": "Type de graphique pour {0}",
    "SeriesTypeDefault": "Par défaut",
    "SeriesTypeBar": "Barres",
    "SeriesTypeLine": "Courbe",
    "HistogramColumnLabel": "Colonne à répartir en classes (numérique)",
    "TreemapGroupLabel": "Colonne de groupe / étiquette",
    "HeatmapColumnLabel": "Catégorie de colonne (X)",
    "HeatmapRowLabel": "Catégorie de ligne (Y)",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ Options avancées",
    "AdvancedOptionsOpen": "▲ Options avancées",
    "ColorByLabel": "Colorer par colonne",
    "ColorByHelp": "Colorer les points par catégorie plutôt que par série.",
    "TooltipColumnsLabel": "Colonnes de l'info-bulle",
    "TooltipColumnsHelp": "(colonnes supplémentaires affichées au survol d'un point de données)",
    "DrillLevelLabel": "Niveau d'exploration {0}",
    "DrillDownHelp": "Définissez une hiérarchie de colonnes pour activer l'exploration par clic (p. ex. Région → Pays → Ville). Les valeurs sont agrégées à chaque niveau.",
    "BookmarksLabel": "Signets",
    "BookmarkNameLabel": "Nom du signet",
    "BookmarkNamePlaceholder": "p. ex. Top 10 par région",
    "SaveBookmarkButton": "Enregistrer la vue actuelle",
    "ApplyBookmarkButton": "Appliquer",
    "DeleteBookmarkButton": "Supprimer",
    "ApplyBookmarkPlaceholder": "— Appliquer un signet —",
    // Data controls
    "DataControlsSectionHeader": "Contrôles des données",
    "SortByColumnLabel": "Trier par colonne",
    "NoneOption": "— Aucun —",
    "SortDirectionLabel": "Sens du tri",
    "AscendingOption": "Croissant",
    "DescendingOption": "Décroissant",
    "RowLimitLabel": "Limite de lignes (0 = toutes)",
    "FilterColumnLabel": "Colonne de filtre",
    "FilterContainsLabel": "Filtre : contient",
    "FilterValuePlaceholder": "Valeur de filtre…",
    "GroupByLabel": "Regrouper par colonne",
    "AggregationLabel": "Agrégation",
    "GroupByHelp": "Les colonnes numériques sont agrégées par groupe. Nombre ajoute une colonne \"Nombre\".",
    "AggNone": "Aucune",
    "AggSum": "Somme",
    "AggAvg": "Moyenne",
    "AggCount": "Nombre",
    "AggMin": "Min",
    "AggMax": "Max",
    // Data table
    "DataTableHeader": "Tableau de données ({0} lignes)",
    "PrevPageButton": "← Préc.",
    "NextPageButton": "Suiv. →",
    "PageOfLabel": "Page {0} sur {1}",
    // Export bar
    "ExportLabel": "Exporter :",
    "ExportPngTitle": "Télécharger le graphique au format PNG",
    "ExportJpegTitle": "Télécharger le graphique au format JPEG",
    "ExportCsvTitle": "Télécharger les données au format CSV",
    "ExportExcelTitle": "Télécharger les données sous forme de classeur Excel"
  }
});
