define([], function() {
  return {
    "PropertyPaneDescription": "הגדרת ויזואליזציית הנתונים",
    // Header
    "HeaderGroupName": "כותרת",
    "WebPartHeaderFieldLabel": "טקסט כותרת",
    "WebPartHeaderPlaceholder": "לדוגמה: לוח מחוונים של מכירות",
    "ShowWebPartHeaderFieldLabel": "הצג כותרת",
    // Chart Settings group
    "ChartSettingsGroupName": "הגדרות תרשים",
    "ChartTitleFieldLabel": "כותרת התרשים",
    "ChartTypeFieldLabel": "סוג תרשים",
    "LegendPositionFieldLabel": "מיקום מקרא",
    "ChartHeightFieldLabel": "גובה התרשים (px)",
    "ShowLegendFieldLabel": "הצג מקרא",
    "StackedFieldLabel": "מוערם (עמודות/קו)",
    "ShowDataTableFieldLabel": "הצג טבלת נתונים",
    "ShowExportBarFieldLabel": "הצג סרגל ייצוא",
    "XAxisLabelFieldLabel": "תווית ציר X (אופציונלי)",
    "XAxisPlaceholder": "ברירת המחדל היא העמודה שנבחרה",
    "YAxisLabelFieldLabel": "תווית ציר Y (אופציונלי)",
    "YAxisPlaceholder": "ברירת המחדל היא העמודות שנבחרו",
    // Chart type group headers
    "ChartGroupStandard": "תרשימים רגילים",
    "ChartGroupSpecialized": "תרשימים מיוחדים",
    // Chart type options
    "ChartTypeBarLabel": "תרשים עמודות (אנכי)",
    "ChartTypeHorizontalBarLabel": "תרשים עמודות (אופקי)",
    "ChartTypeLineLabel": "תרשים קו",
    "ChartTypeAreaLabel": "תרשים שטח",
    "ChartTypeScatterLabel": "תרשים פיזור",
    "ChartTypePieLabel": "תרשים עוגה",
    "ChartTypeDoughnutLabel": "תרשים טבעת",
    "ChartTypeBubbleLabel": "תרשים בועות",
    "ChartTypeRadarLabel": "תרשים מכ\"ם",
    "ChartTypeKpiLabel": "אריח KPI",
    "ChartTypeHistogramLabel": "היסטוגרמה",
    "ChartTypeWaterfallLabel": "תרשים מפל",
    "ChartTypeBoxplotLabel": "תרשים קופסה",
    "ChartTypeViolinLabel": "תרשים כינור",
    "ChartTypeBeforeAfterLabel": "תרשים לפני-אחרי",
    "ChartTypeTreemapLabel": "מפת עץ",
    "ChartTypeHeatmapLabel": "מפת חום",
    "HistogramBinsFieldLabel": "מקטעי היסטוגרמה",
    "AppearancePageDescription": "צבעים, תוויות וצירים",
    "AdvancedPageDescription": "ניתוח, קווי ייחוס, אינטראקטיביות ורענון נתונים",
    // Legend position options
    "LegendTopLabel": "למעלה",
    "LegendBottomLabel": "למטה",
    "LegendLeftLabel": "שמאל",
    "LegendRightLabel": "ימין",
    // Colors group
    "ColorsGroupName": "צבעים",
    "ColorPaletteFieldLabel": "לוח צבעים",
    "PaletteOfficeLabel": "Office (ברירת מחדל)",
    "PaletteVibrantLabel": "תוסס",
    "PalettePastelLabel": "פסטל",
    "PaletteMonochromeLabel": "מונוכרום",
    "PaletteTrafficLightLabel": "רמזור",
    "PaletteWarmLabel": "חם",
    "PaletteCoolLabel": "קר",
    // Data Labels group
    "DataLabelsGroupName": "תוויות נתונים ועיצוב",
    "ShowDataLabelsFieldLabel": "הצג תוויות נתונים",
    "ValuePrefixFieldLabel": "קידומת ערך",
    "ValuePrefixPlaceholder": "לדוגמה: ₪",
    "ValueSuffixFieldLabel": "סיומת ערך",
    "ValueSuffixPlaceholder": "לדוגמה: %",
    "ValueDecimalsFieldLabel": "מספר ספרות אחרי הנקודה",
    "AbbreviateNumbersFieldLabel": "קצר מספרים (K/M)",
    // Axes & Grid group
    "AxesGridGroupName": "צירים ורשת",
    "YAxisMinFieldLabel": "מינימום ציר Y",
    "YAxisMaxFieldLabel": "מקסימום ציר Y",
    "AutoPlaceholder": "אוטומטי",
    "NumericValidationError": "הזן מספר, או השאר ריק לערך אוטומטי.",
    "ColorValidationError": "הזן צבע הקסדצימלי (לדוגמה #d13438), או השאר ריק לברירת המחדל.",
    "LogScaleFieldLabel": "סולם לוגריתמי (Y)",
    "LogScaleXFieldLabel": "סולם לוגריתמי (X)",
    "StepLineFieldLabel": "אינטרפולציית מדרגות",
    "ShowGridLinesFieldLabel": "הצג קווי רשת",
    "XLabelRotationFieldLabel": "סיבוב תוויות X (מעלות)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "סוג ציר X",
    "XAxisTypeAuto": "זיהוי אוטומטי",
    "XAxisTypeCategory": "קטגוריה",
    "XAxisTypeTime": "זמן (תאריכים)",
    // Analytics group
    "AnalyticsGroupName": "ניתוח",
    "TrendlineFieldLabel": "קו מגמה",
    "TrendlineNone": "ללא",
    "TrendlineLinear": "ליניארי",
    "TrendlineMovingAverage": "ממוצע נע",
    "TrendWindowFieldLabel": "חלון ממוצע נע",
    "TrendSuffix": " (מגמה)",
    "ForecastPeriodsFieldLabel": "תקופות תחזית (קו מגמה ליניארי)",
    // Reference line
    "ReferenceLineGroupName": "קו ייחוס",
    "ReferenceLineTypeFieldLabel": "קו ייחוס",
    "ReferenceLineValueFieldLabel": "ערך קבוע",
    "ReferenceLineColorFieldLabel": "צבע קו (הקסדצימלי)",
    "RefLineFixed": "ערך קבוע",
    "RefLineMean": "ממוצע",
    "RefLineMedian": "חציון",
    // Dual Y axis group
    "DualAxisGroupName": "ציר Y כפול",
    "Y2ColumnsFieldLabel": "סדרות הציר הימני (שמות עמודות מופרדים בפסיקים)",
    "Y2ColumnsPlaceholder": "לדוגמה: Margin,Growth",
    "Y2AxisLabelFieldLabel": "תווית הציר הימני",
    "LogScaleY2FieldLabel": "סולם לוגריתמי (ציר ימני)",
    // Error bars group
    "ErrorBarsGroupName": "פסי שגיאה",
    "ErrorBarTypeFieldLabel": "סוג פס שגיאה",
    "ErrorBarTypeNone": "ללא",
    "ErrorBarTypeCustom": "עמודה מותאמת אישית (±)",
    "ErrorBarTypeSd": "סטיית תקן (מחושב)",
    "ErrorBarTypeSem": "טעות תקן של הממוצע (מחושב)",
    "ErrorBarColumnFieldLabel": "עמודת ערך שגיאה",
    // Significance annotations group
    "SignificanceGroupName": "סוגריים של מובהקות",
    "SignificancePairsFieldLabel": "זוגות סוגריים",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "סוגר אחד בכל שורה: col1,col2,label  — לדוגמה GroupA,GroupB,*  או  GroupA,GroupB,p<0.05  (מערך JSON מתקבל גם הוא)",
    "BeforeAfterColumnsError": "תרשים לפני-אחרי דורש בדיוק 2 עמודות Y — אחת לערכי \"לפני\" ואחת לערכי \"אחרי\".",
    // Interactivity
    "InteractivityGroupName": "אינטראקטיביות",
    "ShowViewerFiltersFieldLabel": "הצג מסננים לצופים",
    "DetailsOnDemandFieldLabel": "הצג שורות נתונים בלחיצה",
    "ShowDataPointsFieldLabel": "הצג נקודות נתונים מעל העמודות",
    "ShowBubbleSizeLegendFieldLabel": "הצג מקרא גודל בועות",
    "ViewerFilterLabel": "מסנן:",
    "ViewerFilterColumnAria": "עמודת מסנן",
    "ViewerFilterValueAria": "ערך מסנן",
    "DrillAllLabel": "הכול",
    "DetailsChipLabel": "פרטים: {0} ({1} שורות)",
    // KPI
    "KpiSubLabel": "{0} • {1} • {2} שורות",
    // Conditional formatting group
    "ConditionalGroupName": "עיצוב מותנה",
    "ThresholdValueFieldLabel": "ערך סף",
    "ThresholdValuePlaceholder": "כבוי",
    "ThresholdDirectionFieldLabel": "הדגש ערכים",
    "ThresholdBelow": "מתחת לסף",
    "ThresholdAbove": "מעל הסף",
    "ThresholdColorFieldLabel": "צבע הדגשה (הקסדצימלי)",
    // Data & refresh group
    "DataRefreshGroupName": "נתונים ורענון",
    "RefreshIntervalFieldLabel": "מרווח רענון אוטומטי (דקות, 0 = כבוי)",
    "CacheMinutesFieldLabel": "שמירת נתונים במטמון (דקות, 0 = כבוי)",
    // Dynamic data
    "DynamicDataCategoryLabel": "קטגוריה שנבחרה",
    "DynamicDataValueLabel": "ערך שנבחר",
    "DynamicDataSeriesLabel": "סדרה שנבחרה",
    // Legacy / unused
    "DataSourceGroupName": "מקור נתונים",
    // Main component
    "HideDataSourceButton": "▲ הסתר מקור נתונים",
    "ConfigureDataSourceButton": "▼ הגדר מקור נתונים",
    "RowsLoadedBadge": "✓ נטענו {0} שורות",
    "ReadModeLoadError": "לא ניתן לטעון נתונים: {0}. עבור למצב עריכה כדי להגדיר מחדש את מקור הנתונים.",
    "RefreshDataButton": "↻ רענן נתונים",
    "RefreshingLabel": "מרענן…",
    "RefreshDataTitle": "טען מחדש נתונים מהמקור שהוגדר",
    // Chart renderer
    "NoDataMessage": "עדיין לא נטענו נתונים. הגדר את מקור הנתונים למעלה ולחץ על טען נתונים.",
    "SelectMappingsMessage": "הנתונים נטענו ({0} שורות). בחר מיפויי עמודות למעלה כדי להציג את התרשים.",
    "ChartRenderErrorLabel": "שגיאה בעיבוד התרשים: {0}",
    "UnsupportedChartTypeLabel": "סוג תרשים לא נתמך: {0}",
    "ChartAriaLabel": "תרשים ויזואליזציית נתונים",
    "FilterOperatorLabel": "אופרטור",
    "FilterValueLabel": "ערך",
    "FilterOpContains": "מכיל",
    "FilterOpEquals": "שווה ל",
    "FilterOpNotEquals": "אינו שווה ל",
    "FilterOpGt": "גדול מ",
    "FilterOpLt": "קטן מ",
    "FilterOpBetween": "בין (נמוך..גבוה)",
    "FilterOpIsEmpty": "ריק",
    "FilterOpNotEmpty": "אינו ריק",
    "AddFilterButton": "+ הוסף מסנן",
    "RemoveFilterButton": "הסר",
    "SelectValuePlaceholder": "בחר ערך…",
    "ViewerFilterOperatorAria": "אופרטור מסנן",
    "PaletteColorblindLabel": "מותאם לעיוורון צבעים",
    "WaterfallGroupName": "מפל",
    "WaterfallShowTotalFieldLabel": "הצג עמודת סכום כולל",
    "WaterfallPositiveColorFieldLabel": "צבע עלייה",
    "WaterfallNegativeColorFieldLabel": "צבע ירידה",
    "WaterfallTotalColorFieldLabel": "צבע סכום כולל",
    "WaterfallTotalLabel": "סך הכול",
    "ExternalFilterGroupName": "סינון מרכיב Web Part אחר",
    "ExternalFilterFieldLabel": "מקור ערך המסנן",
    "ExternalFilterColumnFieldLabel": "עמודה לסינון",
    "ExternalFilterColumnPlaceholder": "ברירת המחדל היא עמודת ציר X",
    "ViewAsTableButton": "הצג כטבלה",
    "HideTableButton": "הסתר טבלה",
    "ChartKeyboardHint": "השתמש במקשי החצים כדי לעבור בין נקודות נתונים וב-Enter כדי לבחור אחת.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "קידומת ערך Y2",
    "Y2ValueSuffixFieldLabel": "סיומת ערך Y2",
    "AnnotationsGroupName": "הערות",
    "AnnotationsFieldLabel": "הערות",
    "AnnotationsPlaceholder": "ינואר, השקת מוצר",
    "AnnotationsHelp": "אחת בכל שורה: ערך ציר X, פסיק, ולאחריו טקסט ההערה. סמן אנכי יצויר בערך X זה.",
    "BeforeLabel": "לפני",
    "AfterLabel": "אחרי",
    "RowLabel": "שורה {0}",
    "PointsSuffix": " (נקודות)",
    "ExportSheetName": "נתונים",
    "RefreshFailedNote": "הרענון האחרון נכשל: {0}. מוצגים נתונים שנטענו קודם.",
    "TruncatedDataNote": "מוצגות רק {0} השורות הראשונות; במקור יש עוד נתונים.",
    "ScatterNumericWarning": "תרשימי פיזור ובועות דורשים ערכים מספריים. בעמודה \"{0}\" אין נתונים מספריים — בחר עמודה אחרת במיפוי למעלה.",
    "TimeAxisUnparseableWarning": "בעמודת ציר X‏ \"{0}\" אין ערכים שניתן לפרש כתאריכים. שנה את סוג ציר X ל\"קטגוריה\", או מפה עמודת תאריכים.",
    // Data source panel
    "DataSourceSectionHeader": "מקור נתונים",
    "SourceUploadLabel": "העלה קובץ",
    "SourceSharePointListLabel": "רשימת SharePoint",
    "SourceSharePointFileLabel": "קובץ SharePoint",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "נתיב Graph API",
    "GraphPathHelp": "נתיב יחסי של Microsoft Graph, לדוגמה /me/memberOf או /reports/getTeamsUserActivityUserCounts(period='D7'). מקור זה דורש הרשאות Graph שאושרו על ידי מנהל מערכת — כל מקורות הנתונים האחרים פועלים בלעדיהן.",
    "SheetNameLabel": "גיליון Excel",
    "DelimiterLabel": "תו מפריד",
    "DelimiterAutoDetect": "זיהוי אוטומטי",
    "DelimiterComma": "פסיק (,)",
    "DelimiterTab": "טאב",
    "DelimiterSemicolon": "נקודה-פסיק (;)",
    "DelimiterPipe": "קו אנכי (|)",
    "SiteUrlLabel": "כתובת URL של האתר (אופציונלי)",
    "SiteUrlHelp": "השאר ריק כדי להשתמש באתר הנוכחי.",
    "ListNameLabel": "שם הרשימה",
    "LoadingListsLabel": "— טוען רשימות…",
    "SelectListPlaceholder": "— בחר רשימה —",
    "EnterListNamePlaceholder": "הזן שם רשימה",
    "ListNameExamplePlaceholder": "לדוגמה: נתוני מכירות",
    "ListDiscoveryError": "לא ניתן לטעון רשימות — הזן שם באופן ידני למטה.",
    "FileUrlLabel": "כתובת URL של הקובץ (CSV/TSV/Excel ב-SharePoint)",
    "FileUrlHelp": "כתובת URL מלאה של קובץ בספריית מסמכים.",
    "ApiUrlLabel": "כתובת URL של ה-API",
    "DataPathLabel": "נתיב נתונים (אופציונלי)",
    "DataPathHelp": "נתיב מופרד בנקודות אל המערך בתגובת ה-JSON. השאר ריק אם השורש הוא מערך. עבור SharePoint REST API השתמש ב-\"value\".",
    "UploadHelp": "העלה קובץ CSV,‏ TSV או Excel ‏(.xlsx,‏ .xls).",
    "LoadedFileRowsLabel": "— {0} שורות",
    "ChangeFileButton": "החלף קובץ…",
    "ClearButton": "נקה",
    "ChooseFileButton": "בחר קובץ…",
    "LoadDataButton": "טען נתונים",
    "LoadingLabel": "טוען…",
    "ErrorSelectListName": "בחר שם רשימה או הזן אותו.",
    "ErrorEnterFileUrl": "הזן כתובת URL של קובץ.",
    "ErrorEnterUrl": "הזן כתובת URL.",
    "ErrorLoadList": "טעינת רשימת SharePoint נכשלה: {0}",
    "ErrorLoadFile": "טעינת הקובץ נכשלה: {0}",
    "ErrorFetchData": "אחזור הנתונים נכשל: {0}",
    "ErrorDataPathNotFound": "נתיב הנתונים \"{0}\" לא נמצא בתגובה.",
    "ErrorUrlReturnedHtml": "כתובת URL זו החזירה דף אינטרנט ולא קובץ. השתמש בנתיב ההורדה הישיר של הקובץ, ולא בכתובת שיתוף מסוג \"העתק קישור\".",
    "ErrorRequestTimedOut": "תם הזמן הקצוב לבקשה. בדוק את כתובת ה-URL ואת חיבור הרשת שלך.",
    "ErrorNonJsonResponse": "לא ניתן היה לנתח את התגובה כ-JSON.",
    "ErrorUnsupportedFileType": "סוג קובץ לא נתמך. העלה קובץ מסוג CSV, TSV, XLSX או XLS.",
    "ErrorReadFile": "קריאת הקובץ נכשלה",
    "ErrorParseFile": "ניתוח הקובץ נכשל",
    "LoadedRowsColumns": "נטענו {0} שורות עם {1} עמודות.",
    "LoadedRowsColumnsPersist": "נטענו {0} שורות עם {1} עמודות. הנתונים יישמרו לאחר שתעזוב את הדף.",
    "SizeWarning": "מערך הנתונים ({0}KB) חורג ממגבלת השמירה של 200KB. התרשים יציג נתונים במהלך הפעלה זו אך הם יימחקו בטעינה מחדש של הדף. עבור קבצים גדולים, העלה אותם לספריית SharePoint והשתמש במקור קובץ SharePoint.",
    "ListTruncatedWarning": "ברשימה זו יש {0} פריטים או יותר; נטענו רק {0} הראשונים.",
    "GraphTruncatedWarning": "בתוצאת Microsoft Graph זו יש יותר עמודים ממה שניתן היה לטעון; נאחזרו רק {0} העמודים הראשונים.",
    "CsvParseWarning": "לא ניתן היה לנתח {0} שורות והן דולגו.",
    // Column mapper
    "ColumnMappingSectionHeader": "מיפוי עמודות",
    "CategoryColumnLabel": "עמודת קטגוריה (X / תוויות)",
    "LabelColumnLabel": "עמודת תווית",
    "XAxisColumnLabel": "עמודת ציר X",
    "ValueColumnLabel": "עמודת ערך",
    "YAxisColumnLabel": "עמודת ציר Y",
    "YAxisColumnsLabel": "עמודות ציר Y",
    "YAxisColumnsHelp": "(בחר אחת או יותר; לחץ על דוגמית הצבע כדי להגדיר צבע)",
    "SelectColumnPlaceholder": "— בחר עמודה —",
    "ScatterLabelColumnLabel": "תווית נקודה",
    "SizeColumnLabel":"עמודת גודל / רדיוס",
    "NoSizeColumnOption": "— ללא (גודל קבוע) —",
    "SeriesColorTitle": "צבע עבור {0}",
    "SeriesTypeTitle": "סוג תרשים עבור {0}",
    "SeriesTypeDefault": "ברירת מחדל",
    "SeriesTypeBar": "עמודות",
    "SeriesTypeLine": "קו",
    "HistogramColumnLabel": "עמודה לחלוקה למקטעים (מספרית)",
    "TreemapGroupLabel": "עמודת קבוצה / תווית",
    "HeatmapColumnLabel": "קטגוריית עמודה (X)",
    "HeatmapRowLabel": "קטגוריית שורה (Y)",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ אפשרויות מתקדמות",
    "AdvancedOptionsOpen": "▲ אפשרויות מתקדמות",
    "ColorByLabel": "צבע לפי עמודה",
    "ColorByHelp": "צבע נקודות לפי קטגוריה ולא לפי סדרה.",
    "TooltipColumnsLabel": "עמודות של הסבר כלי",
    "TooltipColumnsHelp": "(עמודות נוספות המוצגות בעת ריחוף מעל נקודת נתונים)",
    "DrillLevelLabel": "רמת חדירה {0}",
    "DrillDownHelp": "הגדר היררכיית עמודות כדי לאפשר חדירה בלחיצה (לדוגמה אזור ← מדינה ← עיר). הערכים מסוכמים בכל רמה.",
    "BookmarksLabel": "סימניות",
    "BookmarkNameLabel": "שם הסימנייה",
    "BookmarkNamePlaceholder": "לדוגמה: 10 המובילים לפי אזור",
    "SaveBookmarkButton": "שמור תצוגה נוכחית",
    "ApplyBookmarkButton": "החל",
    "DeleteBookmarkButton": "מחק",
    "ApplyBookmarkPlaceholder": "— החל סימנייה —",
    // Data controls
    "DataControlsSectionHeader": "בקרות נתונים",
    "SortByColumnLabel": "מיין לפי עמודה",
    "NoneOption": "— ללא —",
    "SortDirectionLabel": "כיוון מיון",
    "AscendingOption": "עולה",
    "DescendingOption": "יורד",
    "RowLimitLabel": "מגבלת שורות (0 = הכול)",
    "FilterColumnLabel": "עמודת מסנן",
    "FilterContainsLabel": "מסנן: מכיל",
    "FilterValuePlaceholder": "ערך מסנן…",
    "GroupByLabel": "קבץ לפי עמודה",
    "AggregationLabel": "צבירה",
    "GroupByHelp": "עמודות מספריות מסוכמות לכל קבוצה. ספירה מוסיפה עמודת \"ספירה\".",
    "AggNone": "ללא",
    "AggSum": "סכום",
    "AggAvg": "ממוצע",
    "AggCount": "ספירה",
    "AggMin": "מינימום",
    "AggMax": "מקסימום",
    // Data table
    "DataTableHeader": "טבלת נתונים ({0} שורות)",
    "PrevPageButton": "→ הקודם",
    "NextPageButton": "הבא ←",
    "PageOfLabel": "עמוד {0} מתוך {1}",
    // Export bar
    "ExportLabel": "ייצוא:",
    "ExportPngTitle": "הורד תרשים כתמונת PNG",
    "ExportJpegTitle": "הורד תרשים כתמונת JPEG",
    "ExportCsvTitle": "הורד נתונים כ-CSV",
    "ExportExcelTitle": "הורד נתונים כחוברת עבודה של Excel"
  }
});
