define([], function() {
  return {
    "PropertyPaneDescription": "अपना डेटा विज़ुअलाइज़ेशन कॉन्फ़िगर करें",
    // Header
    "HeaderGroupName": "हेडर",
    "WebPartHeaderFieldLabel": "हेडर टेक्स्ट",
    "WebPartHeaderPlaceholder": "उदा. बिक्री डैशबोर्ड",
    "ShowWebPartHeaderFieldLabel": "हेडर दिखाएँ",
    // Chart Settings group
    "ChartSettingsGroupName": "चार्ट सेटिंग",
    "ChartTitleFieldLabel": "चार्ट शीर्षक",
    "ChartTypeFieldLabel": "चार्ट प्रकार",
    "LegendPositionFieldLabel": "लेजेंड की स्थिति",
    "ChartHeightFieldLabel": "चार्ट की ऊँचाई (px)",
    "ShowLegendFieldLabel": "लेजेंड दिखाएँ",
    "StackedFieldLabel": "स्टैक्ड (बार/लाइन)",
    "ShowDataTableFieldLabel": "डेटा तालिका दिखाएँ",
    "ShowExportBarFieldLabel": "निर्यात बार दिखाएँ",
    "XAxisLabelFieldLabel": "X अक्ष लेबल (वैकल्पिक)",
    "XAxisPlaceholder": "डिफ़ॉल्ट रूप से चयनित कॉलम",
    "YAxisLabelFieldLabel": "Y अक्ष लेबल (वैकल्पिक)",
    "YAxisPlaceholder": "डिफ़ॉल्ट रूप से चयनित कॉलम",
    // Chart type group headers
    "ChartGroupStandard": "मानक चार्ट",
    "ChartGroupSpecialized": "विशिष्ट चार्ट",
    // Chart type options
    "ChartTypeBarLabel": "बार चार्ट (ऊर्ध्वाधर)",
    "ChartTypeHorizontalBarLabel": "बार चार्ट (क्षैतिज)",
    "ChartTypeLineLabel": "लाइन चार्ट",
    "ChartTypeAreaLabel": "एरिया चार्ट",
    "ChartTypeScatterLabel": "स्कैटर प्लॉट",
    "ChartTypePieLabel": "पाई चार्ट",
    "ChartTypeDoughnutLabel": "डोनट चार्ट",
    "ChartTypeBubbleLabel": "बबल चार्ट",
    "ChartTypeRadarLabel": "रडार चार्ट",
    "ChartTypeKpiLabel": "KPI टाइल",
    "ChartTypeHistogramLabel": "हिस्टोग्राम",
    "ChartTypeWaterfallLabel": "वॉटरफ़ॉल चार्ट",
    "ChartTypeBoxplotLabel": "बॉक्स प्लॉट",
    "ChartTypeViolinLabel": "वायलिन प्लॉट",
    "ChartTypeBeforeAfterLabel": "पहले-बाद प्लॉट",
    "ChartTypeTreemapLabel": "ट्रीमैप",
    "ChartTypeHeatmapLabel": "हीटमैप",
    "HistogramBinsFieldLabel": "हिस्टोग्राम बिन",
    "AppearancePageDescription": "रंग, लेबल और अक्ष",
    "AdvancedPageDescription": "विश्लेषण, संदर्भ रेखाएँ, इंटरैक्टिविटी और डेटा रीफ़्रेश",
    // Legend position options
    "LegendTopLabel": "ऊपर",
    "LegendBottomLabel": "नीचे",
    "LegendLeftLabel": "बाएँ",
    "LegendRightLabel": "दाएँ",
    // Colors group
    "ColorsGroupName": "रंग",
    "ColorPaletteFieldLabel": "रंग पैलेट",
    "PaletteOfficeLabel": "Office (डिफ़ॉल्ट)",
    "PaletteVibrantLabel": "चटख",
    "PalettePastelLabel": "पेस्टल",
    "PaletteMonochromeLabel": "एकवर्णी",
    "PaletteTrafficLightLabel": "ट्रैफ़िक लाइट",
    "PaletteWarmLabel": "गर्म",
    "PaletteCoolLabel": "ठंडा",
    // Data Labels group
    "DataLabelsGroupName": "डेटा लेबल और स्वरूपण",
    "ShowDataLabelsFieldLabel": "डेटा लेबल दिखाएँ",
    "ValuePrefixFieldLabel": "मान उपसर्ग",
    "ValuePrefixPlaceholder": "उदा. ₹",
    "ValueSuffixFieldLabel": "मान प्रत्यय",
    "ValueSuffixPlaceholder": "उदा. %",
    "ValueDecimalsFieldLabel": "दशमलव स्थान",
    "AbbreviateNumbersFieldLabel": "संख्याएँ संक्षिप्त करें (K/M)",
    // Axes & Grid group
    "AxesGridGroupName": "अक्ष और ग्रिड",
    "YAxisMinFieldLabel": "Y अक्ष न्यूनतम",
    "YAxisMaxFieldLabel": "Y अक्ष अधिकतम",
    "AutoPlaceholder": "स्वचालित",
    "NumericValidationError": "कोई संख्या दर्ज करें, या स्वचालित के लिए खाली छोड़ें।",
    "ColorValidationError": "हेक्स रंग दर्ज करें (उदा. #d13438), या डिफ़ॉल्ट के लिए खाली छोड़ें।",
    "LogScaleFieldLabel": "लघुगणकीय स्केल (Y)",
    "LogScaleXFieldLabel": "लघुगणकीय स्केल (X)",
    "StepLineFieldLabel": "स्टेप इंटरपोलेशन",
    "ShowGridLinesFieldLabel": "ग्रिड लाइनें दिखाएँ",
    "XLabelRotationFieldLabel": "X लेबल घुमाव (डिग्री)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "X अक्ष प्रकार",
    "XAxisTypeAuto": "स्वतः पहचानें",
    "XAxisTypeCategory": "श्रेणी",
    "XAxisTypeTime": "समय (तिथियाँ)",
    // Analytics group
    "AnalyticsGroupName": "विश्लेषण",
    "TrendlineFieldLabel": "ट्रेंडलाइन",
    "TrendlineNone": "कोई नहीं",
    "TrendlineLinear": "रैखिक",
    "TrendlineMovingAverage": "मूविंग एवरेज",
    "TrendWindowFieldLabel": "मूविंग एवरेज विंडो",
    "TrendSuffix": " (ट्रेंड)",
    "ForecastPeriodsFieldLabel": "पूर्वानुमान अवधियाँ (रैखिक ट्रेंडलाइन)",
    // Reference line
    "ReferenceLineGroupName": "संदर्भ रेखा",
    "ReferenceLineTypeFieldLabel": "संदर्भ रेखा",
    "ReferenceLineValueFieldLabel": "निश्चित मान",
    "ReferenceLineColorFieldLabel": "रेखा का रंग (हेक्स)",
    "RefLineFixed": "निश्चित मान",
    "RefLineMean": "माध्य",
    "RefLineMedian": "माध्यिका",
    // Dual Y axis group
    "DualAxisGroupName": "दोहरा Y अक्ष",
    "Y2ColumnsFieldLabel": "दाएँ अक्ष की श्रृंखला (अल्पविराम से अलग किए गए कॉलम नाम)",
    "Y2ColumnsPlaceholder": "उदा. Margin,Growth",
    "Y2AxisLabelFieldLabel": "दाएँ अक्ष का लेबल",
    "LogScaleY2FieldLabel": "लघुगणकीय स्केल (दायाँ अक्ष)",
    // Error bars group
    "ErrorBarsGroupName": "त्रुटि बार",
    "ErrorBarTypeFieldLabel": "त्रुटि बार प्रकार",
    "ErrorBarTypeNone": "कोई नहीं",
    "ErrorBarTypeCustom": "कस्टम कॉलम (±)",
    "ErrorBarTypeSd": "मानक विचलन (परिकलित)",
    "ErrorBarTypeSem": "माध्य की मानक त्रुटि (परिकलित)",
    "ErrorBarColumnFieldLabel": "त्रुटि मान कॉलम",
    // Significance annotations group
    "SignificanceGroupName": "सार्थकता ब्रैकेट",
    "SignificancePairsFieldLabel": "ब्रैकेट जोड़ियाँ",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "प्रति पंक्ति एक ब्रैकेट: col1,col2,label  — उदा. GroupA,GroupB,*  या  GroupA,GroupB,p<0.05  (JSON ऐरे भी स्वीकार्य है)",
    "BeforeAfterColumnsError": "पहले-बाद चार्ट के लिए ठीक 2 Y कॉलम आवश्यक हैं — एक पहले के मानों के लिए और एक बाद के मानों के लिए।",
    // Interactivity
    "InteractivityGroupName": "इंटरैक्टिविटी",
    "ShowViewerFiltersFieldLabel": "दर्शकों को फ़िल्टर दिखाएँ",
    "DetailsOnDemandFieldLabel": "क्लिक करने पर डेटा पंक्तियाँ दिखाएँ",
    "ShowDataPointsFieldLabel": "बार पर डेटा बिंदु ओवरले करें",
    "ShowBubbleSizeLegendFieldLabel": "बबल आकार लेजेंड दिखाएँ",
    "ViewerFilterLabel": "फ़िल्टर:",
    "ViewerFilterColumnAria": "फ़िल्टर कॉलम",
    "ViewerFilterValueAria": "फ़िल्टर मान",
    "DrillAllLabel": "सभी",
    "DetailsChipLabel": "विवरण: {0} ({1} पंक्तियाँ)",
    // KPI
    "KpiSubLabel": "{0} • {1} • {2} पंक्तियाँ",
    // Conditional formatting group
    "ConditionalGroupName": "सशर्त स्वरूपण",
    "ThresholdValueFieldLabel": "सीमा मान",
    "ThresholdValuePlaceholder": "बंद",
    "ThresholdDirectionFieldLabel": "मान हाइलाइट करें",
    "ThresholdBelow": "सीमा से नीचे",
    "ThresholdAbove": "सीमा से ऊपर",
    "ThresholdColorFieldLabel": "हाइलाइट रंग (हेक्स)",
    // Data & refresh group
    "DataRefreshGroupName": "डेटा और रीफ़्रेश",
    "RefreshIntervalFieldLabel": "स्वतः रीफ़्रेश अंतराल (मिनट, 0 = बंद)",
    "CacheMinutesFieldLabel": "डेटा कैश करें (मिनट, 0 = बंद)",
    // Dynamic data
    "DynamicDataCategoryLabel": "चयनित श्रेणी",
    "DynamicDataValueLabel": "चयनित मान",
    "DynamicDataSeriesLabel": "चयनित श्रृंखला",
    // Legacy / unused
    "DataSourceGroupName": "डेटा स्रोत",
    // Main component
    "HideDataSourceButton": "▲ डेटा स्रोत छिपाएँ",
    "ConfigureDataSourceButton": "▼ डेटा स्रोत कॉन्फ़िगर करें",
    "RowsLoadedBadge": "✓ {0} पंक्तियाँ लोड हुईं",
    "ReadModeLoadError": "डेटा लोड नहीं हो सका: {0}. डेटा स्रोत को दोबारा कॉन्फ़िगर करने के लिए संपादन मोड में जाएँ।",
    "RefreshDataButton": "↻ डेटा रीफ़्रेश करें",
    "RefreshingLabel": "रीफ़्रेश हो रहा है…",
    "RefreshDataTitle": "कॉन्फ़िगर किए गए स्रोत से डेटा फिर से लोड करें",
    // Chart renderer
    "NoDataMessage": "अभी तक कोई डेटा लोड नहीं हुआ है। ऊपर अपना डेटा स्रोत कॉन्फ़िगर करें और डेटा लोड करें पर क्लिक करें।",
    "SelectMappingsMessage": "डेटा लोड हो गया ({0} पंक्तियाँ)। चार्ट दिखाने के लिए ऊपर कॉलम मैपिंग चुनें।",
    "ChartRenderErrorLabel": "चार्ट रेंडरिंग त्रुटि: {0}",
    "UnsupportedChartTypeLabel": "असमर्थित चार्ट प्रकार: {0}",
    "ChartAriaLabel": "डेटा विज़ुअलाइज़ेशन चार्ट",
    "FilterOperatorLabel": "ऑपरेटर",
    "FilterValueLabel": "मान",
    "FilterOpContains": "शामिल है",
    "FilterOpEquals": "बराबर है",
    "FilterOpNotEquals": "बराबर नहीं है",
    "FilterOpGt": "इससे बड़ा",
    "FilterOpLt": "इससे छोटा",
    "FilterOpBetween": "के बीच (निम्न..उच्च)",
    "FilterOpIsEmpty": "खाली है",
    "FilterOpNotEmpty": "खाली नहीं है",
    "AddFilterButton": "+ फ़िल्टर जोड़ें",
    "RemoveFilterButton": "निकालें",
    "SelectValuePlaceholder": "मान चुनें…",
    "ViewerFilterOperatorAria": "फ़िल्टर ऑपरेटर",
    "PaletteColorblindLabel": "रंग-अंधता के अनुकूल",
    "WaterfallGroupName": "वॉटरफ़ॉल",
    "WaterfallShowTotalFieldLabel": "कुल बार दिखाएँ",
    "WaterfallPositiveColorFieldLabel": "वृद्धि का रंग",
    "WaterfallNegativeColorFieldLabel": "कमी का रंग",
    "WaterfallTotalColorFieldLabel": "कुल का रंग",
    "WaterfallTotalLabel": "कुल",
    "ExternalFilterGroupName": "किसी अन्य वेब पार्ट से फ़िल्टर करें",
    "ExternalFilterFieldLabel": "फ़िल्टर मान का स्रोत",
    "ExternalFilterColumnFieldLabel": "फ़िल्टर करने के लिए कॉलम",
    "ExternalFilterColumnPlaceholder": "डिफ़ॉल्ट रूप से X अक्ष कॉलम",
    "ViewAsTableButton": "तालिका के रूप में देखें",
    "HideTableButton": "तालिका छिपाएँ",
    "ChartKeyboardHint": "डेटा बिंदुओं के बीच जाने के लिए तीर कुंजियों का और किसी एक को चुनने के लिए Enter का उपयोग करें।",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Y2 मान उपसर्ग",
    "Y2ValueSuffixFieldLabel": "Y2 मान प्रत्यय",
    "AnnotationsGroupName": "टिप्पणियाँ",
    "AnnotationsFieldLabel": "टिप्पणियाँ",
    "AnnotationsPlaceholder": "जन., उत्पाद लॉन्च",
    "AnnotationsHelp": "प्रति पंक्ति एक: X अक्ष का मान, एक अल्पविराम, फिर टिप्पणी का पाठ। उस X मान पर एक ऊर्ध्वाधर मार्कर बनाया जाता है।",
    "BeforeLabel": "पहले",
    "AfterLabel": "बाद में",
    "RowLabel": "पंक्ति {0}",
    "PointsSuffix": " (बिंदु)",
    "ExportSheetName": "डेटा",
    "RefreshFailedNote": "पिछला रीफ़्रेश विफल रहा: {0}. पहले लोड किया गया डेटा दिखाया जा रहा है।",
    "TruncatedDataNote": "केवल पहली {0} पंक्तियाँ दिखाई गई हैं; स्रोत में और डेटा है।",
    "ScatterNumericWarning": "स्कैटर और बबल चार्ट के लिए संख्यात्मक मान आवश्यक हैं। कॉलम \"{0}\" में कोई संख्यात्मक डेटा नहीं है — ऊपर मैपिंग में कोई दूसरा कॉलम चुनें।",
    "TimeAxisUnparseableWarning": "X अक्ष कॉलम \"{0}\" में ऐसे कोई मान नहीं हैं जिन्हें तिथि के रूप में पार्स किया जा सके। X अक्ष प्रकार को \"श्रेणी\" पर सेट करें, या कोई तिथि कॉलम मैप करें।",
    // Data source panel
    "DataSourceSectionHeader": "डेटा स्रोत",
    "SourceUploadLabel": "फ़ाइल अपलोड करें",
    "SourceSharePointListLabel": "SharePoint सूची",
    "SourceSharePointFileLabel": "SharePoint फ़ाइल",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API पथ",
    "GraphPathHelp": "सापेक्ष Microsoft Graph पथ, उदा. /me/memberOf या /reports/getTeamsUserActivityUserCounts(period='D7')। इस स्रोत के लिए व्यवस्थापक द्वारा अनुमोदित Graph अनुमतियाँ आवश्यक हैं — अन्य सभी डेटा स्रोत इनके बिना काम करते हैं।",
    "SheetNameLabel": "Excel शीट",
    "DelimiterLabel": "सीमांकक",
    "DelimiterAutoDetect": "स्वतः पहचानें",
    "DelimiterComma": "अल्पविराम (,)",
    "DelimiterTab": "टैब",
    "DelimiterSemicolon": "अर्धविराम (;)",
    "DelimiterPipe": "पाइप (|)",
    "SiteUrlLabel": "साइट URL (वैकल्पिक)",
    "SiteUrlHelp": "वर्तमान साइट का उपयोग करने के लिए खाली छोड़ें।",
    "ListNameLabel": "सूची का नाम",
    "LoadingListsLabel": "— सूचियाँ लोड हो रही हैं…",
    "SelectListPlaceholder": "— सूची चुनें —",
    "EnterListNamePlaceholder": "सूची का नाम दर्ज करें",
    "ListNameExamplePlaceholder": "उदा. बिक्री डेटा",
    "ListDiscoveryError": "सूचियाँ लोड नहीं हो सकीं — नीचे नाम मैन्युअल रूप से दर्ज करें।",
    "FileUrlLabel": "फ़ाइल URL (SharePoint में CSV/TSV/Excel)",
    "FileUrlHelp": "दस्तावेज़ लाइब्रेरी में किसी फ़ाइल का पूरा URL।",
    "ApiUrlLabel": "API URL",
    "DataPathLabel": "डेटा पथ (वैकल्पिक)",
    "DataPathHelp": "JSON प्रतिक्रिया में ऐरे तक बिंदु-विभाजित पथ। यदि रूट एक ऐरे है तो खाली छोड़ें। SharePoint REST API के लिए \"value\" का उपयोग करें।",
    "UploadHelp": "CSV, TSV या Excel (.xlsx, .xls) फ़ाइल अपलोड करें।",
    "LoadedFileRowsLabel": "— {0} पंक्तियाँ",
    "ChangeFileButton": "फ़ाइल बदलें…",
    "ClearButton": "साफ़ करें",
    "ChooseFileButton": "फ़ाइल चुनें…",
    "LoadDataButton": "डेटा लोड करें",
    "LoadingLabel": "लोड हो रहा है…",
    "ErrorSelectListName": "कृपया सूची का नाम चुनें या दर्ज करें।",
    "ErrorEnterFileUrl": "कृपया फ़ाइल URL दर्ज करें।",
    "ErrorEnterUrl": "कृपया URL दर्ज करें।",
    "ErrorLoadList": "SharePoint सूची लोड करने में विफल: {0}",
    "ErrorLoadFile": "फ़ाइल लोड करने में विफल: {0}",
    "ErrorFetchData": "डेटा प्राप्त करने में विफल: {0}",
    "ErrorDataPathNotFound": "डेटा पथ \"{0}\" प्रतिक्रिया में नहीं मिला।",
    "ErrorUrlReturnedHtml": "इस URL ने फ़ाइल के बजाय एक वेब पेज लौटाया। सीधे फ़ाइल डाउनलोड पथ का उपयोग करें, \"लिंक कॉपी करें\" साझाकरण URL का नहीं।",
    "ErrorRequestTimedOut": "अनुरोध का समय समाप्त हो गया। URL और अपना नेटवर्क कनेक्शन जाँचें।",
    "ErrorNonJsonResponse": "प्रतिक्रिया को JSON के रूप में पार्स नहीं किया जा सका।",
    "ErrorUnsupportedFileType": "असमर्थित फ़ाइल प्रकार। कृपया .csv, .tsv, .xlsx या .xls फ़ाइल अपलोड करें।",
    "ErrorReadFile": "फ़ाइल पढ़ने में विफल",
    "ErrorParseFile": "फ़ाइल पार्स करने में विफल",
    "LoadedRowsColumns": "{1} कॉलम के साथ {0} पंक्तियाँ लोड हुईं।",
    "LoadedRowsColumnsPersist": "{1} कॉलम के साथ {0} पंक्तियाँ लोड हुईं। पृष्ठ छोड़ने पर भी डेटा बना रहेगा।",
    "SizeWarning": "डेटासेट ({0}KB) 200KB की स्थायित्व सीमा से अधिक है। चार्ट इस सत्र में डेटा दिखाएगा, लेकिन पृष्ठ पुनः लोड होने पर वह साफ़ हो जाएगा। बड़ी फ़ाइलों के लिए, उन्हें SharePoint लाइब्रेरी में अपलोड करें और SharePoint फ़ाइल स्रोत का उपयोग करें।",
    "ListTruncatedWarning": "इस सूची में {0} या अधिक आइटम हैं; केवल पहले {0} लोड किए गए।",
    "GraphTruncatedWarning": "इस Microsoft Graph परिणाम में लोड किए जा सकने वाले पृष्ठों से अधिक पृष्ठ हैं; केवल पहले {0} पृष्ठ प्राप्त किए गए।",
    "CsvParseWarning": "{0} पंक्ति(याँ) पार्स नहीं की जा सकीं और छोड़ दी गईं।",
    // Column mapper
    "ColumnMappingSectionHeader": "कॉलम मैपिंग",
    "CategoryColumnLabel": "श्रेणी कॉलम (X / लेबल)",
    "LabelColumnLabel": "लेबल कॉलम",
    "XAxisColumnLabel": "X अक्ष कॉलम",
    "ValueColumnLabel": "मान कॉलम",
    "YAxisColumnLabel": "Y अक्ष कॉलम",
    "YAxisColumnsLabel": "Y अक्ष कॉलम",
    "YAxisColumnsHelp": "(एक या अधिक चुनें; रंग सेट करने के लिए स्वैच पर क्लिक करें)",
    "SelectColumnPlaceholder": "— कॉलम चुनें —",
    "ScatterLabelColumnLabel": "बिंदु लेबल",
    "SizeColumnLabel":"आकार / त्रिज्या कॉलम",
    "NoSizeColumnOption": "— कोई नहीं (निश्चित आकार) —",
    "SeriesColorTitle": "{0} के लिए रंग",
    "SeriesTypeTitle": "{0} के लिए चार्ट प्रकार",
    "SeriesTypeDefault": "डिफ़ॉल्ट",
    "SeriesTypeBar": "बार",
    "SeriesTypeLine": "लाइन",
    "HistogramColumnLabel": "बिन करने के लिए कॉलम (संख्यात्मक)",
    "TreemapGroupLabel": "समूह / लेबल कॉलम",
    "HeatmapColumnLabel": "कॉलम (X) श्रेणी",
    "HeatmapRowLabel": "पंक्ति (Y) श्रेणी",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ उन्नत विकल्प",
    "AdvancedOptionsOpen": "▲ उन्नत विकल्प",
    "ColorByLabel": "कॉलम के आधार पर रंग",
    "ColorByHelp": "बिंदुओं को श्रृंखला के बजाय श्रेणी के आधार पर रंगें।",
    "TooltipColumnsLabel": "टूलटिप कॉलम",
    "TooltipColumnsHelp": "(डेटा बिंदु पर होवर करने पर दिखाए जाने वाले अतिरिक्त कॉलम)",
    "DrillLevelLabel": "ड्रिल स्तर {0}",
    "DrillDownHelp": "क्लिक करके ड्रिल करने के लिए कॉलम पदानुक्रम परिभाषित करें (उदा. क्षेत्र → देश → शहर)। प्रत्येक स्तर पर मान एकत्रित किए जाते हैं।",
    "BookmarksLabel": "बुकमार्क",
    "BookmarkNameLabel": "बुकमार्क का नाम",
    "BookmarkNamePlaceholder": "उदा. क्षेत्र के अनुसार शीर्ष 10",
    "SaveBookmarkButton": "वर्तमान दृश्य सहेजें",
    "ApplyBookmarkButton": "लागू करें",
    "DeleteBookmarkButton": "हटाएँ",
    "ApplyBookmarkPlaceholder": "— बुकमार्क लागू करें —",
    // Data controls
    "DataControlsSectionHeader": "डेटा नियंत्रण",
    "SortByColumnLabel": "कॉलम के अनुसार क्रमबद्ध करें",
    "NoneOption": "— कोई नहीं —",
    "SortDirectionLabel": "क्रम की दिशा",
    "AscendingOption": "आरोही",
    "DescendingOption": "अवरोही",
    "RowLimitLabel": "पंक्ति सीमा (0 = सभी)",
    "FilterColumnLabel": "फ़िल्टर कॉलम",
    "FilterContainsLabel": "फ़िल्टर: शामिल है",
    "FilterValuePlaceholder": "फ़िल्टर मान…",
    "GroupByLabel": "कॉलम के अनुसार समूहित करें",
    "AggregationLabel": "एकत्रीकरण",
    "GroupByHelp": "संख्यात्मक कॉलम प्रति समूह एकत्रित किए जाते हैं। गणना एक \"गणना\" कॉलम जोड़ती है।",
    "AggNone": "कोई नहीं",
    "AggSum": "योग",
    "AggAvg": "औसत",
    "AggCount": "गणना",
    "AggMin": "न्यूनतम",
    "AggMax": "अधिकतम",
    // Data table
    "DataTableHeader": "डेटा तालिका ({0} पंक्तियाँ)",
    "PrevPageButton": "← पिछला",
    "NextPageButton": "अगला →",
    "PageOfLabel": "पृष्ठ {0} / {1}",
    // Export bar
    "ExportLabel": "निर्यात:",
    "ExportPngTitle": "चार्ट को PNG छवि के रूप में डाउनलोड करें",
    "ExportJpegTitle": "चार्ट को JPEG छवि के रूप में डाउनलोड करें",
    "ExportCsvTitle": "डेटा को CSV के रूप में डाउनलोड करें",
    "ExportExcelTitle": "डेटा को Excel कार्यपुस्तिका के रूप में डाउनलोड करें"
  }
});
