define([], function() {
  return {
    "PropertyPaneDescription": "Az adatvizualizáció konfigurálása",
    // Header
    "HeaderGroupName": "Fejléc",
    "WebPartHeaderFieldLabel": "Fejléc szövege",
    "WebPartHeaderPlaceholder": "pl. Értékesítési irányítópult",
    "ShowWebPartHeaderFieldLabel": "Fejléc megjelenítése",
    // Chart Settings group
    "ChartSettingsGroupName": "Diagrambeállítások",
    "ChartTitleFieldLabel": "Diagram címe",
    "ChartTypeFieldLabel": "Diagramtípus",
    "LegendPositionFieldLabel": "Jelmagyarázat helye",
    "ChartHeightFieldLabel": "Diagram magassága (px)",
    "ShowLegendFieldLabel": "Jelmagyarázat megjelenítése",
    "StackedFieldLabel": "Halmozott (oszlop/vonal)",
    "ShowDataTableFieldLabel": "Adattábla megjelenítése",
    "ShowExportBarFieldLabel": "Exportálási sáv megjelenítése",
    "XAxisLabelFieldLabel": "X tengely felirata (nem kötelező)",
    "XAxisPlaceholder": "Alapértelmezés szerint a kijelölt oszlop",
    "YAxisLabelFieldLabel": "Y tengely felirata (nem kötelező)",
    "YAxisPlaceholder": "Alapértelmezés szerint a kijelölt oszlopok",
    // Chart type group headers
    "ChartGroupStandard": "Szabványos diagramok",
    "ChartGroupSpecialized": "Speciális diagramok",
    // Chart type options
    "ChartTypeBarLabel": "Oszlopdiagram (függőleges)",
    "ChartTypeHorizontalBarLabel": "Sávdiagram (vízszintes)",
    "ChartTypeLineLabel": "Vonaldiagram",
    "ChartTypeAreaLabel": "Területdiagram",
    "ChartTypeScatterLabel": "Pontdiagram",
    "ChartTypePieLabel": "Kördiagram",
    "ChartTypeDoughnutLabel": "Fánkdiagram",
    "ChartTypeBubbleLabel": "Buborékdiagram",
    "ChartTypeRadarLabel": "Sugárdiagram",
    "ChartTypeKpiLabel": "KPI-csempe",
    "ChartTypeHistogramLabel": "Hisztogram",
    "ChartTypeWaterfallLabel": "Vízesésdiagram",
    "ChartTypeBoxplotLabel": "Dobozdiagram",
    "ChartTypeViolinLabel": "Hegedűdiagram",
    "ChartTypeBeforeAfterLabel": "Előtte-utána diagram",
    "ChartTypeTreemapLabel": "Fatérkép",
    "ChartTypeHeatmapLabel": "Hőtérkép",
    "HistogramBinsFieldLabel": "Hisztogram osztályai",
    "AppearancePageDescription": "Színek, feliratok és tengelyek",
    "AdvancedPageDescription": "Elemzés, referenciavonalak, interaktivitás és adatfrissítés",
    // Legend position options
    "LegendTopLabel": "Felül",
    "LegendBottomLabel": "Alul",
    "LegendLeftLabel": "Balra",
    "LegendRightLabel": "Jobbra",
    // Colors group
    "ColorsGroupName": "Színek",
    "ColorPaletteFieldLabel": "Színpaletta",
    "PaletteOfficeLabel": "Office (alapértelmezett)",
    "PaletteVibrantLabel": "Élénk",
    "PalettePastelLabel": "Pasztell",
    "PaletteMonochromeLabel": "Egyszínű",
    "PaletteTrafficLightLabel": "Közlekedési lámpa",
    "PaletteWarmLabel": "Meleg",
    "PaletteCoolLabel": "Hideg",
    // Data Labels group
    "DataLabelsGroupName": "Adatfeliratok és formázás",
    "ShowDataLabelsFieldLabel": "Adatfeliratok megjelenítése",
    "ValuePrefixFieldLabel": "Érték előtagja",
    "ValuePrefixPlaceholder": "pl. Ft",
    "ValueSuffixFieldLabel": "Érték utótagja",
    "ValueSuffixPlaceholder": "pl. %",
    "ValueDecimalsFieldLabel": "Tizedeshelyek",
    "AbbreviateNumbersFieldLabel": "Számok rövidítése (K/M)",
    // Axes & Grid group
    "AxesGridGroupName": "Tengelyek és rács",
    "YAxisMinFieldLabel": "Y tengely minimuma",
    "YAxisMaxFieldLabel": "Y tengely maximuma",
    "AutoPlaceholder": "Automatikus",
    "NumericValidationError": "Adjon meg egy számot, vagy hagyja üresen az automatikus beállításhoz.",
    "ColorValidationError": "Adjon meg egy hexadecimális színt (pl. #d13438), vagy hagyja üresen az alapértelmezéshez.",
    "LogScaleFieldLabel": "Logaritmikus skála (Y)",
    "LogScaleXFieldLabel": "Logaritmikus skála (X)",
    "StepLineFieldLabel": "Lépcsős interpoláció",
    "ShowGridLinesFieldLabel": "Rácsvonalak megjelenítése",
    "XLabelRotationFieldLabel": "X feliratok elforgatása (fok)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "X tengely típusa",
    "XAxisTypeAuto": "Automatikus felismerés",
    "XAxisTypeCategory": "Kategória",
    "XAxisTypeTime": "Idő (dátumok)",
    // Analytics group
    "AnalyticsGroupName": "Elemzés",
    "TrendlineFieldLabel": "Trendvonal",
    "TrendlineNone": "Nincs",
    "TrendlineLinear": "Lineáris",
    "TrendlineMovingAverage": "Mozgóátlag",
    "TrendWindowFieldLabel": "Mozgóátlag ablaka",
    "TrendSuffix": " (trend)",
    "ForecastPeriodsFieldLabel": "Előrejelzési időszakok (lineáris trendvonal)",
    // Reference line
    "ReferenceLineGroupName": "Referenciavonal",
    "ReferenceLineTypeFieldLabel": "Referenciavonal",
    "ReferenceLineValueFieldLabel": "Rögzített érték",
    "ReferenceLineColorFieldLabel": "Vonal színe (hex)",
    "RefLineFixed": "Rögzített érték",
    "RefLineMean": "Átlag",
    "RefLineMedian": "Medián",
    // Dual Y axis group
    "DualAxisGroupName": "Kettős Y tengely",
    "Y2ColumnsFieldLabel": "Jobb oldali tengely adatsorai (vesszővel elválasztott oszlopnevek)",
    "Y2ColumnsPlaceholder": "pl. Margin,Growth",
    "Y2AxisLabelFieldLabel": "Jobb oldali tengely felirata",
    "LogScaleY2FieldLabel": "Logaritmikus skála (jobb oldali tengely)",
    // Error bars group
    "ErrorBarsGroupName": "Hibasávok",
    "ErrorBarTypeFieldLabel": "Hibasáv típusa",
    "ErrorBarTypeNone": "Nincs",
    "ErrorBarTypeCustom": "Egyéni oszlop (±)",
    "ErrorBarTypeSd": "Szórás (számított)",
    "ErrorBarTypeSem": "Az átlag standard hibája (számított)",
    "ErrorBarColumnFieldLabel": "Hibaérték oszlopa",
    // Significance annotations group
    "SignificanceGroupName": "Szignifikanciazárójelek",
    "SignificancePairsFieldLabel": "Zárójelpárok",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Soronként egy zárójel: oszlop1,oszlop2,felirat  — pl. AcsoportA,BcsoportB,*  vagy  AcsoportA,BcsoportB,p<0.05  (JSON-tömb is elfogadott)",
    "BeforeAfterColumnsError": "Az előtte-utána diagramhoz pontosan 2 Y oszlop szükséges — egy az Előtte értékekhez, egy az Utána értékekhez.",
    // Interactivity
    "InteractivityGroupName": "Interaktivitás",
    "ShowViewerFiltersFieldLabel": "Szűrők megjelenítése a megtekintőknek",
    "DetailsOnDemandFieldLabel": "Adatsorok megjelenítése kattintásra",
    "ShowDataPointsFieldLabel": "Adatpontok megjelenítése az oszlopokon",
    "ShowBubbleSizeLegendFieldLabel": "Buborékméret-jelmagyarázat megjelenítése",
    "ViewerFilterLabel": "Szűrő:",
    "ViewerFilterColumnAria": "Szűrő oszlopa",
    "ViewerFilterValueAria": "Szűrő értéke",
    "DrillAllLabel": "Mind",
    "DetailsChipLabel": "Részletek: {0} ({1} sor)",
    // KPI
    "KpiSubLabel": "{0} • {1} • {2} sor",
    // Conditional formatting group
    "ConditionalGroupName": "Feltételes formázás",
    "ThresholdValueFieldLabel": "Küszöbérték",
    "ThresholdValuePlaceholder": "Ki",
    "ThresholdDirectionFieldLabel": "Értékek kiemelése",
    "ThresholdBelow": "Küszöb alatt",
    "ThresholdAbove": "Küszöb felett",
    "ThresholdColorFieldLabel": "Kiemelés színe (hex)",
    // Data & refresh group
    "DataRefreshGroupName": "Adatok és frissítés",
    "RefreshIntervalFieldLabel": "Automatikus frissítés időköze (perc, 0 = ki)",
    "CacheMinutesFieldLabel": "Adatok gyorsítótárazása (perc, 0 = ki)",
    // Dynamic data
    "DynamicDataCategoryLabel": "Kijelölt kategória",
    "DynamicDataValueLabel": "Kijelölt érték",
    "DynamicDataSeriesLabel": "Kijelölt adatsor",
    // Legacy / unused
    "DataSourceGroupName": "Adatforrás",
    // Main component
    "HideDataSourceButton": "▲ Adatforrás elrejtése",
    "ConfigureDataSourceButton": "▼ Adatforrás konfigurálása",
    "RowsLoadedBadge": "✓ {0} sor betöltve",
    "ReadModeLoadError": "Az adatok nem tölthetők be: {0}. Az adatforrás újrakonfigurálásához váltson szerkesztési módra.",
    "RefreshDataButton": "↻ Adatok frissítése",
    "RefreshingLabel": "Frissítés…",
    "RefreshDataTitle": "Adatok újratöltése a konfigurált forrásból",
    // Chart renderer
    "NoDataMessage": "Még nincs betöltött adat. Konfigurálja fent az adatforrást, és kattintson az Adatok betöltése gombra.",
    "SelectMappingsMessage": "Az adatok betöltve ({0} sor). A diagram megjelenítéséhez válassza ki fent az oszlopleképezéseket.",
    "ChartRenderErrorLabel": "Diagram-megjelenítési hiba: {0}",
    "UnsupportedChartTypeLabel": "Nem támogatott diagramtípus: {0}",
    "ChartAriaLabel": "Adatvizualizációs diagram",
    "FilterOperatorLabel": "Operátor",
    "FilterValueLabel": "Érték",
    "FilterOpContains": "tartalmazza",
    "FilterOpEquals": "egyenlő",
    "FilterOpNotEquals": "nem egyenlő",
    "FilterOpGt": "nagyobb, mint",
    "FilterOpLt": "kisebb, mint",
    "FilterOpBetween": "között (alsó..felső)",
    "FilterOpIsEmpty": "üres",
    "FilterOpNotEmpty": "nem üres",
    "AddFilterButton": "+ Szűrő hozzáadása",
    "RemoveFilterButton": "Eltávolítás",
    "SelectValuePlaceholder": "Érték kiválasztása…",
    "ViewerFilterOperatorAria": "Szűrő operátora",
    "PaletteColorblindLabel": "Színtévesztőknek is megfelelő",
    "WaterfallGroupName": "Vízesés",
    "WaterfallShowTotalFieldLabel": "Összesítő oszlop megjelenítése",
    "WaterfallPositiveColorFieldLabel": "Növekedés színe",
    "WaterfallNegativeColorFieldLabel": "Csökkenés színe",
    "WaterfallTotalColorFieldLabel": "Összesítés színe",
    "WaterfallTotalLabel": "Összesen",
    "ExternalFilterGroupName": "Szűrés másik webalkatrészből",
    "ExternalFilterFieldLabel": "Szűrőérték forrása",
    "ExternalFilterColumnFieldLabel": "Szűrendő oszlop",
    "ExternalFilterColumnPlaceholder": "Alapértelmezés szerint az X tengely oszlopa",
    "ViewAsTableButton": "Megjelenítés táblázatként",
    "HideTableButton": "Táblázat elrejtése",
    "ChartKeyboardHint": "A nyílbillentyűkkel léphet az adatpontok között, az Enter billentyűvel pedig kijelölhet egyet.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Y2 érték előtagja",
    "Y2ValueSuffixFieldLabel": "Y2 érték utótagja",
    "AnnotationsGroupName": "Jegyzetek",
    "AnnotationsFieldLabel": "Jegyzetek",
    "AnnotationsPlaceholder": "Jan, Termékbevezetés",
    "AnnotationsHelp": "Soronként egy: az X tengely értéke, egy vessző, majd a jegyzet szövege. Az adott X értéknél függőleges jelölő jelenik meg.",
    "BeforeLabel": "Előtte",
    "AfterLabel": "Utána",
    "RowLabel": "{0}. sor",
    "PointsSuffix": " (pontok)",
    "ExportSheetName": "Adatok",
    "RefreshFailedNote": "Az utolsó frissítés sikertelen volt: {0}. A korábban betöltött adatok láthatók.",
    "TruncatedDataNote": "Csak az első {0} sor látható; a forrás több adatot tartalmaz.",
    "ScatterNumericWarning": "A pont- és buborékdiagramokhoz numerikus értékek szükségesek. A(z) \"{0}\" oszlop nem tartalmaz numerikus adatot — válasszon másik oszlopot a fenti leképezésben.",
    "TimeAxisUnparseableWarning": "A(z) \"{0}\" X tengely oszlopban nincs dátumként értelmezhető érték. Állítsa az X tengely típusát \"Kategória\" értékre, vagy képezzen le egy dátumoszlopot.",
    // Data source panel
    "DataSourceSectionHeader": "Adatforrás",
    "SourceUploadLabel": "Fájl feltöltése",
    "SourceSharePointListLabel": "SharePoint-lista",
    "SourceSharePointFileLabel": "SharePoint-fájl",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API elérési útja",
    "GraphPathHelp": "Relatív Microsoft Graph-elérési út, pl. /me/memberOf vagy /reports/getTeamsUserActivityUserCounts(period='D7'). Ehhez a forráshoz rendszergazda által jóváhagyott Graph-engedélyek szükségesek — az összes többi adatforrás ezek nélkül is működik.",
    "SheetNameLabel": "Excel-munkalap",
    "DelimiterLabel": "Elválasztó",
    "DelimiterAutoDetect": "Automatikus felismerés",
    "DelimiterComma": "Vessző (,)",
    "DelimiterTab": "Tabulátor",
    "DelimiterSemicolon": "Pontosvessző (;)",
    "DelimiterPipe": "Függőleges vonal (|)",
    "SiteUrlLabel": "Webhely URL-címe (nem kötelező)",
    "SiteUrlHelp": "Hagyja üresen az aktuális webhely használatához.",
    "ListNameLabel": "Lista neve",
    "LoadingListsLabel": "— Listák betöltése…",
    "SelectListPlaceholder": "— Válasszon listát —",
    "EnterListNamePlaceholder": "Adja meg a lista nevét",
    "ListNameExamplePlaceholder": "pl. Értékesítési adatok",
    "ListDiscoveryError": "A listák nem tölthetők be — adja meg a nevet kézzel alább.",
    "FileUrlLabel": "Fájl URL-címe (CSV/TSV/Excel a SharePointban)",
    "FileUrlHelp": "Egy dokumentumtárban lévő fájl teljes URL-címe.",
    "ApiUrlLabel": "API URL-címe",
    "DataPathLabel": "Adatelérési út (nem kötelező)",
    "DataPathHelp": "Ponttal elválasztott elérési út a JSON-válaszban lévő tömbhöz. Hagyja üresen, ha a gyökér tömb. A SharePoint REST API esetén használja a \"value\" értéket.",
    "UploadHelp": "Töltsön fel egy CSV-, TSV- vagy Excel-fájlt (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} sor",
    "ChangeFileButton": "Fájl módosítása…",
    "ClearButton": "Törlés",
    "ChooseFileButton": "Fájl kiválasztása…",
    "LoadDataButton": "Adatok betöltése",
    "LoadingLabel": "Betöltés…",
    "ErrorSelectListName": "Válasszon ki vagy adjon meg egy listanevet.",
    "ErrorEnterFileUrl": "Adja meg a fájl URL-címét.",
    "ErrorEnterUrl": "Adjon meg egy URL-címet.",
    "ErrorLoadList": "A SharePoint-lista betöltése sikertelen: {0}",
    "ErrorLoadFile": "A fájl betöltése sikertelen: {0}",
    "ErrorFetchData": "Az adatok lekérése sikertelen: {0}",
    "ErrorDataPathNotFound": "A(z) \"{0}\" adatelérési út nem található a válaszban.",
    "ErrorUrlReturnedHtml": "Ez az URL weboldalt adott vissza, nem fájlt. A közvetlen fájlletöltési útvonalat használja, ne a \"Hivatkozás másolása\" megosztási URL-t.",
    "ErrorRequestTimedOut": "A kérés időtúllépés miatt megszakadt. Ellenőrizze az URL-t és a hálózati kapcsolatot.",
    "ErrorNonJsonResponse": "A választ nem sikerült JSON-ként elemezni.",
    "ErrorUnsupportedFileType": "Nem támogatott fájltípus. Töltsön fel .csv, .tsv, .xlsx vagy .xls fájlt.",
    "ErrorReadFile": "A fájl olvasása sikertelen",
    "ErrorParseFile": "A fájl elemzése sikertelen",
    "LoadedRowsColumns": "{0} sor betöltve, {1} oszloppal.",
    "LoadedRowsColumnsPersist": "{0} sor betöltve, {1} oszloppal. Az adatok megmaradnak, amikor elhagyja az oldalt.",
    "SizeWarning": "Az adatkészlet ({0} KB) meghaladja a 200 KB-os megőrzési korlátot. A diagram ebben a munkamenetben megjeleníti az adatokat, de az oldal újratöltésekor törlődnek. Nagy fájlok esetén töltse fel őket egy SharePoint-tárba, és használja a SharePoint-fájl forrást.",
    "ListTruncatedWarning": "Ez a lista {0} vagy több elemet tartalmaz; csak az első {0} lett betöltve.",
    "GraphTruncatedWarning": "Ez a Microsoft Graph-eredmény több oldalt tartalmaz, mint amennyi betölthető volt; csak az első {0} oldal lett lekérve.",
    "CsvParseWarning": "{0} sort nem sikerült elemezni, ezért kimaradt.",
    // Column mapper
    "ColumnMappingSectionHeader": "Oszlopleképezés",
    "CategoryColumnLabel": "Kategóriaoszlop (X / feliratok)",
    "LabelColumnLabel": "Feliratoszlop",
    "XAxisColumnLabel": "X tengely oszlopa",
    "ValueColumnLabel": "Értékoszlop",
    "YAxisColumnLabel": "Y tengely oszlopa",
    "YAxisColumnsLabel": "Y tengely oszlopai",
    "YAxisColumnsHelp": "(válasszon egyet vagy többet; a színminta kattintással állítható)",
    "SelectColumnPlaceholder": "— Válasszon oszlopot —",
    "ScatterLabelColumnLabel": "Pont felirata",
    "SizeColumnLabel":"Méret / sugár oszlopa",
    "NoSizeColumnOption": "— Nincs (rögzített méret) —",
    "SeriesColorTitle": "Szín: {0}",
    "SeriesTypeTitle": "Diagramtípus: {0}",
    "SeriesTypeDefault": "Alapértelmezett",
    "SeriesTypeBar": "Oszlop",
    "SeriesTypeLine": "Vonal",
    "HistogramColumnLabel": "Osztályokba sorolandó oszlop (numerikus)",
    "TreemapGroupLabel": "Csoport / feliratoszlop",
    "HeatmapColumnLabel": "Oszlop (X) kategóriája",
    "HeatmapRowLabel": "Sor (Y) kategóriája",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ Speciális beállítások",
    "AdvancedOptionsOpen": "▲ Speciális beállítások",
    "ColorByLabel": "Színezés oszlop szerint",
    "ColorByHelp": "A pontok színezése kategória szerint az adatsor helyett.",
    "TooltipColumnsLabel": "Elemleírás oszlopai",
    "TooltipColumnsHelp": "(további oszlopok, amelyek egy adatpont fölé mutatva jelennek meg)",
    "DrillLevelLabel": "{0}. részletezési szint",
    "DrillDownHelp": "Definiáljon oszlophierarchiát a kattintásos részletezéshez (pl. Régió → Ország → Város). Az értékek minden szinten összesítésre kerülnek.",
    "BookmarksLabel": "Könyvjelzők",
    "BookmarkNameLabel": "Könyvjelző neve",
    "BookmarkNamePlaceholder": "pl. Top 10 régiónként",
    "SaveBookmarkButton": "Aktuális nézet mentése",
    "ApplyBookmarkButton": "Alkalmaz",
    "DeleteBookmarkButton": "Törlés",
    "ApplyBookmarkPlaceholder": "— Könyvjelző alkalmazása —",
    // Data controls
    "DataControlsSectionHeader": "Adatvezérlők",
    "SortByColumnLabel": "Rendezés oszlop szerint",
    "NoneOption": "— Nincs —",
    "SortDirectionLabel": "Rendezési irány",
    "AscendingOption": "Növekvő",
    "DescendingOption": "Csökkenő",
    "RowLimitLabel": "Sorkorlát (0 = mind)",
    "FilterColumnLabel": "Szűrő oszlopa",
    "FilterContainsLabel": "Szűrő: tartalmazza",
    "FilterValuePlaceholder": "Szűrő értéke…",
    "GroupByLabel": "Csoportosítás oszlop szerint",
    "AggregationLabel": "Összesítés",
    "GroupByHelp": "A numerikus oszlopok csoportonként összesítve jelennek meg. A Darabszám egy \"Darabszám\" oszlopot ad hozzá.",
    "AggNone": "Nincs",
    "AggSum": "Összeg",
    "AggAvg": "Átlag",
    "AggCount": "Darabszám",
    "AggMin": "Min.",
    "AggMax": "Max.",
    // Data table
    "DataTableHeader": "Adattábla ({0} sor)",
    "PrevPageButton": "← Előző",
    "NextPageButton": "Következő →",
    "PageOfLabel": "{0}. oldal / {1}",
    // Export bar
    "ExportLabel": "Exportálás:",
    "ExportPngTitle": "A diagram letöltése PNG-képként",
    "ExportJpegTitle": "A diagram letöltése JPEG-képként",
    "ExportCsvTitle": "Az adatok letöltése CSV-fájlként",
    "ExportExcelTitle": "Az adatok letöltése Excel-munkafüzetként"
  }
});
