define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurasikan visualisasi data Anda",
    // Header
    "HeaderGroupName": "Header",
    "WebPartHeaderFieldLabel": "Teks Header",
    "WebPartHeaderPlaceholder": "mis. Dasbor Penjualan",
    "ShowWebPartHeaderFieldLabel": "Tampilkan Header",
    // Chart Settings group
    "ChartSettingsGroupName": "Pengaturan Bagan",
    "ChartTitleFieldLabel": "Judul Bagan",
    "ChartTypeFieldLabel": "Jenis Bagan",
    "LegendPositionFieldLabel": "Posisi Legenda",
    "ChartHeightFieldLabel": "Tinggi Bagan (px)",
    "ShowLegendFieldLabel": "Tampilkan Legenda",
    "StackedFieldLabel": "Bertumpuk (Batang/Garis)",
    "ShowDataTableFieldLabel": "Tampilkan Tabel Data",
    "ShowExportBarFieldLabel": "Tampilkan Bilah Ekspor",
    "XAxisLabelFieldLabel": "Label Sumbu X (opsional)",
    "XAxisPlaceholder": "Default ke kolom yang dipilih",
    "YAxisLabelFieldLabel": "Label Sumbu Y (opsional)",
    "YAxisPlaceholder": "Default ke kolom yang dipilih",
    // Chart type group headers
    "ChartGroupStandard": "Bagan Standar",
    "ChartGroupSpecialized": "Bagan Khusus",
    // Chart type options
    "ChartTypeBarLabel": "Bagan Batang (Vertikal)",
    "ChartTypeHorizontalBarLabel": "Bagan Batang (Horizontal)",
    "ChartTypeLineLabel": "Bagan Garis",
    "ChartTypeAreaLabel": "Bagan Area",
    "ChartTypeScatterLabel": "Plot Sebar",
    "ChartTypePieLabel": "Bagan Pai",
    "ChartTypeDoughnutLabel": "Bagan Donat",
    "ChartTypeBubbleLabel": "Bagan Gelembung",
    "ChartTypeRadarLabel": "Bagan Radar",
    "ChartTypeKpiLabel": "Ubin KPI",
    "ChartTypeHistogramLabel": "Histogram",
    "ChartTypeWaterfallLabel": "Bagan Air Terjun",
    "ChartTypeBoxplotLabel": "Plot Kotak",
    "ChartTypeViolinLabel": "Plot Biola",
    "ChartTypeBeforeAfterLabel": "Plot Sebelum-Sesudah",
    "ChartTypeTreemapLabel": "Treemap",
    "ChartTypeHeatmapLabel": "Peta Panas",
    "HistogramBinsFieldLabel": "Bin Histogram",
    "AppearancePageDescription": "Warna, label, dan sumbu",
    "AdvancedPageDescription": "Analitik, garis referensi, interaktivitas, dan penyegaran data",
    // Legend position options
    "LegendTopLabel": "Atas",
    "LegendBottomLabel": "Bawah",
    "LegendLeftLabel": "Kiri",
    "LegendRightLabel": "Kanan",
    // Colors group
    "ColorsGroupName": "Warna",
    "ColorPaletteFieldLabel": "Palet Warna",
    "PaletteOfficeLabel": "Office (Default)",
    "PaletteVibrantLabel": "Cerah",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Monokrom",
    "PaletteTrafficLightLabel": "Lampu Lalu Lintas",
    "PaletteWarmLabel": "Hangat",
    "PaletteCoolLabel": "Dingin",
    // Data Labels group
    "DataLabelsGroupName": "Label Data & Pemformatan",
    "ShowDataLabelsFieldLabel": "Tampilkan Label Data",
    "ValuePrefixFieldLabel": "Awalan Nilai",
    "ValuePrefixPlaceholder": "mis. Rp",
    "ValueSuffixFieldLabel": "Akhiran Nilai",
    "ValueSuffixPlaceholder": "mis. %",
    "ValueDecimalsFieldLabel": "Tempat Desimal",
    "AbbreviateNumbersFieldLabel": "Singkat Angka (K/M)",
    // Axes & Grid group
    "AxesGridGroupName": "Sumbu & Kisi",
    "YAxisMinFieldLabel": "Minimum Sumbu Y",
    "YAxisMaxFieldLabel": "Maksimum Sumbu Y",
    "AutoPlaceholder": "Otomatis",
    "NumericValidationError": "Masukkan angka, atau biarkan kosong untuk otomatis.",
    "ColorValidationError": "Masukkan warna hex (mis. #d13438), atau biarkan kosong untuk default.",
    "LogScaleFieldLabel": "Skala Logaritmik (Y)",
    "LogScaleXFieldLabel": "Skala Logaritmik (X)",
    "StepLineFieldLabel": "Interpolasi Langkah",
    "ShowGridLinesFieldLabel": "Tampilkan Garis Kisi",
    "XLabelRotationFieldLabel": "Rotasi Label X (derajat)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "Jenis Sumbu X",
    "XAxisTypeAuto": "Deteksi otomatis",
    "XAxisTypeCategory": "Kategori",
    "XAxisTypeTime": "Waktu (tanggal)",
    // Analytics group
    "AnalyticsGroupName": "Analitik",
    "TrendlineFieldLabel": "Garis Tren",
    "TrendlineNone": "Tidak Ada",
    "TrendlineLinear": "Linier",
    "TrendlineMovingAverage": "Rata-Rata Bergerak",
    "TrendWindowFieldLabel": "Jendela Rata-Rata Bergerak",
    "TrendSuffix": " (tren)",
    "ForecastPeriodsFieldLabel": "Periode Prakiraan (garis tren linier)",
    // Reference line
    "ReferenceLineGroupName": "Garis Referensi",
    "ReferenceLineTypeFieldLabel": "Garis Referensi",
    "ReferenceLineValueFieldLabel": "Nilai Tetap",
    "ReferenceLineColorFieldLabel": "Warna Garis (hex)",
    "RefLineFixed": "Nilai tetap",
    "RefLineMean": "Rata-rata",
    "RefLineMedian": "Median",
    // Dual Y axis group
    "DualAxisGroupName": "Sumbu Y Ganda",
    "Y2ColumnsFieldLabel": "Seri sumbu kanan (nama kolom dipisahkan koma)",
    "Y2ColumnsPlaceholder": "mis. Margin,Growth",
    "Y2AxisLabelFieldLabel": "Label sumbu kanan",
    "LogScaleY2FieldLabel": "Skala Log (Sumbu Kanan)",
    // Error bars group
    "ErrorBarsGroupName": "Bilah Galat",
    "ErrorBarTypeFieldLabel": "Jenis Bilah Galat",
    "ErrorBarTypeNone": "Tidak Ada",
    "ErrorBarTypeCustom": "Kolom kustom (±)",
    "ErrorBarTypeSd": "Simpangan Baku (dihitung)",
    "ErrorBarTypeSem": "Galat Baku Rata-Rata (dihitung)",
    "ErrorBarColumnFieldLabel": "Kolom nilai galat",
    // Significance annotations group
    "SignificanceGroupName": "Tanda Kurung Signifikansi",
    "SignificancePairsFieldLabel": "Pasangan tanda kurung",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Satu tanda kurung per baris: kol1,kol2,label  — mis. GrupA,GrupB,*  atau  GrupA,GrupB,p<0.05  (larik JSON juga diterima)",
    "BeforeAfterColumnsError": "Bagan Sebelum-Sesudah memerlukan tepat 2 kolom Y — satu untuk nilai Sebelum dan satu untuk nilai Sesudah.",
    // Interactivity
    "InteractivityGroupName": "Interaktivitas",
    "ShowViewerFiltersFieldLabel": "Tampilkan Filter kepada Pemirsa",
    "DetailsOnDemandFieldLabel": "Tampilkan baris data saat diklik",
    "ShowDataPointsFieldLabel": "Tampilkan Titik Data di Atas Batang",
    "ShowBubbleSizeLegendFieldLabel": "Tampilkan Legenda Ukuran Gelembung",
    "ViewerFilterLabel": "Filter:",
    "ViewerFilterColumnAria": "Kolom filter",
    "ViewerFilterValueAria": "Nilai filter",
    "DrillAllLabel": "Semua",
    "DetailsChipLabel": "Detail: {0} ({1} baris)",
    // KPI
    "KpiSubLabel": "{0} • {1} • {2} baris",
    // Conditional formatting group
    "ConditionalGroupName": "Pemformatan Bersyarat",
    "ThresholdValueFieldLabel": "Nilai Ambang Batas",
    "ThresholdValuePlaceholder": "Nonaktif",
    "ThresholdDirectionFieldLabel": "Sorot Nilai",
    "ThresholdBelow": "Di bawah ambang batas",
    "ThresholdAbove": "Di atas ambang batas",
    "ThresholdColorFieldLabel": "Warna Sorotan (hex)",
    // Data & refresh group
    "DataRefreshGroupName": "Data & Penyegaran",
    "RefreshIntervalFieldLabel": "Interval Penyegaran Otomatis (menit, 0 = nonaktif)",
    "CacheMinutesFieldLabel": "Cache Data (menit, 0 = nonaktif)",
    // Dynamic data
    "DynamicDataCategoryLabel": "Kategori yang dipilih",
    "DynamicDataValueLabel": "Nilai yang dipilih",
    "DynamicDataSeriesLabel": "Seri yang dipilih",
    // Legacy / unused
    "DataSourceGroupName": "Sumber Data",
    // Main component
    "HideDataSourceButton": "▲ Sembunyikan Sumber Data",
    "ConfigureDataSourceButton": "▼ Konfigurasikan Sumber Data",
    "RowsLoadedBadge": "✓ {0} baris dimuat",
    "ReadModeLoadError": "Tidak dapat memuat data: {0}. Beralih ke mode Edit untuk mengonfigurasi ulang sumber data.",
    "RefreshDataButton": "↻ Segarkan Data",
    "RefreshingLabel": "Menyegarkan…",
    "RefreshDataTitle": "Muat ulang data dari sumber yang dikonfigurasi",
    // Chart renderer
    "NoDataMessage": "Belum ada data yang dimuat. Konfigurasikan sumber data Anda di atas dan klik Muat Data.",
    "SelectMappingsMessage": "Data dimuat ({0} baris). Pilih pemetaan kolom di atas untuk menampilkan bagan.",
    "ChartRenderErrorLabel": "Kesalahan merender bagan: {0}",
    "UnsupportedChartTypeLabel": "Jenis bagan tidak didukung: {0}",
    "ChartAriaLabel": "Bagan visualisasi data",
    "FilterOperatorLabel": "Operator",
    "FilterValueLabel": "Nilai",
    "FilterOpContains": "berisi",
    "FilterOpEquals": "sama dengan",
    "FilterOpNotEquals": "tidak sama dengan",
    "FilterOpGt": "lebih besar dari",
    "FilterOpLt": "lebih kecil dari",
    "FilterOpBetween": "antara (rendah..tinggi)",
    "FilterOpIsEmpty": "kosong",
    "FilterOpNotEmpty": "tidak kosong",
    "AddFilterButton": "+ Tambahkan filter",
    "RemoveFilterButton": "Hapus",
    "SelectValuePlaceholder": "Pilih nilai…",
    "ViewerFilterOperatorAria": "Operator filter",
    "PaletteColorblindLabel": "Aman untuk buta warna",
    "WaterfallGroupName": "Air Terjun",
    "WaterfallShowTotalFieldLabel": "Tampilkan Batang Total",
    "WaterfallPositiveColorFieldLabel": "Warna Kenaikan",
    "WaterfallNegativeColorFieldLabel": "Warna Penurunan",
    "WaterfallTotalColorFieldLabel": "Warna Total",
    "WaterfallTotalLabel": "Total",
    "ExternalFilterGroupName": "Filter dari Komponen Web Lain",
    "ExternalFilterFieldLabel": "Sumber Nilai Filter",
    "ExternalFilterColumnFieldLabel": "Kolom untuk Difilter",
    "ExternalFilterColumnPlaceholder": "Default ke kolom sumbu X",
    "ViewAsTableButton": "Lihat sebagai tabel",
    "HideTableButton": "Sembunyikan tabel",
    "ChartKeyboardHint": "Gunakan tombol panah untuk berpindah antar titik data dan Enter untuk memilih salah satunya.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Awalan Nilai Y2",
    "Y2ValueSuffixFieldLabel": "Akhiran Nilai Y2",
    "AnnotationsGroupName": "Anotasi",
    "AnnotationsFieldLabel": "Anotasi",
    "AnnotationsPlaceholder": "Jan, Peluncuran produk",
    "AnnotationsHelp": "Satu per baris: nilai sumbu X, koma, lalu teks catatan. Penanda vertikal digambar pada nilai X tersebut.",
    "BeforeLabel": "Sebelum",
    "AfterLabel": "Sesudah",
    "RowLabel": "Baris {0}",
    "PointsSuffix": " (titik)",
    "ExportSheetName": "Data",
    "RefreshFailedNote": "Penyegaran terakhir gagal: {0}. Menampilkan data yang dimuat sebelumnya.",
    "TruncatedDataNote": "Hanya {0} baris pertama yang ditampilkan; sumber memiliki lebih banyak data.",
    "ScatterNumericWarning": "Bagan sebar dan gelembung memerlukan nilai numerik. Kolom \"{0}\" tidak memiliki data numerik — pilih kolom lain pada pemetaan di atas.",
    "TimeAxisUnparseableWarning": "Kolom sumbu X \"{0}\" tidak memiliki nilai yang dapat diurai sebagai tanggal. Ubah Jenis Sumbu X menjadi \"Kategori\", atau petakan kolom tanggal.",
    // Data source panel
    "DataSourceSectionHeader": "Sumber Data",
    "SourceUploadLabel": "Unggah File",
    "SourceSharePointListLabel": "Daftar SharePoint",
    "SourceSharePointFileLabel": "File SharePoint",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Jalur Graph API",
    "GraphPathHelp": "Jalur Microsoft Graph relatif, mis. /me/memberOf atau /reports/getTeamsUserActivityUserCounts(period='D7'). Sumber ini memerlukan izin Graph yang disetujui administrator — semua sumber data lainnya berfungsi tanpa izin tersebut.",
    "SheetNameLabel": "Lembar Excel",
    "DelimiterLabel": "Pemisah",
    "DelimiterAutoDetect": "Deteksi otomatis",
    "DelimiterComma": "Koma (,)",
    "DelimiterTab": "Tab",
    "DelimiterSemicolon": "Titik koma (;)",
    "DelimiterPipe": "Garis vertikal (|)",
    "SiteUrlLabel": "URL Situs (opsional)",
    "SiteUrlHelp": "Biarkan kosong untuk menggunakan situs saat ini.",
    "ListNameLabel": "Nama Daftar",
    "LoadingListsLabel": "— Memuat daftar…",
    "SelectListPlaceholder": "— Pilih daftar —",
    "EnterListNamePlaceholder": "Masukkan nama daftar",
    "ListNameExamplePlaceholder": "mis. Data Penjualan",
    "ListDiscoveryError": "Tidak dapat memuat daftar — masukkan nama secara manual di bawah.",
    "FileUrlLabel": "URL File (CSV/TSV/Excel di SharePoint)",
    "FileUrlHelp": "URL lengkap ke file di pustaka dokumen.",
    "ApiUrlLabel": "URL API",
    "DataPathLabel": "Jalur Data (opsional)",
    "DataPathHelp": "Jalur yang dipisahkan titik ke larik dalam respons JSON. Biarkan kosong jika root berupa larik. Untuk SharePoint REST API gunakan \"value\".",
    "UploadHelp": "Unggah file CSV, TSV, atau Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} baris",
    "ChangeFileButton": "Ganti File…",
    "ClearButton": "Hapus",
    "ChooseFileButton": "Pilih File…",
    "LoadDataButton": "Muat Data",
    "LoadingLabel": "Memuat…",
    "ErrorSelectListName": "Pilih atau masukkan nama daftar.",
    "ErrorEnterFileUrl": "Masukkan URL file.",
    "ErrorEnterUrl": "Masukkan URL.",
    "ErrorLoadList": "Gagal memuat daftar SharePoint: {0}",
    "ErrorLoadFile": "Gagal memuat file: {0}",
    "ErrorFetchData": "Gagal mengambil data: {0}",
    "ErrorDataPathNotFound": "Jalur data \"{0}\" tidak ditemukan dalam respons.",
    "ErrorUrlReturnedHtml": "URL ini mengembalikan halaman web, bukan file. Gunakan jalur unduhan file langsung, bukan URL berbagi \"Salin tautan\".",
    "ErrorRequestTimedOut": "Permintaan habis waktu. Periksa URL dan koneksi jaringan Anda.",
    "ErrorNonJsonResponse": "Respons tidak dapat diurai sebagai JSON.",
    "ErrorUnsupportedFileType": "Jenis file tidak didukung. Unggah file .csv, .tsv, .xlsx, atau .xls.",
    "ErrorReadFile": "Gagal membaca file",
    "ErrorParseFile": "Gagal mengurai file",
    "LoadedRowsColumns": "Memuat {0} baris dengan {1} kolom.",
    "LoadedRowsColumnsPersist": "Memuat {0} baris dengan {1} kolom. Data akan tetap tersimpan saat Anda meninggalkan halaman.",
    "SizeWarning": "Himpunan data ({0}KB) melebihi batas penyimpanan 200KB. Bagan akan menampilkan data selama sesi ini tetapi akan terhapus saat halaman dimuat ulang. Untuk file besar, unggah ke pustaka SharePoint dan gunakan sumber File SharePoint.",
    "ListTruncatedWarning": "Daftar ini memiliki {0} item atau lebih; hanya {0} item pertama yang dimuat.",
    "GraphTruncatedWarning": "Hasil Microsoft Graph ini memiliki lebih banyak halaman daripada yang dapat dimuat; hanya {0} halaman pertama yang diambil.",
    "CsvParseWarning": "{0} baris tidak dapat diurai dan dilewati.",
    // Column mapper
    "ColumnMappingSectionHeader": "Pemetaan Kolom",
    "CategoryColumnLabel": "Kolom Kategori (X / Label)",
    "LabelColumnLabel": "Kolom Label",
    "XAxisColumnLabel": "Kolom Sumbu X",
    "ValueColumnLabel": "Kolom Nilai",
    "YAxisColumnLabel": "Kolom Sumbu Y",
    "YAxisColumnsLabel": "Kolom Sumbu Y",
    "YAxisColumnsHelp": "(pilih satu atau lebih; klik sampel warna untuk mengatur warna)",
    "SelectColumnPlaceholder": "— Pilih kolom —",
    "ScatterLabelColumnLabel": "Label Titik",
    "SizeColumnLabel":"Kolom Ukuran / Radius",
    "NoSizeColumnOption": "— Tidak ada (ukuran tetap) —",
    "SeriesColorTitle": "Warna untuk {0}",
    "SeriesTypeTitle": "Jenis bagan untuk {0}",
    "SeriesTypeDefault": "Default",
    "SeriesTypeBar": "Batang",
    "SeriesTypeLine": "Garis",
    "HistogramColumnLabel": "Kolom untuk Dibin (numerik)",
    "TreemapGroupLabel": "Kolom Grup / Label",
    "HeatmapColumnLabel": "Kategori Kolom (X)",
    "HeatmapRowLabel": "Kategori Baris (Y)",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ Opsi Lanjutan",
    "AdvancedOptionsOpen": "▲ Opsi Lanjutan",
    "ColorByLabel": "Warnai menurut Kolom",
    "ColorByHelp": "Warnai titik menurut kategori, bukan menurut seri.",
    "TooltipColumnsLabel": "Kolom Tooltip",
    "TooltipColumnsHelp": "(kolom tambahan yang ditampilkan saat mengarahkan kursor ke titik data)",
    "DrillLevelLabel": "Tingkat Drill {0}",
    "DrillDownHelp": "Tentukan hierarki kolom untuk mengaktifkan klik-untuk-drill (mis. Wilayah → Negara → Kota). Nilai diagregasi pada setiap tingkat.",
    "BookmarksLabel": "Penanda",
    "BookmarkNameLabel": "Nama Penanda",
    "BookmarkNamePlaceholder": "mis. 10 Teratas per Wilayah",
    "SaveBookmarkButton": "Simpan Tampilan Saat Ini",
    "ApplyBookmarkButton": "Terapkan",
    "DeleteBookmarkButton": "Hapus",
    "ApplyBookmarkPlaceholder": "— Terapkan penanda —",
    // Data controls
    "DataControlsSectionHeader": "Kontrol Data",
    "SortByColumnLabel": "Urutkan menurut Kolom",
    "NoneOption": "— Tidak ada —",
    "SortDirectionLabel": "Arah Pengurutan",
    "AscendingOption": "Naik",
    "DescendingOption": "Turun",
    "RowLimitLabel": "Batas Baris (0 = semua)",
    "FilterColumnLabel": "Kolom Filter",
    "FilterContainsLabel": "Filter: berisi",
    "FilterValuePlaceholder": "Nilai filter…",
    "GroupByLabel": "Kelompokkan menurut Kolom",
    "AggregationLabel": "Agregasi",
    "GroupByHelp": "Kolom numerik diagregasi per grup. Hitung menambahkan kolom \"Hitung\".",
    "AggNone": "Tidak Ada",
    "AggSum": "Jumlah",
    "AggAvg": "Rata-rata",
    "AggCount": "Hitung",
    "AggMin": "Min",
    "AggMax": "Maks",
    // Data table
    "DataTableHeader": "Tabel Data ({0} baris)",
    "PrevPageButton": "← Sebelumnya",
    "NextPageButton": "Berikutnya →",
    "PageOfLabel": "Halaman {0} dari {1}",
    // Export bar
    "ExportLabel": "Ekspor:",
    "ExportPngTitle": "Unduh bagan sebagai gambar PNG",
    "ExportJpegTitle": "Unduh bagan sebagai gambar JPEG",
    "ExportCsvTitle": "Unduh data sebagai CSV",
    "ExportExcelTitle": "Unduh data sebagai buku kerja Excel"
  }
});
