define([], function() {
  return {
    "PropertyPaneDescription": "Configura la visualizzazione dei dati",
    "HeaderGroupName": "Intestazione",
    "WebPartHeaderFieldLabel": "Testo intestazione",
    "WebPartHeaderPlaceholder": "ad es. Dashboard vendite",
    "ShowWebPartHeaderFieldLabel": "Mostra intestazione",
    "ChartSettingsGroupName": "Impostazioni grafico",
    "ChartTitleFieldLabel": "Titolo grafico",
    "ChartTypeFieldLabel": "Tipo di grafico",
    "LegendPositionFieldLabel": "Posizione legenda",
    "ChartHeightFieldLabel": "Altezza grafico (px)",
    "ShowLegendFieldLabel": "Mostra legenda",
    "StackedFieldLabel": "In pila (barre/linee)",
    "ShowDataTableFieldLabel": "Mostra tabella dati",
    "ShowExportBarFieldLabel": "Mostra barra di esportazione",
    "XAxisLabelFieldLabel": "Etichetta asse X (facoltativa)",
    "XAxisPlaceholder": "Per impostazione predefinita, la colonna selezionata",
    "YAxisLabelFieldLabel": "Etichetta asse Y (facoltativa)",
    "YAxisPlaceholder": "Per impostazione predefinita, le colonne selezionate",
    "ChartGroupStandard": "Grafici standard",
    "ChartGroupSpecialized": "Grafici specializzati",
    "ChartTypeBarLabel": "Grafico a barre (verticale)",
    "ChartTypeHorizontalBarLabel": "Grafico a barre (orizzontale)",
    "ChartTypeLineLabel": "Grafico a linee",
    "ChartTypeAreaLabel": "Grafico ad area",
    "ChartTypeScatterLabel": "Grafico a dispersione",
    "ChartTypePieLabel": "Grafico a torta",
    "ChartTypeDoughnutLabel": "Grafico ad anello",
    "ChartTypeBubbleLabel": "Grafico a bolle",
    "ChartTypeRadarLabel": "Grafico radar",
    "ChartTypeKpiLabel": "Riquadro KPI",
    "ChartTypeHistogramLabel": "Istogramma",
    "ChartTypeWaterfallLabel": "Grafico a cascata",
    "ChartTypeBoxplotLabel": "Boxplot",
    "ChartTypeViolinLabel": "Grafico a violino",
    "ChartTypeBeforeAfterLabel": "Grafico prima-dopo",
    "ChartTypeTreemapLabel": "Mappa ad albero",
    "ChartTypeHeatmapLabel": "Mappa termica",
    "HistogramBinsFieldLabel": "Intervalli istogramma",
    "AppearancePageDescription": "Colori, etichette e assi",
    "AdvancedPageDescription": "Analisi, linee di riferimento, interattività e aggiornamento dei dati",
    "LegendTopLabel": "In alto",
    "LegendBottomLabel": "In basso",
    "LegendLeftLabel": "A sinistra",
    "LegendRightLabel": "A destra",
    "ColorsGroupName": "Colori",
    "ColorPaletteFieldLabel": "Tavolozza colori",
    "PaletteOfficeLabel": "Office (predefinita)",
    "PaletteVibrantLabel": "Vivace",
    "PalettePastelLabel": "Pastello",
    "PaletteMonochromeLabel": "Monocromatica",
    "PaletteTrafficLightLabel": "Semaforo",
    "PaletteWarmLabel": "Calda",
    "PaletteCoolLabel": "Fredda",
    "DataLabelsGroupName": "Etichette dati e formattazione",
    "ShowDataLabelsFieldLabel": "Mostra etichette dati",
    "ValuePrefixFieldLabel": "Prefisso valore",
    "ValuePrefixPlaceholder": "ad es. €",
    "ValueSuffixFieldLabel": "Suffisso valore",
    "ValueSuffixPlaceholder": "ad es. %",
    "ValueDecimalsFieldLabel": "Cifre decimali",
    "AbbreviateNumbersFieldLabel": "Abbrevia numeri (K/M)",
    "AxesGridGroupName": "Assi e griglia",
    "YAxisMinFieldLabel": "Minimo asse Y",
    "YAxisMaxFieldLabel": "Massimo asse Y",
    "AutoPlaceholder": "Automatico",
    "NumericValidationError": "Immetti un numero oppure lascia vuoto per il valore automatico.",
    "ColorValidationError": "Immetti un colore esadecimale (ad es. #d13438) oppure lascia vuoto per il valore predefinito.",
    "LogScaleFieldLabel": "Scala logaritmica (Y)",
    "LogScaleXFieldLabel": "Scala logaritmica (X)",
    "StepLineFieldLabel": "Interpolazione a gradini",
    "ShowGridLinesFieldLabel": "Mostra linee della griglia",
    "XLabelRotationFieldLabel": "Rotazione etichette X (gradi)",
    "XAxisTypeFieldLabel": "Tipo di asse X",
    "XAxisTypeAuto": "Rilevamento automatico",
    "XAxisTypeCategory": "Categoria",
    "XAxisTypeTime": "Tempo (date)",
    "AnalyticsGroupName": "Analisi",
    "TrendlineFieldLabel": "Linea di tendenza",
    "TrendlineNone": "Nessuna",
    "TrendlineLinear": "Lineare",
    "TrendlineMovingAverage": "Media mobile",
    "TrendWindowFieldLabel": "Finestra media mobile",
    "TrendSuffix": " (tendenza)",
    "ForecastPeriodsFieldLabel": "Periodi di previsione (linea di tendenza lineare)",
    "ReferenceLineGroupName": "Linea di riferimento",
    "ReferenceLineTypeFieldLabel": "Linea di riferimento",
    "ReferenceLineValueFieldLabel": "Valore fisso",
    "ReferenceLineColorFieldLabel": "Colore linea (esadecimale)",
    "RefLineFixed": "Valore fisso",
    "RefLineMean": "Media",
    "RefLineMedian": "Mediana",
    "DualAxisGroupName": "Doppio asse Y",
    "Y2ColumnsFieldLabel": "Serie asse destro (nomi di colonna separati da virgole)",
    "Y2ColumnsPlaceholder": "ad es. Margine,Crescita",
    "Y2AxisLabelFieldLabel": "Etichetta asse destro",
    "LogScaleY2FieldLabel": "Scala logaritmica (asse destro)",
    "ErrorBarsGroupName": "Barre di errore",
    "ErrorBarTypeFieldLabel": "Tipo di barra di errore",
    "ErrorBarTypeNone": "Nessuna",
    "ErrorBarTypeCustom": "Colonna personalizzata (±)",
    "ErrorBarTypeSd": "Dev. standard (calcolata)",
    "ErrorBarTypeSem": "Errore standard della media (calcolato)",
    "ErrorBarColumnFieldLabel": "Colonna valore di errore",
    "SignificanceGroupName": "Parentesi di significatività",
    "SignificancePairsFieldLabel": "Coppie di parentesi",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Una parentesi per riga: col1,col2,etichetta  — ad es. GruppoA,GruppoB,*  oppure  GruppoA,GruppoB,p<0.05  (è accettato anche un array JSON)",
    "BeforeAfterColumnsError": "Il grafico prima-dopo richiede esattamente 2 colonne Y: una per i valori Prima e una per i valori Dopo.",
    "InteractivityGroupName": "Interattività",
    "ShowViewerFiltersFieldLabel": "Mostra filtri ai visitatori",
    "DetailsOnDemandFieldLabel": "Mostra righe di dati al clic",
    "ShowDataPointsFieldLabel": "Sovrapponi punti dati alle barre",
    "ShowBubbleSizeLegendFieldLabel": "Mostra legenda dimensione bolle",
    "ViewerFilterLabel": "Filtro:",
    "ViewerFilterColumnAria": "Colonna filtro",
    "ViewerFilterValueAria": "Valore filtro",
    "DrillAllLabel": "Tutti",
    "DetailsChipLabel": "Dettagli: {0} ({1} righe)",
    "KpiSubLabel": "{0} • {1} • {2} righe",
    "ConditionalGroupName": "Formattazione condizionale",
    "ThresholdValueFieldLabel": "Valore soglia",
    "ThresholdValuePlaceholder": "Disattivato",
    "ThresholdDirectionFieldLabel": "Evidenzia valori",
    "ThresholdBelow": "Sotto la soglia",
    "ThresholdAbove": "Sopra la soglia",
    "ThresholdColorFieldLabel": "Colore evidenziazione (esadecimale)",
    "DataRefreshGroupName": "Dati e aggiornamento",
    "RefreshIntervalFieldLabel": "Intervallo di aggiornamento automatico (minuti, 0 = disattivato)",
    "CacheMinutesFieldLabel": "Memorizza dati nella cache (minuti, 0 = disattivato)",
    "DynamicDataCategoryLabel": "Categoria selezionata",
    "DynamicDataValueLabel": "Valore selezionato",
    "DynamicDataSeriesLabel": "Serie selezionata",
    "DataSourceGroupName": "Origine dati",
    "HideDataSourceButton": "▲ Nascondi origine dati",
    "ConfigureDataSourceButton": "▼ Configura origine dati",
    "RowsLoadedBadge": "✓ {0} righe caricate",
    "ReadModeLoadError": "Impossibile caricare i dati: {0}. Passa alla modalità di modifica per riconfigurare l'origine dati.",
    "RefreshDataButton": "↻ Aggiorna dati",
    "RefreshingLabel": "Aggiornamento in corso…",
    "RefreshDataTitle": "Ricarica i dati dall'origine configurata",
    "NoDataMessage": "Nessun dato ancora caricato. Configura l'origine dati qui sopra e fai clic su Carica dati.",
    "SelectMappingsMessage": "Dati caricati ({0} righe). Seleziona i mapping delle colonne qui sopra per visualizzare il grafico.",
    "ChartRenderErrorLabel": "Errore di rendering del grafico: {0}",
    "UnsupportedChartTypeLabel": "Tipo di grafico non supportato: {0}",
    "ChartAriaLabel": "Grafico di visualizzazione dei dati",
    "FilterOperatorLabel": "Operatore",
    "FilterValueLabel": "Valore",
    "FilterOpContains": "contiene",
    "FilterOpEquals": "è uguale a",
    "FilterOpNotEquals": "non è uguale a",
    "FilterOpGt": "maggiore di",
    "FilterOpLt": "minore di",
    "FilterOpBetween": "tra (min..max)",
    "FilterOpIsEmpty": "è vuoto",
    "FilterOpNotEmpty": "non è vuoto",
    "AddFilterButton": "+ Aggiungi filtro",
    "RemoveFilterButton": "Rimuovi",
    "SelectValuePlaceholder": "Seleziona valore…",
    "ViewerFilterOperatorAria": "Operatore filtro",
    "PaletteColorblindLabel": "Adatta ai daltonici",
    "WaterfallGroupName": "Cascata",
    "WaterfallShowTotalFieldLabel": "Mostra barra del totale",
    "WaterfallPositiveColorFieldLabel": "Colore aumento",
    "WaterfallNegativeColorFieldLabel": "Colore diminuzione",
    "WaterfallTotalColorFieldLabel": "Colore totale",
    "WaterfallTotalLabel": "Totale",
    "ExternalFilterGroupName": "Filtra da un altro elemento Web Part",
    "ExternalFilterFieldLabel": "Origine valore filtro",
    "ExternalFilterColumnFieldLabel": "Colonna da filtrare",
    "ExternalFilterColumnPlaceholder": "Per impostazione predefinita, la colonna dell'asse X",
    "ViewAsTableButton": "Visualizza come tabella",
    "HideTableButton": "Nascondi tabella",
    "ChartKeyboardHint": "Usa i tasti freccia per spostarti tra i punti dati e Invio per selezionarne uno.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Prefisso valore Y2",
    "Y2ValueSuffixFieldLabel": "Suffisso valore Y2",
    "AnnotationsGroupName": "Annotazioni",
    "AnnotationsFieldLabel": "Annotazioni",
    "AnnotationsPlaceholder": "Gen, Lancio del prodotto",
    "AnnotationsHelp": "Una per riga: il valore dell'asse X, una virgola, quindi il testo della nota. In corrispondenza di quel valore X viene disegnato un indicatore verticale.",
    "BeforeLabel": "Prima",
    "AfterLabel": "Dopo",
    "RowLabel": "Riga {0}",
    "PointsSuffix": " (punti)",
    "ExportSheetName": "Dati",
    "RefreshFailedNote": "Ultimo aggiornamento non riuscito: {0}. Vengono mostrati i dati caricati in precedenza.",
    "TruncatedDataNote": "Vengono mostrate solo le prime {0} righe; l'origine contiene altri dati.",
    "ScatterNumericWarning": "I grafici a dispersione e a bolle richiedono valori numerici. La colonna \"{0}\" non contiene dati numerici: scegli un'altra colonna nel mapping qui sopra.",
    "TimeAxisUnparseableWarning": "La colonna dell'asse X \"{0}\" non contiene valori interpretabili come date. Imposta Tipo di asse X su \"Categoria\" oppure mappa una colonna di date.",
    "DataSourceSectionHeader": "Origine dati",
    "SourceUploadLabel": "Carica file",
    "SourceSharePointListLabel": "Elenco SharePoint",
    "SourceSharePointFileLabel": "File SharePoint",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Percorso Graph API",
    "GraphPathHelp": "Percorso relativo di Microsoft Graph, ad es. /me/memberOf oppure /reports/getTeamsUserActivityUserCounts(period='D7'). Questa origine richiede autorizzazioni Graph approvate da un amministratore: tutte le altre origini dati funzionano senza.",
    "SheetNameLabel": "Foglio Excel",
    "DelimiterLabel": "Delimitatore",
    "DelimiterAutoDetect": "Rilevamento automatico",
    "DelimiterComma": "Virgola (,)",
    "DelimiterTab": "Tabulazione",
    "DelimiterSemicolon": "Punto e virgola (;)",
    "DelimiterPipe": "Barra verticale (|)",
    "SiteUrlLabel": "URL del sito (facoltativo)",
    "SiteUrlHelp": "Lascia vuoto per usare il sito corrente.",
    "ListNameLabel": "Nome elenco",
    "LoadingListsLabel": "— Caricamento elenchi…",
    "SelectListPlaceholder": "— Seleziona un elenco —",
    "EnterListNamePlaceholder": "Immetti il nome dell'elenco",
    "ListNameExamplePlaceholder": "ad es. Dati vendite",
    "ListDiscoveryError": "Impossibile caricare gli elenchi: immetti il nome manualmente qui sotto.",
    "FileUrlLabel": "URL del file (CSV/TSV/Excel in SharePoint)",
    "FileUrlHelp": "URL completo di un file in una raccolta documenti.",
    "ApiUrlLabel": "URL API",
    "DataPathLabel": "Percorso dati (facoltativo)",
    "DataPathHelp": "Percorso separato da punti dell'array nella risposta JSON. Lascia vuoto se la radice è un array. Per SharePoint REST API usa \"value\".",
    "UploadHelp": "Carica un file CSV, TSV o Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} righe",
    "ChangeFileButton": "Cambia file…",
    "ClearButton": "Cancella",
    "ChooseFileButton": "Scegli file…",
    "LoadDataButton": "Carica dati",
    "LoadingLabel": "Caricamento…",
    "ErrorSelectListName": "Seleziona o immetti il nome di un elenco.",
    "ErrorEnterFileUrl": "Immetti l'URL di un file.",
    "ErrorEnterUrl": "Immetti un URL.",
    "ErrorLoadList": "Impossibile caricare l'elenco SharePoint: {0}",
    "ErrorLoadFile": "Impossibile caricare il file: {0}",
    "ErrorFetchData": "Impossibile recuperare i dati: {0}",
    "ErrorDataPathNotFound": "Il percorso dati \"{0}\" non è stato trovato nella risposta.",
    "ErrorUrlReturnedHtml": "Questo URL ha restituito una pagina Web, non un file. Usa il percorso di download diretto del file, non un URL di condivisione \"Copia collegamento\".",
    "ErrorRequestTimedOut": "Richiesta scaduta. Controlla l'URL e la connessione di rete.",
    "ErrorNonJsonResponse": "Impossibile analizzare la risposta come JSON.",
    "ErrorUnsupportedFileType": "Tipo di file non supportato. Carica un file .csv, .tsv, .xlsx o .xls.",
    "ErrorReadFile": "Impossibile leggere il file",
    "ErrorParseFile": "Impossibile analizzare il file",
    "LoadedRowsColumns": "Caricate {0} righe con {1} colonne.",
    "LoadedRowsColumnsPersist": "Caricate {0} righe con {1} colonne. I dati verranno mantenuti quando lasci la pagina.",
    "SizeWarning": "Il set di dati ({0}KB) supera il limite di persistenza di 200KB. Il grafico mostrerà i dati durante questa sessione ma verrà azzerato al ricaricamento della pagina. Per file di grandi dimensioni, caricali in una raccolta di SharePoint e usa l'origine File SharePoint.",
    "ListTruncatedWarning": "Questo elenco contiene {0} o più elementi; sono stati caricati solo i primi {0}.",
    "GraphTruncatedWarning": "Questo risultato di Microsoft Graph contiene più pagine di quante ne siano state caricate; sono state recuperate solo le prime {0} pagine.",
    "CsvParseWarning": "{0} righe non hanno potuto essere analizzate e sono state ignorate.",
    "ColumnMappingSectionHeader": "Mapping colonne",
    "CategoryColumnLabel": "Colonna categoria (X / etichette)",
    "LabelColumnLabel": "Colonna etichetta",
    "XAxisColumnLabel": "Colonna asse X",
    "ValueColumnLabel": "Colonna valore",
    "YAxisColumnLabel": "Colonna asse Y",
    "YAxisColumnsLabel": "Colonne asse Y",
    "YAxisColumnsHelp": "(selezionane una o più; fai clic sul campione per impostare il colore)",
    "SelectColumnPlaceholder": "— Seleziona colonna —",
    "ScatterLabelColumnLabel": "Etichetta punto",
    "SizeColumnLabel": "Colonna dimensione / raggio",
    "NoSizeColumnOption": "— Nessuna (dimensione fissa) —",
    "SeriesColorTitle": "Colore per {0}",
    "SeriesTypeTitle": "Tipo di grafico per {0}",
    "SeriesTypeDefault": "Predefinito",
    "SeriesTypeBar": "Barre",
    "SeriesTypeLine": "Linee",
    "HistogramColumnLabel": "Colonna da suddividere (numerica)",
    "TreemapGroupLabel": "Colonna gruppo / etichetta",
    "HeatmapColumnLabel": "Categoria colonna (X)",
    "HeatmapRowLabel": "Categoria riga (Y)",
    "AdvancedOptionsClosed": "▼ Opzioni avanzate",
    "AdvancedOptionsOpen": "▲ Opzioni avanzate",
    "ColorByLabel": "Colora per colonna",
    "ColorByHelp": "Colora i punti per categoria anziché per serie.",
    "TooltipColumnsLabel": "Colonne descrizione comando",
    "TooltipColumnsHelp": "(colonne aggiuntive mostrate al passaggio del mouse su un punto dati)",
    "DrillLevelLabel": "Livello di drill {0}",
    "DrillDownHelp": "Definisci una gerarchia di colonne per abilitare il drill con clic (ad es. Regione → Paese → Città). I valori vengono aggregati a ogni livello.",
    "BookmarksLabel": "Segnalibri",
    "BookmarkNameLabel": "Nome segnalibro",
    "BookmarkNamePlaceholder": "ad es. Primi 10 per regione",
    "SaveBookmarkButton": "Salva vista corrente",
    "ApplyBookmarkButton": "Applica",
    "DeleteBookmarkButton": "Elimina",
    "ApplyBookmarkPlaceholder": "— Applica un segnalibro —",
    "DataControlsSectionHeader": "Controlli dati",
    "SortByColumnLabel": "Ordina per colonna",
    "NoneOption": "— Nessuno —",
    "SortDirectionLabel": "Direzione ordinamento",
    "AscendingOption": "Crescente",
    "DescendingOption": "Decrescente",
    "RowLimitLabel": "Limite righe (0 = tutte)",
    "FilterColumnLabel": "Colonna filtro",
    "FilterContainsLabel": "Filtro: contiene",
    "FilterValuePlaceholder": "Valore filtro…",
    "GroupByLabel": "Raggruppa per colonna",
    "AggregationLabel": "Aggregazione",
    "GroupByHelp": "Le colonne numeriche vengono aggregate per gruppo. Conteggio aggiunge una colonna \"Count\".",
    "AggNone": "Nessuna",
    "AggSum": "Somma",
    "AggAvg": "Media",
    "AggCount": "Conteggio",
    "AggMin": "Min",
    "AggMax": "Max",
    "DataTableHeader": "Tabella dati ({0} righe)",
    "PrevPageButton": "← Prec.",
    "NextPageButton": "Succ. →",
    "PageOfLabel": "Pagina {0} di {1}",
    "ExportLabel": "Esporta:",
    "ExportPngTitle": "Scarica il grafico come immagine PNG",
    "ExportJpegTitle": "Scarica il grafico come immagine JPEG",
    "ExportCsvTitle": "Scarica i dati come CSV",
    "ExportExcelTitle": "Scarica i dati come cartella di lavoro Excel"
  }
});
