define([], function() {
  return {
    "PropertyPaneDescription": "データ視覚化を構成します",
    "HeaderGroupName": "ヘッダー",
    "WebPartHeaderFieldLabel": "ヘッダー テキスト",
    "WebPartHeaderPlaceholder": "例: 売上ダッシュボード",
    "ShowWebPartHeaderFieldLabel": "ヘッダーを表示する",
    "ChartSettingsGroupName": "グラフの設定",
    "ChartTitleFieldLabel": "グラフ タイトル",
    "ChartTypeFieldLabel": "グラフの種類",
    "LegendPositionFieldLabel": "凡例の位置",
    "ChartHeightFieldLabel": "グラフの高さ (px)",
    "ShowLegendFieldLabel": "凡例を表示する",
    "StackedFieldLabel": "積み上げ (棒/折れ線)",
    "ShowDataTableFieldLabel": "データ テーブルを表示する",
    "ShowExportBarFieldLabel": "エクスポート バーを表示する",
    "XAxisLabelFieldLabel": "X 軸ラベル (省略可能)",
    "XAxisPlaceholder": "既定では選択した列",
    "YAxisLabelFieldLabel": "Y 軸ラベル (省略可能)",
    "YAxisPlaceholder": "既定では選択した列",
    "ChartGroupStandard": "標準グラフ",
    "ChartGroupSpecialized": "専用グラフ",
    "ChartTypeBarLabel": "棒グラフ (縦)",
    "ChartTypeHorizontalBarLabel": "棒グラフ (横)",
    "ChartTypeLineLabel": "折れ線グラフ",
    "ChartTypeAreaLabel": "面グラフ",
    "ChartTypeScatterLabel": "散布図",
    "ChartTypePieLabel": "円グラフ",
    "ChartTypeDoughnutLabel": "ドーナツ グラフ",
    "ChartTypeBubbleLabel": "バブル チャート",
    "ChartTypeRadarLabel": "レーダー チャート",
    "ChartTypeKpiLabel": "KPI タイル",
    "ChartTypeHistogramLabel": "ヒストグラム",
    "ChartTypeWaterfallLabel": "ウォーターフォール グラフ",
    "ChartTypeBoxplotLabel": "箱ひげ図",
    "ChartTypeViolinLabel": "バイオリン プロット",
    "ChartTypeBeforeAfterLabel": "前後比較プロット",
    "ChartTypeTreemapLabel": "ツリーマップ",
    "ChartTypeHeatmapLabel": "ヒート マップ",
    "HistogramBinsFieldLabel": "ヒストグラムのビン数",
    "AppearancePageDescription": "色、ラベル、軸",
    "AdvancedPageDescription": "分析、基準線、対話機能、データの更新",
    "LegendTopLabel": "上",
    "LegendBottomLabel": "下",
    "LegendLeftLabel": "左",
    "LegendRightLabel": "右",
    "ColorsGroupName": "色",
    "ColorPaletteFieldLabel": "カラー パレット",
    "PaletteOfficeLabel": "Office (既定)",
    "PaletteVibrantLabel": "ビビッド",
    "PalettePastelLabel": "パステル",
    "PaletteMonochromeLabel": "モノクロ",
    "PaletteTrafficLightLabel": "信号機",
    "PaletteWarmLabel": "暖色",
    "PaletteCoolLabel": "寒色",
    "DataLabelsGroupName": "データ ラベルと書式設定",
    "ShowDataLabelsFieldLabel": "データ ラベルを表示する",
    "ValuePrefixFieldLabel": "値のプレフィックス",
    "ValuePrefixPlaceholder": "例: ¥",
    "ValueSuffixFieldLabel": "値のサフィックス",
    "ValueSuffixPlaceholder": "例: %",
    "ValueDecimalsFieldLabel": "小数点以下の桁数",
    "AbbreviateNumbersFieldLabel": "数値を省略表示する (K/M)",
    "AxesGridGroupName": "軸とグリッド",
    "YAxisMinFieldLabel": "Y 軸の最小値",
    "YAxisMaxFieldLabel": "Y 軸の最大値",
    "AutoPlaceholder": "自動",
    "NumericValidationError": "数値を入力してください。自動にする場合は空白のままにします。",
    "ColorValidationError": "16 進数の色 (例: #d13438) を入力してください。既定にする場合は空白のままにします。",
    "LogScaleFieldLabel": "対数目盛 (Y)",
    "LogScaleXFieldLabel": "対数目盛 (X)",
    "StepLineFieldLabel": "階段状補間",
    "ShowGridLinesFieldLabel": "グリッド線を表示する",
    "XLabelRotationFieldLabel": "X ラベルの回転 (度)",
    "XAxisTypeFieldLabel": "X 軸の種類",
    "XAxisTypeAuto": "自動検出",
    "XAxisTypeCategory": "カテゴリ",
    "XAxisTypeTime": "時間 (日付)",
    "AnalyticsGroupName": "分析",
    "TrendlineFieldLabel": "近似曲線",
    "TrendlineNone": "なし",
    "TrendlineLinear": "線形",
    "TrendlineMovingAverage": "移動平均",
    "TrendWindowFieldLabel": "移動平均の期間",
    "TrendSuffix": " (トレンド)",
    "ForecastPeriodsFieldLabel": "予測期間 (線形近似曲線)",
    "ReferenceLineGroupName": "基準線",
    "ReferenceLineTypeFieldLabel": "基準線",
    "ReferenceLineValueFieldLabel": "固定値",
    "ReferenceLineColorFieldLabel": "線の色 (16 進数)",
    "RefLineFixed": "固定値",
    "RefLineMean": "平均",
    "RefLineMedian": "中央値",
    "DualAxisGroupName": "2 軸 Y 軸",
    "Y2ColumnsFieldLabel": "右軸の系列 (列名をコンマで区切る)",
    "Y2ColumnsPlaceholder": "例: 利益率,成長率",
    "Y2AxisLabelFieldLabel": "右軸ラベル",
    "LogScaleY2FieldLabel": "対数目盛 (右軸)",
    "ErrorBarsGroupName": "誤差範囲",
    "ErrorBarTypeFieldLabel": "誤差範囲の種類",
    "ErrorBarTypeNone": "なし",
    "ErrorBarTypeCustom": "ユーザー設定の列 (±)",
    "ErrorBarTypeSd": "標準偏差 (計算)",
    "ErrorBarTypeSem": "平均の標準誤差 (計算)",
    "ErrorBarColumnFieldLabel": "誤差値の列",
    "SignificanceGroupName": "有意差ブラケット",
    "SignificancePairsFieldLabel": "ブラケットのペア",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "1 行に 1 つのブラケット: 列1,列2,ラベル  — 例: GroupA,GroupB,*  または  GroupA,GroupB,p<0.05  (JSON 配列も使用できます)",
    "BeforeAfterColumnsError": "前後比較グラフには、Y 列がちょうど 2 つ必要です。1 つは変更前の値、もう 1 つは変更後の値です。",
    "InteractivityGroupName": "対話機能",
    "ShowViewerFiltersFieldLabel": "閲覧者にフィルターを表示する",
    "DetailsOnDemandFieldLabel": "クリック時にデータ行を表示する",
    "ShowDataPointsFieldLabel": "棒にデータ ポイントを重ねて表示する",
    "ShowBubbleSizeLegendFieldLabel": "バブル サイズの凡例を表示する",
    "ViewerFilterLabel": "フィルター:",
    "ViewerFilterColumnAria": "フィルターの列",
    "ViewerFilterValueAria": "フィルターの値",
    "DrillAllLabel": "すべて",
    "DetailsChipLabel": "詳細: {0} ({1} 行)",
    "KpiSubLabel": "{0} • {1} • {2} 行",
    "ConditionalGroupName": "条件付き書式",
    "ThresholdValueFieldLabel": "しきい値",
    "ThresholdValuePlaceholder": "オフ",
    "ThresholdDirectionFieldLabel": "強調表示する値",
    "ThresholdBelow": "しきい値未満",
    "ThresholdAbove": "しきい値超過",
    "ThresholdColorFieldLabel": "強調表示の色 (16 進数)",
    "DataRefreshGroupName": "データと更新",
    "RefreshIntervalFieldLabel": "自動更新の間隔 (分、0 = オフ)",
    "CacheMinutesFieldLabel": "データをキャッシュする (分、0 = オフ)",
    "DynamicDataCategoryLabel": "選択されたカテゴリ",
    "DynamicDataValueLabel": "選択された値",
    "DynamicDataSeriesLabel": "選択された系列",
    "DataSourceGroupName": "データ ソース",
    "HideDataSourceButton": "▲ データ ソースを非表示",
    "ConfigureDataSourceButton": "▼ データ ソースを構成",
    "RowsLoadedBadge": "✓ {0} 行を読み込みました",
    "ReadModeLoadError": "データを読み込めませんでした: {0}。データ ソースを再構成するには、編集モードに切り替えてください。",
    "RefreshDataButton": "↻ データを更新",
    "RefreshingLabel": "更新中…",
    "RefreshDataTitle": "構成されたソースからデータを再読み込みします",
    "NoDataMessage": "データはまだ読み込まれていません。上でデータ ソースを構成し、[データの読み込み] をクリックしてください。",
    "SelectMappingsMessage": "データを読み込みました ({0} 行)。グラフを表示するには、上で列のマッピングを選択してください。",
    "ChartRenderErrorLabel": "グラフのレンダリング エラー: {0}",
    "UnsupportedChartTypeLabel": "サポートされていないグラフの種類: {0}",
    "ChartAriaLabel": "データ視覚化グラフ",
    "FilterOperatorLabel": "演算子",
    "FilterValueLabel": "値",
    "FilterOpContains": "を含む",
    "FilterOpEquals": "と等しい",
    "FilterOpNotEquals": "と等しくない",
    "FilterOpGt": "より大きい",
    "FilterOpLt": "より小さい",
    "FilterOpBetween": "範囲内 (下限..上限)",
    "FilterOpIsEmpty": "が空",
    "FilterOpNotEmpty": "が空でない",
    "AddFilterButton": "+ フィルターを追加",
    "RemoveFilterButton": "削除",
    "SelectValuePlaceholder": "値を選択…",
    "ViewerFilterOperatorAria": "フィルターの演算子",
    "PaletteColorblindLabel": "色覚多様性に配慮",
    "WaterfallGroupName": "ウォーターフォール",
    "WaterfallShowTotalFieldLabel": "合計バーを表示する",
    "WaterfallPositiveColorFieldLabel": "増加の色",
    "WaterfallNegativeColorFieldLabel": "減少の色",
    "WaterfallTotalColorFieldLabel": "合計の色",
    "WaterfallTotalLabel": "合計",
    "ExternalFilterGroupName": "別の Web パーツからフィルター",
    "ExternalFilterFieldLabel": "フィルター値のソース",
    "ExternalFilterColumnFieldLabel": "フィルター対象の列",
    "ExternalFilterColumnPlaceholder": "既定では X 軸の列",
    "ViewAsTableButton": "テーブルとして表示",
    "HideTableButton": "テーブルを非表示",
    "ChartKeyboardHint": "方向キーでデータ ポイント間を移動し、Enter キーで選択します。",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Y2 値のプレフィックス",
    "Y2ValueSuffixFieldLabel": "Y2 値のサフィックス",
    "AnnotationsGroupName": "注釈",
    "AnnotationsFieldLabel": "注釈",
    "AnnotationsPlaceholder": "1月, 製品発売",
    "AnnotationsHelp": "1 行に 1 つ: X 軸の値、コンマ、注釈テキストの順に入力します。その X 値の位置に縦のマーカーが描画されます。",
    "BeforeLabel": "変更前",
    "AfterLabel": "変更後",
    "RowLabel": "行 {0}",
    "PointsSuffix": " (ポイント)",
    "ExportSheetName": "データ",
    "RefreshFailedNote": "前回の更新に失敗しました: {0}。以前に読み込んだデータを表示しています。",
    "TruncatedDataNote": "最初の {0} 行のみを表示しています。ソースにはさらにデータがあります。",
    "ScatterNumericWarning": "散布図とバブル チャートには数値が必要です。列 \"{0}\" に数値データがありません。上のマッピングで別の列を選択してください。",
    "TimeAxisUnparseableWarning": "X 軸の列 \"{0}\" に、日付として解析できる値がありません。X 軸の種類を \"カテゴリ\" に切り替えるか、日付列をマッピングしてください。",
    "DataSourceSectionHeader": "データ ソース",
    "SourceUploadLabel": "ファイルのアップロード",
    "SourceSharePointListLabel": "SharePoint リスト",
    "SourceSharePointFileLabel": "SharePoint ファイル",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API パス",
    "GraphPathHelp": "Microsoft Graph の相対パス (例: /me/memberOf や /reports/getTeamsUserActivityUserCounts(period='D7'))。このソースには、管理者によって承認された Graph のアクセス許可が必要です。その他のデータ ソースは、アクセス許可なしで動作します。",
    "SheetNameLabel": "Excel シート",
    "DelimiterLabel": "区切り文字",
    "DelimiterAutoDetect": "自動検出",
    "DelimiterComma": "コンマ (,)",
    "DelimiterTab": "タブ",
    "DelimiterSemicolon": "セミコロン (;)",
    "DelimiterPipe": "パイプ (|)",
    "SiteUrlLabel": "サイト URL (省略可能)",
    "SiteUrlHelp": "現在のサイトを使用する場合は空白のままにします。",
    "ListNameLabel": "リスト名",
    "LoadingListsLabel": "— リストを読み込み中…",
    "SelectListPlaceholder": "— リストを選択 —",
    "EnterListNamePlaceholder": "リスト名を入力",
    "ListNameExamplePlaceholder": "例: 売上データ",
    "ListDiscoveryError": "リストを読み込めませんでした。下に名前を手動で入力してください。",
    "FileUrlLabel": "ファイル URL (SharePoint 内の CSV/TSV/Excel)",
    "FileUrlHelp": "ドキュメント ライブラリ内のファイルへの完全な URL。",
    "ApiUrlLabel": "API URL",
    "DataPathLabel": "データ パス (省略可能)",
    "DataPathHelp": "JSON 応答内の配列へのドット区切りのパス。ルートが配列の場合は空白のままにします。SharePoint REST API の場合は \"value\" を使用します。",
    "UploadHelp": "CSV、TSV、または Excel (.xlsx、.xls) ファイルをアップロードします。",
    "LoadedFileRowsLabel": "— {0} 行",
    "ChangeFileButton": "ファイルの変更…",
    "ClearButton": "クリア",
    "ChooseFileButton": "ファイルを選択…",
    "LoadDataButton": "データの読み込み",
    "LoadingLabel": "読み込み中…",
    "ErrorSelectListName": "リスト名を選択または入力してください。",
    "ErrorEnterFileUrl": "ファイル URL を入力してください。",
    "ErrorEnterUrl": "URL を入力してください。",
    "ErrorLoadList": "SharePoint リストを読み込めませんでした: {0}",
    "ErrorLoadFile": "ファイルを読み込めませんでした: {0}",
    "ErrorFetchData": "データを取得できませんでした: {0}",
    "ErrorDataPathNotFound": "データ パス \"{0}\" が応答内に見つかりませんでした。",
    "ErrorUrlReturnedHtml": "この URL はファイルではなく Web ページを返しました。「リンクのコピー」の共有 URL ではなく、ファイルの直接ダウンロード パスを使用してください。",
    "ErrorRequestTimedOut": "要求がタイムアウトしました。URL とネットワーク接続を確認してください。",
    "ErrorNonJsonResponse": "応答を JSON として解析できませんでした。",
    "ErrorUnsupportedFileType": "サポートされていないファイルの種類です。.csv、.tsv、.xlsx、または .xls ファイルをアップロードしてください。",
    "ErrorReadFile": "ファイルを読み取れませんでした",
    "ErrorParseFile": "ファイルを解析できませんでした",
    "LoadedRowsColumns": "{0} 行、{1} 列を読み込みました。",
    "LoadedRowsColumnsPersist": "{0} 行、{1} 列を読み込みました。ページを離れてもデータは保持されます。",
    "SizeWarning": "データセット ({0}KB) が永続化の上限 200KB を超えています。グラフはこのセッション中はデータを表示しますが、ページを再読み込みするとクリアされます。大きなファイルは、SharePoint ライブラリにアップロードし、SharePoint ファイル ソースを使用してください。",
    "ListTruncatedWarning": "このリストには {0} 個以上の項目があります。最初の {0} 個のみが読み込まれました。",
    "GraphTruncatedWarning": "この Microsoft Graph の結果には、読み込める数を超えるページがあります。最初の {0} ページのみが取得されました。",
    "CsvParseWarning": "{0} 行を解析できなかったため、スキップしました。",
    "ColumnMappingSectionHeader": "列のマッピング",
    "CategoryColumnLabel": "カテゴリ列 (X / ラベル)",
    "LabelColumnLabel": "ラベル列",
    "XAxisColumnLabel": "X 軸の列",
    "ValueColumnLabel": "値の列",
    "YAxisColumnLabel": "Y 軸の列",
    "YAxisColumnsLabel": "Y 軸の列",
    "YAxisColumnsHelp": "(1 つ以上を選択。色を設定するにはスウォッチをクリック)",
    "SelectColumnPlaceholder": "— 列を選択 —",
    "ScatterLabelColumnLabel": "ポイント ラベル",
    "SizeColumnLabel": "サイズ / 半径の列",
    "NoSizeColumnOption": "— なし (固定サイズ) —",
    "SeriesColorTitle": "{0} の色",
    "SeriesTypeTitle": "{0} のグラフの種類",
    "SeriesTypeDefault": "既定",
    "SeriesTypeBar": "棒",
    "SeriesTypeLine": "折れ線",
    "HistogramColumnLabel": "ビンに分ける列 (数値)",
    "TreemapGroupLabel": "グループ / ラベル列",
    "HeatmapColumnLabel": "列 (X) のカテゴリ",
    "HeatmapRowLabel": "行 (Y) のカテゴリ",
    "AdvancedOptionsClosed": "▼ 詳細オプション",
    "AdvancedOptionsOpen": "▲ 詳細オプション",
    "ColorByLabel": "列で色分け",
    "ColorByHelp": "系列ではなくカテゴリでポイントを色分けします。",
    "TooltipColumnsLabel": "ヒントの列",
    "TooltipColumnsHelp": "(データ ポイントにポインターを合わせたときに表示される追加の列)",
    "DrillLevelLabel": "ドリル レベル {0}",
    "DrillDownHelp": "クリックでドリルダウンできるように、列の階層を定義します (例: 地域 → 国 → 市区町村)。値は各レベルで集計されます。",
    "BookmarksLabel": "ブックマーク",
    "BookmarkNameLabel": "ブックマーク名",
    "BookmarkNamePlaceholder": "例: 地域別トップ 10",
    "SaveBookmarkButton": "現在のビューを保存",
    "ApplyBookmarkButton": "適用",
    "DeleteBookmarkButton": "削除",
    "ApplyBookmarkPlaceholder": "— ブックマークを適用 —",
    "DataControlsSectionHeader": "データ コントロール",
    "SortByColumnLabel": "並べ替える列",
    "NoneOption": "— なし —",
    "SortDirectionLabel": "並べ替えの方向",
    "AscendingOption": "昇順",
    "DescendingOption": "降順",
    "RowLimitLabel": "行数の上限 (0 = すべて)",
    "FilterColumnLabel": "フィルターの列",
    "FilterContainsLabel": "フィルター: を含む",
    "FilterValuePlaceholder": "フィルターの値…",
    "GroupByLabel": "グループ化する列",
    "AggregationLabel": "集計",
    "GroupByHelp": "数値列はグループごとに集計されます。カウントを選択すると \"Count\" 列が追加されます。",
    "AggNone": "なし",
    "AggSum": "合計",
    "AggAvg": "平均",
    "AggCount": "カウント",
    "AggMin": "最小",
    "AggMax": "最大",
    "DataTableHeader": "データ テーブル ({0} 行)",
    "PrevPageButton": "← 前へ",
    "NextPageButton": "次へ →",
    "PageOfLabel": "ページ {0} / {1}",
    "ExportLabel": "エクスポート:",
    "ExportPngTitle": "グラフを PNG 画像としてダウンロード",
    "ExportJpegTitle": "グラフを JPEG 画像としてダウンロード",
    "ExportCsvTitle": "データを CSV としてダウンロード",
    "ExportExcelTitle": "データを Excel ブックとしてダウンロード"
  }
});
