define([], function() {
  return {
    "PropertyPaneDescription": "데이터 시각화 구성",
    "HeaderGroupName": "머리글",
    "WebPartHeaderFieldLabel": "머리글 텍스트",
    "WebPartHeaderPlaceholder": "예: 영업 대시보드",
    "ShowWebPartHeaderFieldLabel": "머리글 표시",
    "ChartSettingsGroupName": "차트 설정",
    "ChartTitleFieldLabel": "차트 제목",
    "ChartTypeFieldLabel": "차트 종류",
    "LegendPositionFieldLabel": "범례 위치",
    "ChartHeightFieldLabel": "차트 높이(px)",
    "ShowLegendFieldLabel": "범례 표시",
    "StackedFieldLabel": "누적(막대/꺾은선)",
    "ShowDataTableFieldLabel": "데이터 테이블 표시",
    "ShowExportBarFieldLabel": "내보내기 표시줄 표시",
    "XAxisLabelFieldLabel": "X축 레이블(선택 사항)",
    "XAxisPlaceholder": "기본값은 선택한 열",
    "YAxisLabelFieldLabel": "Y축 레이블(선택 사항)",
    "YAxisPlaceholder": "기본값은 선택한 열",
    "ChartGroupStandard": "표준 차트",
    "ChartGroupSpecialized": "전문 차트",
    "ChartTypeBarLabel": "막대 차트(세로)",
    "ChartTypeHorizontalBarLabel": "막대 차트(가로)",
    "ChartTypeLineLabel": "꺾은선형 차트",
    "ChartTypeAreaLabel": "영역형 차트",
    "ChartTypeScatterLabel": "분산형 차트",
    "ChartTypePieLabel": "원형 차트",
    "ChartTypeDoughnutLabel": "도넛형 차트",
    "ChartTypeBubbleLabel": "거품형 차트",
    "ChartTypeRadarLabel": "방사형 차트",
    "ChartTypeKpiLabel": "KPI 타일",
    "ChartTypeHistogramLabel": "히스토그램",
    "ChartTypeWaterfallLabel": "폭포 차트",
    "ChartTypeBoxplotLabel": "상자 수염 그림",
    "ChartTypeViolinLabel": "바이올린 플롯",
    "ChartTypeBeforeAfterLabel": "전후 비교 플롯",
    "ChartTypeTreemapLabel": "트리맵",
    "ChartTypeHeatmapLabel": "히트 맵",
    "HistogramBinsFieldLabel": "히스토그램 구간 수",
    "AppearancePageDescription": "색, 레이블 및 축",
    "AdvancedPageDescription": "분석, 참조선, 상호 작용 및 데이터 새로 고침",
    "LegendTopLabel": "위쪽",
    "LegendBottomLabel": "아래쪽",
    "LegendLeftLabel": "왼쪽",
    "LegendRightLabel": "오른쪽",
    "ColorsGroupName": "색",
    "ColorPaletteFieldLabel": "색 팔레트",
    "PaletteOfficeLabel": "Office(기본값)",
    "PaletteVibrantLabel": "선명한 색",
    "PalettePastelLabel": "파스텔",
    "PaletteMonochromeLabel": "단색",
    "PaletteTrafficLightLabel": "신호등",
    "PaletteWarmLabel": "따뜻한 색",
    "PaletteCoolLabel": "차가운 색",
    "DataLabelsGroupName": "데이터 레이블 및 서식",
    "ShowDataLabelsFieldLabel": "데이터 레이블 표시",
    "ValuePrefixFieldLabel": "값 접두사",
    "ValuePrefixPlaceholder": "예: ₩",
    "ValueSuffixFieldLabel": "값 접미사",
    "ValueSuffixPlaceholder": "예: %",
    "ValueDecimalsFieldLabel": "소수 자릿수",
    "AbbreviateNumbersFieldLabel": "숫자 축약(K/M)",
    "AxesGridGroupName": "축 및 눈금선",
    "YAxisMinFieldLabel": "Y축 최소값",
    "YAxisMaxFieldLabel": "Y축 최대값",
    "AutoPlaceholder": "자동",
    "NumericValidationError": "숫자를 입력하거나 자동으로 설정하려면 비워 두세요.",
    "ColorValidationError": "16진수 색(예: #d13438)을 입력하거나 기본값을 사용하려면 비워 두세요.",
    "LogScaleFieldLabel": "로그 눈금(Y)",
    "LogScaleXFieldLabel": "로그 눈금(X)",
    "StepLineFieldLabel": "계단식 보간",
    "ShowGridLinesFieldLabel": "눈금선 표시",
    "XLabelRotationFieldLabel": "X 레이블 회전(도)",
    "XAxisTypeFieldLabel": "X축 종류",
    "XAxisTypeAuto": "자동 검색",
    "XAxisTypeCategory": "범주",
    "XAxisTypeTime": "시간(날짜)",
    "AnalyticsGroupName": "분석",
    "TrendlineFieldLabel": "추세선",
    "TrendlineNone": "없음",
    "TrendlineLinear": "선형",
    "TrendlineMovingAverage": "이동 평균",
    "TrendWindowFieldLabel": "이동 평균 기간",
    "TrendSuffix": " (추세)",
    "ForecastPeriodsFieldLabel": "예측 기간(선형 추세선)",
    "ReferenceLineGroupName": "참조선",
    "ReferenceLineTypeFieldLabel": "참조선",
    "ReferenceLineValueFieldLabel": "고정 값",
    "ReferenceLineColorFieldLabel": "선 색(16진수)",
    "RefLineFixed": "고정 값",
    "RefLineMean": "평균",
    "RefLineMedian": "중앙값",
    "DualAxisGroupName": "이중 Y축",
    "Y2ColumnsFieldLabel": "오른쪽 축 계열(쉼표로 구분한 열 이름)",
    "Y2ColumnsPlaceholder": "예: 마진,성장률",
    "Y2AxisLabelFieldLabel": "오른쪽 축 레이블",
    "LogScaleY2FieldLabel": "로그 눈금(오른쪽 축)",
    "ErrorBarsGroupName": "오차 막대",
    "ErrorBarTypeFieldLabel": "오차 막대 종류",
    "ErrorBarTypeNone": "없음",
    "ErrorBarTypeCustom": "사용자 지정 열(±)",
    "ErrorBarTypeSd": "표준 편차(계산됨)",
    "ErrorBarTypeSem": "평균의 표준 오차(계산됨)",
    "ErrorBarColumnFieldLabel": "오차 값 열",
    "SignificanceGroupName": "유의성 괄호",
    "SignificancePairsFieldLabel": "괄호 쌍",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "한 줄에 괄호 하나: 열1,열2,레이블  — 예: GroupA,GroupB,*  또는  GroupA,GroupB,p<0.05  (JSON 배열도 사용할 수 있습니다)",
    "BeforeAfterColumnsError": "전후 비교 차트에는 Y 열이 정확히 2개 필요합니다. 하나는 이전 값, 다른 하나는 이후 값용입니다.",
    "InteractivityGroupName": "상호 작용",
    "ShowViewerFiltersFieldLabel": "보는 사람에게 필터 표시",
    "DetailsOnDemandFieldLabel": "클릭 시 데이터 행 표시",
    "ShowDataPointsFieldLabel": "막대에 데이터 요소 겹쳐 표시",
    "ShowBubbleSizeLegendFieldLabel": "거품 크기 범례 표시",
    "ViewerFilterLabel": "필터:",
    "ViewerFilterColumnAria": "필터 열",
    "ViewerFilterValueAria": "필터 값",
    "DrillAllLabel": "모두",
    "DetailsChipLabel": "세부 정보: {0}({1}개 행)",
    "KpiSubLabel": "{0} • {1} • {2}개 행",
    "ConditionalGroupName": "조건부 서식",
    "ThresholdValueFieldLabel": "임계값",
    "ThresholdValuePlaceholder": "끔",
    "ThresholdDirectionFieldLabel": "강조 표시할 값",
    "ThresholdBelow": "임계값 미만",
    "ThresholdAbove": "임계값 초과",
    "ThresholdColorFieldLabel": "강조 표시 색(16진수)",
    "DataRefreshGroupName": "데이터 및 새로 고침",
    "RefreshIntervalFieldLabel": "자동 새로 고침 간격(분, 0 = 끔)",
    "CacheMinutesFieldLabel": "데이터 캐시(분, 0 = 끔)",
    "DynamicDataCategoryLabel": "선택한 범주",
    "DynamicDataValueLabel": "선택한 값",
    "DynamicDataSeriesLabel": "선택한 계열",
    "DataSourceGroupName": "데이터 원본",
    "HideDataSourceButton": "▲ 데이터 원본 숨기기",
    "ConfigureDataSourceButton": "▼ 데이터 원본 구성",
    "RowsLoadedBadge": "✓ {0}개 행을 로드했습니다",
    "ReadModeLoadError": "데이터를 로드할 수 없습니다. {0}. 데이터 원본을 다시 구성하려면 편집 모드로 전환하세요.",
    "RefreshDataButton": "↻ 데이터 새로 고침",
    "RefreshingLabel": "새로 고치는 중…",
    "RefreshDataTitle": "구성된 원본에서 데이터 다시 로드",
    "NoDataMessage": "아직 로드된 데이터가 없습니다. 위에서 데이터 원본을 구성하고 데이터 로드를 클릭하세요.",
    "SelectMappingsMessage": "데이터를 로드했습니다({0}개 행). 차트를 표시하려면 위에서 열 매핑을 선택하세요.",
    "ChartRenderErrorLabel": "차트 렌더링 오류: {0}",
    "UnsupportedChartTypeLabel": "지원되지 않는 차트 종류: {0}",
    "ChartAriaLabel": "데이터 시각화 차트",
    "FilterOperatorLabel": "연산자",
    "FilterValueLabel": "값",
    "FilterOpContains": "포함",
    "FilterOpEquals": "같음",
    "FilterOpNotEquals": "같지 않음",
    "FilterOpGt": "초과",
    "FilterOpLt": "미만",
    "FilterOpBetween": "범위(최소..최대)",
    "FilterOpIsEmpty": "비어 있음",
    "FilterOpNotEmpty": "비어 있지 않음",
    "AddFilterButton": "+ 필터 추가",
    "RemoveFilterButton": "제거",
    "SelectValuePlaceholder": "값 선택…",
    "ViewerFilterOperatorAria": "필터 연산자",
    "PaletteColorblindLabel": "색맹 친화",
    "WaterfallGroupName": "폭포",
    "WaterfallShowTotalFieldLabel": "합계 막대 표시",
    "WaterfallPositiveColorFieldLabel": "증가 색",
    "WaterfallNegativeColorFieldLabel": "감소 색",
    "WaterfallTotalColorFieldLabel": "합계 색",
    "WaterfallTotalLabel": "합계",
    "ExternalFilterGroupName": "다른 웹 파트에서 필터링",
    "ExternalFilterFieldLabel": "필터 값 원본",
    "ExternalFilterColumnFieldLabel": "필터링할 열",
    "ExternalFilterColumnPlaceholder": "기본값은 X축 열",
    "ViewAsTableButton": "테이블로 보기",
    "HideTableButton": "테이블 숨기기",
    "ChartKeyboardHint": "화살표 키를 사용하여 데이터 요소 간에 이동하고 Enter 키를 눌러 선택합니다.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Y2 값 접두사",
    "Y2ValueSuffixFieldLabel": "Y2 값 접미사",
    "AnnotationsGroupName": "주석",
    "AnnotationsFieldLabel": "주석",
    "AnnotationsPlaceholder": "1월, 제품 출시",
    "AnnotationsHelp": "한 줄에 하나씩: X축 값, 쉼표, 메모 텍스트 순서로 입력합니다. 해당 X 값 위치에 세로 표식이 그려집니다.",
    "BeforeLabel": "이전",
    "AfterLabel": "이후",
    "RowLabel": "행 {0}",
    "PointsSuffix": " (요소)",
    "ExportSheetName": "데이터",
    "RefreshFailedNote": "마지막 새로 고침에 실패했습니다. {0}. 이전에 로드한 데이터를 표시합니다.",
    "TruncatedDataNote": "처음 {0}개 행만 표시됩니다. 원본에 더 많은 데이터가 있습니다.",
    "ScatterNumericWarning": "분산형 및 거품형 차트에는 숫자 값이 필요합니다. \"{0}\" 열에 숫자 데이터가 없습니다. 위의 매핑에서 다른 열을 선택하세요.",
    "TimeAxisUnparseableWarning": "X축 열 \"{0}\"에 날짜로 구문 분석할 수 있는 값이 없습니다. X축 종류를 \"범주\"로 전환하거나 날짜 열을 매핑하세요.",
    "DataSourceSectionHeader": "데이터 원본",
    "SourceUploadLabel": "파일 업로드",
    "SourceSharePointListLabel": "SharePoint 목록",
    "SourceSharePointFileLabel": "SharePoint 파일",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API 경로",
    "GraphPathHelp": "Microsoft Graph 상대 경로(예: /me/memberOf 또는 /reports/getTeamsUserActivityUserCounts(period='D7')). 이 원본에는 관리자가 승인한 Graph 권한이 필요하며, 다른 모든 데이터 원본은 권한 없이 작동합니다.",
    "SheetNameLabel": "Excel 시트",
    "DelimiterLabel": "구분 기호",
    "DelimiterAutoDetect": "자동 검색",
    "DelimiterComma": "쉼표(,)",
    "DelimiterTab": "탭",
    "DelimiterSemicolon": "세미콜론(;)",
    "DelimiterPipe": "파이프(|)",
    "SiteUrlLabel": "사이트 URL(선택 사항)",
    "SiteUrlHelp": "현재 사이트를 사용하려면 비워 두세요.",
    "ListNameLabel": "목록 이름",
    "LoadingListsLabel": "— 목록 로드 중…",
    "SelectListPlaceholder": "— 목록 선택 —",
    "EnterListNamePlaceholder": "목록 이름 입력",
    "ListNameExamplePlaceholder": "예: 영업 데이터",
    "ListDiscoveryError": "목록을 로드할 수 없습니다. 아래에 이름을 직접 입력하세요.",
    "FileUrlLabel": "파일 URL(SharePoint의 CSV/TSV/Excel)",
    "FileUrlHelp": "문서 라이브러리에 있는 파일의 전체 URL입니다.",
    "ApiUrlLabel": "API URL",
    "DataPathLabel": "데이터 경로(선택 사항)",
    "DataPathHelp": "JSON 응답의 배열에 대한 점으로 구분된 경로입니다. 루트가 배열이면 비워 두세요. SharePoint REST API의 경우 \"value\"를 사용하세요.",
    "UploadHelp": "CSV, TSV 또는 Excel(.xlsx, .xls) 파일을 업로드하세요.",
    "LoadedFileRowsLabel": "— {0}개 행",
    "ChangeFileButton": "파일 변경…",
    "ClearButton": "지우기",
    "ChooseFileButton": "파일 선택…",
    "LoadDataButton": "데이터 로드",
    "LoadingLabel": "로드하는 중…",
    "ErrorSelectListName": "목록 이름을 선택하거나 입력하세요.",
    "ErrorEnterFileUrl": "파일 URL을 입력하세요.",
    "ErrorEnterUrl": "URL을 입력하세요.",
    "ErrorLoadList": "SharePoint 목록을 로드하지 못했습니다. {0}",
    "ErrorLoadFile": "파일을 로드하지 못했습니다. {0}",
    "ErrorFetchData": "데이터를 가져오지 못했습니다. {0}",
    "ErrorDataPathNotFound": "응답에서 데이터 경로 \"{0}\"을(를) 찾을 수 없습니다.",
    "ErrorUrlReturnedHtml": "이 URL은 파일이 아닌 웹 페이지를 반환했습니다. \"링크 복사\" 공유 URL이 아닌 파일 직접 다운로드 경로를 사용하세요.",
    "ErrorRequestTimedOut": "요청 시간이 초과되었습니다. URL과 네트워크 연결을 확인하세요.",
    "ErrorNonJsonResponse": "응답을 JSON으로 구문 분석할 수 없습니다.",
    "ErrorUnsupportedFileType": "지원되지 않는 파일 형식입니다. .csv, .tsv, .xlsx 또는 .xls 파일을 업로드하세요.",
    "ErrorReadFile": "파일을 읽지 못했습니다",
    "ErrorParseFile": "파일을 구문 분석하지 못했습니다",
    "LoadedRowsColumns": "{0}개 행과 {1}개 열을 로드했습니다.",
    "LoadedRowsColumnsPersist": "{0}개 행과 {1}개 열을 로드했습니다. 페이지를 나가도 데이터가 유지됩니다.",
    "SizeWarning": "데이터 세트({0}KB)가 200KB 지속성 한도를 초과합니다. 차트는 이 세션 동안 데이터를 표시하지만 페이지를 다시 로드하면 지워집니다. 큰 파일은 SharePoint 라이브러리에 업로드하고 SharePoint 파일 원본을 사용하세요.",
    "ListTruncatedWarning": "이 목록에는 {0}개 이상의 항목이 있습니다. 처음 {0}개만 로드되었습니다.",
    "GraphTruncatedWarning": "이 Microsoft Graph 결과에는 로드할 수 있는 것보다 많은 페이지가 있습니다. 처음 {0}개 페이지만 검색되었습니다.",
    "CsvParseWarning": "{0}개 행을 구문 분석할 수 없어 건너뛰었습니다.",
    "ColumnMappingSectionHeader": "열 매핑",
    "CategoryColumnLabel": "범주 열(X / 레이블)",
    "LabelColumnLabel": "레이블 열",
    "XAxisColumnLabel": "X축 열",
    "ValueColumnLabel": "값 열",
    "YAxisColumnLabel": "Y축 열",
    "YAxisColumnsLabel": "Y축 열",
    "YAxisColumnsHelp": "(하나 이상 선택, 색을 설정하려면 색상 견본 클릭)",
    "SelectColumnPlaceholder": "— 열 선택 —",
    "ScatterLabelColumnLabel": "요소 레이블",
    "SizeColumnLabel": "크기/반지름 열",
    "NoSizeColumnOption": "— 없음(고정 크기) —",
    "SeriesColorTitle": "{0}의 색",
    "SeriesTypeTitle": "{0}의 차트 종류",
    "SeriesTypeDefault": "기본값",
    "SeriesTypeBar": "막대",
    "SeriesTypeLine": "꺾은선",
    "HistogramColumnLabel": "구간으로 나눌 열(숫자)",
    "TreemapGroupLabel": "그룹/레이블 열",
    "HeatmapColumnLabel": "열(X) 범주",
    "HeatmapRowLabel": "행(Y) 범주",
    "AdvancedOptionsClosed": "▼ 고급 옵션",
    "AdvancedOptionsOpen": "▲ 고급 옵션",
    "ColorByLabel": "열별 색 지정",
    "ColorByHelp": "계열 대신 범주별로 요소에 색을 지정합니다.",
    "TooltipColumnsLabel": "도구 설명 열",
    "TooltipColumnsHelp": "(데이터 요소 위로 마우스를 가져가면 표시되는 추가 열)",
    "DrillLevelLabel": "드릴 수준 {0}",
    "DrillDownHelp": "클릭하여 드릴다운할 수 있도록 열 계층 구조를 정의합니다(예: 지역 → 국가 → 도시). 값은 각 수준에서 집계됩니다.",
    "BookmarksLabel": "책갈피",
    "BookmarkNameLabel": "책갈피 이름",
    "BookmarkNamePlaceholder": "예: 지역별 상위 10개",
    "SaveBookmarkButton": "현재 보기 저장",
    "ApplyBookmarkButton": "적용",
    "DeleteBookmarkButton": "삭제",
    "ApplyBookmarkPlaceholder": "— 책갈피 적용 —",
    "DataControlsSectionHeader": "데이터 컨트롤",
    "SortByColumnLabel": "정렬 기준 열",
    "NoneOption": "— 없음 —",
    "SortDirectionLabel": "정렬 방향",
    "AscendingOption": "오름차순",
    "DescendingOption": "내림차순",
    "RowLimitLabel": "행 제한(0 = 모두)",
    "FilterColumnLabel": "필터 열",
    "FilterContainsLabel": "필터: 포함",
    "FilterValuePlaceholder": "필터 값…",
    "GroupByLabel": "그룹화 기준 열",
    "AggregationLabel": "집계",
    "GroupByHelp": "숫자 열은 그룹별로 집계됩니다. 개수를 선택하면 \"Count\" 열이 추가됩니다.",
    "AggNone": "없음",
    "AggSum": "합계",
    "AggAvg": "평균",
    "AggCount": "개수",
    "AggMin": "최소",
    "AggMax": "최대",
    "DataTableHeader": "데이터 테이블({0}개 행)",
    "PrevPageButton": "← 이전",
    "NextPageButton": "다음 →",
    "PageOfLabel": "{0}/{1} 페이지",
    "ExportLabel": "내보내기:",
    "ExportPngTitle": "차트를 PNG 이미지로 다운로드",
    "ExportJpegTitle": "차트를 JPEG 이미지로 다운로드",
    "ExportCsvTitle": "데이터를 CSV로 다운로드",
    "ExportExcelTitle": "데이터를 Excel 통합 문서로 다운로드"
  }
});
