define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurer datavisualiseringen",
    "HeaderGroupName": "Topptekst",
    "WebPartHeaderFieldLabel": "Topptekst",
    "WebPartHeaderPlaceholder": "f.eks. Salgsdashbord",
    "ShowWebPartHeaderFieldLabel": "Vis topptekst",
    "ChartSettingsGroupName": "Diagraminnstillinger",
    "ChartTitleFieldLabel": "Diagramtittel",
    "ChartTypeFieldLabel": "Diagramtype",
    "LegendPositionFieldLabel": "Forklaringsposisjon",
    "ChartHeightFieldLabel": "Diagramhøyde (px)",
    "ShowLegendFieldLabel": "Vis forklaring",
    "StackedFieldLabel": "Stablet (søyle/linje)",
    "ShowDataTableFieldLabel": "Vis datatabell",
    "ShowExportBarFieldLabel": "Vis eksportlinje",
    "XAxisLabelFieldLabel": "X-akseetikett (valgfritt)",
    "XAxisPlaceholder": "Bruker den valgte kolonnen som standard",
    "YAxisLabelFieldLabel": "Y-akseetikett (valgfritt)",
    "YAxisPlaceholder": "Bruker de valgte kolonnene som standard",
    "ChartGroupStandard": "Standarddiagrammer",
    "ChartGroupSpecialized": "Spesialiserte diagrammer",
    "ChartTypeBarLabel": "Søylediagram (vertikalt)",
    "ChartTypeHorizontalBarLabel": "Søylediagram (horisontalt)",
    "ChartTypeLineLabel": "Linjediagram",
    "ChartTypeAreaLabel": "Områdediagram",
    "ChartTypeScatterLabel": "Punktdiagram",
    "ChartTypePieLabel": "Sektordiagram",
    "ChartTypeDoughnutLabel": "Smultringdiagram",
    "ChartTypeBubbleLabel": "Boblediagram",
    "ChartTypeRadarLabel": "Radardiagram",
    "ChartTypeKpiLabel": "KPI-flis",
    "ChartTypeHistogramLabel": "Histogram",
    "ChartTypeWaterfallLabel": "Fossefalldiagram",
    "ChartTypeBoxplotLabel": "Boksplott",
    "ChartTypeViolinLabel": "Fiolinplott",
    "ChartTypeBeforeAfterLabel": "Før-etter-diagram",
    "ChartTypeTreemapLabel": "Trekart",
    "ChartTypeHeatmapLabel": "Varmekart",
    "HistogramBinsFieldLabel": "Histogramintervaller",
    "AppearancePageDescription": "Farger, etiketter og akser",
    "AdvancedPageDescription": "Analyse, referanselinjer, interaktivitet og dataoppdatering",
    "LegendTopLabel": "Øverst",
    "LegendBottomLabel": "Nederst",
    "LegendLeftLabel": "Til venstre",
    "LegendRightLabel": "Til høyre",
    "ColorsGroupName": "Farger",
    "ColorPaletteFieldLabel": "Fargepalett",
    "PaletteOfficeLabel": "Office (standard)",
    "PaletteVibrantLabel": "Livlig",
    "PalettePastelLabel": "Pastell",
    "PaletteMonochromeLabel": "Monokrom",
    "PaletteTrafficLightLabel": "Trafikklys",
    "PaletteWarmLabel": "Varm",
    "PaletteCoolLabel": "Kjølig",
    "DataLabelsGroupName": "Dataetiketter og formatering",
    "ShowDataLabelsFieldLabel": "Vis dataetiketter",
    "ValuePrefixFieldLabel": "Verdiprefiks",
    "ValuePrefixPlaceholder": "f.eks. kr",
    "ValueSuffixFieldLabel": "Verdisuffiks",
    "ValueSuffixPlaceholder": "f.eks. %",
    "ValueDecimalsFieldLabel": "Desimaler",
    "AbbreviateNumbersFieldLabel": "Forkort tall (K/M)",
    "AxesGridGroupName": "Akser og rutenett",
    "YAxisMinFieldLabel": "Y-akse minimum",
    "YAxisMaxFieldLabel": "Y-akse maksimum",
    "AutoPlaceholder": "Automatisk",
    "NumericValidationError": "Angi et tall, eller la feltet stå tomt for automatisk.",
    "ColorValidationError": "Angi en heksadesimal farge (f.eks. #d13438), eller la feltet stå tomt for standard.",
    "LogScaleFieldLabel": "Logaritmisk skala (Y)",
    "LogScaleXFieldLabel": "Logaritmisk skala (X)",
    "StepLineFieldLabel": "Trinnvis interpolasjon",
    "ShowGridLinesFieldLabel": "Vis rutenettlinjer",
    "XLabelRotationFieldLabel": "Rotasjon for X-etiketter (grader)",
    "XAxisTypeFieldLabel": "X-akse type",
    "XAxisTypeAuto": "Registrer automatisk",
    "XAxisTypeCategory": "Kategori",
    "XAxisTypeTime": "Tid (datoer)",
    "AnalyticsGroupName": "Analyse",
    "TrendlineFieldLabel": "Trendlinje",
    "TrendlineNone": "Ingen",
    "TrendlineLinear": "Lineær",
    "TrendlineMovingAverage": "Glidende gjennomsnitt",
    "TrendWindowFieldLabel": "Vindu for glidende gjennomsnitt",
    "TrendSuffix": " (trend)",
    "ForecastPeriodsFieldLabel": "Prognoseperioder (lineær trendlinje)",
    "ReferenceLineGroupName": "Referanselinje",
    "ReferenceLineTypeFieldLabel": "Referanselinje",
    "ReferenceLineValueFieldLabel": "Fast verdi",
    "ReferenceLineColorFieldLabel": "Linjefarge (heks.)",
    "RefLineFixed": "Fast verdi",
    "RefLineMean": "Gjennomsnitt",
    "RefLineMedian": "Median",
    "DualAxisGroupName": "Dobbel Y-akse",
    "Y2ColumnsFieldLabel": "Serier på høyre akse (kolonnenavn atskilt med komma)",
    "Y2ColumnsPlaceholder": "f.eks. Margin,Vekst",
    "Y2AxisLabelFieldLabel": "Etikett for høyre akse",
    "LogScaleY2FieldLabel": "Logaritmisk skala (høyre akse)",
    "ErrorBarsGroupName": "Feilsøyler",
    "ErrorBarTypeFieldLabel": "Type feilsøyle",
    "ErrorBarTypeNone": "Ingen",
    "ErrorBarTypeCustom": "Egendefinert kolonne (±)",
    "ErrorBarTypeSd": "Standardavvik (beregnet)",
    "ErrorBarTypeSem": "Standardfeil for gjennomsnitt (beregnet)",
    "ErrorBarColumnFieldLabel": "Kolonne for feilverdi",
    "SignificanceGroupName": "Signifikansparenteser",
    "SignificancePairsFieldLabel": "Parentespar",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Én parentes per linje: kol1,kol2,etikett  — f.eks. GruppeA,GruppeB,*  eller  GruppeA,GruppeB,p<0.05  (JSON-matrise godtas også)",
    "BeforeAfterColumnsError": "Et før-etter-diagram krever nøyaktig 2 Y-kolonner: én for Før-verdier og én for Etter-verdier.",
    "InteractivityGroupName": "Interaktivitet",
    "ShowViewerFiltersFieldLabel": "Vis filtre for besøkende",
    "DetailsOnDemandFieldLabel": "Vis datarader ved klikk",
    "ShowDataPointsFieldLabel": "Legg datapunkter over søyler",
    "ShowBubbleSizeLegendFieldLabel": "Vis forklaring for boblestørrelse",
    "ViewerFilterLabel": "Filter:",
    "ViewerFilterColumnAria": "Filterkolonne",
    "ViewerFilterValueAria": "Filterverdi",
    "DrillAllLabel": "Alle",
    "DetailsChipLabel": "Detaljer: {0} ({1} rader)",
    "KpiSubLabel": "{0} • {1} • {2} rader",
    "ConditionalGroupName": "Betinget formatering",
    "ThresholdValueFieldLabel": "Terskelverdi",
    "ThresholdValuePlaceholder": "Av",
    "ThresholdDirectionFieldLabel": "Uthev verdier",
    "ThresholdBelow": "Under terskel",
    "ThresholdAbove": "Over terskel",
    "ThresholdColorFieldLabel": "Uthevingsfarge (heks.)",
    "DataRefreshGroupName": "Data og oppdatering",
    "RefreshIntervalFieldLabel": "Intervall for automatisk oppdatering (minutter, 0 = av)",
    "CacheMinutesFieldLabel": "Bufre data (minutter, 0 = av)",
    "DynamicDataCategoryLabel": "Valgt kategori",
    "DynamicDataValueLabel": "Valgt verdi",
    "DynamicDataSeriesLabel": "Valgt serie",
    "DataSourceGroupName": "Datakilde",
    "HideDataSourceButton": "▲ Skjul datakilde",
    "ConfigureDataSourceButton": "▼ Konfigurer datakilde",
    "RowsLoadedBadge": "✓ {0} rader lastet inn",
    "ReadModeLoadError": "Kunne ikke laste inn data: {0}. Bytt til redigeringsmodus for å konfigurere datakilden på nytt.",
    "RefreshDataButton": "↻ Oppdater data",
    "RefreshingLabel": "Oppdaterer…",
    "RefreshDataTitle": "Last inn data på nytt fra den konfigurerte kilden",
    "NoDataMessage": "Ingen data er lastet inn ennå. Konfigurer datakilden ovenfor, og klikk på Last inn data.",
    "SelectMappingsMessage": "Data lastet inn ({0} rader). Velg kolonnetilordninger ovenfor for å vise diagrammet.",
    "ChartRenderErrorLabel": "Feil ved gjengivelse av diagram: {0}",
    "UnsupportedChartTypeLabel": "Diagramtypen støttes ikke: {0}",
    "ChartAriaLabel": "Diagram for datavisualisering",
    "FilterOperatorLabel": "Operator",
    "FilterValueLabel": "Verdi",
    "FilterOpContains": "inneholder",
    "FilterOpEquals": "er lik",
    "FilterOpNotEquals": "er ikke lik",
    "FilterOpGt": "større enn",
    "FilterOpLt": "mindre enn",
    "FilterOpBetween": "mellom (lav..høy)",
    "FilterOpIsEmpty": "er tom",
    "FilterOpNotEmpty": "er ikke tom",
    "AddFilterButton": "+ Legg til filter",
    "RemoveFilterButton": "Fjern",
    "SelectValuePlaceholder": "Velg verdi…",
    "ViewerFilterOperatorAria": "Filteroperator",
    "PaletteColorblindLabel": "Fargeblindvennlig",
    "WaterfallGroupName": "Fossefall",
    "WaterfallShowTotalFieldLabel": "Vis totalsøyle",
    "WaterfallPositiveColorFieldLabel": "Farge for økning",
    "WaterfallNegativeColorFieldLabel": "Farge for reduksjon",
    "WaterfallTotalColorFieldLabel": "Farge for total",
    "WaterfallTotalLabel": "Total",
    "ExternalFilterGroupName": "Filtrer fra en annen webdel",
    "ExternalFilterFieldLabel": "Kilde for filterverdi",
    "ExternalFilterColumnFieldLabel": "Kolonne som skal filtreres",
    "ExternalFilterColumnPlaceholder": "Bruker X-akse-kolonnen som standard",
    "ViewAsTableButton": "Vis som tabell",
    "HideTableButton": "Skjul tabell",
    "ChartKeyboardHint": "Bruk piltastene for å flytte mellom datapunkter og Enter for å velge ett.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Y2-verdiprefiks",
    "Y2ValueSuffixFieldLabel": "Y2-verdisuffiks",
    "AnnotationsGroupName": "Merknader",
    "AnnotationsFieldLabel": "Merknader",
    "AnnotationsPlaceholder": "Jan, Produktlansering",
    "AnnotationsHelp": "Én per linje: X-akseverdien, et komma og deretter merknadsteksten. En vertikal markør tegnes ved denne X-verdien.",
    "BeforeLabel": "Før",
    "AfterLabel": "Etter",
    "RowLabel": "Rad {0}",
    "PointsSuffix": " (punkter)",
    "ExportSheetName": "Data",
    "RefreshFailedNote": "Siste oppdatering mislyktes: {0}. Viser data som ble lastet inn tidligere.",
    "TruncatedDataNote": "Bare de første {0} radene vises; kilden har mer data.",
    "ScatterNumericWarning": "Punkt- og boblediagrammer krever numeriske verdier. Kolonnen \"{0}\" har ingen numeriske data. Velg en annen kolonne i tilordningen ovenfor.",
    "TimeAxisUnparseableWarning": "X-akse-kolonnen \"{0}\" har ingen verdier som kan tolkes som datoer. Sett X-akse type til \"Kategori\", eller tilordne en datokolonne.",
    "DataSourceSectionHeader": "Datakilde",
    "SourceUploadLabel": "Last opp fil",
    "SourceSharePointListLabel": "SharePoint-liste",
    "SourceSharePointFileLabel": "SharePoint-fil",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API-bane",
    "GraphPathHelp": "Relativ Microsoft Graph-bane, f.eks. /me/memberOf eller /reports/getTeamsUserActivityUserCounts(period='D7'). Denne kilden krever Graph-tillatelser som er godkjent av en administrator. Alle andre datakilder fungerer uten.",
    "SheetNameLabel": "Excel-ark",
    "DelimiterLabel": "Skilletegn",
    "DelimiterAutoDetect": "Registrer automatisk",
    "DelimiterComma": "Komma (,)",
    "DelimiterTab": "Tabulator",
    "DelimiterSemicolon": "Semikolon (;)",
    "DelimiterPipe": "Loddrett strek (|)",
    "SiteUrlLabel": "Nettsted-URL (valgfritt)",
    "SiteUrlHelp": "La feltet stå tomt for å bruke gjeldende nettsted.",
    "ListNameLabel": "Listenavn",
    "LoadingListsLabel": "— Laster inn lister…",
    "SelectListPlaceholder": "— Velg en liste —",
    "EnterListNamePlaceholder": "Angi listenavn",
    "ListNameExamplePlaceholder": "f.eks. Salgsdata",
    "ListDiscoveryError": "Kunne ikke laste inn lister. Angi navnet manuelt nedenfor.",
    "FileUrlLabel": "Fil-URL (CSV/TSV/Excel i SharePoint)",
    "FileUrlHelp": "Fullstendig URL til en fil i et dokumentbibliotek.",
    "ApiUrlLabel": "API-URL",
    "DataPathLabel": "Databane (valgfritt)",
    "DataPathHelp": "Punktumseparert bane til matrisen i JSON-svaret. La feltet stå tomt hvis roten er en matrise. Bruk \"value\" for SharePoint REST API.",
    "UploadHelp": "Last opp en CSV-, TSV- eller Excel-fil (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} rader",
    "ChangeFileButton": "Endre fil…",
    "ClearButton": "Fjern",
    "ChooseFileButton": "Velg fil…",
    "LoadDataButton": "Last inn data",
    "LoadingLabel": "Laster inn…",
    "ErrorSelectListName": "Velg eller angi et listenavn.",
    "ErrorEnterFileUrl": "Angi en fil-URL.",
    "ErrorEnterUrl": "Angi en URL.",
    "ErrorLoadList": "Kunne ikke laste inn SharePoint-listen: {0}",
    "ErrorLoadFile": "Kunne ikke laste inn filen: {0}",
    "ErrorFetchData": "Kunne ikke hente data: {0}",
    "ErrorDataPathNotFound": "Databanen \"{0}\" ble ikke funnet i svaret.",
    "ErrorUrlReturnedHtml": "Denne URL-en returnerte en nettside, ikke en fil. Bruk den direkte nedlastingsbanen til filen, ikke en delings-URL fra «Kopier kobling».",
    "ErrorRequestTimedOut": "Forespørselen ble tidsavbrutt. Kontroller URL-en og nettverkstilkoblingen.",
    "ErrorNonJsonResponse": "Svaret kunne ikke tolkes som JSON.",
    "ErrorUnsupportedFileType": "Filtypen støttes ikke. Last opp en .csv-, .tsv-, .xlsx- eller .xls-fil.",
    "ErrorReadFile": "Kunne ikke lese filen",
    "ErrorParseFile": "Kunne ikke tolke filen",
    "LoadedRowsColumns": "Lastet inn {0} rader med {1} kolonner.",
    "LoadedRowsColumnsPersist": "Lastet inn {0} rader med {1} kolonner. Dataene beholdes når du forlater siden.",
    "SizeWarning": "Datasettet ({0}KB) overskrider grensen på 200KB for lagring. Diagrammet viser dataene i denne økten, men de blir fjernet når siden lastes inn på nytt. For store filer bør du laste dem opp til et SharePoint-bibliotek og bruke kilden SharePoint-fil.",
    "ListTruncatedWarning": "Denne listen har {0} eller flere elementer. Bare de første {0} ble lastet inn.",
    "GraphTruncatedWarning": "Dette Microsoft Graph-resultatet har flere sider enn det var mulig å laste inn. Bare de første {0} sidene ble hentet.",
    "CsvParseWarning": "{0} rad(er) kunne ikke tolkes og ble hoppet over.",
    "ColumnMappingSectionHeader": "Kolonnetilordning",
    "CategoryColumnLabel": "Kategorikolonne (X / etiketter)",
    "LabelColumnLabel": "Etikettkolonne",
    "XAxisColumnLabel": "X-akse-kolonne",
    "ValueColumnLabel": "Verdikolonne",
    "YAxisColumnLabel": "Y-akse-kolonne",
    "YAxisColumnsLabel": "Y-akse-kolonne(r)",
    "YAxisColumnsHelp": "(velg én eller flere; klikk på fargeruten for å angi farge)",
    "SelectColumnPlaceholder": "— Velg kolonne —",
    "ScatterLabelColumnLabel": "Punktetikett",
    "SizeColumnLabel": "Kolonne for størrelse / radius",
    "NoSizeColumnOption": "— Ingen (fast størrelse) —",
    "SeriesColorTitle": "Farge for {0}",
    "SeriesTypeTitle": "Diagramtype for {0}",
    "SeriesTypeDefault": "Standard",
    "SeriesTypeBar": "Søyle",
    "SeriesTypeLine": "Linje",
    "HistogramColumnLabel": "Kolonne som skal deles inn i intervaller (numerisk)",
    "TreemapGroupLabel": "Gruppe-/etikettkolonne",
    "HeatmapColumnLabel": "Kolonnekategori (X)",
    "HeatmapRowLabel": "Radkategori (Y)",
    "AdvancedOptionsClosed": "▼ Avanserte alternativer",
    "AdvancedOptionsOpen": "▲ Avanserte alternativer",
    "ColorByLabel": "Farge etter kolonne",
    "ColorByHelp": "Farg punkter etter kategori i stedet for etter serie.",
    "TooltipColumnsLabel": "Verktøytips-kolonner",
    "TooltipColumnsHelp": "(ekstra kolonner som vises når du peker på et datapunkt)",
    "DrillLevelLabel": "Drill-nivå {0}",
    "DrillDownHelp": "Definer et kolonnehierarki for å aktivere klikk-for-å-drille (f.eks. Region → Land → By). Verdier aggregeres på hvert nivå.",
    "BookmarksLabel": "Bokmerker",
    "BookmarkNameLabel": "Bokmerkenavn",
    "BookmarkNamePlaceholder": "f.eks. Topp 10 per region",
    "SaveBookmarkButton": "Lagre gjeldende visning",
    "ApplyBookmarkButton": "Bruk",
    "DeleteBookmarkButton": "Slett",
    "ApplyBookmarkPlaceholder": "— Bruk et bokmerke —",
    "DataControlsSectionHeader": "Datakontroller",
    "SortByColumnLabel": "Sorter etter kolonne",
    "NoneOption": "— Ingen —",
    "SortDirectionLabel": "Sorteringsretning",
    "AscendingOption": "Stigende",
    "DescendingOption": "Synkende",
    "RowLimitLabel": "Radgrense (0 = alle)",
    "FilterColumnLabel": "Filterkolonne",
    "FilterContainsLabel": "Filter: inneholder",
    "FilterValuePlaceholder": "Filterverdi…",
    "GroupByLabel": "Grupper etter kolonne",
    "AggregationLabel": "Aggregering",
    "GroupByHelp": "Numeriske kolonner aggregeres per gruppe. Antall legger til en \"Count\"-kolonne.",
    "AggNone": "Ingen",
    "AggSum": "Sum",
    "AggAvg": "Gjennomsnitt",
    "AggCount": "Antall",
    "AggMin": "Min",
    "AggMax": "Maks",
    "DataTableHeader": "Datatabell ({0} rader)",
    "PrevPageButton": "← Forrige",
    "NextPageButton": "Neste →",
    "PageOfLabel": "Side {0} av {1}",
    "ExportLabel": "Eksporter:",
    "ExportPngTitle": "Last ned diagram som PNG-bilde",
    "ExportJpegTitle": "Last ned diagram som JPEG-bilde",
    "ExportCsvTitle": "Last ned data som CSV",
    "ExportExcelTitle": "Last ned data som Excel-arbeidsbok"
  }
});
