define([], function() {
  return {
    "PropertyPaneDescription": "Configureer uw gegevensvisualisatie",
    "HeaderGroupName": "Koptekst",
    "WebPartHeaderFieldLabel": "Koptekst",
    "WebPartHeaderPlaceholder": "bijv. Verkoopdashboard",
    "ShowWebPartHeaderFieldLabel": "Koptekst weergeven",
    "ChartSettingsGroupName": "Grafiekinstellingen",
    "ChartTitleFieldLabel": "Grafiektitel",
    "ChartTypeFieldLabel": "Grafiektype",
    "LegendPositionFieldLabel": "Positie van legenda",
    "ChartHeightFieldLabel": "Grafiekhoogte (px)",
    "ShowLegendFieldLabel": "Legenda weergeven",
    "StackedFieldLabel": "Gestapeld (staaf/lijn)",
    "ShowDataTableFieldLabel": "Gegevenstabel weergeven",
    "ShowExportBarFieldLabel": "Exportbalk weergeven",
    "XAxisLabelFieldLabel": "Label X-as (optioneel)",
    "XAxisPlaceholder": "Standaard de geselecteerde kolom",
    "YAxisLabelFieldLabel": "Label Y-as (optioneel)",
    "YAxisPlaceholder": "Standaard de geselecteerde kolom(men)",
    "ChartGroupStandard": "Standaardgrafieken",
    "ChartGroupSpecialized": "Gespecialiseerde grafieken",
    "ChartTypeBarLabel": "Staafdiagram (verticaal)",
    "ChartTypeHorizontalBarLabel": "Staafdiagram (horizontaal)",
    "ChartTypeLineLabel": "Lijndiagram",
    "ChartTypeAreaLabel": "Vlakdiagram",
    "ChartTypeScatterLabel": "Spreidingsdiagram",
    "ChartTypePieLabel": "Cirkeldiagram",
    "ChartTypeDoughnutLabel": "Ringdiagram",
    "ChartTypeBubbleLabel": "Bellendiagram",
    "ChartTypeRadarLabel": "Radardiagram",
    "ChartTypeKpiLabel": "KPI-tegel",
    "ChartTypeHistogramLabel": "Histogram",
    "ChartTypeWaterfallLabel": "Watervaldiagram",
    "ChartTypeBoxplotLabel": "Boxplot",
    "ChartTypeViolinLabel": "Vioolplot",
    "ChartTypeBeforeAfterLabel": "Voor-na-diagram",
    "ChartTypeTreemapLabel": "Treemap",
    "ChartTypeHeatmapLabel": "Heatmap",
    "HistogramBinsFieldLabel": "Histogramklassen",
    "AppearancePageDescription": "Kleuren, labels en assen",
    "AdvancedPageDescription": "Analyses, referentielijnen, interactiviteit en vernieuwing van gegevens",
    "LegendTopLabel": "Boven",
    "LegendBottomLabel": "Onder",
    "LegendLeftLabel": "Links",
    "LegendRightLabel": "Rechts",
    "ColorsGroupName": "Kleuren",
    "ColorPaletteFieldLabel": "Kleurenpalet",
    "PaletteOfficeLabel": "Office (standaard)",
    "PaletteVibrantLabel": "Levendig",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Monochroom",
    "PaletteTrafficLightLabel": "Stoplicht",
    "PaletteWarmLabel": "Warm",
    "PaletteCoolLabel": "Koel",
    "DataLabelsGroupName": "Gegevenslabels en opmaak",
    "ShowDataLabelsFieldLabel": "Gegevenslabels weergeven",
    "ValuePrefixFieldLabel": "Voorvoegsel waarde",
    "ValuePrefixPlaceholder": "bijv. €",
    "ValueSuffixFieldLabel": "Achtervoegsel waarde",
    "ValueSuffixPlaceholder": "bijv. %",
    "ValueDecimalsFieldLabel": "Aantal decimalen",
    "AbbreviateNumbersFieldLabel": "Getallen afkorten (K/M)",
    "AxesGridGroupName": "Assen en raster",
    "YAxisMinFieldLabel": "Minimum Y-as",
    "YAxisMaxFieldLabel": "Maximum Y-as",
    "AutoPlaceholder": "Automatisch",
    "NumericValidationError": "Voer een getal in of laat leeg voor automatisch.",
    "ColorValidationError": "Voer een hexadecimale kleur in (bijv. #d13438) of laat leeg voor de standaardwaarde.",
    "LogScaleFieldLabel": "Logaritmische schaal (Y)",
    "LogScaleXFieldLabel": "Logaritmische schaal (X)",
    "StepLineFieldLabel": "Trapsgewijze interpolatie",
    "ShowGridLinesFieldLabel": "Rasterlijnen weergeven",
    "XLabelRotationFieldLabel": "Rotatie X-labels (graden)",
    "XAxisTypeFieldLabel": "Type X-as",
    "XAxisTypeAuto": "Automatisch detecteren",
    "XAxisTypeCategory": "Categorie",
    "XAxisTypeTime": "Tijd (datums)",
    "AnalyticsGroupName": "Analyse",
    "TrendlineFieldLabel": "Trendlijn",
    "TrendlineNone": "Geen",
    "TrendlineLinear": "Lineair",
    "TrendlineMovingAverage": "Voortschrijdend gemiddelde",
    "TrendWindowFieldLabel": "Venster voortschrijdend gemiddelde",
    "TrendSuffix": " (trend)",
    "ForecastPeriodsFieldLabel": "Voorspellingsperioden (lineaire trendlijn)",
    "ReferenceLineGroupName": "Referentielijn",
    "ReferenceLineTypeFieldLabel": "Referentielijn",
    "ReferenceLineValueFieldLabel": "Vaste waarde",
    "ReferenceLineColorFieldLabel": "Lijnkleur (hex)",
    "RefLineFixed": "Vaste waarde",
    "RefLineMean": "Gemiddelde",
    "RefLineMedian": "Mediaan",
    "DualAxisGroupName": "Dubbele Y-as",
    "Y2ColumnsFieldLabel": "Reeksen rechteras (kolomnamen gescheiden door komma's)",
    "Y2ColumnsPlaceholder": "bijv. Marge,Groei",
    "Y2AxisLabelFieldLabel": "Label rechteras",
    "LogScaleY2FieldLabel": "Logaritmische schaal (rechteras)",
    "ErrorBarsGroupName": "Foutbalken",
    "ErrorBarTypeFieldLabel": "Type foutbalk",
    "ErrorBarTypeNone": "Geen",
    "ErrorBarTypeCustom": "Aangepaste kolom (±)",
    "ErrorBarTypeSd": "Standaarddeviatie (berekend)",
    "ErrorBarTypeSem": "Standaardfout van het gemiddelde (berekend)",
    "ErrorBarColumnFieldLabel": "Kolom foutwaarde",
    "SignificanceGroupName": "Significantiehaken",
    "SignificancePairsFieldLabel": "Haakparen",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Eén haak per regel: kol1,kol2,label  — bijv. GroepA,GroepB,*  of  GroepA,GroepB,p<0.05  (een JSON-matrix wordt ook geaccepteerd)",
    "BeforeAfterColumnsError": "Een voor-na-diagram vereist precies 2 Y-kolommen: één voor de Voor-waarden en één voor de Na-waarden.",
    "InteractivityGroupName": "Interactiviteit",
    "ShowViewerFiltersFieldLabel": "Filters weergeven voor bezoekers",
    "DetailsOnDemandFieldLabel": "Gegevensrijen weergeven bij klikken",
    "ShowDataPointsFieldLabel": "Gegevenspunten over staven leggen",
    "ShowBubbleSizeLegendFieldLabel": "Legenda voor bellengrootte weergeven",
    "ViewerFilterLabel": "Filter:",
    "ViewerFilterColumnAria": "Filterkolom",
    "ViewerFilterValueAria": "Filterwaarde",
    "DrillAllLabel": "Alle",
    "DetailsChipLabel": "Details: {0} ({1} rijen)",
    "KpiSubLabel": "{0} • {1} • {2} rijen",
    "ConditionalGroupName": "Voorwaardelijke opmaak",
    "ThresholdValueFieldLabel": "Drempelwaarde",
    "ThresholdValuePlaceholder": "Uit",
    "ThresholdDirectionFieldLabel": "Waarden markeren",
    "ThresholdBelow": "Onder drempelwaarde",
    "ThresholdAbove": "Boven drempelwaarde",
    "ThresholdColorFieldLabel": "Markeringskleur (hex)",
    "DataRefreshGroupName": "Gegevens en vernieuwen",
    "RefreshIntervalFieldLabel": "Interval voor automatisch vernieuwen (minuten, 0 = uit)",
    "CacheMinutesFieldLabel": "Gegevens in cache opslaan (minuten, 0 = uit)",
    "DynamicDataCategoryLabel": "Geselecteerde categorie",
    "DynamicDataValueLabel": "Geselecteerde waarde",
    "DynamicDataSeriesLabel": "Geselecteerde reeks",
    "DataSourceGroupName": "Gegevensbron",
    "HideDataSourceButton": "▲ Gegevensbron verbergen",
    "ConfigureDataSourceButton": "▼ Gegevensbron configureren",
    "RowsLoadedBadge": "✓ {0} rijen geladen",
    "ReadModeLoadError": "Kan gegevens niet laden: {0}. Schakel over naar de bewerkingsmodus om de gegevensbron opnieuw te configureren.",
    "RefreshDataButton": "↻ Gegevens vernieuwen",
    "RefreshingLabel": "Vernieuwen…",
    "RefreshDataTitle": "Gegevens opnieuw laden uit de geconfigureerde bron",
    "NoDataMessage": "Er zijn nog geen gegevens geladen. Configureer hierboven uw gegevensbron en klik op Gegevens laden.",
    "SelectMappingsMessage": "Gegevens geladen ({0} rijen). Selecteer hierboven de kolomtoewijzingen om de grafiek weer te geven.",
    "ChartRenderErrorLabel": "Fout bij het weergeven van de grafiek: {0}",
    "UnsupportedChartTypeLabel": "Niet-ondersteund grafiektype: {0}",
    "ChartAriaLabel": "Grafiek voor gegevensvisualisatie",
    "FilterOperatorLabel": "Operator",
    "FilterValueLabel": "Waarde",
    "FilterOpContains": "bevat",
    "FilterOpEquals": "is gelijk aan",
    "FilterOpNotEquals": "is niet gelijk aan",
    "FilterOpGt": "groter dan",
    "FilterOpLt": "kleiner dan",
    "FilterOpBetween": "tussen (laag..hoog)",
    "FilterOpIsEmpty": "is leeg",
    "FilterOpNotEmpty": "is niet leeg",
    "AddFilterButton": "+ Filter toevoegen",
    "RemoveFilterButton": "Verwijderen",
    "SelectValuePlaceholder": "Waarde selecteren…",
    "ViewerFilterOperatorAria": "Filteroperator",
    "PaletteColorblindLabel": "Kleurenblindveilig",
    "WaterfallGroupName": "Watervaldiagram",
    "WaterfallShowTotalFieldLabel": "Totaalbalk weergeven",
    "WaterfallPositiveColorFieldLabel": "Kleur toename",
    "WaterfallNegativeColorFieldLabel": "Kleur afname",
    "WaterfallTotalColorFieldLabel": "Kleur totaal",
    "WaterfallTotalLabel": "Totaal",
    "ExternalFilterGroupName": "Filteren vanuit een andere webonderdeel",
    "ExternalFilterFieldLabel": "Bron van filterwaarde",
    "ExternalFilterColumnFieldLabel": "Te filteren kolom",
    "ExternalFilterColumnPlaceholder": "Standaard de kolom van de X-as",
    "ViewAsTableButton": "Weergeven als tabel",
    "HideTableButton": "Tabel verbergen",
    "ChartKeyboardHint": "Gebruik de pijltoetsen om te navigeren tussen gegevenspunten en Enter om er een te selecteren.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Voorvoegsel Y2-waarde",
    "Y2ValueSuffixFieldLabel": "Achtervoegsel Y2-waarde",
    "AnnotationsGroupName": "Aantekeningen",
    "AnnotationsFieldLabel": "Aantekeningen",
    "AnnotationsPlaceholder": "Jan, Productlancering",
    "AnnotationsHelp": "Eén per regel: de waarde op de X-as, een komma en vervolgens de tekst van de aantekening. Bij die X-waarde wordt een verticale markering getekend.",
    "BeforeLabel": "Voor",
    "AfterLabel": "Na",
    "RowLabel": "Rij {0}",
    "PointsSuffix": " (punten)",
    "ExportSheetName": "Gegevens",
    "RefreshFailedNote": "Laatste vernieuwing mislukt: {0}. Eerder geladen gegevens worden weergegeven.",
    "TruncatedDataNote": "Alleen de eerste {0} rijen worden weergegeven; de bron bevat meer gegevens.",
    "ScatterNumericWarning": "Spreidings- en bellendiagrammen hebben numerieke waarden nodig. De kolom \"{0}\" bevat geen numerieke gegevens. Kies hierboven in de toewijzing een andere kolom.",
    "TimeAxisUnparseableWarning": "De kolom van de X-as \"{0}\" bevat geen waarden die als datums kunnen worden geïnterpreteerd. Stel Type X-as in op \"Categorie\" of wijs een datumkolom toe.",
    "DataSourceSectionHeader": "Gegevensbron",
    "SourceUploadLabel": "Bestand uploaden",
    "SourceSharePointListLabel": "SharePoint-lijst",
    "SourceSharePointFileLabel": "SharePoint-bestand",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API-pad",
    "GraphPathHelp": "Relatief Microsoft Graph-pad, bijv. /me/memberOf of /reports/getTeamsUserActivityUserCounts(period='D7'). Voor deze bron zijn Graph-machtigingen nodig die door een beheerder zijn goedgekeurd. Alle andere gegevensbronnen werken zonder.",
    "SheetNameLabel": "Excel-blad",
    "DelimiterLabel": "Scheidingsteken",
    "DelimiterAutoDetect": "Automatisch detecteren",
    "DelimiterComma": "Komma (,)",
    "DelimiterTab": "Tab",
    "DelimiterSemicolon": "Puntkomma (;)",
    "DelimiterPipe": "Verticale streep (|)",
    "SiteUrlLabel": "Site-URL (optioneel)",
    "SiteUrlHelp": "Laat leeg om de huidige site te gebruiken.",
    "ListNameLabel": "Lijstnaam",
    "LoadingListsLabel": "— Lijsten laden…",
    "SelectListPlaceholder": "— Selecteer een lijst —",
    "EnterListNamePlaceholder": "Voer lijstnaam in",
    "ListNameExamplePlaceholder": "bijv. Verkoopgegevens",
    "ListDiscoveryError": "Kan lijsten niet laden. Voer hieronder de naam handmatig in.",
    "FileUrlLabel": "Bestands-URL (CSV/TSV/Excel in SharePoint)",
    "FileUrlHelp": "Volledige URL naar een bestand in een documentbibliotheek.",
    "ApiUrlLabel": "API-URL",
    "DataPathLabel": "Gegevenspad (optioneel)",
    "DataPathHelp": "Met punten gescheiden pad naar de matrix in het JSON-antwoord. Laat leeg als de hoofdmap een matrix is. Gebruik voor de SharePoint REST API \"value\".",
    "UploadHelp": "Upload een CSV-, TSV- of Excel-bestand (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} rijen",
    "ChangeFileButton": "Bestand wijzigen…",
    "ClearButton": "Wissen",
    "ChooseFileButton": "Bestand kiezen…",
    "LoadDataButton": "Gegevens laden",
    "LoadingLabel": "Laden…",
    "ErrorSelectListName": "Selecteer of voer een lijstnaam in.",
    "ErrorEnterFileUrl": "Voer een bestands-URL in.",
    "ErrorEnterUrl": "Voer een URL in.",
    "ErrorLoadList": "Kan SharePoint-lijst niet laden: {0}",
    "ErrorLoadFile": "Kan bestand niet laden: {0}",
    "ErrorFetchData": "Kan gegevens niet ophalen: {0}",
    "ErrorDataPathNotFound": "Het gegevenspad \"{0}\" is niet gevonden in het antwoord.",
    "ErrorUrlReturnedHtml": "Deze URL heeft een webpagina geretourneerd, geen bestand. Gebruik het directe downloadpad van het bestand, niet een deel-URL van 'Koppeling kopiëren'.",
    "ErrorRequestTimedOut": "Time-out van de aanvraag. Controleer de URL en uw netwerkverbinding.",
    "ErrorNonJsonResponse": "Het antwoord kon niet als JSON worden geparseerd.",
    "ErrorUnsupportedFileType": "Niet-ondersteund bestandstype. Upload een .csv-, .tsv-, .xlsx- of .xls-bestand.",
    "ErrorReadFile": "Kan bestand niet lezen",
    "ErrorParseFile": "Kan bestand niet parseren",
    "LoadedRowsColumns": "{0} rijen met {1} kolommen geladen.",
    "LoadedRowsColumnsPersist": "{0} rijen met {1} kolommen geladen. De gegevens blijven behouden wanneer u de pagina verlaat.",
    "SizeWarning": "De gegevensset ({0}KB) overschrijdt de opslaglimiet van 200KB. De grafiek toont de gegevens tijdens deze sessie, maar wordt gewist bij het opnieuw laden van de pagina. Upload grote bestanden naar een SharePoint-bibliotheek en gebruik de bron SharePoint-bestand.",
    "ListTruncatedWarning": "Deze lijst bevat {0} of meer items; alleen de eerste {0} zijn geladen.",
    "GraphTruncatedWarning": "Dit Microsoft Graph-resultaat heeft meer pagina's dan konden worden geladen; alleen de eerste {0} pagina's zijn opgehaald.",
    "CsvParseWarning": "{0} rij(en) kon(den) niet worden geparseerd en zijn overgeslagen.",
    "ColumnMappingSectionHeader": "Kolomtoewijzing",
    "CategoryColumnLabel": "Categoriekolom (X / labels)",
    "LabelColumnLabel": "Labelkolom",
    "XAxisColumnLabel": "Kolom X-as",
    "ValueColumnLabel": "Waardekolom",
    "YAxisColumnLabel": "Kolom Y-as",
    "YAxisColumnsLabel": "Kolom(men) Y-as",
    "YAxisColumnsHelp": "(selecteer een of meer; klik op het kleurvak om de kleur in te stellen)",
    "SelectColumnPlaceholder": "— Selecteer kolom —",
    "ScatterLabelColumnLabel": "Punt-label",
    "SizeColumnLabel": "Kolom grootte / straal",
    "NoSizeColumnOption": "— Geen (vaste grootte) —",
    "SeriesColorTitle": "Kleur voor {0}",
    "SeriesTypeTitle": "Grafiektype voor {0}",
    "SeriesTypeDefault": "Standaard",
    "SeriesTypeBar": "Staaf",
    "SeriesTypeLine": "Lijn",
    "HistogramColumnLabel": "Kolom om in klassen te verdelen (numeriek)",
    "TreemapGroupLabel": "Groeps-/labelkolom",
    "HeatmapColumnLabel": "Categorie kolom (X)",
    "HeatmapRowLabel": "Categorie rij (Y)",
    "AdvancedOptionsClosed": "▼ Geavanceerde opties",
    "AdvancedOptionsOpen": "▲ Geavanceerde opties",
    "ColorByLabel": "Kleuren op basis van kolom",
    "ColorByHelp": "Kleur punten op categorie in plaats van op reeks.",
    "TooltipColumnsLabel": "Knopinfokolommen",
    "TooltipColumnsHelp": "(extra kolommen die worden weergegeven bij het aanwijzen van een gegevenspunt)",
    "DrillLevelLabel": "Drill-niveau {0}",
    "DrillDownHelp": "Definieer een kolomhiërarchie om doorklikken (drill-down) in te schakelen (bijv. Regio → Land → Stad). Waarden worden op elk niveau samengevoegd.",
    "BookmarksLabel": "Bladwijzers",
    "BookmarkNameLabel": "Naam bladwijzer",
    "BookmarkNamePlaceholder": "bijv. Top 10 per regio",
    "SaveBookmarkButton": "Huidige weergave opslaan",
    "ApplyBookmarkButton": "Toepassen",
    "DeleteBookmarkButton": "Verwijderen",
    "ApplyBookmarkPlaceholder": "— Een bladwijzer toepassen —",
    "DataControlsSectionHeader": "Gegevensbesturing",
    "SortByColumnLabel": "Sorteren op kolom",
    "NoneOption": "— Geen —",
    "SortDirectionLabel": "Sorteerrichting",
    "AscendingOption": "Oplopend",
    "DescendingOption": "Aflopend",
    "RowLimitLabel": "Rijlimiet (0 = alle)",
    "FilterColumnLabel": "Filterkolom",
    "FilterContainsLabel": "Filter: bevat",
    "FilterValuePlaceholder": "Filterwaarde…",
    "GroupByLabel": "Groeperen op kolom",
    "AggregationLabel": "Aggregatie",
    "GroupByHelp": "Numerieke kolommen worden per groep samengevoegd. Aantal voegt een kolom \"Count\" toe.",
    "AggNone": "Geen",
    "AggSum": "Som",
    "AggAvg": "Gemiddelde",
    "AggCount": "Aantal",
    "AggMin": "Min",
    "AggMax": "Max",
    "DataTableHeader": "Gegevenstabel ({0} rijen)",
    "PrevPageButton": "← Vorige",
    "NextPageButton": "Volgende →",
    "PageOfLabel": "Pagina {0} van {1}",
    "ExportLabel": "Exporteren:",
    "ExportPngTitle": "Grafiek downloaden als PNG-afbeelding",
    "ExportJpegTitle": "Grafiek downloaden als JPEG-afbeelding",
    "ExportCsvTitle": "Gegevens downloaden als CSV",
    "ExportExcelTitle": "Gegevens downloaden als Excel-werkmap"
  }
});
