define([], function() {
  return {
    "PropertyPaneDescription": "Skonfiguruj wizualizację danych",
    "HeaderGroupName": "Nagłówek",
    "WebPartHeaderFieldLabel": "Tekst nagłówka",
    "WebPartHeaderPlaceholder": "np. Pulpit sprzedaży",
    "ShowWebPartHeaderFieldLabel": "Pokaż nagłówek",
    "ChartSettingsGroupName": "Ustawienia wykresu",
    "ChartTitleFieldLabel": "Tytuł wykresu",
    "ChartTypeFieldLabel": "Typ wykresu",
    "LegendPositionFieldLabel": "Położenie legendy",
    "ChartHeightFieldLabel": "Wysokość wykresu (px)",
    "ShowLegendFieldLabel": "Pokaż legendę",
    "StackedFieldLabel": "Skumulowany (słupkowy/liniowy)",
    "ShowDataTableFieldLabel": "Pokaż tabelę danych",
    "ShowExportBarFieldLabel": "Pokaż pasek eksportu",
    "XAxisLabelFieldLabel": "Etykieta osi X (opcjonalnie)",
    "XAxisPlaceholder": "Domyślnie wybrana kolumna",
    "YAxisLabelFieldLabel": "Etykieta osi Y (opcjonalnie)",
    "YAxisPlaceholder": "Domyślnie wybrane kolumny",
    "ChartGroupStandard": "Wykresy standardowe",
    "ChartGroupSpecialized": "Wykresy specjalistyczne",
    "ChartTypeBarLabel": "Wykres słupkowy (pionowy)",
    "ChartTypeHorizontalBarLabel": "Wykres słupkowy (poziomy)",
    "ChartTypeLineLabel": "Wykres liniowy",
    "ChartTypeAreaLabel": "Wykres warstwowy",
    "ChartTypeScatterLabel": "Wykres punktowy",
    "ChartTypePieLabel": "Wykres kołowy",
    "ChartTypeDoughnutLabel": "Wykres pierścieniowy",
    "ChartTypeBubbleLabel": "Wykres bąbelkowy",
    "ChartTypeRadarLabel": "Wykres radarowy",
    "ChartTypeKpiLabel": "Kafelek KPI",
    "ChartTypeHistogramLabel": "Histogram",
    "ChartTypeWaterfallLabel": "Wykres kaskadowy",
    "ChartTypeBoxplotLabel": "Wykres pudełkowy",
    "ChartTypeViolinLabel": "Wykres skrzypcowy",
    "ChartTypeBeforeAfterLabel": "Wykres przed-po",
    "ChartTypeTreemapLabel": "Mapa drzewa",
    "ChartTypeHeatmapLabel": "Mapa cieplna",
    "HistogramBinsFieldLabel": "Przedziały histogramu",
    "AppearancePageDescription": "Kolory, etykiety i osie",
    "AdvancedPageDescription": "Analiza, linie odniesienia, interaktywność i odświeżanie danych",
    "LegendTopLabel": "U góry",
    "LegendBottomLabel": "Na dole",
    "LegendLeftLabel": "Po lewej",
    "LegendRightLabel": "Po prawej",
    "ColorsGroupName": "Kolory",
    "ColorPaletteFieldLabel": "Paleta kolorów",
    "PaletteOfficeLabel": "Office (domyślna)",
    "PaletteVibrantLabel": "Żywa",
    "PalettePastelLabel": "Pastelowa",
    "PaletteMonochromeLabel": "Monochromatyczna",
    "PaletteTrafficLightLabel": "Sygnalizacja świetlna",
    "PaletteWarmLabel": "Ciepła",
    "PaletteCoolLabel": "Chłodna",
    "DataLabelsGroupName": "Etykiety danych i formatowanie",
    "ShowDataLabelsFieldLabel": "Pokaż etykiety danych",
    "ValuePrefixFieldLabel": "Prefiks wartości",
    "ValuePrefixPlaceholder": "np. zł",
    "ValueSuffixFieldLabel": "Sufiks wartości",
    "ValueSuffixPlaceholder": "np. %",
    "ValueDecimalsFieldLabel": "Miejsca dziesiętne",
    "AbbreviateNumbersFieldLabel": "Skracaj liczby (K/M)",
    "AxesGridGroupName": "Osie i siatka",
    "YAxisMinFieldLabel": "Minimum osi Y",
    "YAxisMaxFieldLabel": "Maksimum osi Y",
    "AutoPlaceholder": "Automatycznie",
    "NumericValidationError": "Wprowadź liczbę lub pozostaw puste, aby ustawić automatycznie.",
    "ColorValidationError": "Wprowadź kolor szesnastkowy (np. #d13438) lub pozostaw puste, aby użyć domyślnego.",
    "LogScaleFieldLabel": "Skala logarytmiczna (Y)",
    "LogScaleXFieldLabel": "Skala logarytmiczna (X)",
    "StepLineFieldLabel": "Interpolacja schodkowa",
    "ShowGridLinesFieldLabel": "Pokaż linie siatki",
    "XLabelRotationFieldLabel": "Obrót etykiet X (stopnie)",
    "XAxisTypeFieldLabel": "Typ osi X",
    "XAxisTypeAuto": "Wykryj automatycznie",
    "XAxisTypeCategory": "Kategoria",
    "XAxisTypeTime": "Czas (daty)",
    "AnalyticsGroupName": "Analiza",
    "TrendlineFieldLabel": "Linia trendu",
    "TrendlineNone": "Brak",
    "TrendlineLinear": "Liniowa",
    "TrendlineMovingAverage": "Średnia ruchoma",
    "TrendWindowFieldLabel": "Okno średniej ruchomej",
    "TrendSuffix": " (trend)",
    "ForecastPeriodsFieldLabel": "Okresy prognozy (liniowa linia trendu)",
    "ReferenceLineGroupName": "Linia odniesienia",
    "ReferenceLineTypeFieldLabel": "Linia odniesienia",
    "ReferenceLineValueFieldLabel": "Wartość stała",
    "ReferenceLineColorFieldLabel": "Kolor linii (szesnastkowy)",
    "RefLineFixed": "Wartość stała",
    "RefLineMean": "Średnia",
    "RefLineMedian": "Mediana",
    "DualAxisGroupName": "Podwójna oś Y",
    "Y2ColumnsFieldLabel": "Serie na osi prawej (nazwy kolumn oddzielone przecinkami)",
    "Y2ColumnsPlaceholder": "np. Marża,Wzrost",
    "Y2AxisLabelFieldLabel": "Etykieta osi prawej",
    "LogScaleY2FieldLabel": "Skala logarytmiczna (oś prawa)",
    "ErrorBarsGroupName": "Słupki błędów",
    "ErrorBarTypeFieldLabel": "Typ słupka błędów",
    "ErrorBarTypeNone": "Brak",
    "ErrorBarTypeCustom": "Kolumna niestandardowa (±)",
    "ErrorBarTypeSd": "Odch. standardowe (obliczane)",
    "ErrorBarTypeSem": "Błąd standardowy średniej (obliczany)",
    "ErrorBarColumnFieldLabel": "Kolumna wartości błędu",
    "SignificanceGroupName": "Nawiasy istotności",
    "SignificancePairsFieldLabel": "Pary nawiasów",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Jeden nawias na wiersz: kol1,kol2,etykieta  — np. GrupaA,GrupaB,*  lub  GrupaA,GrupaB,p<0.05  (tablica JSON również jest akceptowana)",
    "BeforeAfterColumnsError": "Wykres przed-po wymaga dokładnie 2 kolumn Y — jednej dla wartości Przed i jednej dla wartości Po.",
    "InteractivityGroupName": "Interaktywność",
    "ShowViewerFiltersFieldLabel": "Pokaż filtry odbiorcom",
    "DetailsOnDemandFieldLabel": "Pokaż wiersze danych po kliknięciu",
    "ShowDataPointsFieldLabel": "Nakładaj punkty danych na słupki",
    "ShowBubbleSizeLegendFieldLabel": "Pokaż legendę rozmiaru bąbelków",
    "ViewerFilterLabel": "Filtr:",
    "ViewerFilterColumnAria": "Kolumna filtru",
    "ViewerFilterValueAria": "Wartość filtru",
    "DrillAllLabel": "Wszystkie",
    "DetailsChipLabel": "Szczegóły: {0} (wiersze: {1})",
    "KpiSubLabel": "{0} • {1} • wiersze: {2}",
    "ConditionalGroupName": "Formatowanie warunkowe",
    "ThresholdValueFieldLabel": "Wartość progowa",
    "ThresholdValuePlaceholder": "Wył.",
    "ThresholdDirectionFieldLabel": "Wyróżnij wartości",
    "ThresholdBelow": "Poniżej progu",
    "ThresholdAbove": "Powyżej progu",
    "ThresholdColorFieldLabel": "Kolor wyróżnienia (szesnastkowy)",
    "DataRefreshGroupName": "Dane i odświeżanie",
    "RefreshIntervalFieldLabel": "Interwał automatycznego odświeżania (minuty, 0 = wyłączone)",
    "CacheMinutesFieldLabel": "Buforuj dane (minuty, 0 = wyłączone)",
    "DynamicDataCategoryLabel": "Wybrana kategoria",
    "DynamicDataValueLabel": "Wybrana wartość",
    "DynamicDataSeriesLabel": "Wybrana seria",
    "DataSourceGroupName": "Źródło danych",
    "HideDataSourceButton": "▲ Ukryj źródło danych",
    "ConfigureDataSourceButton": "▼ Skonfiguruj źródło danych",
    "RowsLoadedBadge": "✓ Załadowano wierszy: {0}",
    "ReadModeLoadError": "Nie można załadować danych: {0}. Przełącz się do trybu edycji, aby ponownie skonfigurować źródło danych.",
    "RefreshDataButton": "↻ Odśwież dane",
    "RefreshingLabel": "Odświeżanie…",
    "RefreshDataTitle": "Załaduj ponownie dane ze skonfigurowanego źródła",
    "NoDataMessage": "Nie załadowano jeszcze żadnych danych. Skonfiguruj powyżej źródło danych i kliknij pozycję Załaduj dane.",
    "SelectMappingsMessage": "Dane załadowane (wiersze: {0}). Wybierz powyżej mapowania kolumn, aby wyświetlić wykres.",
    "ChartRenderErrorLabel": "Błąd renderowania wykresu: {0}",
    "UnsupportedChartTypeLabel": "Nieobsługiwany typ wykresu: {0}",
    "ChartAriaLabel": "Wykres wizualizacji danych",
    "FilterOperatorLabel": "Operator",
    "FilterValueLabel": "Wartość",
    "FilterOpContains": "zawiera",
    "FilterOpEquals": "jest równe",
    "FilterOpNotEquals": "nie jest równe",
    "FilterOpGt": "większe niż",
    "FilterOpLt": "mniejsze niż",
    "FilterOpBetween": "między (min..maks)",
    "FilterOpIsEmpty": "jest puste",
    "FilterOpNotEmpty": "nie jest puste",
    "AddFilterButton": "+ Dodaj filtr",
    "RemoveFilterButton": "Usuń",
    "SelectValuePlaceholder": "Wybierz wartość…",
    "ViewerFilterOperatorAria": "Operator filtru",
    "PaletteColorblindLabel": "Przyjazna daltonistom",
    "WaterfallGroupName": "Kaskada",
    "WaterfallShowTotalFieldLabel": "Pokaż słupek sumy",
    "WaterfallPositiveColorFieldLabel": "Kolor wzrostu",
    "WaterfallNegativeColorFieldLabel": "Kolor spadku",
    "WaterfallTotalColorFieldLabel": "Kolor sumy",
    "WaterfallTotalLabel": "Suma",
    "ExternalFilterGroupName": "Filtruj z innego składnika Web Part",
    "ExternalFilterFieldLabel": "Źródło wartości filtru",
    "ExternalFilterColumnFieldLabel": "Kolumna do filtrowania",
    "ExternalFilterColumnPlaceholder": "Domyślnie kolumna osi X",
    "ViewAsTableButton": "Wyświetl jako tabelę",
    "HideTableButton": "Ukryj tabelę",
    "ChartKeyboardHint": "Użyj klawiszy strzałek, aby przechodzić między punktami danych, i klawisza Enter, aby wybrać punkt.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Prefiks wartości Y2",
    "Y2ValueSuffixFieldLabel": "Sufiks wartości Y2",
    "AnnotationsGroupName": "Adnotacje",
    "AnnotationsFieldLabel": "Adnotacje",
    "AnnotationsPlaceholder": "Sty, Premiera produktu",
    "AnnotationsHelp": "Po jednej w wierszu: wartość osi X, przecinek, a następnie tekst notatki. W miejscu tej wartości X rysowany jest pionowy znacznik.",
    "BeforeLabel": "Przed",
    "AfterLabel": "Po",
    "RowLabel": "Wiersz {0}",
    "PointsSuffix": " (punkty)",
    "ExportSheetName": "Dane",
    "RefreshFailedNote": "Ostatnie odświeżanie nie powiodło się: {0}. Wyświetlane są wcześniej załadowane dane.",
    "TruncatedDataNote": "Wyświetlono tylko pierwsze wiersze ({0}); źródło zawiera więcej danych.",
    "ScatterNumericWarning": "Wykresy punktowe i bąbelkowe wymagają wartości liczbowych. Kolumna \"{0}\" nie zawiera danych liczbowych — wybierz inną kolumnę w mapowaniu powyżej.",
    "TimeAxisUnparseableWarning": "Kolumna osi X \"{0}\" nie zawiera wartości, które można zinterpretować jako daty. Zmień Typ osi X na \"Kategoria\" lub zmapuj kolumnę dat.",
    "DataSourceSectionHeader": "Źródło danych",
    "SourceUploadLabel": "Przekaż plik",
    "SourceSharePointListLabel": "Lista programu SharePoint",
    "SourceSharePointFileLabel": "Plik programu SharePoint",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Ścieżka Graph API",
    "GraphPathHelp": "Względna ścieżka Microsoft Graph, np. /me/memberOf lub /reports/getTeamsUserActivityUserCounts(period='D7'). To źródło wymaga uprawnień Graph zatwierdzonych przez administratora — wszystkie pozostałe źródła danych działają bez nich.",
    "SheetNameLabel": "Arkusz Excel",
    "DelimiterLabel": "Ogranicznik",
    "DelimiterAutoDetect": "Wykryj automatycznie",
    "DelimiterComma": "Przecinek (,)",
    "DelimiterTab": "Tabulator",
    "DelimiterSemicolon": "Średnik (;)",
    "DelimiterPipe": "Kreska pionowa (|)",
    "SiteUrlLabel": "Adres URL witryny (opcjonalnie)",
    "SiteUrlHelp": "Pozostaw puste, aby użyć bieżącej witryny.",
    "ListNameLabel": "Nazwa listy",
    "LoadingListsLabel": "— Ładowanie list…",
    "SelectListPlaceholder": "— Wybierz listę —",
    "EnterListNamePlaceholder": "Wprowadź nazwę listy",
    "ListNameExamplePlaceholder": "np. Dane sprzedaży",
    "ListDiscoveryError": "Nie można załadować list — wprowadź nazwę ręcznie poniżej.",
    "FileUrlLabel": "Adres URL pliku (CSV/TSV/Excel w programie SharePoint)",
    "FileUrlHelp": "Pełny adres URL pliku w bibliotece dokumentów.",
    "ApiUrlLabel": "Adres URL interfejsu API",
    "DataPathLabel": "Ścieżka danych (opcjonalnie)",
    "DataPathHelp": "Ścieżka rozdzielana kropkami do tablicy w odpowiedzi JSON. Pozostaw puste, jeśli korzeń jest tablicą. W przypadku SharePoint REST API użyj \"value\".",
    "UploadHelp": "Przekaż plik CSV, TSV lub Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— wiersze: {0}",
    "ChangeFileButton": "Zmień plik…",
    "ClearButton": "Wyczyść",
    "ChooseFileButton": "Wybierz plik…",
    "LoadDataButton": "Załaduj dane",
    "LoadingLabel": "Ładowanie…",
    "ErrorSelectListName": "Wybierz lub wprowadź nazwę listy.",
    "ErrorEnterFileUrl": "Wprowadź adres URL pliku.",
    "ErrorEnterUrl": "Wprowadź adres URL.",
    "ErrorLoadList": "Nie udało się załadować listy programu SharePoint: {0}",
    "ErrorLoadFile": "Nie udało się załadować pliku: {0}",
    "ErrorFetchData": "Nie udało się pobrać danych: {0}",
    "ErrorDataPathNotFound": "Nie znaleziono ścieżki danych \"{0}\" w odpowiedzi.",
    "ErrorUrlReturnedHtml": "Ten adres URL zwrócił stronę internetową, a nie plik. Użyj bezpośredniej ścieżki pobierania pliku, a nie adresu URL udostępniania z opcji „Kopiuj link”.",
    "ErrorRequestTimedOut": "Upłynął limit czasu żądania. Sprawdź adres URL i połączenie sieciowe.",
    "ErrorNonJsonResponse": "Nie można przeanalizować odpowiedzi jako JSON.",
    "ErrorUnsupportedFileType": "Nieobsługiwany typ pliku. Przekaż plik .csv, .tsv, .xlsx lub .xls.",
    "ErrorReadFile": "Nie udało się odczytać pliku",
    "ErrorParseFile": "Nie udało się przeanalizować pliku",
    "LoadedRowsColumns": "Załadowano wiersze: {0}, kolumny: {1}.",
    "LoadedRowsColumnsPersist": "Załadowano wiersze: {0}, kolumny: {1}. Dane zostaną zachowane po opuszczeniu strony.",
    "SizeWarning": "Zestaw danych ({0}KB) przekracza limit trwałego przechowywania wynoszący 200KB. Wykres będzie pokazywać dane w tej sesji, ale zostaną one wyczyszczone po ponownym załadowaniu strony. W przypadku dużych plików przekaż je do biblioteki programu SharePoint i użyj źródła Plik programu SharePoint.",
    "ListTruncatedWarning": "Ta lista zawiera {0} lub więcej elementów; załadowano tylko pierwsze {0}.",
    "GraphTruncatedWarning": "Ten wynik Microsoft Graph ma więcej stron, niż można było załadować; pobrano tylko pierwsze strony ({0}).",
    "CsvParseWarning": "Nie można przeanalizować wierszy ({0}) i zostały pominięte.",
    "ColumnMappingSectionHeader": "Mapowanie kolumn",
    "CategoryColumnLabel": "Kolumna kategorii (X / etykiety)",
    "LabelColumnLabel": "Kolumna etykiet",
    "XAxisColumnLabel": "Kolumna osi X",
    "ValueColumnLabel": "Kolumna wartości",
    "YAxisColumnLabel": "Kolumna osi Y",
    "YAxisColumnsLabel": "Kolumny osi Y",
    "YAxisColumnsHelp": "(wybierz jedną lub więcej; kliknij próbkę, aby ustawić kolor)",
    "SelectColumnPlaceholder": "— Wybierz kolumnę —",
    "ScatterLabelColumnLabel": "Etykieta punktu",
    "SizeColumnLabel": "Kolumna rozmiaru / promienia",
    "NoSizeColumnOption": "— Brak (stały rozmiar) —",
    "SeriesColorTitle": "Kolor dla: {0}",
    "SeriesTypeTitle": "Typ wykresu dla: {0}",
    "SeriesTypeDefault": "Domyślny",
    "SeriesTypeBar": "Słupkowy",
    "SeriesTypeLine": "Liniowy",
    "HistogramColumnLabel": "Kolumna do podziału na przedziały (liczbowa)",
    "TreemapGroupLabel": "Kolumna grupy / etykiety",
    "HeatmapColumnLabel": "Kategoria kolumny (X)",
    "HeatmapRowLabel": "Kategoria wiersza (Y)",
    "AdvancedOptionsClosed": "▼ Opcje zaawansowane",
    "AdvancedOptionsOpen": "▲ Opcje zaawansowane",
    "ColorByLabel": "Koloruj według kolumny",
    "ColorByHelp": "Koloruj punkty według kategorii zamiast według serii.",
    "TooltipColumnsLabel": "Kolumny etykietki narzędzia",
    "TooltipColumnsHelp": "(dodatkowe kolumny wyświetlane po wskazaniu punktu danych)",
    "DrillLevelLabel": "Poziom drążenia {0}",
    "DrillDownHelp": "Zdefiniuj hierarchię kolumn, aby włączyć drążenie po kliknięciu (np. Region → Kraj → Miasto). Wartości są agregowane na każdym poziomie.",
    "BookmarksLabel": "Zakładki",
    "BookmarkNameLabel": "Nazwa zakładki",
    "BookmarkNamePlaceholder": "np. Top 10 według regionu",
    "SaveBookmarkButton": "Zapisz bieżący widok",
    "ApplyBookmarkButton": "Zastosuj",
    "DeleteBookmarkButton": "Usuń",
    "ApplyBookmarkPlaceholder": "— Zastosuj zakładkę —",
    "DataControlsSectionHeader": "Kontrolki danych",
    "SortByColumnLabel": "Sortuj według kolumny",
    "NoneOption": "— Brak —",
    "SortDirectionLabel": "Kierunek sortowania",
    "AscendingOption": "Rosnąco",
    "DescendingOption": "Malejąco",
    "RowLimitLabel": "Limit wierszy (0 = wszystkie)",
    "FilterColumnLabel": "Kolumna filtru",
    "FilterContainsLabel": "Filtr: zawiera",
    "FilterValuePlaceholder": "Wartość filtru…",
    "GroupByLabel": "Grupuj według kolumny",
    "AggregationLabel": "Agregacja",
    "GroupByHelp": "Kolumny liczbowe są agregowane dla każdej grupy. Opcja Liczba dodaje kolumnę \"Count\".",
    "AggNone": "Brak",
    "AggSum": "Suma",
    "AggAvg": "Średnia",
    "AggCount": "Liczba",
    "AggMin": "Min.",
    "AggMax": "Maks.",
    "DataTableHeader": "Tabela danych (wiersze: {0})",
    "PrevPageButton": "← Poprz.",
    "NextPageButton": "Dalej →",
    "PageOfLabel": "Strona {0} z {1}",
    "ExportLabel": "Eksportuj:",
    "ExportPngTitle": "Pobierz wykres jako obraz PNG",
    "ExportJpegTitle": "Pobierz wykres jako obraz JPEG",
    "ExportCsvTitle": "Pobierz dane jako CSV",
    "ExportExcelTitle": "Pobierz dane jako skoroszyt Excel"
  }
});
