define([], function() {
  return {
    "PropertyPaneDescription": "Configure sua visualização de dados",
    "HeaderGroupName": "Cabeçalho",
    "WebPartHeaderFieldLabel": "Texto do cabeçalho",
    "WebPartHeaderPlaceholder": "ex.: Painel de vendas",
    "ShowWebPartHeaderFieldLabel": "Mostrar cabeçalho",
    "ChartSettingsGroupName": "Configurações do gráfico",
    "ChartTitleFieldLabel": "Título do gráfico",
    "ChartTypeFieldLabel": "Tipo de gráfico",
    "LegendPositionFieldLabel": "Posição da legenda",
    "ChartHeightFieldLabel": "Altura do gráfico (px)",
    "ShowLegendFieldLabel": "Mostrar legenda",
    "StackedFieldLabel": "Empilhado (barras/linhas)",
    "ShowDataTableFieldLabel": "Mostrar tabela de dados",
    "ShowExportBarFieldLabel": "Mostrar barra de exportação",
    "XAxisLabelFieldLabel": "Rótulo do eixo X (opcional)",
    "XAxisPlaceholder": "Usa a coluna selecionada por padrão",
    "YAxisLabelFieldLabel": "Rótulo do eixo Y (opcional)",
    "YAxisPlaceholder": "Usa as colunas selecionadas por padrão",
    "ChartGroupStandard": "Gráficos padrão",
    "ChartGroupSpecialized": "Gráficos especializados",
    "ChartTypeBarLabel": "Gráfico de colunas (vertical)",
    "ChartTypeHorizontalBarLabel": "Gráfico de barras (horizontal)",
    "ChartTypeLineLabel": "Gráfico de linhas",
    "ChartTypeAreaLabel": "Gráfico de áreas",
    "ChartTypeScatterLabel": "Gráfico de dispersão",
    "ChartTypePieLabel": "Gráfico de pizza",
    "ChartTypeDoughnutLabel": "Gráfico de rosca",
    "ChartTypeBubbleLabel": "Gráfico de bolhas",
    "ChartTypeRadarLabel": "Gráfico de radar",
    "ChartTypeKpiLabel": "Bloco de KPI",
    "ChartTypeHistogramLabel": "Histograma",
    "ChartTypeWaterfallLabel": "Gráfico de cascata",
    "ChartTypeBoxplotLabel": "Boxplot",
    "ChartTypeViolinLabel": "Gráfico de violino",
    "ChartTypeBeforeAfterLabel": "Gráfico antes-depois",
    "ChartTypeTreemapLabel": "Treemap",
    "ChartTypeHeatmapLabel": "Mapa de calor",
    "HistogramBinsFieldLabel": "Intervalos do histograma",
    "AppearancePageDescription": "Cores, rótulos e eixos",
    "AdvancedPageDescription": "Análises, linhas de referência, interatividade e atualização de dados",
    "LegendTopLabel": "Superior",
    "LegendBottomLabel": "Inferior",
    "LegendLeftLabel": "Esquerda",
    "LegendRightLabel": "Direita",
    "ColorsGroupName": "Cores",
    "ColorPaletteFieldLabel": "Paleta de cores",
    "PaletteOfficeLabel": "Office (padrão)",
    "PaletteVibrantLabel": "Vibrante",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Monocromática",
    "PaletteTrafficLightLabel": "Semáforo",
    "PaletteWarmLabel": "Quente",
    "PaletteCoolLabel": "Fria",
    "DataLabelsGroupName": "Rótulos de dados e formatação",
    "ShowDataLabelsFieldLabel": "Mostrar rótulos de dados",
    "ValuePrefixFieldLabel": "Prefixo do valor",
    "ValuePrefixPlaceholder": "ex.: R$",
    "ValueSuffixFieldLabel": "Sufixo do valor",
    "ValueSuffixPlaceholder": "ex.: %",
    "ValueDecimalsFieldLabel": "Casas decimais",
    "AbbreviateNumbersFieldLabel": "Abreviar números (K/M)",
    "AxesGridGroupName": "Eixos e grade",
    "YAxisMinFieldLabel": "Mínimo do eixo Y",
    "YAxisMaxFieldLabel": "Máximo do eixo Y",
    "AutoPlaceholder": "Automático",
    "NumericValidationError": "Insira um número ou deixe em branco para automático.",
    "ColorValidationError": "Insira uma cor hexadecimal (ex.: #d13438) ou deixe em branco para o padrão.",
    "LogScaleFieldLabel": "Escala logarítmica (Y)",
    "LogScaleXFieldLabel": "Escala logarítmica (X)",
    "StepLineFieldLabel": "Interpolação em degraus",
    "ShowGridLinesFieldLabel": "Mostrar linhas de grade",
    "XLabelRotationFieldLabel": "Rotação do rótulo X (graus)",
    "XAxisTypeFieldLabel": "Tipo do eixo X",
    "XAxisTypeAuto": "Detectar automaticamente",
    "XAxisTypeCategory": "Categoria",
    "XAxisTypeTime": "Tempo (datas)",
    "AnalyticsGroupName": "Análises",
    "TrendlineFieldLabel": "Linha de tendência",
    "TrendlineNone": "Nenhuma",
    "TrendlineLinear": "Linear",
    "TrendlineMovingAverage": "Média móvel",
    "TrendWindowFieldLabel": "Janela da média móvel",
    "TrendSuffix": " (tendência)",
    "ForecastPeriodsFieldLabel": "Períodos de previsão (linha de tendência linear)",
    "ReferenceLineGroupName": "Linha de referência",
    "ReferenceLineTypeFieldLabel": "Linha de referência",
    "ReferenceLineValueFieldLabel": "Valor fixo",
    "ReferenceLineColorFieldLabel": "Cor da linha (hex)",
    "RefLineFixed": "Valor fixo",
    "RefLineMean": "Média",
    "RefLineMedian": "Mediana",
    "DualAxisGroupName": "Eixo Y duplo",
    "Y2ColumnsFieldLabel": "Séries do eixo direito (nomes de colunas separados por vírgula)",
    "Y2ColumnsPlaceholder": "ex.: Margem,Crescimento",
    "Y2AxisLabelFieldLabel": "Rótulo do eixo direito",
    "LogScaleY2FieldLabel": "Escala logarítmica (eixo direito)",
    "ErrorBarsGroupName": "Barras de erro",
    "ErrorBarTypeFieldLabel": "Tipo de barra de erro",
    "ErrorBarTypeNone": "Nenhuma",
    "ErrorBarTypeCustom": "Coluna personalizada (±)",
    "ErrorBarTypeSd": "Desvio padrão (calculado)",
    "ErrorBarTypeSem": "Erro padrão da média (calculado)",
    "ErrorBarColumnFieldLabel": "Coluna do valor de erro",
    "SignificanceGroupName": "Colchetes de significância",
    "SignificancePairsFieldLabel": "Pares de colchetes",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Um colchete por linha: col1,col2,rótulo  — ex.: GrupoA,GrupoB,*  ou  GrupoA,GrupoB,p<0.05  (matriz JSON também aceita)",
    "BeforeAfterColumnsError": "O gráfico antes-depois exige exatamente 2 colunas Y — uma para os valores de antes e outra para os valores de depois.",
    "InteractivityGroupName": "Interatividade",
    "ShowViewerFiltersFieldLabel": "Mostrar filtros aos visualizadores",
    "DetailsOnDemandFieldLabel": "Mostrar linhas de dados ao clicar",
    "ShowDataPointsFieldLabel": "Sobrepor pontos de dados às barras",
    "ShowBubbleSizeLegendFieldLabel": "Mostrar legenda de tamanho das bolhas",
    "ViewerFilterLabel": "Filtro:",
    "ViewerFilterColumnAria": "Coluna do filtro",
    "ViewerFilterValueAria": "Valor do filtro",
    "DrillAllLabel": "Todos",
    "DetailsChipLabel": "Detalhes: {0} ({1} linhas)",
    "KpiSubLabel": "{0} • {1} • {2} linhas",
    "ConditionalGroupName": "Formatação condicional",
    "ThresholdValueFieldLabel": "Valor limite",
    "ThresholdValuePlaceholder": "Desativado",
    "ThresholdDirectionFieldLabel": "Destacar valores",
    "ThresholdBelow": "Abaixo do limite",
    "ThresholdAbove": "Acima do limite",
    "ThresholdColorFieldLabel": "Cor de destaque (hex)",
    "DataRefreshGroupName": "Dados e atualização",
    "RefreshIntervalFieldLabel": "Intervalo de atualização automática (minutos, 0 = desativado)",
    "CacheMinutesFieldLabel": "Armazenar dados em cache (minutos, 0 = desativado)",
    "DynamicDataCategoryLabel": "Categoria selecionada",
    "DynamicDataValueLabel": "Valor selecionado",
    "DynamicDataSeriesLabel": "Série selecionada",
    "DataSourceGroupName": "Fonte de dados",
    "HideDataSourceButton": "▲ Ocultar fonte de dados",
    "ConfigureDataSourceButton": "▼ Configurar fonte de dados",
    "RowsLoadedBadge": "✓ {0} linhas carregadas",
    "ReadModeLoadError": "Não foi possível carregar os dados: {0}. Alterne para o modo de edição para reconfigurar a fonte de dados.",
    "RefreshDataButton": "↻ Atualizar dados",
    "RefreshingLabel": "Atualizando…",
    "RefreshDataTitle": "Recarregar dados da fonte configurada",
    "NoDataMessage": "Nenhum dado carregado ainda. Configure sua fonte de dados acima e clique em Carregar dados.",
    "SelectMappingsMessage": "Dados carregados ({0} linhas). Selecione os mapeamentos de colunas acima para exibir o gráfico.",
    "ChartRenderErrorLabel": "Erro ao renderizar o gráfico: {0}",
    "UnsupportedChartTypeLabel": "Tipo de gráfico não compatível: {0}",
    "ChartAriaLabel": "Gráfico de visualização de dados",
    "FilterOperatorLabel": "Operador",
    "FilterValueLabel": "Valor",
    "FilterOpContains": "contém",
    "FilterOpEquals": "é igual a",
    "FilterOpNotEquals": "não é igual a",
    "FilterOpGt": "maior que",
    "FilterOpLt": "menor que",
    "FilterOpBetween": "entre (mín..máx)",
    "FilterOpIsEmpty": "está vazio",
    "FilterOpNotEmpty": "não está vazio",
    "AddFilterButton": "+ Adicionar filtro",
    "RemoveFilterButton": "Remover",
    "SelectValuePlaceholder": "Selecionar valor…",
    "ViewerFilterOperatorAria": "Operador do filtro",
    "PaletteColorblindLabel": "Seguro para daltonismo",
    "WaterfallGroupName": "Cascata",
    "WaterfallShowTotalFieldLabel": "Mostrar barra de total",
    "WaterfallPositiveColorFieldLabel": "Cor de aumento",
    "WaterfallNegativeColorFieldLabel": "Cor de redução",
    "WaterfallTotalColorFieldLabel": "Cor do total",
    "WaterfallTotalLabel": "Total",
    "ExternalFilterGroupName": "Filtrar a partir de outra web part",
    "ExternalFilterFieldLabel": "Fonte do valor do filtro",
    "ExternalFilterColumnFieldLabel": "Coluna a filtrar",
    "ExternalFilterColumnPlaceholder": "Usa a coluna do eixo X por padrão",
    "ViewAsTableButton": "Exibir como tabela",
    "HideTableButton": "Ocultar tabela",
    "ChartKeyboardHint": "Use as teclas de seta para se mover entre os pontos de dados e Enter para selecionar um.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Prefixo do valor Y2",
    "Y2ValueSuffixFieldLabel": "Sufixo do valor Y2",
    "AnnotationsGroupName": "Anotações",
    "AnnotationsFieldLabel": "Anotações",
    "AnnotationsPlaceholder": "Jan, Lançamento do produto",
    "AnnotationsHelp": "Uma por linha: o valor do eixo X, uma vírgula e o texto da nota. Um marcador vertical é desenhado nesse valor de X.",
    "BeforeLabel": "Antes",
    "AfterLabel": "Depois",
    "RowLabel": "Linha {0}",
    "PointsSuffix": " (pontos)",
    "ExportSheetName": "Dados",
    "RefreshFailedNote": "Falha na última atualização: {0}. Exibindo os dados carregados anteriormente.",
    "TruncatedDataNote": "Somente as primeiras {0} linhas são exibidas; a fonte tem mais dados.",
    "ScatterNumericWarning": "Gráficos de dispersão e de bolhas precisam de valores numéricos. A coluna \"{0}\" não tem dados numéricos — escolha outra coluna no mapeamento acima.",
    "TimeAxisUnparseableWarning": "A coluna do eixo X \"{0}\" não tem valores que possam ser interpretados como datas. Altere o Tipo do eixo X para \"Categoria\" ou mapeie uma coluna de data.",
    "DataSourceSectionHeader": "Fonte de dados",
    "SourceUploadLabel": "Carregar arquivo",
    "SourceSharePointListLabel": "Lista do SharePoint",
    "SourceSharePointFileLabel": "Arquivo do SharePoint",
    "SourceRestApiLabel": "API REST",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Caminho da API do Graph",
    "GraphPathHelp": "Caminho relativo do Microsoft Graph, ex.: /me/memberOf ou /reports/getTeamsUserActivityUserCounts(period='D7'). Essa fonte exige permissões do Graph aprovadas por um administrador — todas as outras fontes de dados funcionam sem elas.",
    "SheetNameLabel": "Planilha do Excel",
    "DelimiterLabel": "Delimitador",
    "DelimiterAutoDetect": "Detectar automaticamente",
    "DelimiterComma": "Vírgula (,)",
    "DelimiterTab": "Tabulação",
    "DelimiterSemicolon": "Ponto e vírgula (;)",
    "DelimiterPipe": "Barra vertical (|)",
    "SiteUrlLabel": "URL do site (opcional)",
    "SiteUrlHelp": "Deixe em branco para usar o site atual.",
    "ListNameLabel": "Nome da lista",
    "LoadingListsLabel": "— Carregando listas…",
    "SelectListPlaceholder": "— Selecione uma lista —",
    "EnterListNamePlaceholder": "Insira o nome da lista",
    "ListNameExamplePlaceholder": "ex.: Dados de vendas",
    "ListDiscoveryError": "Não foi possível carregar as listas — insira o nome manualmente abaixo.",
    "FileUrlLabel": "URL do arquivo (CSV/TSV/Excel no SharePoint)",
    "FileUrlHelp": "URL completa de um arquivo em uma biblioteca de documentos.",
    "ApiUrlLabel": "URL da API",
    "DataPathLabel": "Caminho dos dados (opcional)",
    "DataPathHelp": "Caminho separado por pontos até a matriz na resposta JSON. Deixe em branco se a raiz for uma matriz. Para a API REST do SharePoint, use \"value\".",
    "UploadHelp": "Carregue um arquivo CSV, TSV ou Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} linhas",
    "ChangeFileButton": "Alterar arquivo…",
    "ClearButton": "Limpar",
    "ChooseFileButton": "Escolher arquivo…",
    "LoadDataButton": "Carregar dados",
    "LoadingLabel": "Carregando…",
    "ErrorSelectListName": "Selecione ou insira o nome de uma lista.",
    "ErrorEnterFileUrl": "Insira a URL de um arquivo.",
    "ErrorEnterUrl": "Insira uma URL.",
    "ErrorLoadList": "Falha ao carregar a lista do SharePoint: {0}",
    "ErrorLoadFile": "Falha ao carregar o arquivo: {0}",
    "ErrorFetchData": "Falha ao buscar os dados: {0}",
    "ErrorDataPathNotFound": "O caminho de dados \"{0}\" não foi encontrado na resposta.",
    "ErrorUrlReturnedHtml": "Essa URL retornou uma página da web, não um arquivo. Use o caminho direto de download do arquivo, não uma URL de compartilhamento \"Copiar link\".",
    "ErrorRequestTimedOut": "A solicitação expirou. Verifique a URL e sua conexão de rede.",
    "ErrorNonJsonResponse": "Não foi possível analisar a resposta como JSON.",
    "ErrorUnsupportedFileType": "Tipo de arquivo não compatível. Carregue um arquivo .csv, .tsv, .xlsx ou .xls.",
    "ErrorReadFile": "Falha ao ler o arquivo",
    "ErrorParseFile": "Falha ao analisar o arquivo",
    "LoadedRowsColumns": "{0} linhas com {1} colunas carregadas.",
    "LoadedRowsColumnsPersist": "{0} linhas com {1} colunas carregadas. Os dados serão mantidos quando você sair da página.",
    "SizeWarning": "O conjunto de dados ({0}KB) excede o limite de persistência de 200KB. O gráfico mostrará os dados nesta sessão, mas eles serão apagados ao recarregar a página. Para arquivos grandes, carregue-os em uma biblioteca do SharePoint e use a fonte Arquivo do SharePoint.",
    "ListTruncatedWarning": "Esta lista tem {0} itens ou mais; somente os primeiros {0} foram carregados.",
    "GraphTruncatedWarning": "Este resultado do Microsoft Graph tem mais páginas do que foi possível carregar; somente as primeiras {0} páginas foram recuperadas.",
    "CsvParseWarning": "{0} linha(s) não puderam ser analisadas e foram ignoradas.",
    "ColumnMappingSectionHeader": "Mapeamento de colunas",
    "CategoryColumnLabel": "Coluna de categoria (X / rótulos)",
    "LabelColumnLabel": "Coluna de rótulo",
    "XAxisColumnLabel": "Coluna do eixo X",
    "ValueColumnLabel": "Coluna de valor",
    "YAxisColumnLabel": "Coluna do eixo Y",
    "YAxisColumnsLabel": "Coluna(s) do eixo Y",
    "YAxisColumnsHelp": "(selecione uma ou mais; clique na amostra para definir a cor)",
    "SelectColumnPlaceholder": "— Selecionar coluna —",
    "ScatterLabelColumnLabel": "Rótulo do ponto",
    "SizeColumnLabel":"Coluna de tamanho / raio",
    "NoSizeColumnOption": "— Nenhuma (tamanho fixo) —",
    "SeriesColorTitle": "Cor de {0}",
    "SeriesTypeTitle": "Tipo de gráfico de {0}",
    "SeriesTypeDefault": "Padrão",
    "SeriesTypeBar": "Barras",
    "SeriesTypeLine": "Linha",
    "HistogramColumnLabel": "Coluna a agrupar (numérica)",
    "TreemapGroupLabel": "Coluna de grupo / rótulo",
    "HeatmapColumnLabel": "Categoria da coluna (X)",
    "HeatmapRowLabel": "Categoria da linha (Y)",
    "AdvancedOptionsClosed": "▼ Opções avançadas",
    "AdvancedOptionsOpen": "▲ Opções avançadas",
    "ColorByLabel": "Colorir por coluna",
    "ColorByHelp": "Colorir os pontos por categoria em vez de por série.",
    "TooltipColumnsLabel": "Colunas da dica de ferramenta",
    "TooltipColumnsHelp": "(colunas extras exibidas ao passar o mouse sobre um ponto de dados)",
    "DrillLevelLabel": "Nível de drill {0}",
    "DrillDownHelp": "Defina uma hierarquia de colunas para habilitar o drill por clique (ex.: Região → País → Cidade). Os valores são agregados em cada nível.",
    "BookmarksLabel": "Indicadores",
    "BookmarkNameLabel": "Nome do indicador",
    "BookmarkNamePlaceholder": "ex.: Top 10 por região",
    "SaveBookmarkButton": "Salvar exibição atual",
    "ApplyBookmarkButton": "Aplicar",
    "DeleteBookmarkButton": "Excluir",
    "ApplyBookmarkPlaceholder": "— Aplicar um indicador —",
    "DataControlsSectionHeader": "Controles de dados",
    "SortByColumnLabel": "Classificar por coluna",
    "NoneOption": "— Nenhum —",
    "SortDirectionLabel": "Direção da classificação",
    "AscendingOption": "Crescente",
    "DescendingOption": "Decrescente",
    "RowLimitLabel": "Limite de linhas (0 = todas)",
    "FilterColumnLabel": "Coluna do filtro",
    "FilterContainsLabel": "Filtro: contém",
    "FilterValuePlaceholder": "Valor do filtro…",
    "GroupByLabel": "Agrupar por coluna",
    "AggregationLabel": "Agregação",
    "GroupByHelp": "As colunas numéricas são agregadas por grupo. Contagem adiciona uma coluna \"Contagem\".",
    "AggNone": "Nenhuma",
    "AggSum": "Soma",
    "AggAvg": "Média",
    "AggCount": "Contagem",
    "AggMin": "Mín.",
    "AggMax": "Máx.",
    "DataTableHeader": "Tabela de dados ({0} linhas)",
    "PrevPageButton": "← Anterior",
    "NextPageButton": "Próxima →",
    "PageOfLabel": "Página {0} de {1}",
    "ExportLabel": "Exportar:",
    "ExportPngTitle": "Baixar o gráfico como imagem PNG",
    "ExportJpegTitle": "Baixar o gráfico como imagem JPEG",
    "ExportCsvTitle": "Baixar os dados como CSV",
    "ExportExcelTitle": "Baixar os dados como pasta de trabalho do Excel"
  }
});
