define([], function() {
  return {
    "PropertyPaneDescription": "Configure a sua visualização de dados",
    "HeaderGroupName": "Cabeçalho",
    "WebPartHeaderFieldLabel": "Texto do cabeçalho",
    "WebPartHeaderPlaceholder": "p. ex.: Painel de vendas",
    "ShowWebPartHeaderFieldLabel": "Mostrar cabeçalho",
    "ChartSettingsGroupName": "Definições do gráfico",
    "ChartTitleFieldLabel": "Título do gráfico",
    "ChartTypeFieldLabel": "Tipo de gráfico",
    "LegendPositionFieldLabel": "Posição da legenda",
    "ChartHeightFieldLabel": "Altura do gráfico (px)",
    "ShowLegendFieldLabel": "Mostrar legenda",
    "StackedFieldLabel": "Empilhado (barras/linhas)",
    "ShowDataTableFieldLabel": "Mostrar tabela de dados",
    "ShowExportBarFieldLabel": "Mostrar barra de exportação",
    "XAxisLabelFieldLabel": "Etiqueta do eixo X (opcional)",
    "XAxisPlaceholder": "Utiliza a coluna selecionada por predefinição",
    "YAxisLabelFieldLabel": "Etiqueta do eixo Y (opcional)",
    "YAxisPlaceholder": "Utiliza as colunas selecionadas por predefinição",
    "ChartGroupStandard": "Gráficos padrão",
    "ChartGroupSpecialized": "Gráficos especializados",
    "ChartTypeBarLabel": "Gráfico de colunas (vertical)",
    "ChartTypeHorizontalBarLabel": "Gráfico de barras (horizontal)",
    "ChartTypeLineLabel": "Gráfico de linhas",
    "ChartTypeAreaLabel": "Gráfico de áreas",
    "ChartTypeScatterLabel": "Gráfico de dispersão",
    "ChartTypePieLabel": "Gráfico circular",
    "ChartTypeDoughnutLabel": "Gráfico de anel",
    "ChartTypeBubbleLabel": "Gráfico de bolhas",
    "ChartTypeRadarLabel": "Gráfico de radar",
    "ChartTypeKpiLabel": "Mosaico de KPI",
    "ChartTypeHistogramLabel": "Histograma",
    "ChartTypeWaterfallLabel": "Gráfico de cascata",
    "ChartTypeBoxplotLabel": "Boxplot",
    "ChartTypeViolinLabel": "Gráfico de violino",
    "ChartTypeBeforeAfterLabel": "Gráfico antes-depois",
    "ChartTypeTreemapLabel": "Treemap",
    "ChartTypeHeatmapLabel": "Mapa de calor",
    "HistogramBinsFieldLabel": "Intervalos do histograma",
    "AppearancePageDescription": "Cores, etiquetas e eixos",
    "AdvancedPageDescription": "Análises, linhas de referência, interatividade e atualização de dados",
    "LegendTopLabel": "Superior",
    "LegendBottomLabel": "Inferior",
    "LegendLeftLabel": "Esquerda",
    "LegendRightLabel": "Direita",
    "ColorsGroupName": "Cores",
    "ColorPaletteFieldLabel": "Paleta de cores",
    "PaletteOfficeLabel": "Office (predefinida)",
    "PaletteVibrantLabel": "Vibrante",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Monocromática",
    "PaletteTrafficLightLabel": "Semáforo",
    "PaletteWarmLabel": "Quente",
    "PaletteCoolLabel": "Fria",
    "DataLabelsGroupName": "Etiquetas de dados e formatação",
    "ShowDataLabelsFieldLabel": "Mostrar etiquetas de dados",
    "ValuePrefixFieldLabel": "Prefixo do valor",
    "ValuePrefixPlaceholder": "p. ex.: €",
    "ValueSuffixFieldLabel": "Sufixo do valor",
    "ValueSuffixPlaceholder": "p. ex.: %",
    "ValueDecimalsFieldLabel": "Casas decimais",
    "AbbreviateNumbersFieldLabel": "Abreviar números (K/M)",
    "AxesGridGroupName": "Eixos e grelha",
    "YAxisMinFieldLabel": "Mínimo do eixo Y",
    "YAxisMaxFieldLabel": "Máximo do eixo Y",
    "AutoPlaceholder": "Automático",
    "NumericValidationError": "Introduza um número ou deixe em branco para automático.",
    "ColorValidationError": "Introduza uma cor hexadecimal (p. ex.: #d13438) ou deixe em branco para a predefinida.",
    "LogScaleFieldLabel": "Escala logarítmica (Y)",
    "LogScaleXFieldLabel": "Escala logarítmica (X)",
    "StepLineFieldLabel": "Interpolação em degraus",
    "ShowGridLinesFieldLabel": "Mostrar linhas de grelha",
    "XLabelRotationFieldLabel": "Rotação da etiqueta X (graus)",
    "XAxisTypeFieldLabel": "Tipo do eixo X",
    "XAxisTypeAuto": "Detetar automaticamente",
    "XAxisTypeCategory": "Categoria",
    "XAxisTypeTime": "Tempo (datas)",
    "AnalyticsGroupName": "Análises",
    "TrendlineFieldLabel": "Linha de tendência",
    "TrendlineNone": "Nenhuma",
    "TrendlineLinear": "Linear",
    "TrendlineMovingAverage": "Média móvel",
    "TrendWindowFieldLabel": "Janela da média móvel",
    "TrendSuffix": " (tendência)",
    "ForecastPeriodsFieldLabel": "Períodos de previsão (linha de tendência linear)",
    "ReferenceLineGroupName": "Linha de referência",
    "ReferenceLineTypeFieldLabel": "Linha de referência",
    "ReferenceLineValueFieldLabel": "Valor fixo",
    "ReferenceLineColorFieldLabel": "Cor da linha (hex)",
    "RefLineFixed": "Valor fixo",
    "RefLineMean": "Média",
    "RefLineMedian": "Mediana",
    "DualAxisGroupName": "Eixo Y duplo",
    "Y2ColumnsFieldLabel": "Séries do eixo direito (nomes de colunas separados por vírgulas)",
    "Y2ColumnsPlaceholder": "p. ex.: Margem,Crescimento",
    "Y2AxisLabelFieldLabel": "Etiqueta do eixo direito",
    "LogScaleY2FieldLabel": "Escala logarítmica (eixo direito)",
    "ErrorBarsGroupName": "Barras de erro",
    "ErrorBarTypeFieldLabel": "Tipo de barra de erro",
    "ErrorBarTypeNone": "Nenhuma",
    "ErrorBarTypeCustom": "Coluna personalizada (±)",
    "ErrorBarTypeSd": "Desvio padrão (calculado)",
    "ErrorBarTypeSem": "Erro padrão da média (calculado)",
    "ErrorBarColumnFieldLabel": "Coluna do valor de erro",
    "SignificanceGroupName": "Parênteses de significância",
    "SignificancePairsFieldLabel": "Pares de parênteses",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Um parêntese por linha: col1,col2,etiqueta  — p. ex.: GrupoA,GrupoB,*  ou  GrupoA,GrupoB,p<0.05  (também é aceite uma matriz JSON)",
    "BeforeAfterColumnsError": "O gráfico antes-depois requer exatamente 2 colunas Y — uma para os valores de antes e outra para os valores de depois.",
    "InteractivityGroupName": "Interatividade",
    "ShowViewerFiltersFieldLabel": "Mostrar filtros aos leitores",
    "DetailsOnDemandFieldLabel": "Mostrar linhas de dados ao clicar",
    "ShowDataPointsFieldLabel": "Sobrepor pontos de dados às barras",
    "ShowBubbleSizeLegendFieldLabel": "Mostrar legenda de tamanho das bolhas",
    "ViewerFilterLabel": "Filtro:",
    "ViewerFilterColumnAria": "Coluna do filtro",
    "ViewerFilterValueAria": "Valor do filtro",
    "DrillAllLabel": "Todos",
    "DetailsChipLabel": "Detalhes: {0} ({1} linhas)",
    "KpiSubLabel": "{0} • {1} • {2} linhas",
    "ConditionalGroupName": "Formatação condicional",
    "ThresholdValueFieldLabel": "Valor limite",
    "ThresholdValuePlaceholder": "Desativado",
    "ThresholdDirectionFieldLabel": "Realçar valores",
    "ThresholdBelow": "Abaixo do limite",
    "ThresholdAbove": "Acima do limite",
    "ThresholdColorFieldLabel": "Cor de realce (hex)",
    "DataRefreshGroupName": "Dados e atualização",
    "RefreshIntervalFieldLabel": "Intervalo de atualização automática (minutos, 0 = desativado)",
    "CacheMinutesFieldLabel": "Colocar dados em cache (minutos, 0 = desativado)",
    "DynamicDataCategoryLabel": "Categoria selecionada",
    "DynamicDataValueLabel": "Valor selecionado",
    "DynamicDataSeriesLabel": "Série selecionada",
    "DataSourceGroupName": "Origem de dados",
    "HideDataSourceButton": "▲ Ocultar origem de dados",
    "ConfigureDataSourceButton": "▼ Configurar origem de dados",
    "RowsLoadedBadge": "✓ {0} linhas carregadas",
    "ReadModeLoadError": "Não foi possível carregar os dados: {0}. Mude para o modo de edição para reconfigurar a origem de dados.",
    "RefreshDataButton": "↻ Atualizar dados",
    "RefreshingLabel": "A atualizar…",
    "RefreshDataTitle": "Recarregar os dados da origem configurada",
    "NoDataMessage": "Ainda não foram carregados dados. Configure a origem de dados acima e clique em Carregar dados.",
    "SelectMappingsMessage": "Dados carregados ({0} linhas). Selecione os mapeamentos de colunas acima para apresentar o gráfico.",
    "ChartRenderErrorLabel": "Erro ao compor o gráfico: {0}",
    "UnsupportedChartTypeLabel": "Tipo de gráfico não suportado: {0}",
    "ChartAriaLabel": "Gráfico de visualização de dados",
    "FilterOperatorLabel": "Operador",
    "FilterValueLabel": "Valor",
    "FilterOpContains": "contém",
    "FilterOpEquals": "é igual a",
    "FilterOpNotEquals": "não é igual a",
    "FilterOpGt": "maior do que",
    "FilterOpLt": "menor do que",
    "FilterOpBetween": "entre (mín..máx)",
    "FilterOpIsEmpty": "está vazio",
    "FilterOpNotEmpty": "não está vazio",
    "AddFilterButton": "+ Adicionar filtro",
    "RemoveFilterButton": "Remover",
    "SelectValuePlaceholder": "Selecionar valor…",
    "ViewerFilterOperatorAria": "Operador do filtro",
    "PaletteColorblindLabel": "Adequada a daltonismo",
    "WaterfallGroupName": "Cascata",
    "WaterfallShowTotalFieldLabel": "Mostrar barra de total",
    "WaterfallPositiveColorFieldLabel": "Cor de aumento",
    "WaterfallNegativeColorFieldLabel": "Cor de diminuição",
    "WaterfallTotalColorFieldLabel": "Cor do total",
    "WaterfallTotalLabel": "Total",
    "ExternalFilterGroupName": "Filtrar a partir de outra web part",
    "ExternalFilterFieldLabel": "Origem do valor do filtro",
    "ExternalFilterColumnFieldLabel": "Coluna a filtrar",
    "ExternalFilterColumnPlaceholder": "Utiliza a coluna do eixo X por predefinição",
    "ViewAsTableButton": "Ver como tabela",
    "HideTableButton": "Ocultar tabela",
    "ChartKeyboardHint": "Utilize as teclas de seta para se deslocar entre os pontos de dados e Enter para selecionar um.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Prefixo do valor Y2",
    "Y2ValueSuffixFieldLabel": "Sufixo do valor Y2",
    "AnnotationsGroupName": "Anotações",
    "AnnotationsFieldLabel": "Anotações",
    "AnnotationsPlaceholder": "Jan, Lançamento do produto",
    "AnnotationsHelp": "Uma por linha: o valor do eixo X, uma vírgula e o texto da nota. É desenhado um marcador vertical nesse valor de X.",
    "BeforeLabel": "Antes",
    "AfterLabel": "Depois",
    "RowLabel": "Linha {0}",
    "PointsSuffix": " (pontos)",
    "ExportSheetName": "Dados",
    "RefreshFailedNote": "A última atualização falhou: {0}. A apresentar os dados carregados anteriormente.",
    "TruncatedDataNote": "Apenas as primeiras {0} linhas são apresentadas; a origem tem mais dados.",
    "ScatterNumericWarning": "Os gráficos de dispersão e de bolhas necessitam de valores numéricos. A coluna \"{0}\" não tem dados numéricos — escolha outra coluna no mapeamento acima.",
    "TimeAxisUnparseableWarning": "A coluna do eixo X \"{0}\" não tem valores que possam ser interpretados como datas. Altere o Tipo do eixo X para \"Categoria\" ou mapeie uma coluna de datas.",
    "DataSourceSectionHeader": "Origem de dados",
    "SourceUploadLabel": "Carregar ficheiro",
    "SourceSharePointListLabel": "Lista do SharePoint",
    "SourceSharePointFileLabel": "Ficheiro do SharePoint",
    "SourceRestApiLabel": "API REST",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Caminho da API do Graph",
    "GraphPathHelp": "Caminho relativo do Microsoft Graph, p. ex.: /me/memberOf ou /reports/getTeamsUserActivityUserCounts(period='D7'). Esta origem requer permissões do Graph aprovadas por um administrador — todas as outras origens de dados funcionam sem elas.",
    "SheetNameLabel": "Folha do Excel",
    "DelimiterLabel": "Delimitador",
    "DelimiterAutoDetect": "Detetar automaticamente",
    "DelimiterComma": "Vírgula (,)",
    "DelimiterTab": "Tabulação",
    "DelimiterSemicolon": "Ponto e vírgula (;)",
    "DelimiterPipe": "Barra vertical (|)",
    "SiteUrlLabel": "URL do site (opcional)",
    "SiteUrlHelp": "Deixe em branco para utilizar o site atual.",
    "ListNameLabel": "Nome da lista",
    "LoadingListsLabel": "— A carregar listas…",
    "SelectListPlaceholder": "— Selecione uma lista —",
    "EnterListNamePlaceholder": "Introduza o nome da lista",
    "ListNameExamplePlaceholder": "p. ex.: Dados de vendas",
    "ListDiscoveryError": "Não foi possível carregar as listas — introduza o nome manualmente abaixo.",
    "FileUrlLabel": "URL do ficheiro (CSV/TSV/Excel no SharePoint)",
    "FileUrlHelp": "URL completo de um ficheiro numa biblioteca de documentos.",
    "ApiUrlLabel": "URL da API",
    "DataPathLabel": "Caminho dos dados (opcional)",
    "DataPathHelp": "Caminho separado por pontos até à matriz na resposta JSON. Deixe em branco se a raiz for uma matriz. Para a API REST do SharePoint, utilize \"value\".",
    "UploadHelp": "Carregue um ficheiro CSV, TSV ou Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} linhas",
    "ChangeFileButton": "Alterar ficheiro…",
    "ClearButton": "Limpar",
    "ChooseFileButton": "Escolher ficheiro…",
    "LoadDataButton": "Carregar dados",
    "LoadingLabel": "A carregar…",
    "ErrorSelectListName": "Selecione ou introduza o nome de uma lista.",
    "ErrorEnterFileUrl": "Introduza o URL de um ficheiro.",
    "ErrorEnterUrl": "Introduza um URL.",
    "ErrorLoadList": "Falha ao carregar a lista do SharePoint: {0}",
    "ErrorLoadFile": "Falha ao carregar o ficheiro: {0}",
    "ErrorFetchData": "Falha ao obter os dados: {0}",
    "ErrorDataPathNotFound": "O caminho de dados \"{0}\" não foi encontrado na resposta.",
    "ErrorUrlReturnedHtml": "Este URL devolveu uma página Web, não um ficheiro. Utilize o caminho direto de transferência do ficheiro, não um URL de partilha \"Copiar ligação\".",
    "ErrorRequestTimedOut": "O pedido excedeu o tempo limite. Verifique o URL e a sua ligação de rede.",
    "ErrorNonJsonResponse": "Não foi possível analisar a resposta como JSON.",
    "ErrorUnsupportedFileType": "Tipo de ficheiro não suportado. Carregue um ficheiro .csv, .tsv, .xlsx ou .xls.",
    "ErrorReadFile": "Falha ao ler o ficheiro",
    "ErrorParseFile": "Falha ao analisar o ficheiro",
    "LoadedRowsColumns": "{0} linhas com {1} colunas carregadas.",
    "LoadedRowsColumnsPersist": "{0} linhas com {1} colunas carregadas. Os dados serão mantidos quando sair da página.",
    "SizeWarning": "O conjunto de dados ({0}KB) excede o limite de persistência de 200KB. O gráfico apresentará os dados nesta sessão, mas estes serão apagados ao recarregar a página. Para ficheiros grandes, carregue-os para uma biblioteca do SharePoint e utilize a origem Ficheiro do SharePoint.",
    "ListTruncatedWarning": "Esta lista tem {0} itens ou mais; apenas os primeiros {0} foram carregados.",
    "GraphTruncatedWarning": "Este resultado do Microsoft Graph tem mais páginas do que as que foi possível carregar; apenas as primeiras {0} páginas foram obtidas.",
    "CsvParseWarning": "Não foi possível analisar {0} linha(s), que foram ignoradas.",
    "ColumnMappingSectionHeader": "Mapeamento de colunas",
    "CategoryColumnLabel": "Coluna de categoria (X / etiquetas)",
    "LabelColumnLabel": "Coluna de etiqueta",
    "XAxisColumnLabel": "Coluna do eixo X",
    "ValueColumnLabel": "Coluna de valor",
    "YAxisColumnLabel": "Coluna do eixo Y",
    "YAxisColumnsLabel": "Coluna(s) do eixo Y",
    "YAxisColumnsHelp": "(selecione uma ou mais; clique na amostra para definir a cor)",
    "SelectColumnPlaceholder": "— Selecionar coluna —",
    "ScatterLabelColumnLabel": "Etiqueta do ponto",
    "SizeColumnLabel":"Coluna de tamanho / raio",
    "NoSizeColumnOption": "— Nenhuma (tamanho fixo) —",
    "SeriesColorTitle": "Cor de {0}",
    "SeriesTypeTitle": "Tipo de gráfico de {0}",
    "SeriesTypeDefault": "Predefinido",
    "SeriesTypeBar": "Barras",
    "SeriesTypeLine": "Linha",
    "HistogramColumnLabel": "Coluna a agrupar (numérica)",
    "TreemapGroupLabel": "Coluna de grupo / etiqueta",
    "HeatmapColumnLabel": "Categoria da coluna (X)",
    "HeatmapRowLabel": "Categoria da linha (Y)",
    "AdvancedOptionsClosed": "▼ Opções avançadas",
    "AdvancedOptionsOpen": "▲ Opções avançadas",
    "ColorByLabel": "Colorir por coluna",
    "ColorByHelp": "Colorir os pontos por categoria em vez de por série.",
    "TooltipColumnsLabel": "Colunas da dica de ferramenta",
    "TooltipColumnsHelp": "(colunas adicionais apresentadas ao pousar o rato sobre um ponto de dados)",
    "DrillLevelLabel": "Nível de drill {0}",
    "DrillDownHelp": "Defina uma hierarquia de colunas para ativar o drill por clique (p. ex.: Região → País → Cidade). Os valores são agregados em cada nível.",
    "BookmarksLabel": "Marcadores",
    "BookmarkNameLabel": "Nome do marcador",
    "BookmarkNamePlaceholder": "p. ex.: Top 10 por região",
    "SaveBookmarkButton": "Guardar vista atual",
    "ApplyBookmarkButton": "Aplicar",
    "DeleteBookmarkButton": "Eliminar",
    "ApplyBookmarkPlaceholder": "— Aplicar um marcador —",
    "DataControlsSectionHeader": "Controlos de dados",
    "SortByColumnLabel": "Ordenar por coluna",
    "NoneOption": "— Nenhum —",
    "SortDirectionLabel": "Direção da ordenação",
    "AscendingOption": "Ascendente",
    "DescendingOption": "Descendente",
    "RowLimitLabel": "Limite de linhas (0 = todas)",
    "FilterColumnLabel": "Coluna do filtro",
    "FilterContainsLabel": "Filtro: contém",
    "FilterValuePlaceholder": "Valor do filtro…",
    "GroupByLabel": "Agrupar por coluna",
    "AggregationLabel": "Agregação",
    "GroupByHelp": "As colunas numéricas são agregadas por grupo. Contagem adiciona uma coluna \"Contagem\".",
    "AggNone": "Nenhuma",
    "AggSum": "Soma",
    "AggAvg": "Média",
    "AggCount": "Contagem",
    "AggMin": "Mín.",
    "AggMax": "Máx.",
    "DataTableHeader": "Tabela de dados ({0} linhas)",
    "PrevPageButton": "← Anterior",
    "NextPageButton": "Seguinte →",
    "PageOfLabel": "Página {0} de {1}",
    "ExportLabel": "Exportar:",
    "ExportPngTitle": "Transferir o gráfico como imagem PNG",
    "ExportJpegTitle": "Transferir o gráfico como imagem JPEG",
    "ExportCsvTitle": "Transferir os dados como CSV",
    "ExportExcelTitle": "Transferir os dados como livro do Excel"
  }
});
