define([], function() {
  return {
    "PropertyPaneDescription": "Configurați vizualizarea datelor",
    "HeaderGroupName": "Antet",
    "WebPartHeaderFieldLabel": "Text antet",
    "WebPartHeaderPlaceholder": "de ex. Tablou de bord vânzări",
    "ShowWebPartHeaderFieldLabel": "Afișare antet",
    "ChartSettingsGroupName": "Setări grafic",
    "ChartTitleFieldLabel": "Titlu grafic",
    "ChartTypeFieldLabel": "Tip de grafic",
    "LegendPositionFieldLabel": "Poziție legendă",
    "ChartHeightFieldLabel": "Înălțime grafic (px)",
    "ShowLegendFieldLabel": "Afișare legendă",
    "StackedFieldLabel": "Stivuit (bare/linii)",
    "ShowDataTableFieldLabel": "Afișare tabel de date",
    "ShowExportBarFieldLabel": "Afișare bară de export",
    "XAxisLabelFieldLabel": "Etichetă axa X (opțional)",
    "XAxisPlaceholder": "Implicit, coloana selectată",
    "YAxisLabelFieldLabel": "Etichetă axa Y (opțional)",
    "YAxisPlaceholder": "Implicit, coloanele selectate",
    "ChartGroupStandard": "Grafice standard",
    "ChartGroupSpecialized": "Grafice specializate",
    "ChartTypeBarLabel": "Grafic cu coloane (vertical)",
    "ChartTypeHorizontalBarLabel": "Grafic cu bare (orizontal)",
    "ChartTypeLineLabel": "Grafic cu linii",
    "ChartTypeAreaLabel": "Grafic cu arii",
    "ChartTypeScatterLabel": "Grafic de dispersie",
    "ChartTypePieLabel": "Grafic circular",
    "ChartTypeDoughnutLabel": "Grafic inelar",
    "ChartTypeBubbleLabel": "Grafic cu bule",
    "ChartTypeRadarLabel": "Grafic radar",
    "ChartTypeKpiLabel": "Filă KPI",
    "ChartTypeHistogramLabel": "Histogramă",
    "ChartTypeWaterfallLabel": "Grafic cascadă",
    "ChartTypeBoxplotLabel": "Boxplot",
    "ChartTypeViolinLabel": "Grafic vioară",
    "ChartTypeBeforeAfterLabel": "Grafic înainte-după",
    "ChartTypeTreemapLabel": "Treemap",
    "ChartTypeHeatmapLabel": "Hartă termică",
    "HistogramBinsFieldLabel": "Intervale histogramă",
    "AppearancePageDescription": "Culori, etichete și axe",
    "AdvancedPageDescription": "Analize, linii de referință, interactivitate și reîmprospătarea datelor",
    "LegendTopLabel": "Sus",
    "LegendBottomLabel": "Jos",
    "LegendLeftLabel": "Stânga",
    "LegendRightLabel": "Dreapta",
    "ColorsGroupName": "Culori",
    "ColorPaletteFieldLabel": "Paletă de culori",
    "PaletteOfficeLabel": "Office (implicită)",
    "PaletteVibrantLabel": "Vibrantă",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Monocromă",
    "PaletteTrafficLightLabel": "Semafor",
    "PaletteWarmLabel": "Caldă",
    "PaletteCoolLabel": "Rece",
    "DataLabelsGroupName": "Etichete de date și formatare",
    "ShowDataLabelsFieldLabel": "Afișare etichete de date",
    "ValuePrefixFieldLabel": "Prefix valoare",
    "ValuePrefixPlaceholder": "de ex. $",
    "ValueSuffixFieldLabel": "Sufix valoare",
    "ValueSuffixPlaceholder": "de ex. %",
    "ValueDecimalsFieldLabel": "Zecimale",
    "AbbreviateNumbersFieldLabel": "Abreviere numere (K/M)",
    "AxesGridGroupName": "Axe și grilă",
    "YAxisMinFieldLabel": "Minim axa Y",
    "YAxisMaxFieldLabel": "Maxim axa Y",
    "AutoPlaceholder": "Automat",
    "NumericValidationError": "Introduceți un număr sau lăsați necompletat pentru automat.",
    "ColorValidationError": "Introduceți o culoare hexazecimală (de ex. #d13438) sau lăsați necompletat pentru valoarea implicită.",
    "LogScaleFieldLabel": "Scară logaritmică (Y)",
    "LogScaleXFieldLabel": "Scară logaritmică (X)",
    "StepLineFieldLabel": "Interpolare în trepte",
    "ShowGridLinesFieldLabel": "Afișare linii de grilă",
    "XLabelRotationFieldLabel": "Rotire etichetă X (grade)",
    "XAxisTypeFieldLabel": "Tip axa X",
    "XAxisTypeAuto": "Detectare automată",
    "XAxisTypeCategory": "Categorie",
    "XAxisTypeTime": "Timp (date)",
    "AnalyticsGroupName": "Analize",
    "TrendlineFieldLabel": "Linie de tendință",
    "TrendlineNone": "Niciuna",
    "TrendlineLinear": "Liniară",
    "TrendlineMovingAverage": "Medie mobilă",
    "TrendWindowFieldLabel": "Fereastră medie mobilă",
    "TrendSuffix": " (tendință)",
    "ForecastPeriodsFieldLabel": "Perioade de prognoză (linie de tendință liniară)",
    "ReferenceLineGroupName": "Linie de referință",
    "ReferenceLineTypeFieldLabel": "Linie de referință",
    "ReferenceLineValueFieldLabel": "Valoare fixă",
    "ReferenceLineColorFieldLabel": "Culoare linie (hex)",
    "RefLineFixed": "Valoare fixă",
    "RefLineMean": "Medie",
    "RefLineMedian": "Mediană",
    "DualAxisGroupName": "Axă Y dublă",
    "Y2ColumnsFieldLabel": "Serii pe axa din dreapta (nume de coloane separate prin virgulă)",
    "Y2ColumnsPlaceholder": "de ex. Marjă,Creștere",
    "Y2AxisLabelFieldLabel": "Etichetă axa din dreapta",
    "LogScaleY2FieldLabel": "Scară logaritmică (axa din dreapta)",
    "ErrorBarsGroupName": "Bare de eroare",
    "ErrorBarTypeFieldLabel": "Tip bară de eroare",
    "ErrorBarTypeNone": "Niciuna",
    "ErrorBarTypeCustom": "Coloană personalizată (±)",
    "ErrorBarTypeSd": "Abatere standard (calculată)",
    "ErrorBarTypeSem": "Eroare standard a mediei (calculată)",
    "ErrorBarColumnFieldLabel": "Coloană valoare eroare",
    "SignificanceGroupName": "Paranteze de semnificație",
    "SignificancePairsFieldLabel": "Perechi de paranteze",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "O paranteză pe linie: col1,col2,etichetă  — de ex. GrupA,GrupB,*  sau  GrupA,GrupB,p<0.05  (se acceptă și o matrice JSON)",
    "BeforeAfterColumnsError": "Graficul înainte-după necesită exact 2 coloane Y — una pentru valorile dinainte și una pentru valorile de după.",
    "InteractivityGroupName": "Interactivitate",
    "ShowViewerFiltersFieldLabel": "Afișare filtre pentru vizualizatori",
    "DetailsOnDemandFieldLabel": "Afișare rânduri de date la clic",
    "ShowDataPointsFieldLabel": "Suprapunere puncte de date peste bare",
    "ShowBubbleSizeLegendFieldLabel": "Afișare legendă dimensiune bule",
    "ViewerFilterLabel": "Filtru:",
    "ViewerFilterColumnAria": "Coloană filtru",
    "ViewerFilterValueAria": "Valoare filtru",
    "DrillAllLabel": "Toate",
    "DetailsChipLabel": "Detalii: {0} ({1} rânduri)",
    "KpiSubLabel": "{0} • {1} • {2} rânduri",
    "ConditionalGroupName": "Formatare condiționată",
    "ThresholdValueFieldLabel": "Valoare prag",
    "ThresholdValuePlaceholder": "Dezactivat",
    "ThresholdDirectionFieldLabel": "Evidențiere valori",
    "ThresholdBelow": "Sub prag",
    "ThresholdAbove": "Peste prag",
    "ThresholdColorFieldLabel": "Culoare evidențiere (hex)",
    "DataRefreshGroupName": "Date și reîmprospătare",
    "RefreshIntervalFieldLabel": "Interval de reîmprospătare automată (minute, 0 = dezactivat)",
    "CacheMinutesFieldLabel": "Memorare în cache a datelor (minute, 0 = dezactivat)",
    "DynamicDataCategoryLabel": "Categorie selectată",
    "DynamicDataValueLabel": "Valoare selectată",
    "DynamicDataSeriesLabel": "Serie selectată",
    "DataSourceGroupName": "Sursă de date",
    "HideDataSourceButton": "▲ Ascundere sursă de date",
    "ConfigureDataSourceButton": "▼ Configurare sursă de date",
    "RowsLoadedBadge": "✓ {0} rânduri încărcate",
    "ReadModeLoadError": "Nu s-au putut încărca datele: {0}. Comutați la modul de editare pentru a reconfigura sursa de date.",
    "RefreshDataButton": "↻ Reîmprospătare date",
    "RefreshingLabel": "Se reîmprospătează…",
    "RefreshDataTitle": "Reîncarcă datele din sursa configurată",
    "NoDataMessage": "Nu au fost încărcate încă date. Configurați sursa de date de mai sus și faceți clic pe Încărcare date.",
    "SelectMappingsMessage": "Date încărcate ({0} rânduri). Selectați maparea coloanelor de mai sus pentru a afișa graficul.",
    "ChartRenderErrorLabel": "Eroare la redarea graficului: {0}",
    "UnsupportedChartTypeLabel": "Tip de grafic neacceptat: {0}",
    "ChartAriaLabel": "Grafic de vizualizare a datelor",
    "FilterOperatorLabel": "Operator",
    "FilterValueLabel": "Valoare",
    "FilterOpContains": "conține",
    "FilterOpEquals": "este egal cu",
    "FilterOpNotEquals": "nu este egal cu",
    "FilterOpGt": "mai mare decât",
    "FilterOpLt": "mai mic decât",
    "FilterOpBetween": "între (min..max)",
    "FilterOpIsEmpty": "este necompletat",
    "FilterOpNotEmpty": "nu este necompletat",
    "AddFilterButton": "+ Adăugare filtru",
    "RemoveFilterButton": "Eliminare",
    "SelectValuePlaceholder": "Selectați valoarea…",
    "ViewerFilterOperatorAria": "Operator filtru",
    "PaletteColorblindLabel": "Adaptată daltonismului",
    "WaterfallGroupName": "Cascadă",
    "WaterfallShowTotalFieldLabel": "Afișare bară de total",
    "WaterfallPositiveColorFieldLabel": "Culoare creștere",
    "WaterfallNegativeColorFieldLabel": "Culoare scădere",
    "WaterfallTotalColorFieldLabel": "Culoare total",
    "WaterfallTotalLabel": "Total",
    "ExternalFilterGroupName": "Filtrare din alt web part",
    "ExternalFilterFieldLabel": "Sursă valoare filtru",
    "ExternalFilterColumnFieldLabel": "Coloană de filtrat",
    "ExternalFilterColumnPlaceholder": "Implicit, coloana axei X",
    "ViewAsTableButton": "Vizualizare ca tabel",
    "HideTableButton": "Ascundere tabel",
    "ChartKeyboardHint": "Utilizați tastele săgeți pentru a vă deplasa între punctele de date și Enter pentru a selecta unul.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Prefix valoare Y2",
    "Y2ValueSuffixFieldLabel": "Sufix valoare Y2",
    "AnnotationsGroupName": "Adnotări",
    "AnnotationsFieldLabel": "Adnotări",
    "AnnotationsPlaceholder": "Ian, Lansare produs",
    "AnnotationsHelp": "Câte una pe linie: valoarea de pe axa X, o virgulă, apoi textul notei. La acea valoare X se desenează un marcaj vertical.",
    "BeforeLabel": "Înainte",
    "AfterLabel": "După",
    "RowLabel": "Rândul {0}",
    "PointsSuffix": " (puncte)",
    "ExportSheetName": "Date",
    "RefreshFailedNote": "Ultima reîmprospătare a eșuat: {0}. Se afișează datele încărcate anterior.",
    "TruncatedDataNote": "Sunt afișate numai primele {0} rânduri; sursa conține mai multe date.",
    "ScatterNumericWarning": "Graficele de dispersie și cu bule necesită valori numerice. Coloana \"{0}\" nu conține date numerice — alegeți o altă coloană în maparea de mai sus.",
    "TimeAxisUnparseableWarning": "Coloana axei X \"{0}\" nu conține valori care să poată fi interpretate ca date calendaristice. Schimbați Tipul axei X la \"Categorie\" sau mapați o coloană de date calendaristice.",
    "DataSourceSectionHeader": "Sursă de date",
    "SourceUploadLabel": "Încărcare fișier",
    "SourceSharePointListLabel": "Listă SharePoint",
    "SourceSharePointFileLabel": "Fișier SharePoint",
    "SourceRestApiLabel": "API REST",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Cale API Graph",
    "GraphPathHelp": "Cale relativă Microsoft Graph, de ex. /me/memberOf sau /reports/getTeamsUserActivityUserCounts(period='D7'). Această sursă necesită permisiuni Graph aprobate de un administrator — toate celelalte surse de date funcționează fără ele.",
    "SheetNameLabel": "Foaie Excel",
    "DelimiterLabel": "Delimitator",
    "DelimiterAutoDetect": "Detectare automată",
    "DelimiterComma": "Virgulă (,)",
    "DelimiterTab": "Tabulator",
    "DelimiterSemicolon": "Punct și virgulă (;)",
    "DelimiterPipe": "Bară verticală (|)",
    "SiteUrlLabel": "URL site (opțional)",
    "SiteUrlHelp": "Lăsați necompletat pentru a utiliza site-ul curent.",
    "ListNameLabel": "Nume listă",
    "LoadingListsLabel": "— Se încarcă listele…",
    "SelectListPlaceholder": "— Selectați o listă —",
    "EnterListNamePlaceholder": "Introduceți numele listei",
    "ListNameExamplePlaceholder": "de ex. Date vânzări",
    "ListDiscoveryError": "Nu s-au putut încărca listele — introduceți numele manual mai jos.",
    "FileUrlLabel": "URL fișier (CSV/TSV/Excel în SharePoint)",
    "FileUrlHelp": "URL complet către un fișier dintr-o bibliotecă de documente.",
    "ApiUrlLabel": "URL API",
    "DataPathLabel": "Cale date (opțional)",
    "DataPathHelp": "Cale separată prin puncte către matricea din răspunsul JSON. Lăsați necompletat dacă rădăcina este o matrice. Pentru API-ul REST SharePoint, utilizați \"value\".",
    "UploadHelp": "Încărcați un fișier CSV, TSV sau Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} rânduri",
    "ChangeFileButton": "Schimbare fișier…",
    "ClearButton": "Golire",
    "ChooseFileButton": "Alegere fișier…",
    "LoadDataButton": "Încărcare date",
    "LoadingLabel": "Se încarcă…",
    "ErrorSelectListName": "Selectați sau introduceți un nume de listă.",
    "ErrorEnterFileUrl": "Introduceți un URL de fișier.",
    "ErrorEnterUrl": "Introduceți un URL.",
    "ErrorLoadList": "Încărcarea listei SharePoint a eșuat: {0}",
    "ErrorLoadFile": "Încărcarea fișierului a eșuat: {0}",
    "ErrorFetchData": "Preluarea datelor a eșuat: {0}",
    "ErrorDataPathNotFound": "Calea de date \"{0}\" nu a fost găsită în răspuns.",
    "ErrorUrlReturnedHtml": "Acest URL a returnat o pagină web, nu un fișier. Utilizați calea directă de descărcare a fișierului, nu un URL de partajare de tip \"Copiere link\".",
    "ErrorRequestTimedOut": "Solicitarea a expirat. Verificați URL-ul și conexiunea la rețea.",
    "ErrorNonJsonResponse": "Răspunsul nu a putut fi analizat ca JSON.",
    "ErrorUnsupportedFileType": "Tip de fișier neacceptat. Încărcați un fișier .csv, .tsv, .xlsx sau .xls.",
    "ErrorReadFile": "Citirea fișierului a eșuat",
    "ErrorParseFile": "Analiza fișierului a eșuat",
    "LoadedRowsColumns": "Au fost încărcate {0} rânduri cu {1} coloane.",
    "LoadedRowsColumnsPersist": "Au fost încărcate {0} rânduri cu {1} coloane. Datele vor fi păstrate când părăsiți pagina.",
    "SizeWarning": "Setul de date ({0}KB) depășește limita de persistență de 200KB. Graficul va afișa datele în această sesiune, dar acestea se vor șterge la reîncărcarea paginii. Pentru fișiere mari, încărcați-le într-o bibliotecă SharePoint și utilizați sursa Fișier SharePoint.",
    "ListTruncatedWarning": "Această listă are {0} elemente sau mai multe; au fost încărcate numai primele {0}.",
    "GraphTruncatedWarning": "Acest rezultat Microsoft Graph are mai multe pagini decât s-a putut încărca; au fost preluate numai primele {0} pagini.",
    "CsvParseWarning": "{0} rând(uri) nu au putut fi analizate și au fost omise.",
    "ColumnMappingSectionHeader": "Mapare coloane",
    "CategoryColumnLabel": "Coloană categorie (X / etichete)",
    "LabelColumnLabel": "Coloană etichetă",
    "XAxisColumnLabel": "Coloană axa X",
    "ValueColumnLabel": "Coloană valoare",
    "YAxisColumnLabel": "Coloană axa Y",
    "YAxisColumnsLabel": "Coloană (coloane) axa Y",
    "YAxisColumnsHelp": "(selectați una sau mai multe; faceți clic pe eșantion pentru a seta culoarea)",
    "SelectColumnPlaceholder": "— Selectați coloana —",
    "ScatterLabelColumnLabel": "Etichetă punct",
    "SizeColumnLabel":"Coloană dimensiune / rază",
    "NoSizeColumnOption": "— Niciuna (dimensiune fixă) —",
    "SeriesColorTitle": "Culoare pentru {0}",
    "SeriesTypeTitle": "Tip de grafic pentru {0}",
    "SeriesTypeDefault": "Implicit",
    "SeriesTypeBar": "Bare",
    "SeriesTypeLine": "Linie",
    "HistogramColumnLabel": "Coloană de grupat (numerică)",
    "TreemapGroupLabel": "Coloană grup / etichetă",
    "HeatmapColumnLabel": "Categorie coloană (X)",
    "HeatmapRowLabel": "Categorie rând (Y)",
    "AdvancedOptionsClosed": "▼ Opțiuni avansate",
    "AdvancedOptionsOpen": "▲ Opțiuni avansate",
    "ColorByLabel": "Colorare după coloană",
    "ColorByHelp": "Colorați punctele după categorie, nu după serie.",
    "TooltipColumnsLabel": "Coloane pentru sfat ecran",
    "TooltipColumnsHelp": "(coloane suplimentare afișate la trecerea cu mouse-ul peste un punct de date)",
    "DrillLevelLabel": "Nivel drill {0}",
    "DrillDownHelp": "Definiți o ierarhie de coloane pentru a activa drill prin clic (de ex. Regiune → Țară → Oraș). Valorile sunt agregate la fiecare nivel.",
    "BookmarksLabel": "Marcaje",
    "BookmarkNameLabel": "Nume marcaj",
    "BookmarkNamePlaceholder": "de ex. Top 10 pe regiuni",
    "SaveBookmarkButton": "Salvare vizualizare curentă",
    "ApplyBookmarkButton": "Aplicare",
    "DeleteBookmarkButton": "Ștergere",
    "ApplyBookmarkPlaceholder": "— Aplicați un marcaj —",
    "DataControlsSectionHeader": "Controale de date",
    "SortByColumnLabel": "Sortare după coloană",
    "NoneOption": "— Niciuna —",
    "SortDirectionLabel": "Direcție de sortare",
    "AscendingOption": "Crescător",
    "DescendingOption": "Descrescător",
    "RowLimitLabel": "Limită de rânduri (0 = toate)",
    "FilterColumnLabel": "Coloană filtru",
    "FilterContainsLabel": "Filtru: conține",
    "FilterValuePlaceholder": "Valoare filtru…",
    "GroupByLabel": "Grupare după coloană",
    "AggregationLabel": "Agregare",
    "GroupByHelp": "Coloanele numerice sunt agregate pe grup. Numărare adaugă o coloană \"Numărare\".",
    "AggNone": "Niciuna",
    "AggSum": "Sumă",
    "AggAvg": "Medie",
    "AggCount": "Numărare",
    "AggMin": "Min.",
    "AggMax": "Max.",
    "DataTableHeader": "Tabel de date ({0} rânduri)",
    "PrevPageButton": "← Anterioară",
    "NextPageButton": "Următoarea →",
    "PageOfLabel": "Pagina {0} din {1}",
    "ExportLabel": "Export:",
    "ExportPngTitle": "Descărcați graficul ca imagine PNG",
    "ExportJpegTitle": "Descărcați graficul ca imagine JPEG",
    "ExportCsvTitle": "Descărcați datele ca CSV",
    "ExportExcelTitle": "Descărcați datele ca registru de lucru Excel"
  }
});
