define([], function() {
  return {
    "PropertyPaneDescription": "Настройка визуализации данных",
    "HeaderGroupName": "Заголовок",
    "WebPartHeaderFieldLabel": "Текст заголовка",
    "WebPartHeaderPlaceholder": "например, Панель продаж",
    "ShowWebPartHeaderFieldLabel": "Показать заголовок",
    "ChartSettingsGroupName": "Параметры диаграммы",
    "ChartTitleFieldLabel": "Название диаграммы",
    "ChartTypeFieldLabel": "Тип диаграммы",
    "LegendPositionFieldLabel": "Положение легенды",
    "ChartHeightFieldLabel": "Высота диаграммы (px)",
    "ShowLegendFieldLabel": "Показать легенду",
    "StackedFieldLabel": "С накоплением (гистограмма/график)",
    "ShowDataTableFieldLabel": "Показать таблицу данных",
    "ShowExportBarFieldLabel": "Показать панель экспорта",
    "XAxisLabelFieldLabel": "Подпись оси X (необязательно)",
    "XAxisPlaceholder": "По умолчанию — выбранный столбец",
    "YAxisLabelFieldLabel": "Подпись оси Y (необязательно)",
    "YAxisPlaceholder": "По умолчанию — выбранные столбцы",
    "ChartGroupStandard": "Стандартные диаграммы",
    "ChartGroupSpecialized": "Специализированные диаграммы",
    "ChartTypeBarLabel": "Гистограмма (вертикальная)",
    "ChartTypeHorizontalBarLabel": "Линейчатая диаграмма (горизонтальная)",
    "ChartTypeLineLabel": "График",
    "ChartTypeAreaLabel": "Диаграмма с областями",
    "ChartTypeScatterLabel": "Точечная диаграмма",
    "ChartTypePieLabel": "Круговая диаграмма",
    "ChartTypeDoughnutLabel": "Кольцевая диаграмма",
    "ChartTypeBubbleLabel": "Пузырьковая диаграмма",
    "ChartTypeRadarLabel": "Лепестковая диаграмма",
    "ChartTypeKpiLabel": "Плитка KPI",
    "ChartTypeHistogramLabel": "Гистограмма распределения",
    "ChartTypeWaterfallLabel": "Каскадная диаграмма",
    "ChartTypeBoxplotLabel": "Ящик с усами",
    "ChartTypeViolinLabel": "Скрипичная диаграмма",
    "ChartTypeBeforeAfterLabel": "Диаграмма «до и после»",
    "ChartTypeTreemapLabel": "Древовидная карта",
    "ChartTypeHeatmapLabel": "Тепловая карта",
    "HistogramBinsFieldLabel": "Интервалы гистограммы",
    "AppearancePageDescription": "Цвета, подписи и оси",
    "AdvancedPageDescription": "Аналитика, опорные линии, интерактивность и обновление данных",
    "LegendTopLabel": "Сверху",
    "LegendBottomLabel": "Снизу",
    "LegendLeftLabel": "Слева",
    "LegendRightLabel": "Справа",
    "ColorsGroupName": "Цвета",
    "ColorPaletteFieldLabel": "Цветовая палитра",
    "PaletteOfficeLabel": "Office (по умолчанию)",
    "PaletteVibrantLabel": "Яркая",
    "PalettePastelLabel": "Пастельная",
    "PaletteMonochromeLabel": "Монохромная",
    "PaletteTrafficLightLabel": "Светофор",
    "PaletteWarmLabel": "Тёплая",
    "PaletteCoolLabel": "Холодная",
    "DataLabelsGroupName": "Подписи данных и форматирование",
    "ShowDataLabelsFieldLabel": "Показать подписи данных",
    "ValuePrefixFieldLabel": "Префикс значения",
    "ValuePrefixPlaceholder": "например, $",
    "ValueSuffixFieldLabel": "Суффикс значения",
    "ValueSuffixPlaceholder": "например, %",
    "ValueDecimalsFieldLabel": "Знаков после запятой",
    "AbbreviateNumbersFieldLabel": "Сокращать числа (K/M)",
    "AxesGridGroupName": "Оси и сетка",
    "YAxisMinFieldLabel": "Минимум оси Y",
    "YAxisMaxFieldLabel": "Максимум оси Y",
    "AutoPlaceholder": "Авто",
    "NumericValidationError": "Введите число или оставьте поле пустым для автоматического значения.",
    "ColorValidationError": "Введите шестнадцатеричный код цвета (например, #d13438) или оставьте поле пустым для значения по умолчанию.",
    "LogScaleFieldLabel": "Логарифмическая шкала (Y)",
    "LogScaleXFieldLabel": "Логарифмическая шкала (X)",
    "StepLineFieldLabel": "Ступенчатая интерполяция",
    "ShowGridLinesFieldLabel": "Показать линии сетки",
    "XLabelRotationFieldLabel": "Поворот подписей X (градусы)",
    "XAxisTypeFieldLabel": "Тип оси X",
    "XAxisTypeAuto": "Определять автоматически",
    "XAxisTypeCategory": "Категория",
    "XAxisTypeTime": "Время (даты)",
    "AnalyticsGroupName": "Аналитика",
    "TrendlineFieldLabel": "Линия тренда",
    "TrendlineNone": "Нет",
    "TrendlineLinear": "Линейная",
    "TrendlineMovingAverage": "Скользящее среднее",
    "TrendWindowFieldLabel": "Окно скользящего среднего",
    "TrendSuffix": " (тренд)",
    "ForecastPeriodsFieldLabel": "Периоды прогноза (линейная линия тренда)",
    "ReferenceLineGroupName": "Опорная линия",
    "ReferenceLineTypeFieldLabel": "Опорная линия",
    "ReferenceLineValueFieldLabel": "Фиксированное значение",
    "ReferenceLineColorFieldLabel": "Цвет линии (hex)",
    "RefLineFixed": "Фиксированное значение",
    "RefLineMean": "Среднее",
    "RefLineMedian": "Медиана",
    "DualAxisGroupName": "Двойная ось Y",
    "Y2ColumnsFieldLabel": "Ряды правой оси (имена столбцов через запятую)",
    "Y2ColumnsPlaceholder": "например, Маржа,Рост",
    "Y2AxisLabelFieldLabel": "Подпись правой оси",
    "LogScaleY2FieldLabel": "Логарифмическая шкала (правая ось)",
    "ErrorBarsGroupName": "Планки погрешностей",
    "ErrorBarTypeFieldLabel": "Тип планки погрешностей",
    "ErrorBarTypeNone": "Нет",
    "ErrorBarTypeCustom": "Пользовательский столбец (±)",
    "ErrorBarTypeSd": "Стандартное отклонение (вычисляется)",
    "ErrorBarTypeSem": "Стандартная ошибка среднего (вычисляется)",
    "ErrorBarColumnFieldLabel": "Столбец значений погрешности",
    "SignificanceGroupName": "Скобки значимости",
    "SignificancePairsFieldLabel": "Пары скобок",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Одна скобка в строке: столбец1,столбец2,подпись  — например, ГруппаA,ГруппаB,*  или  ГруппаA,ГруппаB,p<0.05  (также принимается массив JSON)",
    "BeforeAfterColumnsError": "Для диаграммы «до и после» требуется ровно 2 столбца Y — один для значений «до» и один для значений «после».",
    "InteractivityGroupName": "Интерактивность",
    "ShowViewerFiltersFieldLabel": "Показывать фильтры зрителям",
    "DetailsOnDemandFieldLabel": "Показывать строки данных при щелчке",
    "ShowDataPointsFieldLabel": "Накладывать точки данных на столбцы",
    "ShowBubbleSizeLegendFieldLabel": "Показать легенду размеров пузырьков",
    "ViewerFilterLabel": "Фильтр:",
    "ViewerFilterColumnAria": "Столбец фильтра",
    "ViewerFilterValueAria": "Значение фильтра",
    "DrillAllLabel": "Все",
    "DetailsChipLabel": "Сведения: {0} (строк: {1})",
    "KpiSubLabel": "{0} • {1} • строк: {2}",
    "ConditionalGroupName": "Условное форматирование",
    "ThresholdValueFieldLabel": "Пороговое значение",
    "ThresholdValuePlaceholder": "Выкл.",
    "ThresholdDirectionFieldLabel": "Выделять значения",
    "ThresholdBelow": "Ниже порога",
    "ThresholdAbove": "Выше порога",
    "ThresholdColorFieldLabel": "Цвет выделения (hex)",
    "DataRefreshGroupName": "Данные и обновление",
    "RefreshIntervalFieldLabel": "Интервал автообновления (минуты, 0 = выкл.)",
    "CacheMinutesFieldLabel": "Кэшировать данные (минуты, 0 = выкл.)",
    "DynamicDataCategoryLabel": "Выбранная категория",
    "DynamicDataValueLabel": "Выбранное значение",
    "DynamicDataSeriesLabel": "Выбранный ряд",
    "DataSourceGroupName": "Источник данных",
    "HideDataSourceButton": "▲ Скрыть источник данных",
    "ConfigureDataSourceButton": "▼ Настроить источник данных",
    "RowsLoadedBadge": "✓ Загружено строк: {0}",
    "ReadModeLoadError": "Не удалось загрузить данные: {0}. Перейдите в режим редактирования, чтобы перенастроить источник данных.",
    "RefreshDataButton": "↻ Обновить данные",
    "RefreshingLabel": "Обновление…",
    "RefreshDataTitle": "Повторно загрузить данные из настроенного источника",
    "NoDataMessage": "Данные ещё не загружены. Настройте источник данных выше и нажмите «Загрузить данные».",
    "SelectMappingsMessage": "Данные загружены (строк: {0}). Выберите сопоставление столбцов выше, чтобы отобразить диаграмму.",
    "ChartRenderErrorLabel": "Ошибка отрисовки диаграммы: {0}",
    "UnsupportedChartTypeLabel": "Неподдерживаемый тип диаграммы: {0}",
    "ChartAriaLabel": "Диаграмма визуализации данных",
    "FilterOperatorLabel": "Оператор",
    "FilterValueLabel": "Значение",
    "FilterOpContains": "содержит",
    "FilterOpEquals": "равно",
    "FilterOpNotEquals": "не равно",
    "FilterOpGt": "больше",
    "FilterOpLt": "меньше",
    "FilterOpBetween": "между (мин..макс)",
    "FilterOpIsEmpty": "пусто",
    "FilterOpNotEmpty": "не пусто",
    "AddFilterButton": "+ Добавить фильтр",
    "RemoveFilterButton": "Удалить",
    "SelectValuePlaceholder": "Выберите значение…",
    "ViewerFilterOperatorAria": "Оператор фильтра",
    "PaletteColorblindLabel": "Для людей с дальтонизмом",
    "WaterfallGroupName": "Каскад",
    "WaterfallShowTotalFieldLabel": "Показать столбец итога",
    "WaterfallPositiveColorFieldLabel": "Цвет роста",
    "WaterfallNegativeColorFieldLabel": "Цвет падения",
    "WaterfallTotalColorFieldLabel": "Цвет итога",
    "WaterfallTotalLabel": "Итого",
    "ExternalFilterGroupName": "Фильтр из другой веб-части",
    "ExternalFilterFieldLabel": "Источник значения фильтра",
    "ExternalFilterColumnFieldLabel": "Столбец для фильтрации",
    "ExternalFilterColumnPlaceholder": "По умолчанию — столбец оси X",
    "ViewAsTableButton": "Показать как таблицу",
    "HideTableButton": "Скрыть таблицу",
    "ChartKeyboardHint": "Используйте клавиши со стрелками для перехода между точками данных и Enter для выбора точки.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Префикс значения Y2",
    "Y2ValueSuffixFieldLabel": "Суффикс значения Y2",
    "AnnotationsGroupName": "Заметки",
    "AnnotationsFieldLabel": "Заметки",
    "AnnotationsPlaceholder": "Янв, Запуск продукта",
    "AnnotationsHelp": "По одной в строке: значение по оси X, запятая, затем текст заметки. В этой точке оси X рисуется вертикальная метка.",
    "BeforeLabel": "До",
    "AfterLabel": "После",
    "RowLabel": "Строка {0}",
    "PointsSuffix": " (точки)",
    "ExportSheetName": "Данные",
    "RefreshFailedNote": "Не удалось выполнить последнее обновление: {0}. Отображаются ранее загруженные данные.",
    "TruncatedDataNote": "Показаны только первые строки ({0}); в источнике больше данных.",
    "ScatterNumericWarning": "Для точечных и пузырьковых диаграмм нужны числовые значения. В столбце \"{0}\" нет числовых данных — выберите другой столбец в сопоставлении выше.",
    "TimeAxisUnparseableWarning": "В столбце оси X \"{0}\" нет значений, которые можно распознать как даты. Измените тип оси X на \"Категория\" или сопоставьте столбец с датами.",
    "DataSourceSectionHeader": "Источник данных",
    "SourceUploadLabel": "Отправить файл",
    "SourceSharePointListLabel": "Список SharePoint",
    "SourceSharePointFileLabel": "Файл SharePoint",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Путь API Graph",
    "GraphPathHelp": "Относительный путь Microsoft Graph, например /me/memberOf или /reports/getTeamsUserActivityUserCounts(period='D7'). Для этого источника требуются разрешения Graph, утверждённые администратором; все остальные источники данных работают без них.",
    "SheetNameLabel": "Лист Excel",
    "DelimiterLabel": "Разделитель",
    "DelimiterAutoDetect": "Определять автоматически",
    "DelimiterComma": "Запятая (,)",
    "DelimiterTab": "Табуляция",
    "DelimiterSemicolon": "Точка с запятой (;)",
    "DelimiterPipe": "Вертикальная черта (|)",
    "SiteUrlLabel": "URL сайта (необязательно)",
    "SiteUrlHelp": "Оставьте пустым, чтобы использовать текущий сайт.",
    "ListNameLabel": "Название списка",
    "LoadingListsLabel": "— Загрузка списков…",
    "SelectListPlaceholder": "— Выберите список —",
    "EnterListNamePlaceholder": "Введите название списка",
    "ListNameExamplePlaceholder": "например, Данные о продажах",
    "ListDiscoveryError": "Не удалось загрузить списки — введите название вручную ниже.",
    "FileUrlLabel": "URL файла (CSV/TSV/Excel в SharePoint)",
    "FileUrlHelp": "Полный URL файла в библиотеке документов.",
    "ApiUrlLabel": "URL API",
    "DataPathLabel": "Путь к данным (необязательно)",
    "DataPathHelp": "Путь через точки к массиву в ответе JSON. Оставьте пустым, если корневой элемент — массив. Для REST API SharePoint используйте \"value\".",
    "UploadHelp": "Отправьте файл CSV, TSV или Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— строк: {0}",
    "ChangeFileButton": "Изменить файл…",
    "ClearButton": "Очистить",
    "ChooseFileButton": "Выбрать файл…",
    "LoadDataButton": "Загрузить данные",
    "LoadingLabel": "Загрузка…",
    "ErrorSelectListName": "Выберите или введите название списка.",
    "ErrorEnterFileUrl": "Введите URL файла.",
    "ErrorEnterUrl": "Введите URL.",
    "ErrorLoadList": "Не удалось загрузить список SharePoint: {0}",
    "ErrorLoadFile": "Не удалось загрузить файл: {0}",
    "ErrorFetchData": "Не удалось получить данные: {0}",
    "ErrorDataPathNotFound": "Путь к данным \"{0}\" не найден в ответе.",
    "ErrorUrlReturnedHtml": "Этот URL вернул веб-страницу, а не файл. Используйте прямой путь для скачивания файла, а не URL общего доступа «Копировать ссылку».",
    "ErrorRequestTimedOut": "Время ожидания запроса истекло. Проверьте URL и подключение к сети.",
    "ErrorNonJsonResponse": "Не удалось разобрать ответ как JSON.",
    "ErrorUnsupportedFileType": "Неподдерживаемый тип файла. Отправьте файл .csv, .tsv, .xlsx или .xls.",
    "ErrorReadFile": "Не удалось прочитать файл",
    "ErrorParseFile": "Не удалось разобрать файл",
    "LoadedRowsColumns": "Загружено строк: {0}, столбцов: {1}.",
    "LoadedRowsColumnsPersist": "Загружено строк: {0}, столбцов: {1}. Данные сохранятся при выходе со страницы.",
    "SizeWarning": "Набор данных ({0}KB) превышает лимит сохранения в 200KB. Диаграмма покажет данные в этом сеансе, но они будут очищены при перезагрузке страницы. Для больших файлов загрузите их в библиотеку SharePoint и используйте источник «Файл SharePoint».",
    "ListTruncatedWarning": "В этом списке элементов: {0} или больше; загружены только первые {0}.",
    "GraphTruncatedWarning": "Результат Microsoft Graph содержит больше страниц, чем удалось загрузить; получены только первые страницы ({0}).",
    "CsvParseWarning": "Не удалось разобрать строк: {0}; они пропущены.",
    "ColumnMappingSectionHeader": "Сопоставление столбцов",
    "CategoryColumnLabel": "Столбец категорий (X / подписи)",
    "LabelColumnLabel": "Столбец подписей",
    "XAxisColumnLabel": "Столбец оси X",
    "ValueColumnLabel": "Столбец значений",
    "YAxisColumnLabel": "Столбец оси Y",
    "YAxisColumnsLabel": "Столбцы оси Y",
    "YAxisColumnsHelp": "(выберите один или несколько; щёлкните образец, чтобы задать цвет)",
    "SelectColumnPlaceholder": "— Выберите столбец —",
    "ScatterLabelColumnLabel": "Подпись точки",
    "SizeColumnLabel":"Столбец размера / радиуса",
    "NoSizeColumnOption": "— Нет (фиксированный размер) —",
    "SeriesColorTitle": "Цвет для {0}",
    "SeriesTypeTitle": "Тип диаграммы для {0}",
    "SeriesTypeDefault": "По умолчанию",
    "SeriesTypeBar": "Столбцы",
    "SeriesTypeLine": "Линия",
    "HistogramColumnLabel": "Столбец для разбиения (числовой)",
    "TreemapGroupLabel": "Столбец групп / подписей",
    "HeatmapColumnLabel": "Категория столбцов (X)",
    "HeatmapRowLabel": "Категория строк (Y)",
    "AdvancedOptionsClosed": "▼ Дополнительные параметры",
    "AdvancedOptionsOpen": "▲ Дополнительные параметры",
    "ColorByLabel": "Цвет по столбцу",
    "ColorByHelp": "Окрашивать точки по категории, а не по ряду.",
    "TooltipColumnsLabel": "Столбцы подсказки",
    "TooltipColumnsHelp": "(дополнительные столбцы, отображаемые при наведении на точку данных)",
    "DrillLevelLabel": "Уровень детализации {0}",
    "DrillDownHelp": "Задайте иерархию столбцов, чтобы включить детализацию по щелчку (например, Регион → Страна → Город). Значения агрегируются на каждом уровне.",
    "BookmarksLabel": "Закладки",
    "BookmarkNameLabel": "Название закладки",
    "BookmarkNamePlaceholder": "например, Топ-10 по регионам",
    "SaveBookmarkButton": "Сохранить текущее представление",
    "ApplyBookmarkButton": "Применить",
    "DeleteBookmarkButton": "Удалить",
    "ApplyBookmarkPlaceholder": "— Применить закладку —",
    "DataControlsSectionHeader": "Управление данными",
    "SortByColumnLabel": "Сортировать по столбцу",
    "NoneOption": "— Нет —",
    "SortDirectionLabel": "Направление сортировки",
    "AscendingOption": "По возрастанию",
    "DescendingOption": "По убыванию",
    "RowLimitLabel": "Лимит строк (0 = все)",
    "FilterColumnLabel": "Столбец фильтра",
    "FilterContainsLabel": "Фильтр: содержит",
    "FilterValuePlaceholder": "Значение фильтра…",
    "GroupByLabel": "Группировать по столбцу",
    "AggregationLabel": "Агрегирование",
    "GroupByHelp": "Числовые столбцы агрегируются по группам. Вариант «Количество» добавляет столбец \"Количество\".",
    "AggNone": "Нет",
    "AggSum": "Сумма",
    "AggAvg": "Среднее",
    "AggCount": "Количество",
    "AggMin": "Мин.",
    "AggMax": "Макс.",
    "DataTableHeader": "Таблица данных (строк: {0})",
    "PrevPageButton": "← Назад",
    "NextPageButton": "Вперёд →",
    "PageOfLabel": "Страница {0} из {1}",
    "ExportLabel": "Экспорт:",
    "ExportPngTitle": "Скачать диаграмму как изображение PNG",
    "ExportJpegTitle": "Скачать диаграмму как изображение JPEG",
    "ExportCsvTitle": "Скачать данные как CSV",
    "ExportExcelTitle": "Скачать данные как книгу Excel"
  }
});
