define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurera din datavisualisering",
    "HeaderGroupName": "Rubrik",
    "WebPartHeaderFieldLabel": "Rubriktext",
    "WebPartHeaderPlaceholder": "t.ex. Försäljningsöversikt",
    "ShowWebPartHeaderFieldLabel": "Visa rubrik",
    "ChartSettingsGroupName": "Diagraminställningar",
    "ChartTitleFieldLabel": "Diagramrubrik",
    "ChartTypeFieldLabel": "Diagramtyp",
    "LegendPositionFieldLabel": "Teckenförklaringens position",
    "ChartHeightFieldLabel": "Diagramhöjd (px)",
    "ShowLegendFieldLabel": "Visa teckenförklaring",
    "StackedFieldLabel": "Staplat (stapel/linje)",
    "ShowDataTableFieldLabel": "Visa datatabell",
    "ShowExportBarFieldLabel": "Visa exportfält",
    "XAxisLabelFieldLabel": "Etikett för X-axel (valfritt)",
    "XAxisPlaceholder": "Använder som standard den valda kolumnen",
    "YAxisLabelFieldLabel": "Etikett för Y-axel (valfritt)",
    "YAxisPlaceholder": "Använder som standard de valda kolumnerna",
    "ChartGroupStandard": "Standarddiagram",
    "ChartGroupSpecialized": "Specialiserade diagram",
    "ChartTypeBarLabel": "Stapeldiagram (vertikalt)",
    "ChartTypeHorizontalBarLabel": "Liggande stapeldiagram (horisontellt)",
    "ChartTypeLineLabel": "Linjediagram",
    "ChartTypeAreaLabel": "Områdesdiagram",
    "ChartTypeScatterLabel": "Punktdiagram",
    "ChartTypePieLabel": "Cirkeldiagram",
    "ChartTypeDoughnutLabel": "Ringdiagram",
    "ChartTypeBubbleLabel": "Bubbeldiagram",
    "ChartTypeRadarLabel": "Radardiagram",
    "ChartTypeKpiLabel": "KPI-ruta",
    "ChartTypeHistogramLabel": "Histogram",
    "ChartTypeWaterfallLabel": "Vattenfallsdiagram",
    "ChartTypeBoxplotLabel": "Lådagram",
    "ChartTypeViolinLabel": "Violindiagram",
    "ChartTypeBeforeAfterLabel": "Före-efter-diagram",
    "ChartTypeTreemapLabel": "Trädkarta",
    "ChartTypeHeatmapLabel": "Värmekarta",
    "HistogramBinsFieldLabel": "Histogramintervall",
    "AppearancePageDescription": "Färger, etiketter och axlar",
    "AdvancedPageDescription": "Analys, referenslinjer, interaktivitet och datauppdatering",
    "LegendTopLabel": "Överst",
    "LegendBottomLabel": "Nederst",
    "LegendLeftLabel": "Vänster",
    "LegendRightLabel": "Höger",
    "ColorsGroupName": "Färger",
    "ColorPaletteFieldLabel": "Färgpalett",
    "PaletteOfficeLabel": "Office (standard)",
    "PaletteVibrantLabel": "Livfull",
    "PalettePastelLabel": "Pastell",
    "PaletteMonochromeLabel": "Monokrom",
    "PaletteTrafficLightLabel": "Trafikljus",
    "PaletteWarmLabel": "Varm",
    "PaletteCoolLabel": "Sval",
    "DataLabelsGroupName": "Dataetiketter och formatering",
    "ShowDataLabelsFieldLabel": "Visa dataetiketter",
    "ValuePrefixFieldLabel": "Värdeprefix",
    "ValuePrefixPlaceholder": "t.ex. kr",
    "ValueSuffixFieldLabel": "Värdesuffix",
    "ValueSuffixPlaceholder": "t.ex. %",
    "ValueDecimalsFieldLabel": "Antal decimaler",
    "AbbreviateNumbersFieldLabel": "Förkorta tal (K/M)",
    "AxesGridGroupName": "Axlar och rutnät",
    "YAxisMinFieldLabel": "Minimum för Y-axel",
    "YAxisMaxFieldLabel": "Maximum för Y-axel",
    "AutoPlaceholder": "Automatiskt",
    "NumericValidationError": "Ange ett tal, eller lämna tomt för automatiskt.",
    "ColorValidationError": "Ange en hexadecimal färg (t.ex. #d13438), eller lämna tomt för standard.",
    "LogScaleFieldLabel": "Logaritmisk skala (Y)",
    "LogScaleXFieldLabel": "Logaritmisk skala (X)",
    "StepLineFieldLabel": "Stegvis interpolering",
    "ShowGridLinesFieldLabel": "Visa rutnätslinjer",
    "XLabelRotationFieldLabel": "Rotation av X-etikett (grader)",
    "XAxisTypeFieldLabel": "Typ av X-axel",
    "XAxisTypeAuto": "Identifiera automatiskt",
    "XAxisTypeCategory": "Kategori",
    "XAxisTypeTime": "Tid (datum)",
    "AnalyticsGroupName": "Analys",
    "TrendlineFieldLabel": "Trendlinje",
    "TrendlineNone": "Ingen",
    "TrendlineLinear": "Linjär",
    "TrendlineMovingAverage": "Glidande medelvärde",
    "TrendWindowFieldLabel": "Fönster för glidande medelvärde",
    "TrendSuffix": " (trend)",
    "ForecastPeriodsFieldLabel": "Prognosperioder (linjär trendlinje)",
    "ReferenceLineGroupName": "Referenslinje",
    "ReferenceLineTypeFieldLabel": "Referenslinje",
    "ReferenceLineValueFieldLabel": "Fast värde",
    "ReferenceLineColorFieldLabel": "Linjefärg (hex)",
    "RefLineFixed": "Fast värde",
    "RefLineMean": "Medelvärde",
    "RefLineMedian": "Median",
    "DualAxisGroupName": "Dubbel Y-axel",
    "Y2ColumnsFieldLabel": "Serier på högeraxeln (kolumnnamn avgränsade med kommatecken)",
    "Y2ColumnsPlaceholder": "t.ex. Marginal,Tillväxt",
    "Y2AxisLabelFieldLabel": "Etikett för högeraxel",
    "LogScaleY2FieldLabel": "Logaritmisk skala (högeraxel)",
    "ErrorBarsGroupName": "Felstaplar",
    "ErrorBarTypeFieldLabel": "Typ av felstapel",
    "ErrorBarTypeNone": "Ingen",
    "ErrorBarTypeCustom": "Anpassad kolumn (±)",
    "ErrorBarTypeSd": "Standardavvikelse (beräknad)",
    "ErrorBarTypeSem": "Standardfel för medelvärde (beräknat)",
    "ErrorBarColumnFieldLabel": "Kolumn för felvärde",
    "SignificanceGroupName": "Signifikansparenteser",
    "SignificancePairsFieldLabel": "Parenteser",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "En parentes per rad: kol1,kol2,etikett  — t.ex. GruppA,GruppB,*  eller  GruppA,GruppB,p<0.05  (JSON-matris accepteras också)",
    "BeforeAfterColumnsError": "Före-efter-diagram kräver exakt 2 Y-kolumner — en för värden före och en för värden efter.",
    "InteractivityGroupName": "Interaktivitet",
    "ShowViewerFiltersFieldLabel": "Visa filter för besökare",
    "DetailsOnDemandFieldLabel": "Visa datarader vid klick",
    "ShowDataPointsFieldLabel": "Lägg datapunkter ovanpå staplar",
    "ShowBubbleSizeLegendFieldLabel": "Visa teckenförklaring för bubbelstorlek",
    "ViewerFilterLabel": "Filter:",
    "ViewerFilterColumnAria": "Filterkolumn",
    "ViewerFilterValueAria": "Filtervärde",
    "DrillAllLabel": "Alla",
    "DetailsChipLabel": "Information: {0} ({1} rader)",
    "KpiSubLabel": "{0} • {1} • {2} rader",
    "ConditionalGroupName": "Villkorsstyrd formatering",
    "ThresholdValueFieldLabel": "Tröskelvärde",
    "ThresholdValuePlaceholder": "Av",
    "ThresholdDirectionFieldLabel": "Markera värden",
    "ThresholdBelow": "Under tröskelvärdet",
    "ThresholdAbove": "Över tröskelvärdet",
    "ThresholdColorFieldLabel": "Markeringsfärg (hex)",
    "DataRefreshGroupName": "Data och uppdatering",
    "RefreshIntervalFieldLabel": "Intervall för automatisk uppdatering (minuter, 0 = av)",
    "CacheMinutesFieldLabel": "Cachelagra data (minuter, 0 = av)",
    "DynamicDataCategoryLabel": "Vald kategori",
    "DynamicDataValueLabel": "Valt värde",
    "DynamicDataSeriesLabel": "Vald serie",
    "DataSourceGroupName": "Datakälla",
    "HideDataSourceButton": "▲ Dölj datakälla",
    "ConfigureDataSourceButton": "▼ Konfigurera datakälla",
    "RowsLoadedBadge": "✓ {0} rader lästes in",
    "ReadModeLoadError": "Det gick inte att läsa in data: {0}. Växla till redigeringsläge för att konfigurera om datakällan.",
    "RefreshDataButton": "↻ Uppdatera data",
    "RefreshingLabel": "Uppdaterar…",
    "RefreshDataTitle": "Läs in data från den konfigurerade källan igen",
    "NoDataMessage": "Ingen data har lästs in ännu. Konfigurera datakällan ovan och klicka på Läs in data.",
    "SelectMappingsMessage": "Data inläst ({0} rader). Välj kolumnmappningar ovan för att visa diagrammet.",
    "ChartRenderErrorLabel": "Fel vid återgivning av diagram: {0}",
    "UnsupportedChartTypeLabel": "Diagramtypen stöds inte: {0}",
    "ChartAriaLabel": "Diagram för datavisualisering",
    "FilterOperatorLabel": "Operator",
    "FilterValueLabel": "Värde",
    "FilterOpContains": "innehåller",
    "FilterOpEquals": "är lika med",
    "FilterOpNotEquals": "är inte lika med",
    "FilterOpGt": "större än",
    "FilterOpLt": "mindre än",
    "FilterOpBetween": "mellan (lägsta..högsta)",
    "FilterOpIsEmpty": "är tomt",
    "FilterOpNotEmpty": "är inte tomt",
    "AddFilterButton": "+ Lägg till filter",
    "RemoveFilterButton": "Ta bort",
    "SelectValuePlaceholder": "Välj värde…",
    "ViewerFilterOperatorAria": "Filteroperator",
    "PaletteColorblindLabel": "Färgblindsäker",
    "WaterfallGroupName": "Vattenfall",
    "WaterfallShowTotalFieldLabel": "Visa totalstapel",
    "WaterfallPositiveColorFieldLabel": "Färg för ökning",
    "WaterfallNegativeColorFieldLabel": "Färg för minskning",
    "WaterfallTotalColorFieldLabel": "Färg för total",
    "WaterfallTotalLabel": "Totalt",
    "ExternalFilterGroupName": "Filtrera från en annan webbdel",
    "ExternalFilterFieldLabel": "Källa för filtervärde",
    "ExternalFilterColumnFieldLabel": "Kolumn att filtrera",
    "ExternalFilterColumnPlaceholder": "Använder som standard X-axelns kolumn",
    "ViewAsTableButton": "Visa som tabell",
    "HideTableButton": "Dölj tabell",
    "ChartKeyboardHint": "Använd piltangenterna för att flytta mellan datapunkter och Retur för att välja en.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Prefix för Y2-värde",
    "Y2ValueSuffixFieldLabel": "Suffix för Y2-värde",
    "AnnotationsGroupName": "Anteckningar",
    "AnnotationsFieldLabel": "Anteckningar",
    "AnnotationsPlaceholder": "Jan, Produktlansering",
    "AnnotationsHelp": "En per rad: värdet på X-axeln, ett kommatecken och sedan anteckningstexten. En lodrät markör ritas vid det X-värdet.",
    "BeforeLabel": "Före",
    "AfterLabel": "Efter",
    "RowLabel": "Rad {0}",
    "PointsSuffix": " (punkter)",
    "ExportSheetName": "Data",
    "RefreshFailedNote": "Senaste uppdateringen misslyckades: {0}. Visar tidigare inlästa data.",
    "TruncatedDataNote": "Endast de första {0} raderna visas; källan innehåller mer data.",
    "ScatterNumericWarning": "Punkt- och bubbeldiagram kräver numeriska värden. Kolumnen \"{0}\" saknar numeriska data — välj en annan kolumn i mappningen ovan.",
    "TimeAxisUnparseableWarning": "X-axelns kolumn \"{0}\" har inga värden som kan tolkas som datum. Ändra typ av X-axel till \"Kategori\" eller mappa en datumkolumn.",
    "DataSourceSectionHeader": "Datakälla",
    "SourceUploadLabel": "Ladda upp fil",
    "SourceSharePointListLabel": "SharePoint-lista",
    "SourceSharePointFileLabel": "SharePoint-fil",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API-sökväg",
    "GraphPathHelp": "Relativ Microsoft Graph-sökväg, t.ex. /me/memberOf eller /reports/getTeamsUserActivityUserCounts(period='D7'). Den här källan kräver Graph-behörigheter som godkänts av en administratör — alla andra datakällor fungerar utan dem.",
    "SheetNameLabel": "Excel-blad",
    "DelimiterLabel": "Avgränsare",
    "DelimiterAutoDetect": "Identifiera automatiskt",
    "DelimiterComma": "Kommatecken (,)",
    "DelimiterTab": "Tabb",
    "DelimiterSemicolon": "Semikolon (;)",
    "DelimiterPipe": "Lodstreck (|)",
    "SiteUrlLabel": "Webbplatsens URL (valfritt)",
    "SiteUrlHelp": "Lämna tomt om du vill använda den aktuella webbplatsen.",
    "ListNameLabel": "Listnamn",
    "LoadingListsLabel": "— Läser in listor…",
    "SelectListPlaceholder": "— Välj en lista —",
    "EnterListNamePlaceholder": "Ange listnamn",
    "ListNameExamplePlaceholder": "t.ex. Försäljningsdata",
    "ListDiscoveryError": "Det gick inte att läsa in listor — ange namnet manuellt nedan.",
    "FileUrlLabel": "Filens URL (CSV/TSV/Excel i SharePoint)",
    "FileUrlHelp": "Fullständig URL till en fil i ett dokumentbibliotek.",
    "ApiUrlLabel": "API-URL",
    "DataPathLabel": "Datasökväg (valfritt)",
    "DataPathHelp": "Punktavgränsad sökväg till matrisen i JSON-svaret. Lämna tomt om roten är en matris. Använd \"value\" för SharePoint REST API.",
    "UploadHelp": "Ladda upp en CSV-, TSV- eller Excel-fil (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} rader",
    "ChangeFileButton": "Byt fil…",
    "ClearButton": "Rensa",
    "ChooseFileButton": "Välj fil…",
    "LoadDataButton": "Läs in data",
    "LoadingLabel": "Läser in…",
    "ErrorSelectListName": "Välj eller ange ett listnamn.",
    "ErrorEnterFileUrl": "Ange en fil-URL.",
    "ErrorEnterUrl": "Ange en URL.",
    "ErrorLoadList": "Det gick inte att läsa in SharePoint-listan: {0}",
    "ErrorLoadFile": "Det gick inte att läsa in filen: {0}",
    "ErrorFetchData": "Det gick inte att hämta data: {0}",
    "ErrorDataPathNotFound": "Datasökvägen \"{0}\" hittades inte i svaret.",
    "ErrorUrlReturnedHtml": "Den här URL:en returnerade en webbsida, inte en fil. Använd den direkta nedladdningssökvägen till filen, inte en delnings-URL av typen \"Kopiera länk\".",
    "ErrorRequestTimedOut": "Begäran översteg tidsgränsen. Kontrollera URL:en och din nätverksanslutning.",
    "ErrorNonJsonResponse": "Det gick inte att tolka svaret som JSON.",
    "ErrorUnsupportedFileType": "Filtypen stöds inte. Ladda upp en .csv-, .tsv-, .xlsx- eller .xls-fil.",
    "ErrorReadFile": "Det gick inte att läsa filen",
    "ErrorParseFile": "Det gick inte att tolka filen",
    "LoadedRowsColumns": "{0} rader med {1} kolumner lästes in.",
    "LoadedRowsColumnsPersist": "{0} rader med {1} kolumner lästes in. Data sparas när du lämnar sidan.",
    "SizeWarning": "Datamängden ({0}KB) överskrider gränsen på 200KB för bevarande. Diagrammet visar data under den här sessionen men rensas när sidan läses in på nytt. För stora filer bör du ladda upp dem till ett SharePoint-bibliotek och använda källan SharePoint-fil.",
    "ListTruncatedWarning": "Den här listan har {0} objekt eller fler; endast de första {0} lästes in.",
    "GraphTruncatedWarning": "Det här Microsoft Graph-resultatet har fler sidor än vad som kunde läsas in; endast de första {0} sidorna hämtades.",
    "CsvParseWarning": "{0} rad(er) kunde inte tolkas och hoppades över.",
    "ColumnMappingSectionHeader": "Kolumnmappning",
    "CategoryColumnLabel": "Kategorikolumn (X / etiketter)",
    "LabelColumnLabel": "Etikettkolumn",
    "XAxisColumnLabel": "Kolumn för X-axel",
    "ValueColumnLabel": "Värdekolumn",
    "YAxisColumnLabel": "Kolumn för Y-axel",
    "YAxisColumnsLabel": "Kolumn(er) för Y-axel",
    "YAxisColumnsHelp": "(välj en eller flera; klicka på färgrutan för att ange färg)",
    "SelectColumnPlaceholder": "— Välj kolumn —",
    "ScatterLabelColumnLabel": "Punktetikett",
    "SizeColumnLabel":"Storlek-/radiekolumn",
    "NoSizeColumnOption": "— Ingen (fast storlek) —",
    "SeriesColorTitle": "Färg för {0}",
    "SeriesTypeTitle": "Diagramtyp för {0}",
    "SeriesTypeDefault": "Standard",
    "SeriesTypeBar": "Stapel",
    "SeriesTypeLine": "Linje",
    "HistogramColumnLabel": "Kolumn att gruppera (numerisk)",
    "TreemapGroupLabel": "Grupp-/etikettkolumn",
    "HeatmapColumnLabel": "Kategori för kolumn (X)",
    "HeatmapRowLabel": "Kategori för rad (Y)",
    "AdvancedOptionsClosed": "▼ Avancerade alternativ",
    "AdvancedOptionsOpen": "▲ Avancerade alternativ",
    "ColorByLabel": "Färglägg efter kolumn",
    "ColorByHelp": "Färglägg punkter efter kategori i stället för efter serie.",
    "TooltipColumnsLabel": "Kolumner i knappbeskrivning",
    "TooltipColumnsHelp": "(extra kolumner som visas när du pekar på en datapunkt)",
    "DrillLevelLabel": "Detaljnivå {0}",
    "DrillDownHelp": "Definiera en kolumnhierarki för att aktivera detaljnavigering med klick (t.ex. Region → Land → Stad). Värden aggregeras på varje nivå.",
    "BookmarksLabel": "Bokmärken",
    "BookmarkNameLabel": "Bokmärkesnamn",
    "BookmarkNamePlaceholder": "t.ex. Topp 10 per region",
    "SaveBookmarkButton": "Spara aktuell vy",
    "ApplyBookmarkButton": "Tillämpa",
    "DeleteBookmarkButton": "Ta bort",
    "ApplyBookmarkPlaceholder": "— Tillämpa ett bokmärke —",
    "DataControlsSectionHeader": "Datakontroller",
    "SortByColumnLabel": "Sortera efter kolumn",
    "NoneOption": "— Ingen —",
    "SortDirectionLabel": "Sorteringsriktning",
    "AscendingOption": "Stigande",
    "DescendingOption": "Fallande",
    "RowLimitLabel": "Radgräns (0 = alla)",
    "FilterColumnLabel": "Filterkolumn",
    "FilterContainsLabel": "Filter: innehåller",
    "FilterValuePlaceholder": "Filtervärde…",
    "GroupByLabel": "Gruppera efter kolumn",
    "AggregationLabel": "Aggregering",
    "GroupByHelp": "Numeriska kolumner aggregeras per grupp. Antal lägger till en kolumn \"Antal\".",
    "AggNone": "Ingen",
    "AggSum": "Summa",
    "AggAvg": "Medelvärde",
    "AggCount": "Antal",
    "AggMin": "Min",
    "AggMax": "Max",
    "DataTableHeader": "Datatabell ({0} rader)",
    "PrevPageButton": "← Föregående",
    "NextPageButton": "Nästa →",
    "PageOfLabel": "Sida {0} av {1}",
    "ExportLabel": "Exportera:",
    "ExportPngTitle": "Ladda ned diagrammet som PNG-bild",
    "ExportJpegTitle": "Ladda ned diagrammet som JPEG-bild",
    "ExportCsvTitle": "Ladda ned data som CSV",
    "ExportExcelTitle": "Ladda ned data som Excel-arbetsbok"
  }
});
