define([], function() {
  return {
    "PropertyPaneDescription": "กำหนดค่าการแสดงข้อมูลเป็นภาพของคุณ",
    "HeaderGroupName": "ส่วนหัว",
    "WebPartHeaderFieldLabel": "ข้อความส่วนหัว",
    "WebPartHeaderPlaceholder": "เช่น แดชบอร์ดยอดขาย",
    "ShowWebPartHeaderFieldLabel": "แสดงส่วนหัว",
    "ChartSettingsGroupName": "การตั้งค่าแผนภูมิ",
    "ChartTitleFieldLabel": "ชื่อแผนภูมิ",
    "ChartTypeFieldLabel": "ชนิดแผนภูมิ",
    "LegendPositionFieldLabel": "ตำแหน่งคำอธิบายแผนภูมิ",
    "ChartHeightFieldLabel": "ความสูงของแผนภูมิ (px)",
    "ShowLegendFieldLabel": "แสดงคำอธิบายแผนภูมิ",
    "StackedFieldLabel": "แบบซ้อน (แท่ง/เส้น)",
    "ShowDataTableFieldLabel": "แสดงตารางข้อมูล",
    "ShowExportBarFieldLabel": "แสดงแถบส่งออก",
    "XAxisLabelFieldLabel": "ป้ายชื่อแกน X (ไม่บังคับ)",
    "XAxisPlaceholder": "ค่าเริ่มต้นคือคอลัมน์ที่เลือก",
    "YAxisLabelFieldLabel": "ป้ายชื่อแกน Y (ไม่บังคับ)",
    "YAxisPlaceholder": "ค่าเริ่มต้นคือคอลัมน์ที่เลือก",
    "ChartGroupStandard": "แผนภูมิมาตรฐาน",
    "ChartGroupSpecialized": "แผนภูมิเฉพาะทาง",
    "ChartTypeBarLabel": "แผนภูมิแท่ง (แนวตั้ง)",
    "ChartTypeHorizontalBarLabel": "แผนภูมิแท่ง (แนวนอน)",
    "ChartTypeLineLabel": "แผนภูมิเส้น",
    "ChartTypeAreaLabel": "แผนภูมิพื้นที่",
    "ChartTypeScatterLabel": "แผนภูมิกระจาย",
    "ChartTypePieLabel": "แผนภูมิวงกลม",
    "ChartTypeDoughnutLabel": "แผนภูมิโดนัท",
    "ChartTypeBubbleLabel": "แผนภูมิฟอง",
    "ChartTypeRadarLabel": "แผนภูมิเรดาร์",
    "ChartTypeKpiLabel": "ไทล์ KPI",
    "ChartTypeHistogramLabel": "ฮิสโทแกรม",
    "ChartTypeWaterfallLabel": "แผนภูมิน้ำตก",
    "ChartTypeBoxplotLabel": "แผนภูมิกล่อง",
    "ChartTypeViolinLabel": "แผนภูมิไวโอลิน",
    "ChartTypeBeforeAfterLabel": "แผนภูมิก่อน-หลัง",
    "ChartTypeTreemapLabel": "แผนภูมิต้นไม้",
    "ChartTypeHeatmapLabel": "แผนที่ความร้อน",
    "HistogramBinsFieldLabel": "ช่วงของฮิสโทแกรม",
    "AppearancePageDescription": "สี ป้ายชื่อ และแกน",
    "AdvancedPageDescription": "การวิเคราะห์ เส้นอ้างอิง การโต้ตอบ และการรีเฟรชข้อมูล",
    "LegendTopLabel": "ด้านบน",
    "LegendBottomLabel": "ด้านล่าง",
    "LegendLeftLabel": "ด้านซ้าย",
    "LegendRightLabel": "ด้านขวา",
    "ColorsGroupName": "สี",
    "ColorPaletteFieldLabel": "จานสี",
    "PaletteOfficeLabel": "Office (ค่าเริ่มต้น)",
    "PaletteVibrantLabel": "สดใส",
    "PalettePastelLabel": "พาสเทล",
    "PaletteMonochromeLabel": "สีเดียว",
    "PaletteTrafficLightLabel": "สัญญาณไฟจราจร",
    "PaletteWarmLabel": "โทนอุ่น",
    "PaletteCoolLabel": "โทนเย็น",
    "DataLabelsGroupName": "ป้ายชื่อข้อมูลและการจัดรูปแบบ",
    "ShowDataLabelsFieldLabel": "แสดงป้ายชื่อข้อมูล",
    "ValuePrefixFieldLabel": "คำนำหน้าค่า",
    "ValuePrefixPlaceholder": "เช่น ฿",
    "ValueSuffixFieldLabel": "คำต่อท้ายค่า",
    "ValueSuffixPlaceholder": "เช่น %",
    "ValueDecimalsFieldLabel": "ตำแหน่งทศนิยม",
    "AbbreviateNumbersFieldLabel": "ย่อตัวเลข (K/M)",
    "AxesGridGroupName": "แกนและเส้นตาราง",
    "YAxisMinFieldLabel": "ค่าต่ำสุดของแกน Y",
    "YAxisMaxFieldLabel": "ค่าสูงสุดของแกน Y",
    "AutoPlaceholder": "อัตโนมัติ",
    "NumericValidationError": "ป้อนตัวเลข หรือเว้นว่างไว้เพื่อใช้ค่าอัตโนมัติ",
    "ColorValidationError": "ป้อนสีแบบเลขฐานสิบหก (เช่น #d13438) หรือเว้นว่างไว้เพื่อใช้ค่าเริ่มต้น",
    "LogScaleFieldLabel": "มาตราส่วนลอการิทึม (Y)",
    "LogScaleXFieldLabel": "มาตราส่วนลอการิทึม (X)",
    "StepLineFieldLabel": "การประมาณค่าแบบขั้นบันได",
    "ShowGridLinesFieldLabel": "แสดงเส้นตาราง",
    "XLabelRotationFieldLabel": "การหมุนป้ายชื่อ X (องศา)",
    "XAxisTypeFieldLabel": "ชนิดแกน X",
    "XAxisTypeAuto": "ตรวจหาอัตโนมัติ",
    "XAxisTypeCategory": "หมวดหมู่",
    "XAxisTypeTime": "เวลา (วันที่)",
    "AnalyticsGroupName": "การวิเคราะห์",
    "TrendlineFieldLabel": "เส้นแนวโน้ม",
    "TrendlineNone": "ไม่มี",
    "TrendlineLinear": "เชิงเส้น",
    "TrendlineMovingAverage": "ค่าเฉลี่ยเคลื่อนที่",
    "TrendWindowFieldLabel": "ช่วงของค่าเฉลี่ยเคลื่อนที่",
    "TrendSuffix": " (แนวโน้ม)",
    "ForecastPeriodsFieldLabel": "ช่วงเวลาพยากรณ์ (เส้นแนวโน้มเชิงเส้น)",
    "ReferenceLineGroupName": "เส้นอ้างอิง",
    "ReferenceLineTypeFieldLabel": "เส้นอ้างอิง",
    "ReferenceLineValueFieldLabel": "ค่าคงที่",
    "ReferenceLineColorFieldLabel": "สีของเส้น (hex)",
    "RefLineFixed": "ค่าคงที่",
    "RefLineMean": "ค่าเฉลี่ย",
    "RefLineMedian": "ค่ามัธยฐาน",
    "DualAxisGroupName": "แกน Y คู่",
    "Y2ColumnsFieldLabel": "ชุดข้อมูลแกนขวา (ชื่อคอลัมน์คั่นด้วยเครื่องหมายจุลภาค)",
    "Y2ColumnsPlaceholder": "เช่น Margin,Growth",
    "Y2AxisLabelFieldLabel": "ป้ายชื่อแกนขวา",
    "LogScaleY2FieldLabel": "มาตราส่วนลอการิทึม (แกนขวา)",
    "ErrorBarsGroupName": "แท่งค่าคลาดเคลื่อน",
    "ErrorBarTypeFieldLabel": "ชนิดแท่งค่าคลาดเคลื่อน",
    "ErrorBarTypeNone": "ไม่มี",
    "ErrorBarTypeCustom": "คอลัมน์ที่กำหนดเอง (±)",
    "ErrorBarTypeSd": "ส่วนเบี่ยงเบนมาตรฐาน (คำนวณ)",
    "ErrorBarTypeSem": "ความคลาดเคลื่อนมาตรฐานของค่าเฉลี่ย (คำนวณ)",
    "ErrorBarColumnFieldLabel": "คอลัมน์ค่าคลาดเคลื่อน",
    "SignificanceGroupName": "วงเล็บนัยสำคัญ",
    "SignificancePairsFieldLabel": "คู่วงเล็บ",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "หนึ่งวงเล็บต่อบรรทัด: col1,col2,ป้ายชื่อ  — เช่น GroupA,GroupB,*  หรือ  GroupA,GroupB,p<0.05  (รองรับอาร์เรย์ JSON ด้วย)",
    "BeforeAfterColumnsError": "แผนภูมิก่อน-หลังต้องใช้คอลัมน์ Y จำนวน 2 คอลัมน์พอดี — หนึ่งคอลัมน์สำหรับค่าก่อนและอีกหนึ่งคอลัมน์สำหรับค่าหลัง",
    "InteractivityGroupName": "การโต้ตอบ",
    "ShowViewerFiltersFieldLabel": "แสดงตัวกรองให้ผู้ชม",
    "DetailsOnDemandFieldLabel": "แสดงแถวข้อมูลเมื่อคลิก",
    "ShowDataPointsFieldLabel": "วางจุดข้อมูลซ้อนบนแท่ง",
    "ShowBubbleSizeLegendFieldLabel": "แสดงคำอธิบายขนาดฟอง",
    "ViewerFilterLabel": "ตัวกรอง:",
    "ViewerFilterColumnAria": "คอลัมน์ตัวกรอง",
    "ViewerFilterValueAria": "ค่าตัวกรอง",
    "DrillAllLabel": "ทั้งหมด",
    "DetailsChipLabel": "รายละเอียด: {0} ({1} แถว)",
    "KpiSubLabel": "{0} • {1} • {2} แถว",
    "ConditionalGroupName": "การจัดรูปแบบตามเงื่อนไข",
    "ThresholdValueFieldLabel": "ค่าเกณฑ์",
    "ThresholdValuePlaceholder": "ปิด",
    "ThresholdDirectionFieldLabel": "ไฮไลต์ค่า",
    "ThresholdBelow": "ต่ำกว่าเกณฑ์",
    "ThresholdAbove": "สูงกว่าเกณฑ์",
    "ThresholdColorFieldLabel": "สีไฮไลต์ (hex)",
    "DataRefreshGroupName": "ข้อมูลและการรีเฟรช",
    "RefreshIntervalFieldLabel": "ช่วงเวลารีเฟรชอัตโนมัติ (นาที, 0 = ปิด)",
    "CacheMinutesFieldLabel": "แคชข้อมูล (นาที, 0 = ปิด)",
    "DynamicDataCategoryLabel": "หมวดหมู่ที่เลือก",
    "DynamicDataValueLabel": "ค่าที่เลือก",
    "DynamicDataSeriesLabel": "ชุดข้อมูลที่เลือก",
    "DataSourceGroupName": "แหล่งข้อมูล",
    "HideDataSourceButton": "▲ ซ่อนแหล่งข้อมูล",
    "ConfigureDataSourceButton": "▼ กำหนดค่าแหล่งข้อมูล",
    "RowsLoadedBadge": "✓ โหลด {0} แถวแล้ว",
    "ReadModeLoadError": "ไม่สามารถโหลดข้อมูลได้: {0} สลับไปยังโหมดแก้ไขเพื่อกำหนดค่าแหล่งข้อมูลใหม่",
    "RefreshDataButton": "↻ รีเฟรชข้อมูล",
    "RefreshingLabel": "กำลังรีเฟรช…",
    "RefreshDataTitle": "โหลดข้อมูลจากแหล่งที่กำหนดค่าไว้ใหม่",
    "NoDataMessage": "ยังไม่ได้โหลดข้อมูล กำหนดค่าแหล่งข้อมูลด้านบนแล้วคลิก โหลดข้อมูล",
    "SelectMappingsMessage": "โหลดข้อมูลแล้ว ({0} แถว) โปรดเลือกการแมปคอลัมน์ด้านบนเพื่อแสดงแผนภูมิ",
    "ChartRenderErrorLabel": "ข้อผิดพลาดในการเรนเดอร์แผนภูมิ: {0}",
    "UnsupportedChartTypeLabel": "ไม่รองรับชนิดแผนภูมิ: {0}",
    "ChartAriaLabel": "แผนภูมิแสดงข้อมูลเป็นภาพ",
    "FilterOperatorLabel": "ตัวดำเนินการ",
    "FilterValueLabel": "ค่า",
    "FilterOpContains": "มีคำว่า",
    "FilterOpEquals": "เท่ากับ",
    "FilterOpNotEquals": "ไม่เท่ากับ",
    "FilterOpGt": "มากกว่า",
    "FilterOpLt": "น้อยกว่า",
    "FilterOpBetween": "ระหว่าง (ต่ำ..สูง)",
    "FilterOpIsEmpty": "ว่างเปล่า",
    "FilterOpNotEmpty": "ไม่ว่างเปล่า",
    "AddFilterButton": "+ เพิ่มตัวกรอง",
    "RemoveFilterButton": "ลบ",
    "SelectValuePlaceholder": "เลือกค่า…",
    "ViewerFilterOperatorAria": "ตัวดำเนินการตัวกรอง",
    "PaletteColorblindLabel": "เหมาะกับผู้ตาบอดสี",
    "WaterfallGroupName": "น้ำตก",
    "WaterfallShowTotalFieldLabel": "แสดงแท่งผลรวม",
    "WaterfallPositiveColorFieldLabel": "สีของการเพิ่มขึ้น",
    "WaterfallNegativeColorFieldLabel": "สีของการลดลง",
    "WaterfallTotalColorFieldLabel": "สีของผลรวม",
    "WaterfallTotalLabel": "ผลรวม",
    "ExternalFilterGroupName": "กรองจากเว็บพาร์ตอื่น",
    "ExternalFilterFieldLabel": "แหล่งค่าตัวกรอง",
    "ExternalFilterColumnFieldLabel": "คอลัมน์ที่จะกรอง",
    "ExternalFilterColumnPlaceholder": "ค่าเริ่มต้นคือคอลัมน์แกน X",
    "ViewAsTableButton": "ดูเป็นตาราง",
    "HideTableButton": "ซ่อนตาราง",
    "ChartKeyboardHint": "ใช้แป้นลูกศรเพื่อเลื่อนระหว่างจุดข้อมูล และกด Enter เพื่อเลือกจุดข้อมูล",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "คำนำหน้าค่า Y2",
    "Y2ValueSuffixFieldLabel": "คำต่อท้ายค่า Y2",
    "AnnotationsGroupName": "คำอธิบายประกอบ",
    "AnnotationsFieldLabel": "คำอธิบายประกอบ",
    "AnnotationsPlaceholder": "ม.ค., เปิดตัวผลิตภัณฑ์",
    "AnnotationsHelp": "หนึ่งรายการต่อบรรทัด: ค่าบนแกน X ตามด้วยเครื่องหมายจุลภาค แล้วตามด้วยข้อความหมายเหตุ ระบบจะวาดเครื่องหมายแนวตั้งที่ค่า X นั้น",
    "BeforeLabel": "ก่อน",
    "AfterLabel": "หลัง",
    "RowLabel": "แถว {0}",
    "PointsSuffix": " (จุด)",
    "ExportSheetName": "ข้อมูล",
    "RefreshFailedNote": "การรีเฟรชครั้งล่าสุดล้มเหลว: {0} กำลังแสดงข้อมูลที่โหลดไว้ก่อนหน้า",
    "TruncatedDataNote": "แสดงเฉพาะ {0} แถวแรกเท่านั้น แหล่งข้อมูลมีข้อมูลมากกว่านี้",
    "ScatterNumericWarning": "แผนภูมิกระจายและแผนภูมิฟองต้องใช้ค่าตัวเลข คอลัมน์ \"{0}\" ไม่มีข้อมูลตัวเลข — เลือกคอลัมน์อื่นในการแมปด้านบน",
    "TimeAxisUnparseableWarning": "คอลัมน์แกน X \"{0}\" ไม่มีค่าที่สามารถแยกวิเคราะห์เป็นวันที่ได้ เปลี่ยนชนิดแกน X เป็น \"หมวดหมู่\" หรือแมปคอลัมน์วันที่",
    "DataSourceSectionHeader": "แหล่งข้อมูล",
    "SourceUploadLabel": "อัปโหลดไฟล์",
    "SourceSharePointListLabel": "รายการ SharePoint",
    "SourceSharePointFileLabel": "ไฟล์ SharePoint",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "เส้นทาง Graph API",
    "GraphPathHelp": "เส้นทาง Microsoft Graph แบบสัมพัทธ์ เช่น /me/memberOf หรือ /reports/getTeamsUserActivityUserCounts(period='D7') แหล่งข้อมูลนี้ต้องใช้สิทธิ์ Graph ที่ผู้ดูแลระบบอนุมัติ — แหล่งข้อมูลอื่นทั้งหมดใช้งานได้โดยไม่ต้องมีสิทธิ์เหล่านี้",
    "SheetNameLabel": "ชีต Excel",
    "DelimiterLabel": "ตัวคั่น",
    "DelimiterAutoDetect": "ตรวจหาอัตโนมัติ",
    "DelimiterComma": "จุลภาค (,)",
    "DelimiterTab": "แท็บ",
    "DelimiterSemicolon": "อัฒภาค (;)",
    "DelimiterPipe": "ขีดตั้ง (|)",
    "SiteUrlLabel": "URL ของไซต์ (ไม่บังคับ)",
    "SiteUrlHelp": "เว้นว่างไว้เพื่อใช้ไซต์ปัจจุบัน",
    "ListNameLabel": "ชื่อรายการ",
    "LoadingListsLabel": "— กำลังโหลดรายการ…",
    "SelectListPlaceholder": "— เลือกรายการ —",
    "EnterListNamePlaceholder": "ป้อนชื่อรายการ",
    "ListNameExamplePlaceholder": "เช่น ข้อมูลยอดขาย",
    "ListDiscoveryError": "ไม่สามารถโหลดรายการได้ — ป้อนชื่อด้วยตนเองด้านล่าง",
    "FileUrlLabel": "URL ของไฟล์ (CSV/TSV/Excel ใน SharePoint)",
    "FileUrlHelp": "URL แบบเต็มของไฟล์ในคลังเอกสาร",
    "ApiUrlLabel": "URL ของ API",
    "DataPathLabel": "เส้นทางข้อมูล (ไม่บังคับ)",
    "DataPathHelp": "เส้นทางที่คั่นด้วยจุดไปยังอาร์เรย์ในการตอบกลับ JSON เว้นว่างไว้หากรากเป็นอาร์เรย์ สำหรับ SharePoint REST API ให้ใช้ \"value\"",
    "UploadHelp": "อัปโหลดไฟล์ CSV, TSV หรือ Excel (.xlsx, .xls)",
    "LoadedFileRowsLabel": "— {0} แถว",
    "ChangeFileButton": "เปลี่ยนไฟล์…",
    "ClearButton": "ล้าง",
    "ChooseFileButton": "เลือกไฟล์…",
    "LoadDataButton": "โหลดข้อมูล",
    "LoadingLabel": "กำลังโหลด…",
    "ErrorSelectListName": "โปรดเลือกหรือป้อนชื่อรายการ",
    "ErrorEnterFileUrl": "โปรดป้อน URL ของไฟล์",
    "ErrorEnterUrl": "โปรดป้อน URL",
    "ErrorLoadList": "โหลดรายการ SharePoint ไม่สำเร็จ: {0}",
    "ErrorLoadFile": "โหลดไฟล์ไม่สำเร็จ: {0}",
    "ErrorFetchData": "ดึงข้อมูลไม่สำเร็จ: {0}",
    "ErrorDataPathNotFound": "ไม่พบเส้นทางข้อมูล \"{0}\" ในการตอบกลับ",
    "ErrorUrlReturnedHtml": "URL นี้ส่งกลับหน้าเว็บ ไม่ใช่ไฟล์ ใช้เส้นทางดาวน์โหลดไฟล์โดยตรง ไม่ใช่ URL แชร์แบบ \"คัดลอกลิงก์\"",
    "ErrorRequestTimedOut": "คำขอหมดเวลา ตรวจสอบ URL และการเชื่อมต่อเครือข่ายของคุณ",
    "ErrorNonJsonResponse": "ไม่สามารถแยกวิเคราะห์การตอบกลับเป็น JSON ได้",
    "ErrorUnsupportedFileType": "ไม่รองรับชนิดไฟล์ โปรดอัปโหลดไฟล์ .csv, .tsv, .xlsx หรือ .xls",
    "ErrorReadFile": "อ่านไฟล์ไม่สำเร็จ",
    "ErrorParseFile": "แยกวิเคราะห์ไฟล์ไม่สำเร็จ",
    "LoadedRowsColumns": "โหลด {0} แถวที่มี {1} คอลัมน์แล้ว",
    "LoadedRowsColumnsPersist": "โหลด {0} แถวที่มี {1} คอลัมน์แล้ว ข้อมูลจะยังคงอยู่เมื่อคุณออกจากหน้า",
    "SizeWarning": "ชุดข้อมูล ({0}KB) เกินขีดจำกัดการคงข้อมูล 200KB แผนภูมิจะแสดงข้อมูลในเซสชันนี้ แต่จะถูกล้างเมื่อโหลดหน้าใหม่ สำหรับไฟล์ขนาดใหญ่ ให้อัปโหลดไปยังคลัง SharePoint และใช้แหล่งข้อมูลไฟล์ SharePoint",
    "ListTruncatedWarning": "รายการนี้มี {0} รายการขึ้นไป โหลดเฉพาะ {0} รายการแรกเท่านั้น",
    "GraphTruncatedWarning": "ผลลัพธ์ Microsoft Graph นี้มีหน้ามากกว่าที่โหลดได้ ดึงข้อมูลเฉพาะ {0} หน้าแรกเท่านั้น",
    "CsvParseWarning": "ไม่สามารถแยกวิเคราะห์ {0} แถวและข้ามไป",
    "ColumnMappingSectionHeader": "การแมปคอลัมน์",
    "CategoryColumnLabel": "คอลัมน์หมวดหมู่ (X / ป้ายชื่อ)",
    "LabelColumnLabel": "คอลัมน์ป้ายชื่อ",
    "XAxisColumnLabel": "คอลัมน์แกน X",
    "ValueColumnLabel": "คอลัมน์ค่า",
    "YAxisColumnLabel": "คอลัมน์แกน Y",
    "YAxisColumnsLabel": "คอลัมน์แกน Y",
    "YAxisColumnsHelp": "(เลือกหนึ่งคอลัมน์ขึ้นไป คลิกตัวอย่างสีเพื่อตั้งค่าสี)",
    "SelectColumnPlaceholder": "— เลือกคอลัมน์ —",
    "ScatterLabelColumnLabel": "ป้ายชื่อจุด",
    "SizeColumnLabel":"คอลัมน์ขนาด / รัศมี",
    "NoSizeColumnOption": "— ไม่มี (ขนาดคงที่) —",
    "SeriesColorTitle": "สีสำหรับ {0}",
    "SeriesTypeTitle": "ชนิดแผนภูมิสำหรับ {0}",
    "SeriesTypeDefault": "ค่าเริ่มต้น",
    "SeriesTypeBar": "แท่ง",
    "SeriesTypeLine": "เส้น",
    "HistogramColumnLabel": "คอลัมน์ที่จะแบ่งช่วง (ตัวเลข)",
    "TreemapGroupLabel": "คอลัมน์กลุ่ม / ป้ายชื่อ",
    "HeatmapColumnLabel": "หมวดหมู่คอลัมน์ (X)",
    "HeatmapRowLabel": "หมวดหมู่แถว (Y)",
    "AdvancedOptionsClosed": "▼ ตัวเลือกขั้นสูง",
    "AdvancedOptionsOpen": "▲ ตัวเลือกขั้นสูง",
    "ColorByLabel": "ระบายสีตามคอลัมน์",
    "ColorByHelp": "ระบายสีจุดตามหมวดหมู่แทนตามชุดข้อมูล",
    "TooltipColumnsLabel": "คอลัมน์คำแนะนำเครื่องมือ",
    "TooltipColumnsHelp": "(คอลัมน์เพิ่มเติมที่แสดงเมื่อวางเมาส์เหนือจุดข้อมูล)",
    "DrillLevelLabel": "ระดับดริลล์ {0}",
    "DrillDownHelp": "กำหนดลำดับชั้นของคอลัมน์เพื่อเปิดใช้การคลิกเพื่อดริลล์ (เช่น ภูมิภาค → ประเทศ → เมือง) ค่าจะถูกรวมที่แต่ละระดับ",
    "BookmarksLabel": "บุ๊กมาร์ก",
    "BookmarkNameLabel": "ชื่อบุ๊กมาร์ก",
    "BookmarkNamePlaceholder": "เช่น 10 อันดับแรกตามภูมิภาค",
    "SaveBookmarkButton": "บันทึกมุมมองปัจจุบัน",
    "ApplyBookmarkButton": "ใช้",
    "DeleteBookmarkButton": "ลบ",
    "ApplyBookmarkPlaceholder": "— ใช้บุ๊กมาร์ก —",
    "DataControlsSectionHeader": "ตัวควบคุมข้อมูล",
    "SortByColumnLabel": "เรียงลำดับตามคอลัมน์",
    "NoneOption": "— ไม่มี —",
    "SortDirectionLabel": "ทิศทางการเรียงลำดับ",
    "AscendingOption": "จากน้อยไปมาก",
    "DescendingOption": "จากมากไปน้อย",
    "RowLimitLabel": "จำกัดจำนวนแถว (0 = ทั้งหมด)",
    "FilterColumnLabel": "คอลัมน์ตัวกรอง",
    "FilterContainsLabel": "ตัวกรอง: มีคำว่า",
    "FilterValuePlaceholder": "ค่าตัวกรอง…",
    "GroupByLabel": "จัดกลุ่มตามคอลัมน์",
    "AggregationLabel": "การรวมค่า",
    "GroupByHelp": "คอลัมน์ตัวเลขจะถูกรวมค่าตามกลุ่ม \"จำนวน\" จะเพิ่มคอลัมน์ \"จำนวน\"",
    "AggNone": "ไม่มี",
    "AggSum": "ผลรวม",
    "AggAvg": "ค่าเฉลี่ย",
    "AggCount": "จำนวน",
    "AggMin": "ต่ำสุด",
    "AggMax": "สูงสุด",
    "DataTableHeader": "ตารางข้อมูล ({0} แถว)",
    "PrevPageButton": "← ก่อนหน้า",
    "NextPageButton": "ถัดไป →",
    "PageOfLabel": "หน้า {0} จาก {1}",
    "ExportLabel": "ส่งออก:",
    "ExportPngTitle": "ดาวน์โหลดแผนภูมิเป็นรูปภาพ PNG",
    "ExportJpegTitle": "ดาวน์โหลดแผนภูมิเป็นรูปภาพ JPEG",
    "ExportCsvTitle": "ดาวน์โหลดข้อมูลเป็น CSV",
    "ExportExcelTitle": "ดาวน์โหลดข้อมูลเป็นสมุดงาน Excel"
  }
});
