define([], function() {
  return {
    "PropertyPaneDescription": "Veri görselleştirmenizi yapılandırın",
    "HeaderGroupName": "Üst bilgi",
    "WebPartHeaderFieldLabel": "Üst bilgi metni",
    "WebPartHeaderPlaceholder": "ör. Satış panosu",
    "ShowWebPartHeaderFieldLabel": "Üst bilgiyi göster",
    "ChartSettingsGroupName": "Grafik ayarları",
    "ChartTitleFieldLabel": "Grafik başlığı",
    "ChartTypeFieldLabel": "Grafik türü",
    "LegendPositionFieldLabel": "Gösterge konumu",
    "ChartHeightFieldLabel": "Grafik yüksekliği (px)",
    "ShowLegendFieldLabel": "Göstergeyi göster",
    "StackedFieldLabel": "Yığılmış (Çubuk/Çizgi)",
    "ShowDataTableFieldLabel": "Veri tablosunu göster",
    "ShowExportBarFieldLabel": "Dışarı aktarma çubuğunu göster",
    "XAxisLabelFieldLabel": "X ekseni etiketi (isteğe bağlı)",
    "XAxisPlaceholder": "Varsayılan olarak seçili sütun kullanılır",
    "YAxisLabelFieldLabel": "Y ekseni etiketi (isteğe bağlı)",
    "YAxisPlaceholder": "Varsayılan olarak seçili sütun(lar) kullanılır",
    "ChartGroupStandard": "Standart grafikler",
    "ChartGroupSpecialized": "Özel grafikler",
    "ChartTypeBarLabel": "Çubuk grafik (dikey)",
    "ChartTypeHorizontalBarLabel": "Çubuk grafik (yatay)",
    "ChartTypeLineLabel": "Çizgi grafik",
    "ChartTypeAreaLabel": "Alan grafik",
    "ChartTypeScatterLabel": "Dağılım grafiği",
    "ChartTypePieLabel": "Pasta grafik",
    "ChartTypeDoughnutLabel": "Halka grafik",
    "ChartTypeBubbleLabel": "Balon grafik",
    "ChartTypeRadarLabel": "Radar grafik",
    "ChartTypeKpiLabel": "KPI kutucuğu",
    "ChartTypeHistogramLabel": "Histogram",
    "ChartTypeWaterfallLabel": "Şelale grafiği",
    "ChartTypeBoxplotLabel": "Kutu grafiği",
    "ChartTypeViolinLabel": "Keman grafiği",
    "ChartTypeBeforeAfterLabel": "Önce-sonra grafiği",
    "ChartTypeTreemapLabel": "Ağaç haritası",
    "ChartTypeHeatmapLabel": "Isı haritası",
    "HistogramBinsFieldLabel": "Histogram aralıkları",
    "AppearancePageDescription": "Renkler, etiketler ve eksenler",
    "AdvancedPageDescription": "Analiz, başvuru çizgileri, etkileşim ve veri yenileme",
    "LegendTopLabel": "Üst",
    "LegendBottomLabel": "Alt",
    "LegendLeftLabel": "Sol",
    "LegendRightLabel": "Sağ",
    "ColorsGroupName": "Renkler",
    "ColorPaletteFieldLabel": "Renk paleti",
    "PaletteOfficeLabel": "Office (Varsayılan)",
    "PaletteVibrantLabel": "Canlı",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Tek renkli",
    "PaletteTrafficLightLabel": "Trafik ışığı",
    "PaletteWarmLabel": "Sıcak",
    "PaletteCoolLabel": "Soğuk",
    "DataLabelsGroupName": "Veri etiketleri ve biçimlendirme",
    "ShowDataLabelsFieldLabel": "Veri etiketlerini göster",
    "ValuePrefixFieldLabel": "Değer öneki",
    "ValuePrefixPlaceholder": "ör. $",
    "ValueSuffixFieldLabel": "Değer soneki",
    "ValueSuffixPlaceholder": "ör. %",
    "ValueDecimalsFieldLabel": "Ondalık basamak sayısı",
    "AbbreviateNumbersFieldLabel": "Sayıları kısalt (K/M)",
    "AxesGridGroupName": "Eksenler ve ızgara",
    "YAxisMinFieldLabel": "Y ekseni minimum",
    "YAxisMaxFieldLabel": "Y ekseni maksimum",
    "AutoPlaceholder": "Otomatik",
    "NumericValidationError": "Bir sayı girin veya otomatik için boş bırakın.",
    "ColorValidationError": "Onaltılık bir renk girin (ör. #d13438) veya varsayılan için boş bırakın.",
    "LogScaleFieldLabel": "Logaritmik ölçek (Y)",
    "LogScaleXFieldLabel": "Logaritmik ölçek (X)",
    "StepLineFieldLabel": "Basamaklı enterpolasyon",
    "ShowGridLinesFieldLabel": "Izgara çizgilerini göster",
    "XLabelRotationFieldLabel": "X etiketi dönüşü (derece)",
    "XAxisTypeFieldLabel": "X ekseni türü",
    "XAxisTypeAuto": "Otomatik algıla",
    "XAxisTypeCategory": "Kategori",
    "XAxisTypeTime": "Zaman (tarihler)",
    "AnalyticsGroupName": "Analiz",
    "TrendlineFieldLabel": "Eğilim çizgisi",
    "TrendlineNone": "Yok",
    "TrendlineLinear": "Doğrusal",
    "TrendlineMovingAverage": "Hareketli ortalama",
    "TrendWindowFieldLabel": "Hareketli ortalama penceresi",
    "TrendSuffix": " (eğilim)",
    "ForecastPeriodsFieldLabel": "Tahmin dönemleri (doğrusal eğilim çizgisi)",
    "ReferenceLineGroupName": "Başvuru çizgisi",
    "ReferenceLineTypeFieldLabel": "Başvuru çizgisi",
    "ReferenceLineValueFieldLabel": "Sabit değer",
    "ReferenceLineColorFieldLabel": "Çizgi rengi (onaltılık)",
    "RefLineFixed": "Sabit değer",
    "RefLineMean": "Ortalama",
    "RefLineMedian": "Medyan",
    "DualAxisGroupName": "Çift Y ekseni",
    "Y2ColumnsFieldLabel": "Sağ eksen serileri (virgülle ayrılmış sütun adları)",
    "Y2ColumnsPlaceholder": "ör. Marj,Büyüme",
    "Y2AxisLabelFieldLabel": "Sağ eksen etiketi",
    "LogScaleY2FieldLabel": "Logaritmik ölçek (sağ eksen)",
    "ErrorBarsGroupName": "Hata çubukları",
    "ErrorBarTypeFieldLabel": "Hata çubuğu türü",
    "ErrorBarTypeNone": "Yok",
    "ErrorBarTypeCustom": "Özel sütun (±)",
    "ErrorBarTypeSd": "Std. sapma (hesaplanan)",
    "ErrorBarTypeSem": "Ortalamanın std. hatası (hesaplanan)",
    "ErrorBarColumnFieldLabel": "Hata değeri sütunu",
    "SignificanceGroupName": "Anlamlılık parantezleri",
    "SignificancePairsFieldLabel": "Parantez çiftleri",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Her satıra bir parantez: sütun1,sütun2,etiket  — ör. GrupA,GrupB,*  veya  GrupA,GrupB,p<0.05  (JSON dizisi de kabul edilir)",
    "BeforeAfterColumnsError": "Önce-sonra grafiği tam olarak 2 Y sütunu gerektirir — biri Önce değerleri, diğeri Sonra değerleri için.",
    "InteractivityGroupName": "Etkileşim",
    "ShowViewerFiltersFieldLabel": "Görüntüleyenlere filtreleri göster",
    "DetailsOnDemandFieldLabel": "Tıklandığında veri satırlarını göster",
    "ShowDataPointsFieldLabel": "Çubukların üzerine veri noktalarını bindir",
    "ShowBubbleSizeLegendFieldLabel": "Balon boyutu göstergesini göster",
    "ViewerFilterLabel": "Filtre:",
    "ViewerFilterColumnAria": "Filtre sütunu",
    "ViewerFilterValueAria": "Filtre değeri",
    "DrillAllLabel": "Tümü",
    "DetailsChipLabel": "Ayrıntılar: {0} ({1} satır)",
    "KpiSubLabel": "{0} • {1} • {2} satır",
    "ConditionalGroupName": "Koşullu biçimlendirme",
    "ThresholdValueFieldLabel": "Eşik değeri",
    "ThresholdValuePlaceholder": "Kapalı",
    "ThresholdDirectionFieldLabel": "Vurgulanacak değerler",
    "ThresholdBelow": "Eşiğin altı",
    "ThresholdAbove": "Eşiğin üstü",
    "ThresholdColorFieldLabel": "Vurgu rengi (onaltılık)",
    "DataRefreshGroupName": "Veri ve yenileme",
    "RefreshIntervalFieldLabel": "Otomatik yenileme aralığı (dakika, 0 = kapalı)",
    "CacheMinutesFieldLabel": "Verileri önbelleğe al (dakika, 0 = kapalı)",
    "DynamicDataCategoryLabel": "Seçili kategori",
    "DynamicDataValueLabel": "Seçili değer",
    "DynamicDataSeriesLabel": "Seçili seri",
    "DataSourceGroupName": "Veri kaynağı",
    "HideDataSourceButton": "▲ Veri kaynağını gizle",
    "ConfigureDataSourceButton": "▼ Veri kaynağını yapılandır",
    "RowsLoadedBadge": "✓ {0} satır yüklendi",
    "ReadModeLoadError": "Veriler yüklenemedi: {0}. Veri kaynağını yeniden yapılandırmak için Düzenle moduna geçin.",
    "RefreshDataButton": "↻ Verileri yenile",
    "RefreshingLabel": "Yenileniyor…",
    "RefreshDataTitle": "Verileri yapılandırılmış kaynaktan yeniden yükle",
    "NoDataMessage": "Henüz veri yüklenmedi. Yukarıda veri kaynağınızı yapılandırın ve Verileri yükle'ye tıklayın.",
    "SelectMappingsMessage": "Veriler yüklendi ({0} satır). Grafiği görüntülemek için yukarıdan sütun eşlemelerini seçin.",
    "ChartRenderErrorLabel": "Grafik işleme hatası: {0}",
    "UnsupportedChartTypeLabel": "Desteklenmeyen grafik türü: {0}",
    "ChartAriaLabel": "Veri görselleştirme grafiği",
    "FilterOperatorLabel": "İşleç",
    "FilterValueLabel": "Değer",
    "FilterOpContains": "içerir",
    "FilterOpEquals": "eşittir",
    "FilterOpNotEquals": "eşit değildir",
    "FilterOpGt": "büyüktür",
    "FilterOpLt": "küçüktür",
    "FilterOpBetween": "arasında (düşük..yüksek)",
    "FilterOpIsEmpty": "boştur",
    "FilterOpNotEmpty": "boş değildir",
    "AddFilterButton": "+ Filtre ekle",
    "RemoveFilterButton": "Kaldır",
    "SelectValuePlaceholder": "Değer seçin…",
    "ViewerFilterOperatorAria": "Filtre işleci",
    "PaletteColorblindLabel": "Renk körlüğüne uygun",
    "WaterfallGroupName": "Şelale",
    "WaterfallShowTotalFieldLabel": "Toplam çubuğunu göster",
    "WaterfallPositiveColorFieldLabel": "Artış rengi",
    "WaterfallNegativeColorFieldLabel": "Azalış rengi",
    "WaterfallTotalColorFieldLabel": "Toplam rengi",
    "WaterfallTotalLabel": "Toplam",
    "ExternalFilterGroupName": "Başka bir web bölümünden filtrele",
    "ExternalFilterFieldLabel": "Filtre değeri kaynağı",
    "ExternalFilterColumnFieldLabel": "Filtrelenecek sütun",
    "ExternalFilterColumnPlaceholder": "Varsayılan olarak X ekseni sütunu kullanılır",
    "ViewAsTableButton": "Tablo olarak görüntüle",
    "HideTableButton": "Tabloyu gizle",
    "ChartKeyboardHint": "Veri noktaları arasında gezinmek için ok tuşlarını, birini seçmek için Enter tuşunu kullanın.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Y2 değer öneki",
    "Y2ValueSuffixFieldLabel": "Y2 değer soneki",
    "AnnotationsGroupName": "Açıklamalar",
    "AnnotationsFieldLabel": "Açıklamalar",
    "AnnotationsPlaceholder": "Oca, Ürün lansmanı",
    "AnnotationsHelp": "Her satıra bir tane: X ekseni değeri, virgül, ardından not metni. O X değerinde dikey bir işaret çizilir.",
    "BeforeLabel": "Önce",
    "AfterLabel": "Sonra",
    "RowLabel": "Satır {0}",
    "PointsSuffix": " (noktalar)",
    "ExportSheetName": "Veri",
    "RefreshFailedNote": "Son yenileme başarısız oldu: {0}. Daha önce yüklenen veriler gösteriliyor.",
    "TruncatedDataNote": "Yalnızca ilk {0} satır gösteriliyor; kaynakta daha fazla veri var.",
    "ScatterNumericWarning": "Dağılım ve balon grafikleri sayısal değerler gerektirir. \"{0}\" sütununda sayısal veri yok — yukarıdaki eşlemede farklı bir sütun seçin.",
    "TimeAxisUnparseableWarning": "\"{0}\" X ekseni sütununda tarih olarak ayrıştırılabilecek değer yok. X ekseni türünü \"Kategori\" olarak değiştirin veya bir tarih sütunu eşleyin.",
    "DataSourceSectionHeader": "Veri kaynağı",
    "SourceUploadLabel": "Dosya yükle",
    "SourceSharePointListLabel": "SharePoint listesi",
    "SourceSharePointFileLabel": "SharePoint dosyası",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API yolu",
    "GraphPathHelp": "Göreli Microsoft Graph yolu, ör. /me/memberOf veya /reports/getTeamsUserActivityUserCounts(period='D7'). Bu kaynak, bir yönetici tarafından onaylanmış Graph izinleri gerektirir — diğer tüm veri kaynakları bunlar olmadan çalışır.",
    "SheetNameLabel": "Excel sayfası",
    "DelimiterLabel": "Ayırıcı",
    "DelimiterAutoDetect": "Otomatik algıla",
    "DelimiterComma": "Virgül (,)",
    "DelimiterTab": "Sekme",
    "DelimiterSemicolon": "Noktalı virgül (;)",
    "DelimiterPipe": "Dikey çizgi (|)",
    "SiteUrlLabel": "Site URL'si (isteğe bağlı)",
    "SiteUrlHelp": "Geçerli siteyi kullanmak için boş bırakın.",
    "ListNameLabel": "Liste adı",
    "LoadingListsLabel": "— Listeler yükleniyor…",
    "SelectListPlaceholder": "— Bir liste seçin —",
    "EnterListNamePlaceholder": "Liste adını girin",
    "ListNameExamplePlaceholder": "ör. Satış verileri",
    "ListDiscoveryError": "Listeler yüklenemedi — adı aşağıya elle girin.",
    "FileUrlLabel": "Dosya URL'si (SharePoint'te CSV/TSV/Excel)",
    "FileUrlHelp": "Bir belge kitaplığındaki dosyanın tam URL'si.",
    "ApiUrlLabel": "API URL'si",
    "DataPathLabel": "Veri yolu (isteğe bağlı)",
    "DataPathHelp": "JSON yanıtındaki diziye giden, noktayla ayrılmış yol. Kök bir diziyse boş bırakın. SharePoint REST API için \"value\" kullanın.",
    "UploadHelp": "Bir CSV, TSV veya Excel (.xlsx, .xls) dosyası yükleyin.",
    "LoadedFileRowsLabel": "— {0} satır",
    "ChangeFileButton": "Dosyayı değiştir…",
    "ClearButton": "Temizle",
    "ChooseFileButton": "Dosya seç…",
    "LoadDataButton": "Verileri yükle",
    "LoadingLabel": "Yükleniyor…",
    "ErrorSelectListName": "Lütfen bir liste adı seçin veya girin.",
    "ErrorEnterFileUrl": "Lütfen bir dosya URL'si girin.",
    "ErrorEnterUrl": "Lütfen bir URL girin.",
    "ErrorLoadList": "SharePoint listesi yüklenemedi: {0}",
    "ErrorLoadFile": "Dosya yüklenemedi: {0}",
    "ErrorFetchData": "Veriler alınamadı: {0}",
    "ErrorDataPathNotFound": "\"{0}\" veri yolu yanıtta bulunamadı.",
    "ErrorUrlReturnedHtml": "Bu URL bir dosya değil, bir web sayfası döndürdü. \"Bağlantıyı kopyala\" paylaşım URL'sini değil, doğrudan dosya indirme yolunu kullanın.",
    "ErrorRequestTimedOut": "İstek zaman aşımına uğradı. URL'yi ve ağ bağlantınızı denetleyin.",
    "ErrorNonJsonResponse": "Yanıt JSON olarak ayrıştırılamadı.",
    "ErrorUnsupportedFileType": "Desteklenmeyen dosya türü. Lütfen bir .csv, .tsv, .xlsx veya .xls dosyası yükleyin.",
    "ErrorReadFile": "Dosya okunamadı",
    "ErrorParseFile": "Dosya ayrıştırılamadı",
    "LoadedRowsColumns": "{1} sütunlu {0} satır yüklendi.",
    "LoadedRowsColumnsPersist": "{1} sütunlu {0} satır yüklendi. Sayfadan ayrıldığınızda veriler korunacaktır.",
    "SizeWarning": "Veri kümesi ({0}KB) 200KB kalıcılık sınırını aşıyor. Grafik bu oturumda verileri gösterecek ancak sayfa yeniden yüklendiğinde temizlenecek. Büyük dosyalar için bir SharePoint kitaplığına yükleyin ve SharePoint dosyası kaynağını kullanın.",
    "ListTruncatedWarning": "Bu listede {0} veya daha fazla öğe var; yalnızca ilk {0} öğe yüklendi.",
    "GraphTruncatedWarning": "Bu Microsoft Graph sonucunda yüklenebilenden fazla sayfa var; yalnızca ilk {0} sayfa alındı.",
    "CsvParseWarning": "{0} satır ayrıştırılamadı ve atlandı.",
    "ColumnMappingSectionHeader": "Sütun eşleme",
    "CategoryColumnLabel": "Kategori sütunu (X / Etiketler)",
    "LabelColumnLabel": "Etiket sütunu",
    "XAxisColumnLabel": "X ekseni sütunu",
    "ValueColumnLabel": "Değer sütunu",
    "YAxisColumnLabel": "Y ekseni sütunu",
    "YAxisColumnsLabel": "Y ekseni sütun(lar)ı",
    "YAxisColumnsHelp": "(bir veya daha fazla seçin; rengi ayarlamak için renk örneğine tıklayın)",
    "SelectColumnPlaceholder": "— Sütun seçin —",
    "ScatterLabelColumnLabel": "Nokta etiketi",
    "SizeColumnLabel": "Boyut / Yarıçap sütunu",
    "NoSizeColumnOption": "— Yok (sabit boyut) —",
    "SeriesColorTitle": "{0} için renk",
    "SeriesTypeTitle": "{0} için grafik türü",
    "SeriesTypeDefault": "Varsayılan",
    "SeriesTypeBar": "Çubuk",
    "SeriesTypeLine": "Çizgi",
    "HistogramColumnLabel": "Aralıklara bölünecek sütun (sayısal)",
    "TreemapGroupLabel": "Grup / Etiket sütunu",
    "HeatmapColumnLabel": "Sütun (X) kategorisi",
    "HeatmapRowLabel": "Satır (Y) kategorisi",
    "AdvancedOptionsClosed": "▼ Gelişmiş seçenekler",
    "AdvancedOptionsOpen": "▲ Gelişmiş seçenekler",
    "ColorByLabel": "Sütuna göre renklendir",
    "ColorByHelp": "Noktaları seriye göre değil, kategoriye göre renklendirin.",
    "TooltipColumnsLabel": "Araç ipucu sütunları",
    "TooltipColumnsHelp": "(bir veri noktasının üzerine gelindiğinde gösterilen ek sütunlar)",
    "DrillLevelLabel": "Detay düzeyi {0}",
    "DrillDownHelp": "Tıklayarak detaya inmeyi etkinleştirmek için bir sütun hiyerarşisi tanımlayın (ör. Bölge → Ülke → Şehir). Değerler her düzeyde toplanır.",
    "BookmarksLabel": "Yer imleri",
    "BookmarkNameLabel": "Yer imi adı",
    "BookmarkNamePlaceholder": "ör. Bölgeye göre ilk 10",
    "SaveBookmarkButton": "Geçerli görünümü kaydet",
    "ApplyBookmarkButton": "Uygula",
    "DeleteBookmarkButton": "Sil",
    "ApplyBookmarkPlaceholder": "— Bir yer imi uygulayın —",
    "DataControlsSectionHeader": "Veri denetimleri",
    "SortByColumnLabel": "Sütuna göre sırala",
    "NoneOption": "— Yok —",
    "SortDirectionLabel": "Sıralama yönü",
    "AscendingOption": "Artan",
    "DescendingOption": "Azalan",
    "RowLimitLabel": "Satır sınırı (0 = tümü)",
    "FilterColumnLabel": "Filtre sütunu",
    "FilterContainsLabel": "Filtre: içerir",
    "FilterValuePlaceholder": "Filtre değeri…",
    "GroupByLabel": "Sütuna göre grupla",
    "AggregationLabel": "Toplama",
    "GroupByHelp": "Sayısal sütunlar grup başına toplanır. Sayı, bir \"Sayı\" sütunu ekler.",
    "AggNone": "Yok",
    "AggSum": "Toplam",
    "AggAvg": "Ortalama",
    "AggCount": "Sayı",
    "AggMin": "Min",
    "AggMax": "Maks",
    "DataTableHeader": "Veri tablosu ({0} satır)",
    "PrevPageButton": "← Önceki",
    "NextPageButton": "Sonraki →",
    "PageOfLabel": "Sayfa {0} / {1}",
    "ExportLabel": "Dışarı aktar:",
    "ExportPngTitle": "Grafiği PNG resmi olarak indir",
    "ExportJpegTitle": "Grafiği JPEG resmi olarak indir",
    "ExportCsvTitle": "Verileri CSV olarak indir",
    "ExportExcelTitle": "Verileri Excel çalışma kitabı olarak indir"
  }
});
