define([], function() {
  return {
    "PropertyPaneDescription": "Налаштуйте візуалізацію даних",
    "HeaderGroupName": "Заголовок",
    "WebPartHeaderFieldLabel": "Текст заголовка",
    "WebPartHeaderPlaceholder": "наприклад, Панель продажів",
    "ShowWebPartHeaderFieldLabel": "Показати заголовок",
    "ChartSettingsGroupName": "Параметри діаграми",
    "ChartTitleFieldLabel": "Назва діаграми",
    "ChartTypeFieldLabel": "Тип діаграми",
    "LegendPositionFieldLabel": "Розташування легенди",
    "ChartHeightFieldLabel": "Висота діаграми (пікс.)",
    "ShowLegendFieldLabel": "Показати легенду",
    "StackedFieldLabel": "З накопиченням (стовпчикова/лінійна)",
    "ShowDataTableFieldLabel": "Показати таблицю даних",
    "ShowExportBarFieldLabel": "Показати панель експорту",
    "XAxisLabelFieldLabel": "Підпис осі X (необов’язково)",
    "XAxisPlaceholder": "За замовчуванням — вибраний стовпець",
    "YAxisLabelFieldLabel": "Підпис осі Y (необов’язково)",
    "YAxisPlaceholder": "За замовчуванням — вибрані стовпці",
    "ChartGroupStandard": "Стандартні діаграми",
    "ChartGroupSpecialized": "Спеціалізовані діаграми",
    "ChartTypeBarLabel": "Стовпчикова діаграма (вертикальна)",
    "ChartTypeHorizontalBarLabel": "Стовпчикова діаграма (горизонтальна)",
    "ChartTypeLineLabel": "Лінійна діаграма",
    "ChartTypeAreaLabel": "Діаграма з областями",
    "ChartTypeScatterLabel": "Точкова діаграма",
    "ChartTypePieLabel": "Кругова діаграма",
    "ChartTypeDoughnutLabel": "Кільцева діаграма",
    "ChartTypeBubbleLabel": "Бульбашкова діаграма",
    "ChartTypeRadarLabel": "Пелюсткова діаграма",
    "ChartTypeKpiLabel": "Плитка KPI",
    "ChartTypeHistogramLabel": "Гістограма",
    "ChartTypeWaterfallLabel": "Каскадна діаграма",
    "ChartTypeBoxplotLabel": "Діаграма розмаху",
    "ChartTypeViolinLabel": "Скрипкова діаграма",
    "ChartTypeBeforeAfterLabel": "Діаграма «до-після»",
    "ChartTypeTreemapLabel": "Деревоподібна діаграма",
    "ChartTypeHeatmapLabel": "Теплова карта",
    "HistogramBinsFieldLabel": "Інтервали гістограми",
    "AppearancePageDescription": "Кольори, підписи та осі",
    "AdvancedPageDescription": "Аналітика, опорні лінії, інтерактивність і оновлення даних",
    "LegendTopLabel": "Угорі",
    "LegendBottomLabel": "Унизу",
    "LegendLeftLabel": "Ліворуч",
    "LegendRightLabel": "Праворуч",
    "ColorsGroupName": "Кольори",
    "ColorPaletteFieldLabel": "Палітра кольорів",
    "PaletteOfficeLabel": "Office (за замовчуванням)",
    "PaletteVibrantLabel": "Яскрава",
    "PalettePastelLabel": "Пастельна",
    "PaletteMonochromeLabel": "Монохромна",
    "PaletteTrafficLightLabel": "Світлофор",
    "PaletteWarmLabel": "Тепла",
    "PaletteCoolLabel": "Холодна",
    "DataLabelsGroupName": "Підписи даних і форматування",
    "ShowDataLabelsFieldLabel": "Показати підписи даних",
    "ValuePrefixFieldLabel": "Префікс значення",
    "ValuePrefixPlaceholder": "наприклад, $",
    "ValueSuffixFieldLabel": "Суфікс значення",
    "ValueSuffixPlaceholder": "наприклад, %",
    "ValueDecimalsFieldLabel": "Кількість десяткових знаків",
    "AbbreviateNumbersFieldLabel": "Скорочувати числа (K/M)",
    "AxesGridGroupName": "Осі та сітка",
    "YAxisMinFieldLabel": "Мінімум осі Y",
    "YAxisMaxFieldLabel": "Максимум осі Y",
    "AutoPlaceholder": "Авто",
    "NumericValidationError": "Введіть число або залиште поле порожнім для автоматичного значення.",
    "ColorValidationError": "Введіть шістнадцятковий код кольору (наприклад, #d13438) або залиште поле порожнім для значення за замовчуванням.",
    "LogScaleFieldLabel": "Логарифмічна шкала (Y)",
    "LogScaleXFieldLabel": "Логарифмічна шкала (X)",
    "StepLineFieldLabel": "Ступінчаста інтерполяція",
    "ShowGridLinesFieldLabel": "Показати лінії сітки",
    "XLabelRotationFieldLabel": "Поворот підписів осі X (градуси)",
    "XAxisTypeFieldLabel": "Тип осі X",
    "XAxisTypeAuto": "Автовизначення",
    "XAxisTypeCategory": "Категорія",
    "XAxisTypeTime": "Час (дати)",
    "AnalyticsGroupName": "Аналітика",
    "TrendlineFieldLabel": "Лінія тренду",
    "TrendlineNone": "Немає",
    "TrendlineLinear": "Лінійна",
    "TrendlineMovingAverage": "Ковзне середнє",
    "TrendWindowFieldLabel": "Вікно ковзного середнього",
    "TrendSuffix": " (тренд)",
    "ForecastPeriodsFieldLabel": "Періоди прогнозу (лінійна лінія тренду)",
    "ReferenceLineGroupName": "Опорна лінія",
    "ReferenceLineTypeFieldLabel": "Опорна лінія",
    "ReferenceLineValueFieldLabel": "Фіксоване значення",
    "ReferenceLineColorFieldLabel": "Колір лінії (шістнадцятковий)",
    "RefLineFixed": "Фіксоване значення",
    "RefLineMean": "Середнє",
    "RefLineMedian": "Медіана",
    "DualAxisGroupName": "Подвійна вісь Y",
    "Y2ColumnsFieldLabel": "Ряди правої осі (назви стовпців через кому)",
    "Y2ColumnsPlaceholder": "наприклад, Маржа,Зростання",
    "Y2AxisLabelFieldLabel": "Підпис правої осі",
    "LogScaleY2FieldLabel": "Логарифмічна шкала (права вісь)",
    "ErrorBarsGroupName": "Смуги похибок",
    "ErrorBarTypeFieldLabel": "Тип смуги похибок",
    "ErrorBarTypeNone": "Немає",
    "ErrorBarTypeCustom": "Користувацький стовпець (±)",
    "ErrorBarTypeSd": "Стандартне відхилення (обчислюване)",
    "ErrorBarTypeSem": "Стандартна похибка середнього (обчислювана)",
    "ErrorBarColumnFieldLabel": "Стовпець значень похибки",
    "SignificanceGroupName": "Дужки значущості",
    "SignificancePairsFieldLabel": "Пари дужок",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Одна дужка на рядок: стовпець1,стовпець2,підпис  — наприклад, GroupA,GroupB,*  або  GroupA,GroupB,p<0.05  (також підтримується масив JSON)",
    "BeforeAfterColumnsError": "Діаграма «до-після» потребує рівно 2 стовпці Y — один для значень «До» і один для значень «Після».",
    "InteractivityGroupName": "Інтерактивність",
    "ShowViewerFiltersFieldLabel": "Показувати фільтри глядачам",
    "DetailsOnDemandFieldLabel": "Показувати рядки даних після клацання",
    "ShowDataPointsFieldLabel": "Накладати точки даних на стовпці",
    "ShowBubbleSizeLegendFieldLabel": "Показати легенду розміру бульбашок",
    "ViewerFilterLabel": "Фільтр:",
    "ViewerFilterColumnAria": "Стовпець фільтра",
    "ViewerFilterValueAria": "Значення фільтра",
    "DrillAllLabel": "Усі",
    "DetailsChipLabel": "Докладно: {0} (рядків: {1})",
    "KpiSubLabel": "{0} • {1} • рядків: {2}",
    "ConditionalGroupName": "Умовне форматування",
    "ThresholdValueFieldLabel": "Порогове значення",
    "ThresholdValuePlaceholder": "Вимкнено",
    "ThresholdDirectionFieldLabel": "Виділяти значення",
    "ThresholdBelow": "Нижче порогу",
    "ThresholdAbove": "Вище порогу",
    "ThresholdColorFieldLabel": "Колір виділення (шістнадцятковий)",
    "DataRefreshGroupName": "Дані та оновлення",
    "RefreshIntervalFieldLabel": "Інтервал автоматичного оновлення (хвилини, 0 = вимк.)",
    "CacheMinutesFieldLabel": "Кешувати дані (хвилини, 0 = вимк.)",
    "DynamicDataCategoryLabel": "Вибрана категорія",
    "DynamicDataValueLabel": "Вибране значення",
    "DynamicDataSeriesLabel": "Вибраний ряд",
    "DataSourceGroupName": "Джерело даних",
    "HideDataSourceButton": "▲ Приховати джерело даних",
    "ConfigureDataSourceButton": "▼ Налаштувати джерело даних",
    "RowsLoadedBadge": "✓ Завантажено рядків: {0}",
    "ReadModeLoadError": "Не вдалося завантажити дані: {0}. Перейдіть у режим редагування, щоб змінити налаштування джерела даних.",
    "RefreshDataButton": "↻ Оновити дані",
    "RefreshingLabel": "Оновлення…",
    "RefreshDataTitle": "Перезавантажити дані з налаштованого джерела",
    "NoDataMessage": "Дані ще не завантажено. Налаштуйте джерело даних вище та натисніть «Завантажити дані».",
    "SelectMappingsMessage": "Дані завантажено (рядків: {0}). Виберіть зіставлення стовпців вище, щоб відобразити діаграму.",
    "ChartRenderErrorLabel": "Помилка відображення діаграми: {0}",
    "UnsupportedChartTypeLabel": "Непідтримуваний тип діаграми: {0}",
    "ChartAriaLabel": "Діаграма візуалізації даних",
    "FilterOperatorLabel": "Оператор",
    "FilterValueLabel": "Значення",
    "FilterOpContains": "містить",
    "FilterOpEquals": "дорівнює",
    "FilterOpNotEquals": "не дорівнює",
    "FilterOpGt": "більше ніж",
    "FilterOpLt": "менше ніж",
    "FilterOpBetween": "між (мін..макс)",
    "FilterOpIsEmpty": "порожнє",
    "FilterOpNotEmpty": "не порожнє",
    "AddFilterButton": "+ Додати фільтр",
    "RemoveFilterButton": "Видалити",
    "SelectValuePlaceholder": "Виберіть значення…",
    "ViewerFilterOperatorAria": "Оператор фільтра",
    "PaletteColorblindLabel": "Для людей із порушенням кольоросприйняття",
    "WaterfallGroupName": "Каскадна діаграма",
    "WaterfallShowTotalFieldLabel": "Показати стовпець підсумку",
    "WaterfallPositiveColorFieldLabel": "Колір збільшення",
    "WaterfallNegativeColorFieldLabel": "Колір зменшення",
    "WaterfallTotalColorFieldLabel": "Колір підсумку",
    "WaterfallTotalLabel": "Разом",
    "ExternalFilterGroupName": "Фільтр з іншої веб-частини",
    "ExternalFilterFieldLabel": "Джерело значення фільтра",
    "ExternalFilterColumnFieldLabel": "Стовпець для фільтрації",
    "ExternalFilterColumnPlaceholder": "За замовчуванням — стовпець осі X",
    "ViewAsTableButton": "Переглянути як таблицю",
    "HideTableButton": "Приховати таблицю",
    "ChartKeyboardHint": "Використовуйте клавіші зі стрілками для переходу між точками даних і Enter для вибору точки.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Префікс значення Y2",
    "Y2ValueSuffixFieldLabel": "Суфікс значення Y2",
    "AnnotationsGroupName": "Примітки",
    "AnnotationsFieldLabel": "Примітки",
    "AnnotationsPlaceholder": "Січ, Запуск продукту",
    "AnnotationsHelp": "По одній на рядок: значення осі X, кома, потім текст примітки. У цьому значенні X малюється вертикальна позначка.",
    "BeforeLabel": "До",
    "AfterLabel": "Після",
    "RowLabel": "Рядок {0}",
    "PointsSuffix": " (точки)",
    "ExportSheetName": "Дані",
    "RefreshFailedNote": "Останнє оновлення не вдалося: {0}. Показано раніше завантажені дані.",
    "TruncatedDataNote": "Показано лише перші {0} рядків; у джерелі більше даних.",
    "ScatterNumericWarning": "Точкові та бульбашкові діаграми потребують числових значень. Стовпець «{0}» не містить числових даних — виберіть інший стовпець у зіставленні вище.",
    "TimeAxisUnparseableWarning": "У стовпці осі X «{0}» немає значень, які можна розпізнати як дати. Змініть тип осі X на «Категорія» або зіставте стовпець дат.",
    "DataSourceSectionHeader": "Джерело даних",
    "SourceUploadLabel": "Передати файл",
    "SourceSharePointListLabel": "Список SharePoint",
    "SourceSharePointFileLabel": "Файл SharePoint",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Шлях Graph API",
    "GraphPathHelp": "Відносний шлях Microsoft Graph, наприклад /me/memberOf або /reports/getTeamsUserActivityUserCounts(period='D7'). Для цього джерела потрібні дозволи Graph, схвалені адміністратором — усі інші джерела даних працюють без них.",
    "SheetNameLabel": "Аркуш Excel",
    "DelimiterLabel": "Роздільник",
    "DelimiterAutoDetect": "Автовизначення",
    "DelimiterComma": "Кома (,)",
    "DelimiterTab": "Табуляція",
    "DelimiterSemicolon": "Крапка з комою (;)",
    "DelimiterPipe": "Вертикальна риска (|)",
    "SiteUrlLabel": "URL-адреса сайту (необов’язково)",
    "SiteUrlHelp": "Залиште порожнім, щоб використовувати поточний сайт.",
    "ListNameLabel": "Назва списку",
    "LoadingListsLabel": "— Завантаження списків…",
    "SelectListPlaceholder": "— Виберіть список —",
    "EnterListNamePlaceholder": "Введіть назву списку",
    "ListNameExamplePlaceholder": "наприклад, Дані продажів",
    "ListDiscoveryError": "Не вдалося завантажити списки — введіть назву вручну нижче.",
    "FileUrlLabel": "URL-адреса файлу (CSV/TSV/Excel у SharePoint)",
    "FileUrlHelp": "Повна URL-адреса файлу в бібліотеці документів.",
    "ApiUrlLabel": "URL-адреса API",
    "DataPathLabel": "Шлях до даних (необов’язково)",
    "DataPathHelp": "Шлях до масиву у відповіді JSON, розділений крапками. Залиште порожнім, якщо корінь — масив. Для SharePoint REST API використовуйте \"value\".",
    "UploadHelp": "Передайте файл CSV, TSV або Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— рядків: {0}",
    "ChangeFileButton": "Змінити файл…",
    "ClearButton": "Очистити",
    "ChooseFileButton": "Вибрати файл…",
    "LoadDataButton": "Завантажити дані",
    "LoadingLabel": "Завантаження…",
    "ErrorSelectListName": "Виберіть або введіть назву списку.",
    "ErrorEnterFileUrl": "Введіть URL-адресу файлу.",
    "ErrorEnterUrl": "Введіть URL-адресу.",
    "ErrorLoadList": "Не вдалося завантажити список SharePoint: {0}",
    "ErrorLoadFile": "Не вдалося завантажити файл: {0}",
    "ErrorFetchData": "Не вдалося отримати дані: {0}",
    "ErrorDataPathNotFound": "Шлях до даних \"{0}\" не знайдено у відповіді.",
    "ErrorUrlReturnedHtml": "Ця URL-адреса повернула веб-сторінку, а не файл. Використовуйте пряму адресу завантаження файлу, а не URL-адресу спільного доступу «Копіювати посилання».",
    "ErrorRequestTimedOut": "Час очікування запиту минув. Перевірте URL-адресу та підключення до мережі.",
    "ErrorNonJsonResponse": "Не вдалося проаналізувати відповідь як JSON.",
    "ErrorUnsupportedFileType": "Непідтримуваний тип файлу. Передайте файл .csv, .tsv, .xlsx або .xls.",
    "ErrorReadFile": "Не вдалося прочитати файл",
    "ErrorParseFile": "Не вдалося проаналізувати файл",
    "LoadedRowsColumns": "Завантажено рядків: {0}, стовпців: {1}.",
    "LoadedRowsColumnsPersist": "Завантажено рядків: {0}, стовпців: {1}. Дані буде збережено після виходу зі сторінки.",
    "SizeWarning": "Набір даних ({0} КБ) перевищує ліміт збереження 200 КБ. Діаграма показуватиме дані протягом цього сеансу, але буде очищена після перезавантаження сторінки. Для великих файлів передайте їх до бібліотеки SharePoint і використовуйте джерело «Файл SharePoint».",
    "ListTruncatedWarning": "У цьому списку {0} або більше елементів; завантажено лише перші {0}.",
    "GraphTruncatedWarning": "Цей результат Microsoft Graph містить більше сторінок, ніж можна завантажити; отримано лише перші {0} сторінок.",
    "CsvParseWarning": "Рядків, які не вдалося проаналізувати й було пропущено: {0}.",
    "ColumnMappingSectionHeader": "Зіставлення стовпців",
    "CategoryColumnLabel": "Стовпець категорій (X / підписи)",
    "LabelColumnLabel": "Стовпець підписів",
    "XAxisColumnLabel": "Стовпець осі X",
    "ValueColumnLabel": "Стовпець значень",
    "YAxisColumnLabel": "Стовпець осі Y",
    "YAxisColumnsLabel": "Стовпці осі Y",
    "YAxisColumnsHelp": "(виберіть один або кілька; клацніть зразок, щоб задати колір)",
    "SelectColumnPlaceholder": "— Виберіть стовпець —",
    "ScatterLabelColumnLabel": "Підпис точки",
    "SizeColumnLabel": "Стовпець розміру / радіуса",
    "NoSizeColumnOption": "— Немає (фіксований розмір) —",
    "SeriesColorTitle": "Колір для {0}",
    "SeriesTypeTitle": "Тип діаграми для {0}",
    "SeriesTypeDefault": "За замовчуванням",
    "SeriesTypeBar": "Стовпчик",
    "SeriesTypeLine": "Лінія",
    "HistogramColumnLabel": "Стовпець для розбиття на інтервали (числовий)",
    "TreemapGroupLabel": "Стовпець груп / підписів",
    "HeatmapColumnLabel": "Категорія стовпців (X)",
    "HeatmapRowLabel": "Категорія рядків (Y)",
    "AdvancedOptionsClosed": "▼ Додаткові параметри",
    "AdvancedOptionsOpen": "▲ Додаткові параметри",
    "ColorByLabel": "Колір за стовпцем",
    "ColorByHelp": "Розфарбовувати точки за категорією, а не за рядом.",
    "TooltipColumnsLabel": "Стовпці підказки",
    "TooltipColumnsHelp": "(додаткові стовпці, що відображаються під час наведення на точку даних)",
    "DrillLevelLabel": "Рівень деталізації {0}",
    "DrillDownHelp": "Визначте ієрархію стовпців, щоб увімкнути деталізацію клацанням (наприклад, Регіон → Країна → Місто). Значення агрегуються на кожному рівні.",
    "BookmarksLabel": "Закладки",
    "BookmarkNameLabel": "Назва закладки",
    "BookmarkNamePlaceholder": "наприклад, Топ-10 за регіоном",
    "SaveBookmarkButton": "Зберегти поточний вигляд",
    "ApplyBookmarkButton": "Застосувати",
    "DeleteBookmarkButton": "Видалити",
    "ApplyBookmarkPlaceholder": "— Застосувати закладку —",
    "DataControlsSectionHeader": "Керування даними",
    "SortByColumnLabel": "Сортувати за стовпцем",
    "NoneOption": "— Немає —",
    "SortDirectionLabel": "Напрямок сортування",
    "AscendingOption": "За зростанням",
    "DescendingOption": "За спаданням",
    "RowLimitLabel": "Ліміт рядків (0 = усі)",
    "FilterColumnLabel": "Стовпець фільтра",
    "FilterContainsLabel": "Фільтр: містить",
    "FilterValuePlaceholder": "Значення фільтра…",
    "GroupByLabel": "Групувати за стовпцем",
    "AggregationLabel": "Агрегація",
    "GroupByHelp": "Числові стовпці агрегуються для кожної групи. Кількість додає стовпець «Кількість».",
    "AggNone": "Немає",
    "AggSum": "Сума",
    "AggAvg": "Середнє",
    "AggCount": "Кількість",
    "AggMin": "Мін.",
    "AggMax": "Макс.",
    "DataTableHeader": "Таблиця даних (рядків: {0})",
    "PrevPageButton": "← Назад",
    "NextPageButton": "Далі →",
    "PageOfLabel": "Сторінка {0} з {1}",
    "ExportLabel": "Експорт:",
    "ExportPngTitle": "Завантажити діаграму як зображення PNG",
    "ExportJpegTitle": "Завантажити діаграму як зображення JPEG",
    "ExportCsvTitle": "Завантажити дані як CSV",
    "ExportExcelTitle": "Завантажити дані як книгу Excel"
  }
});
