define([], function() {
  return {
    "PropertyPaneDescription": "Định cấu hình trực quan hóa dữ liệu của bạn",
    "HeaderGroupName": "Tiêu đề",
    "WebPartHeaderFieldLabel": "Văn bản tiêu đề",
    "WebPartHeaderPlaceholder": "ví dụ: Bảng điều khiển doanh số",
    "ShowWebPartHeaderFieldLabel": "Hiển thị tiêu đề",
    "ChartSettingsGroupName": "Cài đặt biểu đồ",
    "ChartTitleFieldLabel": "Tiêu đề biểu đồ",
    "ChartTypeFieldLabel": "Loại biểu đồ",
    "LegendPositionFieldLabel": "Vị trí chú giải",
    "ChartHeightFieldLabel": "Chiều cao biểu đồ (px)",
    "ShowLegendFieldLabel": "Hiển thị chú giải",
    "StackedFieldLabel": "Xếp chồng (Cột/Đường)",
    "ShowDataTableFieldLabel": "Hiển thị bảng dữ liệu",
    "ShowExportBarFieldLabel": "Hiển thị thanh xuất",
    "XAxisLabelFieldLabel": "Nhãn trục X (không bắt buộc)",
    "XAxisPlaceholder": "Mặc định là cột đã chọn",
    "YAxisLabelFieldLabel": "Nhãn trục Y (không bắt buộc)",
    "YAxisPlaceholder": "Mặc định là các cột đã chọn",
    "ChartGroupStandard": "Biểu đồ chuẩn",
    "ChartGroupSpecialized": "Biểu đồ chuyên biệt",
    "ChartTypeBarLabel": "Biểu đồ cột (dọc)",
    "ChartTypeHorizontalBarLabel": "Biểu đồ thanh (ngang)",
    "ChartTypeLineLabel": "Biểu đồ đường",
    "ChartTypeAreaLabel": "Biểu đồ vùng",
    "ChartTypeScatterLabel": "Biểu đồ phân tán",
    "ChartTypePieLabel": "Biểu đồ tròn",
    "ChartTypeDoughnutLabel": "Biểu đồ vành khuyên",
    "ChartTypeBubbleLabel": "Biểu đồ bong bóng",
    "ChartTypeRadarLabel": "Biểu đồ radar",
    "ChartTypeKpiLabel": "Ô KPI",
    "ChartTypeHistogramLabel": "Biểu đồ tần suất",
    "ChartTypeWaterfallLabel": "Biểu đồ thác nước",
    "ChartTypeBoxplotLabel": "Biểu đồ hộp",
    "ChartTypeViolinLabel": "Biểu đồ violin",
    "ChartTypeBeforeAfterLabel": "Biểu đồ trước-sau",
    "ChartTypeTreemapLabel": "Biểu đồ cây",
    "ChartTypeHeatmapLabel": "Bản đồ nhiệt",
    "HistogramBinsFieldLabel": "Số khoảng của biểu đồ tần suất",
    "AppearancePageDescription": "Màu sắc, nhãn và trục",
    "AdvancedPageDescription": "Phân tích, đường tham chiếu, tương tác và làm mới dữ liệu",
    "LegendTopLabel": "Trên cùng",
    "LegendBottomLabel": "Dưới cùng",
    "LegendLeftLabel": "Trái",
    "LegendRightLabel": "Phải",
    "ColorsGroupName": "Màu sắc",
    "ColorPaletteFieldLabel": "Bảng màu",
    "PaletteOfficeLabel": "Office (Mặc định)",
    "PaletteVibrantLabel": "Rực rỡ",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Đơn sắc",
    "PaletteTrafficLightLabel": "Đèn giao thông",
    "PaletteWarmLabel": "Ấm",
    "PaletteCoolLabel": "Lạnh",
    "DataLabelsGroupName": "Nhãn dữ liệu và định dạng",
    "ShowDataLabelsFieldLabel": "Hiển thị nhãn dữ liệu",
    "ValuePrefixFieldLabel": "Tiền tố giá trị",
    "ValuePrefixPlaceholder": "ví dụ: $",
    "ValueSuffixFieldLabel": "Hậu tố giá trị",
    "ValueSuffixPlaceholder": "ví dụ: %",
    "ValueDecimalsFieldLabel": "Số chữ số thập phân",
    "AbbreviateNumbersFieldLabel": "Viết tắt số (K/M)",
    "AxesGridGroupName": "Trục và lưới",
    "YAxisMinFieldLabel": "Giá trị nhỏ nhất của trục Y",
    "YAxisMaxFieldLabel": "Giá trị lớn nhất của trục Y",
    "AutoPlaceholder": "Tự động",
    "NumericValidationError": "Nhập một số hoặc để trống để tự động.",
    "ColorValidationError": "Nhập màu thập lục phân (ví dụ: #d13438) hoặc để trống để dùng mặc định.",
    "LogScaleFieldLabel": "Thang logarit (Y)",
    "LogScaleXFieldLabel": "Thang logarit (X)",
    "StepLineFieldLabel": "Nội suy bậc thang",
    "ShowGridLinesFieldLabel": "Hiển thị đường lưới",
    "XLabelRotationFieldLabel": "Xoay nhãn X (độ)",
    "XAxisTypeFieldLabel": "Loại trục X",
    "XAxisTypeAuto": "Tự động phát hiện",
    "XAxisTypeCategory": "Danh mục",
    "XAxisTypeTime": "Thời gian (ngày)",
    "AnalyticsGroupName": "Phân tích",
    "TrendlineFieldLabel": "Đường xu hướng",
    "TrendlineNone": "Không có",
    "TrendlineLinear": "Tuyến tính",
    "TrendlineMovingAverage": "Trung bình động",
    "TrendWindowFieldLabel": "Cửa sổ trung bình động",
    "TrendSuffix": " (xu hướng)",
    "ForecastPeriodsFieldLabel": "Số kỳ dự báo (đường xu hướng tuyến tính)",
    "ReferenceLineGroupName": "Đường tham chiếu",
    "ReferenceLineTypeFieldLabel": "Đường tham chiếu",
    "ReferenceLineValueFieldLabel": "Giá trị cố định",
    "ReferenceLineColorFieldLabel": "Màu đường (thập lục phân)",
    "RefLineFixed": "Giá trị cố định",
    "RefLineMean": "Trung bình",
    "RefLineMedian": "Trung vị",
    "DualAxisGroupName": "Trục Y kép",
    "Y2ColumnsFieldLabel": "Chuỗi trục bên phải (tên cột phân tách bằng dấu phẩy)",
    "Y2ColumnsPlaceholder": "ví dụ: Biên lợi nhuận,Tăng trưởng",
    "Y2AxisLabelFieldLabel": "Nhãn trục bên phải",
    "LogScaleY2FieldLabel": "Thang logarit (trục bên phải)",
    "ErrorBarsGroupName": "Thanh sai số",
    "ErrorBarTypeFieldLabel": "Loại thanh sai số",
    "ErrorBarTypeNone": "Không có",
    "ErrorBarTypeCustom": "Cột tùy chỉnh (±)",
    "ErrorBarTypeSd": "Độ lệch chuẩn (được tính)",
    "ErrorBarTypeSem": "Sai số chuẩn của trung bình (được tính)",
    "ErrorBarColumnFieldLabel": "Cột giá trị sai số",
    "SignificanceGroupName": "Dấu ngoặc ý nghĩa thống kê",
    "SignificancePairsFieldLabel": "Cặp dấu ngoặc",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "Mỗi dòng một dấu ngoặc: cột1,cột2,nhãn  — ví dụ: GroupA,GroupB,*  hoặc  GroupA,GroupB,p<0.05  (cũng chấp nhận mảng JSON)",
    "BeforeAfterColumnsError": "Biểu đồ trước-sau yêu cầu đúng 2 cột Y — một cho giá trị Trước và một cho giá trị Sau.",
    "InteractivityGroupName": "Tương tác",
    "ShowViewerFiltersFieldLabel": "Hiển thị bộ lọc cho người xem",
    "DetailsOnDemandFieldLabel": "Hiển thị các hàng dữ liệu khi nhấp",
    "ShowDataPointsFieldLabel": "Chồng điểm dữ liệu lên các cột",
    "ShowBubbleSizeLegendFieldLabel": "Hiển thị chú giải kích thước bong bóng",
    "ViewerFilterLabel": "Bộ lọc:",
    "ViewerFilterColumnAria": "Cột bộ lọc",
    "ViewerFilterValueAria": "Giá trị bộ lọc",
    "DrillAllLabel": "Tất cả",
    "DetailsChipLabel": "Chi tiết: {0} ({1} hàng)",
    "KpiSubLabel": "{0} • {1} • {2} hàng",
    "ConditionalGroupName": "Định dạng có điều kiện",
    "ThresholdValueFieldLabel": "Giá trị ngưỡng",
    "ThresholdValuePlaceholder": "Tắt",
    "ThresholdDirectionFieldLabel": "Đánh dấu các giá trị",
    "ThresholdBelow": "Dưới ngưỡng",
    "ThresholdAbove": "Trên ngưỡng",
    "ThresholdColorFieldLabel": "Màu đánh dấu (thập lục phân)",
    "DataRefreshGroupName": "Dữ liệu và làm mới",
    "RefreshIntervalFieldLabel": "Khoảng thời gian tự động làm mới (phút, 0 = tắt)",
    "CacheMinutesFieldLabel": "Lưu đệm dữ liệu (phút, 0 = tắt)",
    "DynamicDataCategoryLabel": "Danh mục đã chọn",
    "DynamicDataValueLabel": "Giá trị đã chọn",
    "DynamicDataSeriesLabel": "Chuỗi đã chọn",
    "DataSourceGroupName": "Nguồn dữ liệu",
    "HideDataSourceButton": "▲ Ẩn nguồn dữ liệu",
    "ConfigureDataSourceButton": "▼ Định cấu hình nguồn dữ liệu",
    "RowsLoadedBadge": "✓ Đã tải {0} hàng",
    "ReadModeLoadError": "Không thể tải dữ liệu: {0}. Chuyển sang chế độ Chỉnh sửa để định cấu hình lại nguồn dữ liệu.",
    "RefreshDataButton": "↻ Làm mới dữ liệu",
    "RefreshingLabel": "Đang làm mới…",
    "RefreshDataTitle": "Tải lại dữ liệu từ nguồn đã định cấu hình",
    "NoDataMessage": "Chưa tải dữ liệu nào. Hãy định cấu hình nguồn dữ liệu ở trên và nhấp vào Tải dữ liệu.",
    "SelectMappingsMessage": "Đã tải dữ liệu ({0} hàng). Vui lòng chọn ánh xạ cột ở trên để hiển thị biểu đồ.",
    "ChartRenderErrorLabel": "Lỗi hiển thị biểu đồ: {0}",
    "UnsupportedChartTypeLabel": "Loại biểu đồ không được hỗ trợ: {0}",
    "ChartAriaLabel": "Biểu đồ trực quan hóa dữ liệu",
    "FilterOperatorLabel": "Toán tử",
    "FilterValueLabel": "Giá trị",
    "FilterOpContains": "chứa",
    "FilterOpEquals": "bằng",
    "FilterOpNotEquals": "không bằng",
    "FilterOpGt": "lớn hơn",
    "FilterOpLt": "nhỏ hơn",
    "FilterOpBetween": "trong khoảng (thấp..cao)",
    "FilterOpIsEmpty": "trống",
    "FilterOpNotEmpty": "không trống",
    "AddFilterButton": "+ Thêm bộ lọc",
    "RemoveFilterButton": "Xóa",
    "SelectValuePlaceholder": "Chọn giá trị…",
    "ViewerFilterOperatorAria": "Toán tử bộ lọc",
    "PaletteColorblindLabel": "Thân thiện với người mù màu",
    "WaterfallGroupName": "Thác nước",
    "WaterfallShowTotalFieldLabel": "Hiển thị cột tổng",
    "WaterfallPositiveColorFieldLabel": "Màu tăng",
    "WaterfallNegativeColorFieldLabel": "Màu giảm",
    "WaterfallTotalColorFieldLabel": "Màu tổng",
    "WaterfallTotalLabel": "Tổng",
    "ExternalFilterGroupName": "Lọc từ phần web khác",
    "ExternalFilterFieldLabel": "Nguồn giá trị bộ lọc",
    "ExternalFilterColumnFieldLabel": "Cột cần lọc",
    "ExternalFilterColumnPlaceholder": "Mặc định là cột trục X",
    "ViewAsTableButton": "Xem dạng bảng",
    "HideTableButton": "Ẩn bảng",
    "ChartKeyboardHint": "Dùng các phím mũi tên để di chuyển giữa các điểm dữ liệu và Enter để chọn một điểm.",
    "ChartPointAnnouncement": "{0}: {1}",
    "Y2ValuePrefixFieldLabel": "Tiền tố giá trị Y2",
    "Y2ValueSuffixFieldLabel": "Hậu tố giá trị Y2",
    "AnnotationsGroupName": "Chú thích",
    "AnnotationsFieldLabel": "Chú thích",
    "AnnotationsPlaceholder": "Thg 1, Ra mắt sản phẩm",
    "AnnotationsHelp": "Mỗi dòng một chú thích: giá trị trục X, dấu phẩy, rồi văn bản ghi chú. Một điểm đánh dấu dọc được vẽ tại giá trị X đó.",
    "BeforeLabel": "Trước",
    "AfterLabel": "Sau",
    "RowLabel": "Hàng {0}",
    "PointsSuffix": " (điểm)",
    "ExportSheetName": "Dữ liệu",
    "RefreshFailedNote": "Lần làm mới gần nhất không thành công: {0}. Đang hiển thị dữ liệu đã tải trước đó.",
    "TruncatedDataNote": "Chỉ hiển thị {0} hàng đầu tiên; nguồn còn nhiều dữ liệu hơn.",
    "ScatterNumericWarning": "Biểu đồ phân tán và bong bóng cần giá trị số. Cột \"{0}\" không có dữ liệu số — hãy chọn cột khác trong phần ánh xạ ở trên.",
    "TimeAxisUnparseableWarning": "Cột trục X \"{0}\" không có giá trị nào có thể phân tích thành ngày. Hãy chuyển Loại trục X sang \"Danh mục\" hoặc ánh xạ một cột ngày.",
    "DataSourceSectionHeader": "Nguồn dữ liệu",
    "SourceUploadLabel": "Tải tệp lên",
    "SourceSharePointListLabel": "Danh sách SharePoint",
    "SourceSharePointFileLabel": "Tệp SharePoint",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Đường dẫn Graph API",
    "GraphPathHelp": "Đường dẫn Microsoft Graph tương đối, ví dụ: /me/memberOf hoặc /reports/getTeamsUserActivityUserCounts(period='D7'). Nguồn này yêu cầu quyền Graph được quản trị viên phê duyệt — tất cả các nguồn dữ liệu khác hoạt động mà không cần các quyền này.",
    "SheetNameLabel": "Trang tính Excel",
    "DelimiterLabel": "Dấu phân tách",
    "DelimiterAutoDetect": "Tự động phát hiện",
    "DelimiterComma": "Dấu phẩy (,)",
    "DelimiterTab": "Tab",
    "DelimiterSemicolon": "Dấu chấm phẩy (;)",
    "DelimiterPipe": "Dấu gạch đứng (|)",
    "SiteUrlLabel": "URL trang (không bắt buộc)",
    "SiteUrlHelp": "Để trống để sử dụng trang hiện tại.",
    "ListNameLabel": "Tên danh sách",
    "LoadingListsLabel": "— Đang tải danh sách…",
    "SelectListPlaceholder": "— Chọn một danh sách —",
    "EnterListNamePlaceholder": "Nhập tên danh sách",
    "ListNameExamplePlaceholder": "ví dụ: Dữ liệu doanh số",
    "ListDiscoveryError": "Không thể tải danh sách — hãy nhập tên thủ công bên dưới.",
    "FileUrlLabel": "URL tệp (CSV/TSV/Excel trong SharePoint)",
    "FileUrlHelp": "URL đầy đủ tới một tệp trong thư viện tài liệu.",
    "ApiUrlLabel": "URL API",
    "DataPathLabel": "Đường dẫn dữ liệu (không bắt buộc)",
    "DataPathHelp": "Đường dẫn phân tách bằng dấu chấm tới mảng trong phản hồi JSON. Để trống nếu gốc là một mảng. Với SharePoint REST API, hãy dùng \"value\".",
    "UploadHelp": "Tải lên tệp CSV, TSV hoặc Excel (.xlsx, .xls).",
    "LoadedFileRowsLabel": "— {0} hàng",
    "ChangeFileButton": "Đổi tệp…",
    "ClearButton": "Xóa",
    "ChooseFileButton": "Chọn tệp…",
    "LoadDataButton": "Tải dữ liệu",
    "LoadingLabel": "Đang tải…",
    "ErrorSelectListName": "Vui lòng chọn hoặc nhập tên danh sách.",
    "ErrorEnterFileUrl": "Vui lòng nhập URL tệp.",
    "ErrorEnterUrl": "Vui lòng nhập URL.",
    "ErrorLoadList": "Không thể tải danh sách SharePoint: {0}",
    "ErrorLoadFile": "Không thể tải tệp: {0}",
    "ErrorFetchData": "Không thể lấy dữ liệu: {0}",
    "ErrorDataPathNotFound": "Không tìm thấy đường dẫn dữ liệu \"{0}\" trong phản hồi.",
    "ErrorUrlReturnedHtml": "URL này trả về một trang web, không phải một tệp. Hãy dùng đường dẫn tải xuống tệp trực tiếp, không dùng URL chia sẻ \"Sao chép liên kết\".",
    "ErrorRequestTimedOut": "Yêu cầu đã hết thời gian chờ. Hãy kiểm tra URL và kết nối mạng của bạn.",
    "ErrorNonJsonResponse": "Không thể phân tích phản hồi dưới dạng JSON.",
    "ErrorUnsupportedFileType": "Loại tệp không được hỗ trợ. Vui lòng tải lên tệp .csv, .tsv, .xlsx hoặc .xls.",
    "ErrorReadFile": "Không thể đọc tệp",
    "ErrorParseFile": "Không thể phân tích tệp",
    "LoadedRowsColumns": "Đã tải {0} hàng với {1} cột.",
    "LoadedRowsColumnsPersist": "Đã tải {0} hàng với {1} cột. Dữ liệu sẽ được giữ lại khi bạn rời khỏi trang.",
    "SizeWarning": "Tập dữ liệu ({0}KB) vượt quá giới hạn lưu giữ 200KB. Biểu đồ sẽ hiển thị dữ liệu trong phiên này nhưng sẽ bị xóa khi tải lại trang. Với tệp lớn, hãy tải lên thư viện SharePoint và dùng nguồn Tệp SharePoint.",
    "ListTruncatedWarning": "Danh sách này có {0} mục trở lên; chỉ {0} mục đầu tiên được tải.",
    "GraphTruncatedWarning": "Kết quả Microsoft Graph này có nhiều trang hơn mức có thể tải; chỉ {0} trang đầu tiên được truy xuất.",
    "CsvParseWarning": "{0} hàng không thể phân tích và đã bị bỏ qua.",
    "ColumnMappingSectionHeader": "Ánh xạ cột",
    "CategoryColumnLabel": "Cột danh mục (X / Nhãn)",
    "LabelColumnLabel": "Cột nhãn",
    "XAxisColumnLabel": "Cột trục X",
    "ValueColumnLabel": "Cột giá trị",
    "YAxisColumnLabel": "Cột trục Y",
    "YAxisColumnsLabel": "Các cột trục Y",
    "YAxisColumnsHelp": "(chọn một hoặc nhiều; nhấp vào mẫu màu để đặt màu)",
    "SelectColumnPlaceholder": "— Chọn cột —",
    "ScatterLabelColumnLabel": "Nhãn điểm",
    "SizeColumnLabel": "Cột kích thước / bán kính",
    "NoSizeColumnOption": "— Không (kích thước cố định) —",
    "SeriesColorTitle": "Màu cho {0}",
    "SeriesTypeTitle": "Loại biểu đồ cho {0}",
    "SeriesTypeDefault": "Mặc định",
    "SeriesTypeBar": "Cột",
    "SeriesTypeLine": "Đường",
    "HistogramColumnLabel": "Cột để chia khoảng (số)",
    "TreemapGroupLabel": "Cột nhóm / nhãn",
    "HeatmapColumnLabel": "Danh mục cột (X)",
    "HeatmapRowLabel": "Danh mục hàng (Y)",
    "AdvancedOptionsClosed": "▼ Tùy chọn nâng cao",
    "AdvancedOptionsOpen": "▲ Tùy chọn nâng cao",
    "ColorByLabel": "Tô màu theo cột",
    "ColorByHelp": "Tô màu các điểm theo danh mục thay vì theo chuỗi.",
    "TooltipColumnsLabel": "Cột chú giải công cụ",
    "TooltipColumnsHelp": "(các cột bổ sung hiển thị khi di chuột qua một điểm dữ liệu)",
    "DrillLevelLabel": "Cấp khoan sâu {0}",
    "DrillDownHelp": "Xác định phân cấp cột để bật khoan sâu bằng cách nhấp (ví dụ: Khu vực → Quốc gia → Thành phố). Các giá trị được tổng hợp ở mỗi cấp.",
    "BookmarksLabel": "Dấu trang",
    "BookmarkNameLabel": "Tên dấu trang",
    "BookmarkNamePlaceholder": "ví dụ: Top 10 theo khu vực",
    "SaveBookmarkButton": "Lưu chế độ xem hiện tại",
    "ApplyBookmarkButton": "Áp dụng",
    "DeleteBookmarkButton": "Xóa",
    "ApplyBookmarkPlaceholder": "— Áp dụng một dấu trang —",
    "DataControlsSectionHeader": "Điều khiển dữ liệu",
    "SortByColumnLabel": "Sắp xếp theo cột",
    "NoneOption": "— Không có —",
    "SortDirectionLabel": "Hướng sắp xếp",
    "AscendingOption": "Tăng dần",
    "DescendingOption": "Giảm dần",
    "RowLimitLabel": "Giới hạn hàng (0 = tất cả)",
    "FilterColumnLabel": "Cột bộ lọc",
    "FilterContainsLabel": "Bộ lọc: chứa",
    "FilterValuePlaceholder": "Giá trị bộ lọc…",
    "GroupByLabel": "Nhóm theo cột",
    "AggregationLabel": "Tổng hợp",
    "GroupByHelp": "Các cột số được tổng hợp theo từng nhóm. Đếm sẽ thêm một cột \"Đếm\".",
    "AggNone": "Không có",
    "AggSum": "Tổng",
    "AggAvg": "Trung bình",
    "AggCount": "Đếm",
    "AggMin": "Nhỏ nhất",
    "AggMax": "Lớn nhất",
    "DataTableHeader": "Bảng dữ liệu ({0} hàng)",
    "PrevPageButton": "← Trước",
    "NextPageButton": "Sau →",
    "PageOfLabel": "Trang {0} / {1}",
    "ExportLabel": "Xuất:",
    "ExportPngTitle": "Tải biểu đồ xuống dưới dạng ảnh PNG",
    "ExportJpegTitle": "Tải biểu đồ xuống dưới dạng ảnh JPEG",
    "ExportCsvTitle": "Tải dữ liệu xuống dưới dạng CSV",
    "ExportExcelTitle": "Tải dữ liệu xuống dưới dạng sổ làm việc Excel"
  }
});
