define([], function() {
  return {
    "PropertyPaneDescription": "配置数据可视化",
    "HeaderGroupName": "标题",
    "WebPartHeaderFieldLabel": "标题文本",
    "WebPartHeaderPlaceholder": "例如：销售仪表板",
    "ShowWebPartHeaderFieldLabel": "显示标题",
    "ChartSettingsGroupName": "图表设置",
    "ChartTitleFieldLabel": "图表标题",
    "ChartTypeFieldLabel": "图表类型",
    "LegendPositionFieldLabel": "图例位置",
    "ChartHeightFieldLabel": "图表高度(px)",
    "ShowLegendFieldLabel": "显示图例",
    "StackedFieldLabel": "堆积(条形/折线)",
    "ShowDataTableFieldLabel": "显示数据表",
    "ShowExportBarFieldLabel": "显示导出栏",
    "XAxisLabelFieldLabel": "X 轴标签(可选)",
    "XAxisPlaceholder": "默认为所选列",
    "YAxisLabelFieldLabel": "Y 轴标签(可选)",
    "YAxisPlaceholder": "默认为所选列",
    "ChartGroupStandard": "标准图表",
    "ChartGroupSpecialized": "专用图表",
    "ChartTypeBarLabel": "柱形图(垂直)",
    "ChartTypeHorizontalBarLabel": "条形图(水平)",
    "ChartTypeLineLabel": "折线图",
    "ChartTypeAreaLabel": "面积图",
    "ChartTypeScatterLabel": "散点图",
    "ChartTypePieLabel": "饼图",
    "ChartTypeDoughnutLabel": "圆环图",
    "ChartTypeBubbleLabel": "气泡图",
    "ChartTypeRadarLabel": "雷达图",
    "ChartTypeKpiLabel": "KPI 磁贴",
    "ChartTypeHistogramLabel": "直方图",
    "ChartTypeWaterfallLabel": "瀑布图",
    "ChartTypeBoxplotLabel": "箱线图",
    "ChartTypeViolinLabel": "小提琴图",
    "ChartTypeBeforeAfterLabel": "前后对比图",
    "ChartTypeTreemapLabel": "树状图",
    "ChartTypeHeatmapLabel": "热力图",
    "HistogramBinsFieldLabel": "直方图分箱数",
    "AppearancePageDescription": "颜色、标签和坐标轴",
    "AdvancedPageDescription": "分析、参考线、交互和数据刷新",
    "LegendTopLabel": "顶部",
    "LegendBottomLabel": "底部",
    "LegendLeftLabel": "左侧",
    "LegendRightLabel": "右侧",
    "ColorsGroupName": "颜色",
    "ColorPaletteFieldLabel": "调色板",
    "PaletteOfficeLabel": "Office(默认)",
    "PaletteVibrantLabel": "鲜艳",
    "PalettePastelLabel": "柔和",
    "PaletteMonochromeLabel": "单色",
    "PaletteTrafficLightLabel": "红绿灯",
    "PaletteWarmLabel": "暖色",
    "PaletteCoolLabel": "冷色",
    "DataLabelsGroupName": "数据标签和格式设置",
    "ShowDataLabelsFieldLabel": "显示数据标签",
    "ValuePrefixFieldLabel": "值前缀",
    "ValuePrefixPlaceholder": "例如：$",
    "ValueSuffixFieldLabel": "值后缀",
    "ValueSuffixPlaceholder": "例如：%",
    "ValueDecimalsFieldLabel": "小数位数",
    "AbbreviateNumbersFieldLabel": "缩写数字(K/M)",
    "AxesGridGroupName": "坐标轴和网格",
    "YAxisMinFieldLabel": "Y 轴最小值",
    "YAxisMaxFieldLabel": "Y 轴最大值",
    "AutoPlaceholder": "自动",
    "NumericValidationError": "请输入数字，或留空以自动确定。",
    "ColorValidationError": "请输入十六进制颜色(例如 #d13438)，或留空以使用默认值。",
    "LogScaleFieldLabel": "对数刻度(Y)",
    "LogScaleXFieldLabel": "对数刻度(X)",
    "StepLineFieldLabel": "阶梯插值",
    "ShowGridLinesFieldLabel": "显示网格线",
    "XLabelRotationFieldLabel": "X 标签旋转(度)",
    "XAxisTypeFieldLabel": "X 轴类型",
    "XAxisTypeAuto": "自动检测",
    "XAxisTypeCategory": "类别",
    "XAxisTypeTime": "时间(日期)",
    "AnalyticsGroupName": "分析",
    "TrendlineFieldLabel": "趋势线",
    "TrendlineNone": "无",
    "TrendlineLinear": "线性",
    "TrendlineMovingAverage": "移动平均",
    "TrendWindowFieldLabel": "移动平均窗口",
    "TrendSuffix": "(趋势)",
    "ForecastPeriodsFieldLabel": "预测周期(线性趋势线)",
    "ReferenceLineGroupName": "参考线",
    "ReferenceLineTypeFieldLabel": "参考线",
    "ReferenceLineValueFieldLabel": "固定值",
    "ReferenceLineColorFieldLabel": "线条颜色(十六进制)",
    "RefLineFixed": "固定值",
    "RefLineMean": "平均值",
    "RefLineMedian": "中位数",
    "DualAxisGroupName": "双 Y 轴",
    "Y2ColumnsFieldLabel": "右轴系列(以逗号分隔的列名)",
    "Y2ColumnsPlaceholder": "例如：利润率,增长率",
    "Y2AxisLabelFieldLabel": "右轴标签",
    "LogScaleY2FieldLabel": "对数刻度(右轴)",
    "ErrorBarsGroupName": "误差线",
    "ErrorBarTypeFieldLabel": "误差线类型",
    "ErrorBarTypeNone": "无",
    "ErrorBarTypeCustom": "自定义列(±)",
    "ErrorBarTypeSd": "标准差(计算得出)",
    "ErrorBarTypeSem": "均值标准误差(计算得出)",
    "ErrorBarColumnFieldLabel": "误差值列",
    "SignificanceGroupName": "显著性括号",
    "SignificancePairsFieldLabel": "括号对",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "每行一个括号：列1,列2,标签  — 例如 GroupA,GroupB,*  或  GroupA,GroupB,p<0.05  (也接受 JSON 数组)",
    "BeforeAfterColumnsError": "前后对比图需要恰好 2 个 Y 列 — 一个用于“之前”的值，一个用于“之后”的值。",
    "InteractivityGroupName": "交互",
    "ShowViewerFiltersFieldLabel": "向查看者显示筛选器",
    "DetailsOnDemandFieldLabel": "单击时显示数据行",
    "ShowDataPointsFieldLabel": "在柱形上叠加数据点",
    "ShowBubbleSizeLegendFieldLabel": "显示气泡大小图例",
    "ViewerFilterLabel": "筛选:",
    "ViewerFilterColumnAria": "筛选列",
    "ViewerFilterValueAria": "筛选值",
    "DrillAllLabel": "全部",
    "DetailsChipLabel": "详细信息：{0}({1} 行)",
    "KpiSubLabel": "{0} • {1} • {2} 行",
    "ConditionalGroupName": "条件格式",
    "ThresholdValueFieldLabel": "阈值",
    "ThresholdValuePlaceholder": "关闭",
    "ThresholdDirectionFieldLabel": "突出显示值",
    "ThresholdBelow": "低于阈值",
    "ThresholdAbove": "高于阈值",
    "ThresholdColorFieldLabel": "突出显示颜色(十六进制)",
    "DataRefreshGroupName": "数据和刷新",
    "RefreshIntervalFieldLabel": "自动刷新间隔(分钟，0 = 关闭)",
    "CacheMinutesFieldLabel": "缓存数据(分钟，0 = 关闭)",
    "DynamicDataCategoryLabel": "所选类别",
    "DynamicDataValueLabel": "所选值",
    "DynamicDataSeriesLabel": "所选系列",
    "DataSourceGroupName": "数据源",
    "HideDataSourceButton": "▲ 隐藏数据源",
    "ConfigureDataSourceButton": "▼ 配置数据源",
    "RowsLoadedBadge": "✓ 已加载 {0} 行",
    "ReadModeLoadError": "无法加载数据：{0}。请切换到编辑模式以重新配置数据源。",
    "RefreshDataButton": "↻ 刷新数据",
    "RefreshingLabel": "正在刷新…",
    "RefreshDataTitle": "从已配置的源重新加载数据",
    "NoDataMessage": "尚未加载数据。请在上方配置数据源，然后单击“加载数据”。",
    "SelectMappingsMessage": "数据已加载({0} 行)。请在上方选择列映射以显示图表。",
    "ChartRenderErrorLabel": "图表呈现错误：{0}",
    "UnsupportedChartTypeLabel": "不支持的图表类型：{0}",
    "ChartAriaLabel": "数据可视化图表",
    "FilterOperatorLabel": "运算符",
    "FilterValueLabel": "值",
    "FilterOpContains": "包含",
    "FilterOpEquals": "等于",
    "FilterOpNotEquals": "不等于",
    "FilterOpGt": "大于",
    "FilterOpLt": "小于",
    "FilterOpBetween": "介于(低..高)",
    "FilterOpIsEmpty": "为空",
    "FilterOpNotEmpty": "不为空",
    "AddFilterButton": "+ 添加筛选器",
    "RemoveFilterButton": "删除",
    "SelectValuePlaceholder": "选择值…",
    "ViewerFilterOperatorAria": "筛选运算符",
    "PaletteColorblindLabel": "色盲友好",
    "WaterfallGroupName": "瀑布图",
    "WaterfallShowTotalFieldLabel": "显示总计柱",
    "WaterfallPositiveColorFieldLabel": "增加颜色",
    "WaterfallNegativeColorFieldLabel": "减少颜色",
    "WaterfallTotalColorFieldLabel": "总计颜色",
    "WaterfallTotalLabel": "总计",
    "ExternalFilterGroupName": "来自其他 Web 部件的筛选器",
    "ExternalFilterFieldLabel": "筛选值来源",
    "ExternalFilterColumnFieldLabel": "要筛选的列",
    "ExternalFilterColumnPlaceholder": "默认为 X 轴列",
    "ViewAsTableButton": "以表格形式查看",
    "HideTableButton": "隐藏表格",
    "ChartKeyboardHint": "使用箭头键在数据点之间移动，按 Enter 键选择数据点。",
    "ChartPointAnnouncement": "{0}：{1}",
    "Y2ValuePrefixFieldLabel": "Y2 值前缀",
    "Y2ValueSuffixFieldLabel": "Y2 值后缀",
    "AnnotationsGroupName": "批注",
    "AnnotationsFieldLabel": "批注",
    "AnnotationsPlaceholder": "Jan, Product launch",
    "AnnotationsHelp": "每行一条：X 轴值、逗号，然后是批注文本。将在该 X 值处绘制一条垂直标记。",
    "BeforeLabel": "之前",
    "AfterLabel": "之后",
    "RowLabel": "第 {0} 行",
    "PointsSuffix": "(点)",
    "ExportSheetName": "数据",
    "RefreshFailedNote": "上次刷新失败：{0}。正在显示之前加载的数据。",
    "TruncatedDataNote": "仅显示前 {0} 行；数据源中还有更多数据。",
    "ScatterNumericWarning": "散点图和气泡图需要数值。列“{0}”没有数值数据 — 请在上方的映射中选择其他列。",
    "TimeAxisUnparseableWarning": "X 轴列“{0}”中没有可解析为日期的值。请将 X 轴类型切换为“类别”，或映射日期列。",
    "DataSourceSectionHeader": "数据源",
    "SourceUploadLabel": "上传文件",
    "SourceSharePointListLabel": "SharePoint 列表",
    "SourceSharePointFileLabel": "SharePoint 文件",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API 路径",
    "GraphPathHelp": "相对 Microsoft Graph 路径，例如 /me/memberOf 或 /reports/getTeamsUserActivityUserCounts(period='D7')。此数据源需要管理员批准的 Graph 权限 — 所有其他数据源无需这些权限即可使用。",
    "SheetNameLabel": "Excel 工作表",
    "DelimiterLabel": "分隔符",
    "DelimiterAutoDetect": "自动检测",
    "DelimiterComma": "逗号(,)",
    "DelimiterTab": "制表符",
    "DelimiterSemicolon": "分号(;)",
    "DelimiterPipe": "竖线(|)",
    "SiteUrlLabel": "站点 URL(可选)",
    "SiteUrlHelp": "留空以使用当前站点。",
    "ListNameLabel": "列表名称",
    "LoadingListsLabel": "— 正在加载列表…",
    "SelectListPlaceholder": "— 选择列表 —",
    "EnterListNamePlaceholder": "输入列表名称",
    "ListNameExamplePlaceholder": "例如：销售数据",
    "ListDiscoveryError": "无法加载列表 — 请在下方手动输入名称。",
    "FileUrlLabel": "文件 URL(SharePoint 中的 CSV/TSV/Excel)",
    "FileUrlHelp": "文档库中文件的完整 URL。",
    "ApiUrlLabel": "API URL",
    "DataPathLabel": "数据路径(可选)",
    "DataPathHelp": "指向 JSON 响应中数组的以点分隔的路径。如果根节点是数组，请留空。对于 SharePoint REST API，请使用 \"value\"。",
    "UploadHelp": "上传 CSV、TSV 或 Excel(.xlsx、.xls)文件。",
    "LoadedFileRowsLabel": "— {0} 行",
    "ChangeFileButton": "更改文件…",
    "ClearButton": "清除",
    "ChooseFileButton": "选择文件…",
    "LoadDataButton": "加载数据",
    "LoadingLabel": "正在加载…",
    "ErrorSelectListName": "请选择或输入列表名称。",
    "ErrorEnterFileUrl": "请输入文件 URL。",
    "ErrorEnterUrl": "请输入 URL。",
    "ErrorLoadList": "无法加载 SharePoint 列表：{0}",
    "ErrorLoadFile": "无法加载文件：{0}",
    "ErrorFetchData": "无法获取数据：{0}",
    "ErrorDataPathNotFound": "在响应中未找到数据路径 \"{0}\"。",
    "ErrorUrlReturnedHtml": "此 URL 返回的是网页，而不是文件。请使用直接的文件下载路径，而不是“复制链接”共享 URL。",
    "ErrorRequestTimedOut": "请求超时。请检查 URL 和网络连接。",
    "ErrorNonJsonResponse": "无法将响应解析为 JSON。",
    "ErrorUnsupportedFileType": "不支持的文件类型。请上传 .csv、.tsv、.xlsx 或 .xls 文件。",
    "ErrorReadFile": "无法读取文件",
    "ErrorParseFile": "无法解析文件",
    "LoadedRowsColumns": "已加载 {0} 行 {1} 列。",
    "LoadedRowsColumnsPersist": "已加载 {0} 行 {1} 列。离开页面后数据将保留。",
    "SizeWarning": "数据集({0}KB)超过 200KB 的持久化限制。图表将在本次会话中显示数据，但会在页面重新加载时清除。对于大型文件，请上传到 SharePoint 库并使用“SharePoint 文件”数据源。",
    "ListTruncatedWarning": "此列表有 {0} 个或更多项目；仅加载了前 {0} 个。",
    "GraphTruncatedWarning": "此 Microsoft Graph 结果的页数超出可加载范围；仅检索了前 {0} 页。",
    "CsvParseWarning": "有 {0} 行无法解析，已跳过。",
    "ColumnMappingSectionHeader": "列映射",
    "CategoryColumnLabel": "类别列(X / 标签)",
    "LabelColumnLabel": "标签列",
    "XAxisColumnLabel": "X 轴列",
    "ValueColumnLabel": "值列",
    "YAxisColumnLabel": "Y 轴列",
    "YAxisColumnsLabel": "Y 轴列",
    "YAxisColumnsHelp": "(选择一个或多个；单击色板以设置颜色)",
    "SelectColumnPlaceholder": "— 选择列 —",
    "ScatterLabelColumnLabel": "点标签",
    "SizeColumnLabel": "大小 / 半径列",
    "NoSizeColumnOption": "— 无(固定大小) —",
    "SeriesColorTitle": "{0} 的颜色",
    "SeriesTypeTitle": "{0} 的图表类型",
    "SeriesTypeDefault": "默认",
    "SeriesTypeBar": "柱形",
    "SeriesTypeLine": "折线",
    "HistogramColumnLabel": "要分箱的列(数值)",
    "TreemapGroupLabel": "分组 / 标签列",
    "HeatmapColumnLabel": "列(X)类别",
    "HeatmapRowLabel": "行(Y)类别",
    "AdvancedOptionsClosed": "▼ 高级选项",
    "AdvancedOptionsOpen": "▲ 高级选项",
    "ColorByLabel": "按列着色",
    "ColorByHelp": "按类别而不是按系列为数据点着色。",
    "TooltipColumnsLabel": "工具提示列",
    "TooltipColumnsHelp": "(悬停在数据点上时显示的额外列)",
    "DrillLevelLabel": "钻取级别 {0}",
    "DrillDownHelp": "定义列层次结构以启用单击钻取(例如 地区 → 国家/地区 → 城市)。值将在每个级别进行聚合。",
    "BookmarksLabel": "书签",
    "BookmarkNameLabel": "书签名称",
    "BookmarkNamePlaceholder": "例如：按地区排名前 10",
    "SaveBookmarkButton": "保存当前视图",
    "ApplyBookmarkButton": "应用",
    "DeleteBookmarkButton": "删除",
    "ApplyBookmarkPlaceholder": "— 应用书签 —",
    "DataControlsSectionHeader": "数据控件",
    "SortByColumnLabel": "按列排序",
    "NoneOption": "— 无 —",
    "SortDirectionLabel": "排序方向",
    "AscendingOption": "升序",
    "DescendingOption": "降序",
    "RowLimitLabel": "行数限制(0 = 全部)",
    "FilterColumnLabel": "筛选列",
    "FilterContainsLabel": "筛选：包含",
    "FilterValuePlaceholder": "筛选值…",
    "GroupByLabel": "按列分组",
    "AggregationLabel": "聚合",
    "GroupByHelp": "数值列按组聚合。“计数”会添加一个“计数”列。",
    "AggNone": "无",
    "AggSum": "求和",
    "AggAvg": "平均值",
    "AggCount": "计数",
    "AggMin": "最小值",
    "AggMax": "最大值",
    "DataTableHeader": "数据表({0} 行)",
    "PrevPageButton": "← 上一页",
    "NextPageButton": "下一页 →",
    "PageOfLabel": "第 {0} 页，共 {1} 页",
    "ExportLabel": "导出：",
    "ExportPngTitle": "将图表下载为 PNG 图像",
    "ExportJpegTitle": "将图表下载为 JPEG 图像",
    "ExportCsvTitle": "将数据下载为 CSV",
    "ExportExcelTitle": "将数据下载为 Excel 工作簿"
  }
});
