define([], function() {
  return {
    "PropertyPaneDescription": "設定資料視覺效果",
    "HeaderGroupName": "標題",
    "WebPartHeaderFieldLabel": "標題文字",
    "WebPartHeaderPlaceholder": "例如：銷售儀表板",
    "ShowWebPartHeaderFieldLabel": "顯示標題",
    "ChartSettingsGroupName": "圖表設定",
    "ChartTitleFieldLabel": "圖表標題",
    "ChartTypeFieldLabel": "圖表類型",
    "LegendPositionFieldLabel": "圖例位置",
    "ChartHeightFieldLabel": "圖表高度 (px)",
    "ShowLegendFieldLabel": "顯示圖例",
    "StackedFieldLabel": "堆疊 (橫條圖/折線圖)",
    "ShowDataTableFieldLabel": "顯示資料表",
    "ShowExportBarFieldLabel": "顯示匯出列",
    "XAxisLabelFieldLabel": "X 軸標籤 (選擇性)",
    "XAxisPlaceholder": "預設為所選資料行",
    "YAxisLabelFieldLabel": "Y 軸標籤 (選擇性)",
    "YAxisPlaceholder": "預設為所選資料行",
    "ChartGroupStandard": "標準圖表",
    "ChartGroupSpecialized": "專用圖表",
    "ChartTypeBarLabel": "直條圖 (垂直)",
    "ChartTypeHorizontalBarLabel": "橫條圖 (水平)",
    "ChartTypeLineLabel": "折線圖",
    "ChartTypeAreaLabel": "區域圖",
    "ChartTypeScatterLabel": "散佈圖",
    "ChartTypePieLabel": "圓形圖",
    "ChartTypeDoughnutLabel": "環圈圖",
    "ChartTypeBubbleLabel": "泡泡圖",
    "ChartTypeRadarLabel": "雷達圖",
    "ChartTypeKpiLabel": "KPI 磚",
    "ChartTypeHistogramLabel": "直方圖",
    "ChartTypeWaterfallLabel": "瀑布圖",
    "ChartTypeBoxplotLabel": "盒鬚圖",
    "ChartTypeViolinLabel": "小提琴圖",
    "ChartTypeBeforeAfterLabel": "前後對照圖",
    "ChartTypeTreemapLabel": "矩形樹狀結構圖",
    "ChartTypeHeatmapLabel": "熱度圖",
    "HistogramBinsFieldLabel": "直方圖分組數",
    "AppearancePageDescription": "色彩、標籤和座標軸",
    "AdvancedPageDescription": "分析、參考線、互動和資料重新整理",
    "LegendTopLabel": "頂端",
    "LegendBottomLabel": "底端",
    "LegendLeftLabel": "左側",
    "LegendRightLabel": "右側",
    "ColorsGroupName": "色彩",
    "ColorPaletteFieldLabel": "調色盤",
    "PaletteOfficeLabel": "Office (預設)",
    "PaletteVibrantLabel": "鮮豔",
    "PalettePastelLabel": "粉彩",
    "PaletteMonochromeLabel": "單色",
    "PaletteTrafficLightLabel": "紅綠燈",
    "PaletteWarmLabel": "暖色",
    "PaletteCoolLabel": "冷色",
    "DataLabelsGroupName": "資料標籤與格式設定",
    "ShowDataLabelsFieldLabel": "顯示資料標籤",
    "ValuePrefixFieldLabel": "值前置詞",
    "ValuePrefixPlaceholder": "例如：$",
    "ValueSuffixFieldLabel": "值後置詞",
    "ValueSuffixPlaceholder": "例如：%",
    "ValueDecimalsFieldLabel": "小數位數",
    "AbbreviateNumbersFieldLabel": "縮寫數字 (K/M)",
    "AxesGridGroupName": "座標軸與格線",
    "YAxisMinFieldLabel": "Y 軸最小值",
    "YAxisMaxFieldLabel": "Y 軸最大值",
    "AutoPlaceholder": "自動",
    "NumericValidationError": "請輸入數字，或保留空白以自動決定。",
    "ColorValidationError": "請輸入十六進位色彩 (例如 #d13438)，或保留空白以使用預設值。",
    "LogScaleFieldLabel": "對數刻度 (Y)",
    "LogScaleXFieldLabel": "對數刻度 (X)",
    "StepLineFieldLabel": "階梯內插",
    "ShowGridLinesFieldLabel": "顯示格線",
    "XLabelRotationFieldLabel": "X 標籤旋轉 (度)",
    "XAxisTypeFieldLabel": "X 軸類型",
    "XAxisTypeAuto": "自動偵測",
    "XAxisTypeCategory": "類別",
    "XAxisTypeTime": "時間 (日期)",
    "AnalyticsGroupName": "分析",
    "TrendlineFieldLabel": "趨勢線",
    "TrendlineNone": "無",
    "TrendlineLinear": "線性",
    "TrendlineMovingAverage": "移動平均",
    "TrendWindowFieldLabel": "移動平均視窗",
    "TrendSuffix": " (趨勢)",
    "ForecastPeriodsFieldLabel": "預測期間 (線性趨勢線)",
    "ReferenceLineGroupName": "參考線",
    "ReferenceLineTypeFieldLabel": "參考線",
    "ReferenceLineValueFieldLabel": "固定值",
    "ReferenceLineColorFieldLabel": "線條色彩 (十六進位)",
    "RefLineFixed": "固定值",
    "RefLineMean": "平均值",
    "RefLineMedian": "中位數",
    "DualAxisGroupName": "雙 Y 軸",
    "Y2ColumnsFieldLabel": "右軸數列 (以逗號分隔的資料行名稱)",
    "Y2ColumnsPlaceholder": "例如：利潤率,成長率",
    "Y2AxisLabelFieldLabel": "右軸標籤",
    "LogScaleY2FieldLabel": "對數刻度 (右軸)",
    "ErrorBarsGroupName": "誤差線",
    "ErrorBarTypeFieldLabel": "誤差線類型",
    "ErrorBarTypeNone": "無",
    "ErrorBarTypeCustom": "自訂資料行 (±)",
    "ErrorBarTypeSd": "標準差 (計算)",
    "ErrorBarTypeSem": "平均值標準誤差 (計算)",
    "ErrorBarColumnFieldLabel": "誤差值資料行",
    "SignificanceGroupName": "顯著性括弧",
    "SignificancePairsFieldLabel": "括弧配對",
    "SignificancePairsPlaceholder": "A,B,*\nC,D,**",
    "SignificancePairsHelp": "每行一個括弧：資料行1,資料行2,標籤  — 例如 GroupA,GroupB,*  或  GroupA,GroupB,p<0.05  (也接受 JSON 陣列)",
    "BeforeAfterColumnsError": "前後對照圖需要剛好 2 個 Y 資料行 — 一個用於「之前」的值，一個用於「之後」的值。",
    "InteractivityGroupName": "互動",
    "ShowViewerFiltersFieldLabel": "向檢視者顯示篩選",
    "DetailsOnDemandFieldLabel": "按一下時顯示資料列",
    "ShowDataPointsFieldLabel": "在直條上疊加資料點",
    "ShowBubbleSizeLegendFieldLabel": "顯示泡泡大小圖例",
    "ViewerFilterLabel": "篩選：",
    "ViewerFilterColumnAria": "篩選資料行",
    "ViewerFilterValueAria": "篩選值",
    "DrillAllLabel": "全部",
    "DetailsChipLabel": "詳細資料：{0} ({1} 列)",
    "KpiSubLabel": "{0} • {1} • {2} 列",
    "ConditionalGroupName": "條件式格式設定",
    "ThresholdValueFieldLabel": "臨界值",
    "ThresholdValuePlaceholder": "關閉",
    "ThresholdDirectionFieldLabel": "醒目提示值",
    "ThresholdBelow": "低於臨界值",
    "ThresholdAbove": "高於臨界值",
    "ThresholdColorFieldLabel": "醒目提示色彩 (十六進位)",
    "DataRefreshGroupName": "資料與重新整理",
    "RefreshIntervalFieldLabel": "自動重新整理間隔 (分鐘，0 = 關閉)",
    "CacheMinutesFieldLabel": "快取資料 (分鐘，0 = 關閉)",
    "DynamicDataCategoryLabel": "所選類別",
    "DynamicDataValueLabel": "所選值",
    "DynamicDataSeriesLabel": "所選數列",
    "DataSourceGroupName": "資料來源",
    "HideDataSourceButton": "▲ 隱藏資料來源",
    "ConfigureDataSourceButton": "▼ 設定資料來源",
    "RowsLoadedBadge": "✓ 已載入 {0} 列",
    "ReadModeLoadError": "無法載入資料：{0}。請切換至編輯模式以重新設定資料來源。",
    "RefreshDataButton": "↻ 重新整理資料",
    "RefreshingLabel": "正在重新整理…",
    "RefreshDataTitle": "從已設定的來源重新載入資料",
    "NoDataMessage": "尚未載入資料。請在上方設定資料來源，然後按一下 [載入資料]。",
    "SelectMappingsMessage": "已載入資料 ({0} 列)。請在上方選取資料行對應以顯示圖表。",
    "ChartRenderErrorLabel": "圖表轉譯錯誤：{0}",
    "UnsupportedChartTypeLabel": "不支援的圖表類型：{0}",
    "ChartAriaLabel": "資料視覺效果圖表",
    "FilterOperatorLabel": "運算子",
    "FilterValueLabel": "值",
    "FilterOpContains": "包含",
    "FilterOpEquals": "等於",
    "FilterOpNotEquals": "不等於",
    "FilterOpGt": "大於",
    "FilterOpLt": "小於",
    "FilterOpBetween": "介於 (低..高)",
    "FilterOpIsEmpty": "為空白",
    "FilterOpNotEmpty": "不是空白",
    "AddFilterButton": "+ 新增篩選",
    "RemoveFilterButton": "移除",
    "SelectValuePlaceholder": "選取值…",
    "ViewerFilterOperatorAria": "篩選運算子",
    "PaletteColorblindLabel": "色盲適用",
    "WaterfallGroupName": "瀑布圖",
    "WaterfallShowTotalFieldLabel": "顯示總計橫條",
    "WaterfallPositiveColorFieldLabel": "增加色彩",
    "WaterfallNegativeColorFieldLabel": "減少色彩",
    "WaterfallTotalColorFieldLabel": "總計色彩",
    "WaterfallTotalLabel": "總計",
    "ExternalFilterGroupName": "來自其他網頁組件的篩選",
    "ExternalFilterFieldLabel": "篩選值來源",
    "ExternalFilterColumnFieldLabel": "要篩選的資料行",
    "ExternalFilterColumnPlaceholder": "預設為 X 軸資料行",
    "ViewAsTableButton": "以表格檢視",
    "HideTableButton": "隱藏表格",
    "ChartKeyboardHint": "使用方向鍵在資料點之間移動，按 Enter 鍵選取資料點。",
    "ChartPointAnnouncement": "{0}：{1}",
    "Y2ValuePrefixFieldLabel": "Y2 值前置詞",
    "Y2ValueSuffixFieldLabel": "Y2 值後置詞",
    "AnnotationsGroupName": "註解",
    "AnnotationsFieldLabel": "註解",
    "AnnotationsPlaceholder": "Jan, Product launch",
    "AnnotationsHelp": "每行一則：X 軸值、逗號，然後是註解文字。系統會在該 X 值處繪製垂直標記。",
    "BeforeLabel": "之前",
    "AfterLabel": "之後",
    "RowLabel": "第 {0} 列",
    "PointsSuffix": " (點)",
    "ExportSheetName": "資料",
    "RefreshFailedNote": "上次重新整理失敗：{0}。正在顯示先前載入的資料。",
    "TruncatedDataNote": "僅顯示前 {0} 列；來源中還有更多資料。",
    "ScatterNumericWarning": "散佈圖和泡泡圖需要數值。資料行「{0}」沒有數值資料 — 請在上方的對應中選擇其他資料行。",
    "TimeAxisUnparseableWarning": "X 軸資料行「{0}」中沒有可剖析為日期的值。請將 X 軸類型切換為「類別」，或對應日期資料行。",
    "DataSourceSectionHeader": "資料來源",
    "SourceUploadLabel": "上傳檔案",
    "SourceSharePointListLabel": "SharePoint 清單",
    "SourceSharePointFileLabel": "SharePoint 檔案",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API 路徑",
    "GraphPathHelp": "相對的 Microsoft Graph 路徑，例如 /me/memberOf 或 /reports/getTeamsUserActivityUserCounts(period='D7')。此來源需要系統管理員核准的 Graph 權限 — 所有其他資料來源不需要這些權限即可運作。",
    "SheetNameLabel": "Excel 工作表",
    "DelimiterLabel": "分隔符號",
    "DelimiterAutoDetect": "自動偵測",
    "DelimiterComma": "逗號 (,)",
    "DelimiterTab": "定位字元",
    "DelimiterSemicolon": "分號 (;)",
    "DelimiterPipe": "直線 (|)",
    "SiteUrlLabel": "網站 URL (選擇性)",
    "SiteUrlHelp": "保留空白以使用目前的網站。",
    "ListNameLabel": "清單名稱",
    "LoadingListsLabel": "— 正在載入清單…",
    "SelectListPlaceholder": "— 選取清單 —",
    "EnterListNamePlaceholder": "輸入清單名稱",
    "ListNameExamplePlaceholder": "例如：銷售資料",
    "ListDiscoveryError": "無法載入清單 — 請在下方手動輸入名稱。",
    "FileUrlLabel": "檔案 URL (SharePoint 中的 CSV/TSV/Excel)",
    "FileUrlHelp": "文件庫中檔案的完整 URL。",
    "ApiUrlLabel": "API URL",
    "DataPathLabel": "資料路徑 (選擇性)",
    "DataPathHelp": "指向 JSON 回應中陣列的以點分隔路徑。如果根是陣列，請保留空白。對於 SharePoint REST API，請使用 \"value\"。",
    "UploadHelp": "上傳 CSV、TSV 或 Excel (.xlsx、.xls) 檔案。",
    "LoadedFileRowsLabel": "— {0} 列",
    "ChangeFileButton": "變更檔案…",
    "ClearButton": "清除",
    "ChooseFileButton": "選擇檔案…",
    "LoadDataButton": "載入資料",
    "LoadingLabel": "正在載入…",
    "ErrorSelectListName": "請選取或輸入清單名稱。",
    "ErrorEnterFileUrl": "請輸入檔案 URL。",
    "ErrorEnterUrl": "請輸入 URL。",
    "ErrorLoadList": "無法載入 SharePoint 清單：{0}",
    "ErrorLoadFile": "無法載入檔案：{0}",
    "ErrorFetchData": "無法擷取資料：{0}",
    "ErrorDataPathNotFound": "在回應中找不到資料路徑 \"{0}\"。",
    "ErrorUrlReturnedHtml": "此 URL 傳回的是網頁，而不是檔案。請使用直接的檔案下載路徑，而不是「複製連結」共用 URL。",
    "ErrorRequestTimedOut": "要求已逾時。請檢查 URL 和網路連線。",
    "ErrorNonJsonResponse": "無法將回應剖析為 JSON。",
    "ErrorUnsupportedFileType": "不支援的檔案類型。請上傳 .csv、.tsv、.xlsx 或 .xls 檔案。",
    "ErrorReadFile": "無法讀取檔案",
    "ErrorParseFile": "無法剖析檔案",
    "LoadedRowsColumns": "已載入 {0} 列 {1} 個資料行。",
    "LoadedRowsColumnsPersist": "已載入 {0} 列 {1} 個資料行。離開頁面後資料將會保留。",
    "SizeWarning": "資料集 ({0}KB) 超過 200KB 的保存限制。圖表將在此工作階段中顯示資料，但會在頁面重新載入時清除。對於大型檔案，請上傳至 SharePoint 文件庫並使用 SharePoint 檔案來源。",
    "ListTruncatedWarning": "此清單有 {0} 個或更多項目；僅載入前 {0} 個。",
    "GraphTruncatedWarning": "此 Microsoft Graph 結果的頁數超過可載入的範圍；僅擷取前 {0} 頁。",
    "CsvParseWarning": "有 {0} 列無法剖析，已略過。",
    "ColumnMappingSectionHeader": "資料行對應",
    "CategoryColumnLabel": "類別資料行 (X / 標籤)",
    "LabelColumnLabel": "標籤資料行",
    "XAxisColumnLabel": "X 軸資料行",
    "ValueColumnLabel": "值資料行",
    "YAxisColumnLabel": "Y 軸資料行",
    "YAxisColumnsLabel": "Y 軸資料行",
    "YAxisColumnsHelp": "(選取一或多個；按一下色票以設定色彩)",
    "SelectColumnPlaceholder": "— 選取資料行 —",
    "ScatterLabelColumnLabel": "點標籤",
    "SizeColumnLabel": "大小 / 半徑資料行",
    "NoSizeColumnOption": "— 無 (固定大小) —",
    "SeriesColorTitle": "{0} 的色彩",
    "SeriesTypeTitle": "{0} 的圖表類型",
    "SeriesTypeDefault": "預設",
    "SeriesTypeBar": "直條",
    "SeriesTypeLine": "折線",
    "HistogramColumnLabel": "要分組的資料行 (數值)",
    "TreemapGroupLabel": "群組 / 標籤資料行",
    "HeatmapColumnLabel": "資料行 (X) 類別",
    "HeatmapRowLabel": "列 (Y) 類別",
    "AdvancedOptionsClosed": "▼ 進階選項",
    "AdvancedOptionsOpen": "▲ 進階選項",
    "ColorByLabel": "依資料行著色",
    "ColorByHelp": "依類別而非依數列為資料點著色。",
    "TooltipColumnsLabel": "工具提示資料行",
    "TooltipColumnsHelp": "(將滑鼠停留在資料點上時顯示的額外資料行)",
    "DrillLevelLabel": "下鑽層級 {0}",
    "DrillDownHelp": "定義資料行階層以啟用按一下下鑽 (例如 區域 → 國家/地區 → 城市)。值會在每個層級彙總。",
    "BookmarksLabel": "書籤",
    "BookmarkNameLabel": "書籤名稱",
    "BookmarkNamePlaceholder": "例如：依區域前 10 名",
    "SaveBookmarkButton": "儲存目前的檢視",
    "ApplyBookmarkButton": "套用",
    "DeleteBookmarkButton": "刪除",
    "ApplyBookmarkPlaceholder": "— 套用書籤 —",
    "DataControlsSectionHeader": "資料控制項",
    "SortByColumnLabel": "依資料行排序",
    "NoneOption": "— 無 —",
    "SortDirectionLabel": "排序方向",
    "AscendingOption": "遞增",
    "DescendingOption": "遞減",
    "RowLimitLabel": "列數限制 (0 = 全部)",
    "FilterColumnLabel": "篩選資料行",
    "FilterContainsLabel": "篩選：包含",
    "FilterValuePlaceholder": "篩選值…",
    "GroupByLabel": "依資料行分組",
    "AggregationLabel": "彙總",
    "GroupByHelp": "數值資料行會依群組彙總。「計數」會新增「計數」資料行。",
    "AggNone": "無",
    "AggSum": "加總",
    "AggAvg": "平均值",
    "AggCount": "計數",
    "AggMin": "最小值",
    "AggMax": "最大值",
    "DataTableHeader": "資料表 ({0} 列)",
    "PrevPageButton": "← 上一頁",
    "NextPageButton": "下一頁 →",
    "PageOfLabel": "第 {0} 頁，共 {1} 頁",
    "ExportLabel": "匯出：",
    "ExportPngTitle": "將圖表下載為 PNG 影像",
    "ExportJpegTitle": "將圖表下載為 JPEG 影像",
    "ExportCsvTitle": "將資料下載為 CSV",
    "ExportExcelTitle": "將資料下載為 Excel 活頁簿"
  }
});
